Add better support for using deprecated symbols internally
openssl/openssl pull request #10608
Opened 2019-12-11 13:47 UTC by levitte

OPENSSL_SUPPRESS_DEPRECATED only does half the job, in telling the
deprecation macros not to add the warning attribute.  However, with
'no-deprecated', the symbols are still removed entirely, while we
might still want to use them internally.

The solution is to permit <openssl/opensslconf.h> macros to be
modified internally, such as undefining OPENSSL_NO_DEPRECATED in this
case.

However, with the way <openssl/opensslconf.h> includes
<openssl/macros.h>, that's easier said than done.  That's solved by
generating <openssl/configuration.h> instead, and add a new
<openssl/opensslconf.h> that includes <openssl/configuration.h> as
well as <openssl/macros.h>, thus allowing to replace an inclusion of
<openssl/opensslconf.h> with this:

    #include <openssl/configuration.h>

    #undef OPENSSL_NO_DEPRECATED
    #define OPENSSL_SUPPRESS_DEPRECATED

    #include <openssl/macros.h>

Or simply add the following prior to any other openssl inclusion:

    #include <openssl/configuration.h>

    #undef OPENSSL_NO_DEPRECATED
    #define OPENSSL_SUPPRESS_DEPRECATED

Note that undefining OPENSSL_NO_DEPRECATED must never be done by
applications, since the symbols must still be exported by the
library.  Internal test programs are excempt of this rule, though.

2019-12-11 13:47 UTC, levitte commented
This should make @mattcaswell's life slightly easier in #10580

2019-12-11 15:45 UTC, t-j-h approved these changes

2019-12-11 16:02 UTC, t8m requested changes

2019-12-11 16:02 UTC, t8m commented on CHANGES
> +     include/openssl/opensslconf.h.in, which differs in not including
s/opensslconf.h.in/configuration.h.in/

2019-12-11 18:01 UTC, levitte commented on CHANGES
> +     include/openssl/opensslconf.h.in, which differs in not including
Fixed

2019-12-12 08:24 UTC, levitte commented
Does @t-j-h's approval hold through the tiny change to CHANGES?  If not, someone needs to approve/re-approve

2019-12-12 08:32 UTC, t8m approved these changes
I can provide the approval as well.

2019-12-12 08:38 UTC, paulidale approved these changes

2019-12-13 09:14 UTC, levitte commented
Merged.

46994f71631922565924e3ca6303950c36337b33 Add better support for using deprecated symbols internally

2019-12-13 09:14 UTC, closed without merging