Allow to continue on UNABLE_TO_VERIFY_LEAF_SIGNATURE
openssl/openssl pull request #11359
Opened 2020-03-18 15:12 UTC by misery

This unifies the behaviour of a single certificate with
an unknown CA certificate with a self-signed certificate.
The user callback can mask that error to retrieve additional
error information. So the user application can decide to
abort the connection instead to be forced by openssl.

This change in behaviour is backward compatible as user callbacks
who don't want to ignore UNABLE_TO_VERIFY_LEAF_SIGNATURE will
still abort the connection by default.

CLA: trivial
GH: #11297

2020-04-15 07:51 UTC, misery commented
Ping? Opinions?

2020-06-30 10:20 UTC, misery commented
ping?

2020-10-01 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2020-10-01 12:09 UTC, DDvO approved these changes
Nice improvement

2020-10-01 18:10 UTC, misery reviewed
By the way... If n is 0 or lower. Is n-- still valid?

2020-10-01 18:32 UTC, mspncp commented
@misery I guess I completely misunderstood you question on first read, sorry. Indeed, what happens if `sk_X509_value()` is called with a negative value @DDvO?

https://github.com/openssl/openssl/blob/ad3bb58e90bd49e2f42021637bc5354082319377/crypto/x509/x509_vfy.c#L1724-L1726

2020-10-01 18:37 UTC, misery commented
> @misery I guess I completely misunderstood you question on first read, sorry. Indeed, what happens if `sk_X509_value()` is called with a negative value @DDvO?
> 
> https://github.com/openssl/openssl/blob/ad3bb58e90bd49e2f42021637bc5354082319377/crypto/x509/x509_vfy.c#L1724-L1726

Thanks for feedback! Maybe I need to set n to 0 after callback? Don't know openssl internal enough for that.

2020-10-01 18:40 UTC, mspncp commented
Please also replace the line
```
GH: #11297
```
by 
```
Fixes #11297
```
in your commit message.

2020-10-01 18:46 UTC, mspncp commented
> Thanks for feedback! Maybe I need to set n to 0 after callback? Don't know openssl internal enough for that.

I haven't actually been following the discussion #11297 and did not go into the details of the verification code. So I can't tell you offhand whether that  would be the correct fix. Maybe @DDvO can say more about it.

2020-10-01 20:40 UTC, DDvO commented
In this case (i.e., when the callback returns `1` on a chain that consists of just one cert) 
it does not hurt that `n` can become negative (or to be more specific, will be `-1`).

The `ctx->error_depth` becomes `-1` but this should be irrelevant because `internal_verify()` returns success.
The variable `xs` will be assigned to NULL due to `sk_X509_value(ctx->chain, n)` but is not used thereafter.
Yet note that due to the following `while (n >= 0)` the function will not do any further checks,
and after reading #11297 I found that this is not what you wanted.
I need to withdraw my quick approval because your PR so far essentially has no effect.

2020-10-01 20:48 UTC, DDvO requested changes
So far your PR has essentially no effect.
I've suggested a real solution.

2020-10-01 20:48 UTC, DDvO commented on crypto/x509/x509_vfy.c
> +                return 0;
What you really need is
```
if (verify_cb_cert(ctx, xi, 0,
                   X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE) {
    xs = xi;
    goto check_cert_time;
} else {
    return 0;
}

2020-10-01 20:49 UTC, misery commented
Well, why no effect? It works with my tests. Maybe it must be adjusted because of n.

		if (n <= 0) {
			if (!verify_cb_cert(ctx, xi, 0,
				X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE))
					return 0;
			n = 0;
		} else
			n--;

2020-10-01 21:02 UTC, misery commented
Thanks for your review!

2020-10-01 21:11 UTC, richsalz commented
Get rid of the "else after goto"  And consider inverting the test:
```
if (!verify_cb_cert(ctx, xi, 0,
                   X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE)
    return 0;
xs = xi;
goto check_cert_time;
```

2020-10-01 21:19 UTC, DDvO commented
> Well, why no effect? It works with my tests.

Strange that it worked for you - if `n <= 0` and the callback says 'yes' then `internal_verify()` does not do any further checks.

> Maybe it must be adjusted because of n.
> 
> ```
> 	if (n <= 0) {
> 		if (!verify_cb_cert(ctx, xi, 0,
> 			X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE))
> 				return 0;
> 		n = 0;
> 	} else
> 		n--;
> ```

This solution would have the same effect as mine because also with it `x509_check_cert_time()` is called while the self-signature check is certainly not done because in the given case the cert in question (`xs`, which is the same as `xi`) is not self-issued and thus cannot be self-signed.

2020-10-01 21:22 UTC, DDvO commented
Please handle this Travis CI failure (due to a warning):
```
crypto/x509/x509_vfy.c: In function 'internal_verify':

crypto/x509/x509_vfy.c:1753:12: error: suggest explicit braces to avoid ambiguous 'else' [-Werror=parentheses]

         if (n <= 0)

            ^

crypto/x509/x509_vfy.c:1758:17: error: label 'check_cert_time' used but not defined

                 goto check_cert_time;

                 ^
cc1: all warnings being treated as errors
```

2020-10-02 08:54 UTC, misery commented
Thanks! Done...

2020-10-02 09:43 UTC, t8m commented
This should be directly cherry-pickable to master.

2020-10-02 10:41 UTC, misery commented
> This should be directly cherry-pickable to master.

Works for me.

2020-10-02 11:00 UTC, DDvO approved these changes
Good that you took over also @richsalz's suggestion,
which makes it even nicer.

2020-10-03 07:53 UTC, DDvO commented
This still requires an OTC approval.

2020-10-03 08:21 UTC, DDvO commented
We should also clean up the code in order to get rid of all those "goto check_cert(_time);" which make the control flow hard to follow.
We could do that in a separate PR or as part of this one, removing the label and simplifying the beginning of `internal_verify()` to:
```
    int n = sk_X509_num(ctx->chain) - 1;
    X509 *xi = sk_X509_value(ctx->chain, n);
    X509 *xs = xi;

    ctx->error_depth = n;
    /*
     * With DANE-verified bare public key TA signatures, it remains only to
     * check the timestamps of the top certificate.  We report the issuer as
     * NULL, since all we have is a bare key.
     */
    if (ctx->bare_ta_signed) {
        xi = NULL;
    } else if (!ctx->check_issued(ctx, xi, xi)
               /* exceptional case: last cert in the chain is not self-issued */
               && ((ctx->param->flags & X509_V_FLAG_PARTIAL_CHAIN) == 0)) {
        if (n > 0) {
            n--;
            ctx->error_depth = n;
            xs = sk_X509_value(ctx->chain, n);
        } else if (!verify_cb_cert(ctx, xi, 0,
                                   X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE)) {
            return 0;
        }
    }
```

2020-10-05 08:47 UTC, t8m approved these changes

2020-10-05 08:51 UTC, t8m commented
Thinking about this more, this is really something that does not belong to 1.1.1 branch as it is strictly speaking not a bug fix.
No need to update the PR, we will cherry-pick it to master.

2020-10-05 08:54 UTC, t8m commented
The change is also borderline on the CLA:trivial designation. But I think it is still acceptable. @DDvO do you agree this is trivial change?

2020-10-05 09:04 UTC, DDvO commented
> The change is also borderline on the CLA:trivial designation. But I think it is still acceptable. @DDvO do you agree this is trivial change?

Thanks @t8m for your further comments, your approval, and your question.
I definitely agree with CLA:trivial here, in particular since the final form of this minor improvement was suggested by @richsalz and me who have signed a CLA.

2020-10-05 09:07 UTC, DDvO commented
I suggest adding "Fixes #11297" to the commit message when doing the merge.

2020-10-05 09:59 UTC, mspncp commented
> I suggest adding "Fixes #11297" to the commit message when doing the merge.

It's already in the commit message: https://github.com/openssl/openssl/pull/11359/commits/231c228f14d716d8981c25421dc247c08251de60

2020-10-06 09:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2020-10-06 14:36 UTC, DDvO commented
@misery, I wanted to merge this (or better to say, cherry-pick the commit on top of master),
but the label referred to in your commit, which is meant for 1.1.1, needs to be adapted for the master:
replace `goto check_cert` by `goto check_cert_time`.

2020-10-06 14:38 UTC, DDvO commented
@misery, would it be important for your application to have this change also backported on version 1.1.1?

2020-10-06 14:56 UTC, misery commented
> @misery, would it be important for your application to have this change also backported on version 1.1.1?

Yes, otherwise it is remotely possible to skip further checks like expiration date. The attacker could use an out-dated certificate. 

Normally that would be stopped by our own truststore. But there could be a slightly time window until we dropped the certificate from the truststore.

2020-10-06 15:54 UTC, DDvO commented
So it really would be good to have this little feature extension/fix also in 1.1.1.
@t8m, @mattcaswell, @levitte, is this acceptable?

2020-10-06 16:17 UTC, t8m commented
I suppose we would have to have an OTC vote for that.

2020-10-06 16:19 UTC, t8m commented
@misery could you please open a new PR against master? We can merge that one easily and then we can have a vote for the 1.1.1 exception for this PR.

2020-10-06 20:08 UTC, misery commented
Thanks! I created a new PR for master: https://github.com/openssl/openssl/pull/13083

2020-10-08 14:52 UTC, DDvO commented
> I suppose we would have to have an OTC vote for that.

@t8m, could you please bring this to the agenda there?

2020-10-09 13:06 UTC, romen commented
I updated the labels to reflect the current state.

I also applied the `hold: need otc decision` label on behalf of @t8m that already opened a [vote about it](https://www.mail-archive.com/openssl-project@openssl.org/msg02158.html).

2020-10-09 13:11 UTC, romen commented
@misery @DDvO @t8m I am not terribly familiar with this code, and I feel inclined to abstain with a `+0` at the moment.

I think it would help informing my opinion for the vote, and easily turn this into a `+1` if any of you could write a short argument on why this could be seen as a bug or security fix to support inclusion in 1.1.1.

2020-10-09 13:33 UTC, DDvO commented
> I suppose we would have to have an OTC vote for that.

@t8m, could you please bring this to the agenda there?

> I updated the labels to reflect the current state.
> 
> I also applied the `hold: need otc decision` label on behalf of @t8m that already opened a [vote about it](https://www.mail-archive.com/openssl-project@openssl.org/msg02158.html).

Thanks @t8m and @romen.

2020-10-09 13:45 UTC, DDvO commented
> I think it would help informing my opinion for the vote, and easily turn this into a `+1` if any of you could write a short argument on why this could be seen as a bug or security fix to support inclusion in 1.1.1.

Within the OpenSSL X.509 certificate chain verification code in `x509_vfy.c` 
there are currently two flavors of invocations of the optional certificate verification callback function:
1. Giving the callback the chance to decide to abort or continue with standard verification
2. Giving the callback the chance to decide to abort or take over any remaining verification activity

where the first flavor is used in the majority of cases.

The choice with of the two flavors is used at which places appears pretty ad-hoc and is not documented,
which can be seen as a bug at design/conceptual level.

This PR contributes to solving this by changing for one situation the choice from 2. to 1., which appears more appropriate.

2020-10-09 13:48 UTC, t8m commented
@romen it is not a security issue by itself. Of course if application supplying the callback and overriding the UNABLE_TO_VERIFY_LEAF_SIGNATURE error blindly decides to ignore that expiration checks are not done it would be a security issue of the application. This change would just make it to be avoided.

IMO the argument that it is a bug fix is that for self-signed certificates the expiration check is called although the signature is not verified either (there is no sense in verifying the self signature). So the behavior is inconsistent between self-signed and non-self-signed leaf certificates.

2020-10-09 15:02 UTC, romen commented
Thanks both @t8m and @DDvO .

Regarding the "breaking change" aspect, is my understanding that this change is basically opt-in and only affect applications that want to catch `UNABLE_TO_VERIFY_LEAF_SIGNATURE` in this particular case, and thus can only benefit from merging this?

If my understanding is not correct, how likely do you estimate this change could affect existing applications? And how badly?

2020-10-09 15:03 UTC, romen commented
Thinking about the potentially breaking change, even in the case it is only opt-in and can't have negative effects.

One thing that I might like to see included in this PR before merging if the vote passes, is an entry in `NEWS` or `CHANGES` to alert users of the change (this would probably apply to `master` as well): what are your thoughts about it?

2020-10-09 15:21 UTC, t8m commented
Well in theory there could be existing application that wants to waive the UNABLE_TO_VERIFY_LEAF_SIGNATURE check and does not care about checking the expiration time and does not care about self signed certs and is unable to handle (waive) further errors from the expiration time checks. This application would be broken by this change. It is also fairly convolute and improbable scenario that such application exists.

2020-10-10 11:13 UTC, DDvO commented
> Well in theory there could be existing application that wants to waive the UNABLE_TO_VERIFY_LEAF_SIGNATURE check and does not care about checking the expiration time and does not care about self signed certs and is unable to handle (waive) further errors from the expiration time checks. This application would be broken by this change. It is also fairly convolute and improbable scenario that such application exists.

If such an application exists, it could still waive any errors from the expiration time checks, using the same callback function.

2020-10-26 13:05 UTC, t8m commented
The OTC vote has passed so the PR can be now merged.

2020-10-26 13:08 UTC, t8m commented
Merged to 1.1.1 branch. Thank you for the contribution.

2020-10-26 13:08 UTC, closed without merging