EVP: Fix EVP_PKEY_copy_parameters() for a newly allocated |to|
openssl/openssl pull request #11368
Opened 2020-03-19 22:24 UTC by levitte

We didn't account for that possibility, and tried to upgrade an empty key
to be provided.  evp_pkey_upgrade_to_provider() doesn't handle empty keys
too well, so we need to check that it doesn't get one.

Fixes #11366

2020-03-19 22:38 UTC, slontis requested changes
Code looks reasonable.. Please add the test to confirm there are not more problems :).

2020-03-19 23:19 UTC, mattcaswell approved these changes
Approved.

Note: I think we may also have problems where we copy parameters between two keys of the same type in the same provider. None of our current keymgmt implementation seem to implement the "copy" function (OSSL_FUNC_KEYMGMT_COPY).

2020-03-19 23:20 UTC, mattcaswell requested changes
Oh...actually. Just read @slontis's comment. A test would be good.

2020-03-20 05:14 UTC, levitte commented
Yup, test on its way.

2020-03-20 05:51 UTC, levitte commented
Ohhhhhhh...  copy hasn't been implemented everywhere.  This opens up for a side question, should it be mandatory to implement OP_keymgmt_copy?  Right now it's not, 'cause I didn't see it as fundamental function, but maybe it is?

2020-03-20 05:51 UTC, levitte commented
Oh, now I see that @mattcaswell said that same thing

2020-03-20 05:58 UTC, levitte commented
As to the question if OP_keymgmt_copy should be mandatory, I remembered that it's not necessary.  There's a fallback to using export/import.

2020-03-20 08:25 UTC, mattcaswell commented
> As to the question if OP_keymgmt_copy should be mandatory, I remembered that it's not necessary. There's a fallback to using export/import.

Hmmm. I'm fairly sure I've seen this fail if you don't have the copy there, so I'm not sure this is working.

2020-03-20 10:42 UTC, levitte commented
> Hmmm. I'm fairly sure I've seen this fail if you don't have the copy there, so I'm not sure this is working.

Yup.  The code in `evp_keymgmt_util_copy()`  is stoopid and checks if `from->keymgmt->copy` is non-NULL before it has a chance of trying the export/import method...  I'm dealing with that right now.

2020-03-21 05:32 UTC, levitte commented
Closing this in favour of #11375

2020-03-21 05:32 UTC, closed without merging