WPACKET: don't write DER length when we don't want to
openssl/openssl pull request #11703
Opened 2020-05-01 16:43 UTC by levitte

With endfirst writing, it could be that we want to abandon any zero
length sub-packet.  That's what WPACKET_FLAGS_ABANDON_ON_ZERO_LENGTH,
but the DER length writing code didn't look at it.  Now it does.

2020-05-01 16:46 UTC, mattcaswell submitted a review, later dismissed
LGTM. Approved assuming CIs agree and you fix the commit message to actually make sense ;-)

2020-05-01 16:59 UTC, levitte commented
> ... and you fix the commit message to actually make sense ;-)

Better?

2020-05-01 17:19 UTC, mattcaswell commented
> Better now?

Yes - thanks!

2020-05-01 17:27 UTC, levitte commented
> Yes - thanks!

I actually had a good laugh when I re-read it.  Complete gibberish!

2020-05-01 21:39 UTC, kaduk requested changes
The commit message talks about `WPACKET_FLGAS_ABANDON_ON_ZERO_LENGTH` but the code checks `WPACKET_FLAGS_NON_ZERO_LENGTH`.

2020-05-01 21:46 UTC, mattcaswell commented
> The commit message talks about WPACKET_FLGAS_ABANDON_ON_ZERO_LENGTH but the code checks WPACKET_FLAGS_NON_ZERO_LENGTH.

Oops. Good catch!

2020-05-02 06:53 UTC, levitte commented on crypto/packet.c
> +                   || (sub->flags & WPACKET_FLAGS_NON_ZERO_LENGTH) == 0)) {
Hold on, this isn't right...

2020-05-02 06:55 UTC, levitte commented on crypto/packet.c
> +                   || (sub->flags & WPACKET_FLAGS_NON_ZERO_LENGTH) == 0)) {
Ah, I see others discovered the same thing.

2020-05-02 06:57 UTC, levitte commented on crypto/packet.c
> +                   || (sub->flags & WPACKET_FLAGS_NON_ZERO_LENGTH) == 0)) {
Fixed

2020-05-02 08:50 UTC, levitte commented
Travis failure not relevant here.  Fix in #11708

2020-05-02 22:16 UTC, kaduk approved these changes
That looks better now, thanks.

2020-05-02 23:20 UTC, mattcaswell approved these changes

2020-05-03 23:00 UTC, openssl-machine commented
This pull request is ready to merge

2020-05-04 03:50 UTC, levitte commented
Merged

12cbb8e0497bc4990cfb02f1b9ebe23df9b53a2c WPACKET: don't write DER length when we don't want to

2020-05-04 03:50 UTC, closed without merging