Add a NULL check to EVP_PKEY_assign
openssl/openssl pull request #12863
Opened 2020-09-12 14:53 UTC by jwalch

Fixes  #12619

##### Checklist
- [x] tests are added or updated

2020-09-12 18:38 UTC, levitte requested changes

2020-09-12 18:38 UTC, levitte commented on crypto/evp/p_lib.c
> +    if (key && (EVP_PKEY_type(type) == EVP_PKEY_EC)) {
Please change `key` to `key != NULL`

2020-09-14 08:23 UTC, mattcaswell commented
Please can you submit a CLA? Or if you consider this to be a trivial contribution (from a copyright perspective) - please add the line "CLA: trivial" in a line on its own in the commit description.

2020-09-14 13:11 UTC, jwalch commented
I sent in an ICLA to legal@opensslfoundation.org from the email address in question (jeremy.walch@gmail.com) more than a week ago now...

2020-09-14 13:16 UTC, mattcaswell commented
Close/reopen to kick CLA bot

2020-09-14 13:16 UTC, mattcaswell commented
> I sent in an ICLA to legal@opensslfoundation.org from the email address in question (jeremy.walch@gmail.com) more than a week ago now...

Apologies. This somehow got over looked. I've processed it now.

2020-09-14 13:17 UTC, mattcaswell approved these changes
LGTM

2020-09-15 16:37 UTC, t8m approved these changes

2020-09-16 17:00 UTC, openssl-machine commented
This pull request is ready to merge

2020-09-17 07:38 UTC, t8m commented
Merged to master. Thank you for the contribution.

2020-09-17 07:38 UTC, closed without merging