WIP: Fix lhash
openssl/openssl pull request #12860
Opened 2020-09-11 13:11 UTC by mattcaswell

This PR follows on from #12781 that fixed this safestack code. The same fix is applied to the lhash code.

Since this builds on the changes from #12781 all of those commits are reproduced here and so this PR is marked as WIP. As soon as #12781 is merged I will take it out of WIP.

2020-09-12 06:06 UTC, slontis commented
Make update?

2020-09-13 10:32 UTC, mattcaswell commented
I rebased this now that #12781 is in, and have taken it out of WIP.

2020-09-13 13:46 UTC, richsalz commented
Thank you for doing this.  When I started I had no idea it would be so much work.

2020-09-15 13:15 UTC, levitte commented on util/libcrypto.num
> +conf_method_st                          ?	3_0_0	EXIST::VARIABLE:
Er...  what?

2020-09-15 13:15 UTC, levitte commented on util/libcrypto.num
> +ERR_new                                 ?	3_0_0	NOEXIST::FUNCTION:
!!! What?

2020-09-15 13:17 UTC, levitte commented
I'll have a look at the weirdness going on here...

2020-09-15 15:14 UTC, levitte commented
The weirdness was because OpenSSL::ParseC didn't recognise function bodies, so it didn't handle explicit inline functions.  Fix in #12882

2020-09-15 15:17 UTC, levitte requested changes

2020-09-15 15:17 UTC, levitte commented on include/openssl/lhash.h
> +    }
Please add `LHASH_OF(type)` here, without ending semicolon, so that it's truly interchangeable with `DEFINE_LHASH_OF`

2020-09-15 15:17 UTC, levitte commented on util/perl/OpenSSL/stackhash.pm
> +DEFINE_LHASH_OF_INTERNAL(${type})
Add a semicolon at the end of this line

2020-09-16 10:15 UTC, mattcaswell commented
This is now dependent on #12882

2020-09-16 14:59 UTC, mattcaswell commented
I added in the commits from #12882, and added in the fixups suggested by @levitte above. Lets see how travis behaves now.

2020-09-17 12:22 UTC, mattcaswell commented
CIs passed, but there was a conflict with master so I have rebased this.

Still looking for an approval - this is needed for beta 1.

2020-09-17 12:29 UTC, levitte approved these changes
LGTM

2020-09-18 12:30 UTC, mattcaswell commented
Travis red cross is not relevant.

2020-09-18 12:41 UTC, mattcaswell commented
Pushed. Thanks.

2020-09-18 12:41 UTC, closed without merging