Fix of getentropy() usage (master)
openssl/openssl pull request #13114
Opened 2020-10-12 09:53 UTC by millikk

**Brief**
Several embedded toolchains may provide dummy implemented `getentropy()` function which always returns -1 and sets errno to the `ENOSYS`. As a result the function `SSL_CTX_new()` fails to create a new context

More details: [Issue#13002: Getting random data failed on some embedded Linux platforms](https://github.com/openssl/openssl/issues/13002)

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2020-10-12 10:45 UTC, paulidale approved these changes

2020-10-12 12:09 UTC, mspncp requested changes
@millikk you provided an excellent description of the issue and your fix. Unfortunately, none of that has entered the commit message, which is a pity.

```
Applied the fix 13002

CLA: trivial
```

Could you please change your commit message to make it more self contained? The following commit message is just an example of how it could look like and was crafted from your description. Feel free to change it as you like.


```
syscall_random(): don't fail if the getentropy() function is a dummy

Several embedded toolchains may provide dummy implemented getentropy()
function which always returns -1 and sets errno to the ENOSYS.

As a result the function SSL_CTX_new() fails to create a new context.


Fixes #13002
CLA: trivial
```

Apart from the commit message, I'm ok with the pull request and will approve as soon as it is change. I also agree that it's a (legally) trivial change.

2020-10-12 12:19 UTC, mspncp commented
Sorry, I just read the rest of #13112 and noticed that I misunderstood paulidale's intention here. That's why I restored the 'cla required' label.

2020-10-12 23:46 UTC, millikk commented
@mspncp, I submitted the CLA and updated the description in the commit

2020-10-13 00:24 UTC, paulidale approved these changes

2020-10-13 04:51 UTC, mspncp approved these changes
LGTM

The 'CLA: trivial' still needs to be removed from the commit message, but this could also be done by the team member who merges the pull request.

2020-10-14 05:00 UTC, openssl-machine commented
This pull request is ready to merge

2020-10-14 05:51 UTC, mspncp commented
The last [force-push](https://github.com/openssl/openssl/compare/ea000cb93933eb6fb679c40e5f4e2cb9caae40cd..5fba1a5d0b9d0e408beb96b6f0fad094c052e215) only amended the commit message to remove the `CLA: trivial` label. No re-review required.

2020-10-14 05:57 UTC, mspncp commented
Merged to master as 8e596a93bc266259f1ef0d56601e58bbfe18317a. Thank you @millikk and congratulations to your first contribution to OpenSSL!

2020-10-14 06:01 UTC, closed without merging

2020-10-14 10:06 UTC, millikk commented
Thank you all so much :)