Fix Solaris Sparc build issues
openssl/openssl pull request #13253
Opened 2020-10-27 06:38 UTC by jon-oracle

The first of these appears to have been merged recently in #13213 , but the other is caused by https://github.com/openssl/openssl/commit/028b31b32da97ada44140120297511eae518ed42

The build fails with Oracle Studio 12.6 due to unresolved symbols:

```
-bash-4.4$ make 
make depend && make _build_sw 
cc  -Iinclude -Iapps/include  -xarch=v9 -xstrconst -Xa -g -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL   -c -o test/shlibloadtest-bin-shlibloadtest.o test/shlibloadtest.c 
cc: Warning: -xarch=v9 is deprecated, use -m64 -xarch=sparc instead 
rm -f test/shlibloadtest 
${LDCMD:-cc} -xarch=v9 -xstrconst -Xa -g -mt  \ 
       -o test/shlibloadtest \ 
       test/shlibloadtest-bin-shlibloadtest.o \ 
       -lsocket -lnsl -ldl -lpthread  
cc: Warning: -xarch=v9 is deprecated, use -m64 -xarch=sparc instead 
Undefined                       first referenced 
symbol                             in file 
OPENSSL_LH_stats_bio                test/shlibloadtest-bin-shlibloadtest.o 
OPENSSL_LH_get_down_load            test/shlibloadtest-bin-shlibloadtest.o 
OPENSSL_LH_set_down_load            test/shlibloadtest-bin-shlibloadtest.o 
OPENSSL_LH_new                      test/shlibloadtest-bin-shlibloadtest.o 
OPENSSL_LH_retrieve                 test/shlibloadtest-bin-shlibloadtest.o 
OPENSSL_LH_free                     test/shlibloadtest-bin-shlibloadtest.o 
OPENSSL_LH_node_stats_bio           test/shlibloadtest-bin-shlibloadtest.o 
OPENSSL_LH_num_items                test/shlibloadtest-bin-shlibloadtest.o 
OPENSSL_LH_node_usage_stats_bio     test/shlibloadtest-bin-shlibloadtest.o 
OPENSSL_LH_delete                   test/shlibloadtest-bin-shlibloadtest.o 
OPENSSL_LH_insert                   test/shlibloadtest-bin-shlibloadtest.o 
OPENSSL_LH_doall                    test/shlibloadtest-bin-shlibloadtest.o 
OPENSSL_LH_error                    test/shlibloadtest-bin-shlibloadtest.o 
OPENSSL_LH_flush                    test/shlibloadtest-bin-shlibloadtest.o 
ld: fatal: symbol referencing errors 
*** Error code 2 
make: Fatal error: Command failed for target `test/shlibloadtest' 
Current working directory /scratch/jspillet/jaffa/openssl-cmphang 
*** Error code 1 
make: Fatal error: Command failed for target `build_sw' 
-bash-4.4$ 
```

This PR reverses the change.

2020-10-27 06:42 UTC, slontis commented
@mattcaswell : This was removed in 
https://github.com/openssl/openssl/commit/028b31b32da97ada44140120297511eae518ed42

The statement that it was no longer needed appears to not be true :)

2020-10-27 06:43 UTC, slontis approved these changes

2020-10-29 10:09 UTC, mattcaswell requested changes
This is the wrong fix.

I assume the problematic lines are due to the two `DEFINE_LHASH_OF` calls in lhash.h. Looks like these were missed from being converted in #12860. They should be changed to a call to `generate_lhash_macros` as per the other changes in #12860.

2020-10-29 13:02 UTC, mattcaswell commented
My alternative fix is in #13274.

2020-10-30 01:00 UTC, jon-oracle commented
@mattcaswell  No worries. Feel free to close this one and merge #13274 instead.

2020-10-30 14:52 UTC, mattcaswell commented
Closing in favour of #13274 which has now been pushed.

2020-10-30 14:52 UTC, closed without merging