Fix some warnings from clang 10 in params.c
openssl/openssl pull request #13366
Opened 2020-11-10 12:27 UTC by mattcaswell

clang 10 was emitting warnings similar to the following from params.c:

````
crypto/params.c:411:40: error: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Werror,-Wimplicit-int-float-conversion]
            if (d >= INT64_MIN && d <= INT64_MAX && d == (int64_t)d) {
````

The comparison against INT64_MAX is unnecessary. Instead we can simply check that
the value round trips successfully.

2020-11-10 12:55 UTC, paulidale reviewed
I have some doubts that the round trip check is sufficient.  I suspect that there could be edge cases where the conversion from double to int isn't exact but gets rounded back to the _correct_ value.

We guarantee that only exact conversions are done automatically.

2020-11-10 12:55 UTC, paulidale commented on crypto/params.c
> +            if (d >= INT64_MIN && d == (int64_t)d) {
The check against INT64_MIN is the same -- it just happens that INT64_MIN can be represented as a double.

2020-11-10 13:11 UTC, paulidale requested changes
I think I've figured out appropriate values.  We know the integer length, so we know the exact bounds for the reals that can be exactly converted.

2020-11-10 13:11 UTC, paulidale commented on crypto/params.c
> +            if (d >= INT64_MIN && d == (int64_t)d) {
The check for d being integral is already done, so `d >= ldexp(1, -64) && d < ldexp(1, 64)` would work here but I don't think we can handle the libm dependency.

This is a bit obtuse, but I think `d >= INT64_MIN && -d > INT64_MIN` will work.

2020-11-10 13:11 UTC, paulidale commented on crypto/params.c
> +            if (val >= 0 && val == (uint32_t)val) {
This change isn't required.  UINT32_MAX comfortably fits into a double.

2020-11-10 13:11 UTC, paulidale commented on crypto/params.c
> +            if (val >= INT32_MIN && val == (int32_t)val) {
Likewise, this one should be reverted.

2020-11-10 13:11 UTC, paulidale commented on crypto/params.c
> +            if (d >= 0 && d == (uint64_t)d) {
The original is wrong here too 👍 

Changing the comparison to `d >= 0 && d < 18446744073709551616.` should work.

2020-11-10 13:44 UTC, mattcaswell commented
> I have some doubts that the round trip check is sufficient. I suspect that there could be edge cases where the conversion from double to int isn't exact but gets rounded back to the correct value.

And why does a range check improve that situation?

2020-11-10 22:02 UTC, paulidale commented
For values inside the range, conversion will be exact.  The source double carries 53 bits of mantissa.  These fit into a 64 bit integer just fine.

My concerns about about values outside the range check.  With a fresher mind, I'm unable to come up with an obvious failure case.  I still think we're best avoiding this situation: it's undefined behaviour in C.  It's also a fairly expensive operation whereas a pair of double compares is cheap.

2020-11-10 22:19 UTC, kroeckx commented
Some platforms like arm only have a 32 bit double, so a 24 bit
mantissa.

Using INT64 is clearly wrong, it's being converted from a long.

A problem like this was previously fixed in
082c041b4233b17b80129d4ac6b33a28014442b0

2020-11-11 01:17 UTC, paulidale commented
Thanks @kroeckx, that's the one.  Int64 is correct I think.  The int/long/size_t/time_t differences have been resolved by the time this stuff runs.  Everything should either be 32 or 64 bit and signed or unsigned.

2020-11-11 09:23 UTC, mattcaswell commented
I'm wondering why we need the `OSSL_PARAM_REAL` support in these functions anyway? Do we ever actually use this anywhere?

Anyway, @paulidale since you seem to have a pretty clear idea about what needs to be done - do you want to take this PR over?

2020-11-11 11:25 UTC, paulidale commented
Okay, I'll take this one on.

2020-11-11 11:25 UTC, closed without merging