[WIP] Remove the old DEPRECATEDIN macros
openssl/openssl pull request #13461
Opened 2020-11-20 10:46 UTC by levitte

They (almost) serve no purpose any more

-----

This is WIP until all old DEPRECATEDIN_x_y_z macros have been switched to use the OSSL_DEPRECATEDIN_x_y_z attribute macro.  #13460 does the bulk of that already.

2021-01-30 19:57 UTC, levitte commented
Now that all uses of the old macros have been refactored to the new form, we can finally remove the old.
I just rebased this PR, and the CIs should confirm that this is indeed fine at this point.

2021-01-30 20:01 UTC, richsalz commented
And these?
```
util/mkdef.pl:            next unless /^DEPRECATEDIN_(\d+)_(\d+)(?:_(\d+))?$/;
util/perl/OpenSSL/ParseC.pm:    # DEPRECATEDIN_x_y[_z].
util/perl/OpenSSL/ParseC.pm:    { regexp   => qr/(DEPRECATEDIN_\d+_\d+(?:_\d+)?)<<<\((.*)\)>>>/,
```

2021-01-30 22:08 UTC, levitte commented
Well spotted.  Will fix promptly

2021-01-30 22:10 UTC, levitte commented
The mkdef.pl one isn't a C macro name, it's a feature name in util/*.num, so it doesn't count.

2021-01-30 22:14 UTC, levitte commented
Done

2021-02-01 13:49 UTC, t8m requested changes

2021-02-01 13:49 UTC, t8m commented on apps/lib/http_server.c
> +        if (BIO_vsnprintf(buf, sizeof(buf), fmt, ap) > 0)
This is completely unrelated so it should be a separate commit, shouldn't it?

2021-02-01 13:49 UTC, t8m commented on apps/lib/names.c
> +#include <strings.h>             /* strcasecmp() */
Similarly here and in other files where strings.h is added or `#define _XOPEN_SOURCE 500` is added.

2021-02-03 21:18 UTC, levitte commented
@t8m, you were right, those mysterious additions was a mistake.  Now undone.

2021-02-04 11:32 UTC, levitte commented
Ping

2021-02-04 11:48 UTC, t8m approved these changes

2021-02-05 12:00 UTC, openssl-machine commented
This pull request is ready to merge

2021-02-05 13:12 UTC, levitte commented
Merged

1e3affbbcd85856c78e50c6bf56144bf9bc0eb23 Remove the old DEPRECATEDIN macros

2021-02-05 13:12 UTC, closed without merging