Fix cipher reinit on s390x if no key is specified
openssl/openssl pull request #13984
Opened 2021-01-27 10:09 UTC by juergenchrist

If key==null on EVP_CipherInit_ex, the init functions for the hardware
implementation is not called.  The s390x implementation of OFB and CPB mode
used the init function to copy the IV into the hardware causing test failures
on cipher reinit.  Fix this by moving the copy operation into the cipher
operation.

Signed-off-by: Juergen Christ <jchrist@linux.ibm.com>

##### Checklist

2021-01-27 10:14 UTC, t8m approved these changes

2021-01-27 10:20 UTC, p-steuer approved these changes

2021-01-27 10:44 UTC, p-steuer requested changes
Please change the commit message: CPB mode -> CFB mode, i ll re-approve.

2021-01-27 10:47 UTC, p-steuer approved these changes

2021-01-27 10:53 UTC, t8m commented
still approved

2021-01-28 11:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2021-01-28 14:28 UTC, p-steuer commented
merged.

master: https://github.com/openssl/openssl/commit/732a4d15b0da7c04437ea828b2915a691b6e38db

2021-01-28 14:28 UTC, closed without merging