Fix compiling error on arm
openssl/openssl pull request #14346
Opened 2021-03-01 06:13 UTC by zorrorffm

Fixes #14313

Building with master branch on arm, the error is reported as below

test/p_test.c: In function 'p_set_error':
test/p_test.c:122:56: error: incompatible type for argument 4 of 'c_vset_error'
c_vset_error(NULL, ERR_PACK(lib, 0, reason), NULL, NULL);
                                                                                    ^~~~
test/p_test.c:122:56: note: expected 'va_list {aka __va_list}' but argument is of type 'void *'
Makefile:23428: recipe for target 'test/p_test-dso-p_test.o' failed

This fix simply replaces NULL with va_list variable.

2021-03-01 06:19 UTC, paulidale requested changes
Passing an uninitialised variable in is not a robust fix.

2021-03-01 07:24 UTC, zorrorffm commented
va_list has different implementations(char * or struct) on different platforms.  It seems there isn't a common approach to initialize va_list variable. Here c_vset_error, setting arguments fmt as NULL,  will call ERR_vset_error(int lib, int reason, const char *fmt, va_list args) that guarantee  the 'va_list args' won't be misused by telling if fmt is NULL.

Do you have any idea how to initialize va_list? Thanks.

2021-03-01 07:31 UTC, paulidale commented
Have a second function that doesn't take the va_list?  Or wrap it with a varadic function that does a va_start.  As far as I'm aware, the _only_ way to initialise a va_list is using va_start.

2021-03-01 10:23 UTC, paulidale approved these changes

2021-03-01 10:23 UTC, paulidale commented
Much better!

2021-03-01 10:29 UTC, mattcaswell approved these changes

2021-03-02 11:00 UTC, openssl-machine commented
This pull request is ready to merge

2021-03-02 11:25 UTC, paulidale commented
Merged to master, thanks for the fix.

2021-03-02 11:25 UTC, closed without merging