Fix threading issues in crypto/provider_core.c
openssl/openssl pull request #14354
Opened 2021-03-01 12:30 UTC by levitte

## Make ossl_provider_disable_fallback_loading() thread safe 

-----

##  Make provider provider_init thread safe, and flag checking/setting too

provider_init() makes changes in the provider structure, and needs a
bit of protection to ensure that doesn't happen concurrently with race
conditions.

This also demands a bit of protection of the flags, since they are
bits and presumably occupy the same byte in memory.

2021-03-01 13:04 UTC, mattcaswell requested changes
Please can we add a test for this in test_multi (threadstest.c), i.e. one that would fail if running under thread sanitizer before this change and pass afterwards.

2021-03-01 15:33 UTC, levitte commented
> Please can we add a test for this in test_multi (threadstest.c), i.e. one that would fail if running under thread sanitizer before this change and pass afterwards.

Yup, PR coming up!

2021-03-01 16:11 UTC, levitte commented
See #14372 for the test

2021-03-01 16:14 UTC, levitte commented
This is now rebased on top of #14372, to (hopefully) demonstrate the fix

2021-03-01 16:25 UTC, mattcaswell submitted a review, later dismissed
Approved subject to the typo being fixed.

2021-03-01 16:25 UTC, mattcaswell commented on crypto/provider_core.c
> +     * checked here and set at the end, but also because this functions
typo: function

2021-03-01 16:59 UTC, t8m commented
Sanitizer build failures seem to be relevant!

2021-03-01 18:01 UTC, levitte commented
> Sanitizer build failures seem to be relevant!

Interestingly, it's not the *thread* sanitizer reacting!

2021-03-01 18:02 UTC, levitte commented on crypto/provider_core.c
> +     * checked here and set at the end, but also because this functions
Fixed

2021-03-02 17:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2021-03-03 13:51 UTC, levitte commented
There were a few fixups, please re-approve, @mattcaswell

2021-03-03 14:29 UTC, mattcaswell approved these changes

2021-03-03 23:31 UTC, paulidale approved these changes

2021-03-04 00:58 UTC, mkris86 commented
Ugh

2021-03-04 00:59 UTC, mkris86 approved these changes

2021-03-04 00:59 UTC, mkris86 approved these changes

2021-03-04 15:11 UTC, levitte commented
Merged

2f17e978a0ec5becda8a61dcf3e7840740ccdfd3 test/threadstest.c: Add a test to load providers concurrently
d60a8e0a2345205242e21aae35815645708580c4 Make ossl_provider_disable_fallback_loading() thread safe
c2ec2bb7c146d1e48568f27d11dca02c06c36338 Make provider provider_init thread safe, and flag checking/setting too

2021-03-04 15:11 UTC, closed without merging