Fix DER reading from stdin for BIO_f_readbuffer
openssl/openssl pull request #14599
Opened 2021-03-18 05:27 UTC by slontis

Fixes #14559

The intitial implementation of the gets() function tried using the next bio's gets() function.
For a file BIO this returned incorrect data for binary data containing 0x00.
Just buffering all data during gets() did not work however since some
applications open and close the bio multiple times when dealing with pem
files containing multiple entries.. This does not work
when reading from stdin unless the data if buffered one byte at a time.

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

2021-03-18 05:30 UTC, slontis commented
Manually verified that previous issues raised also still work... i.e.

````
> cat test/certs/leaf.pem | ./apps/openssl x509 -MD5 -fingerprint -noout -inform PEM
> cat test/recipes/20-test_dhparam_check_data/dhx_ffdhe2048.pem | ./apps/openssl dhparam -noout -text
````

2021-03-18 06:18 UTC, levitte requested changes

2021-03-18 06:18 UTC, levitte commented on test/recipes/61-test_bio_readbuffer.t
> +        "running bio_readbuffer_test $pemfile");
Add a line ending, please

2021-03-18 06:18 UTC, levitte commented on test/recipes/61-test_bio_readbuffer.t
> +        "running bio_readbuffer_test $derfile");
Nit: this quote should be aligned with the outermost parenthesis.  The same goes for the next test case

2021-03-18 06:47 UTC, paulidale commented on crypto/bio/bf_readbuff.c
> +            *(buf++) = p[num_chars];
consider dropping the parenthesis: it's `*buf++`

2021-03-18 06:47 UTC, paulidale commented on crypto/bio/bf_readbuff.c
> +         *(buf++) = *p;
Same here.

2021-03-18 06:47 UTC, paulidale commented on crypto/bio/bf_readbuff.c
> +     p = &(ctx->ibuf[ctx->ibuf_off]);
The parenthesis here are option too, although `p = ctx->ibuf + ctx->ibuf_off;` is even more succinct.

2021-03-18 06:57 UTC, slontis commented
looks like I have an off by 1 error here..

2021-03-18 09:47 UTC, t8m approved these changes

2021-03-18 09:59 UTC, paulidale approved these changes
I did a double take on that `1 +` but figured you knew what you were doing....

2021-03-18 23:36 UTC, slontis commented
> I did a double take on that `1 +` but figured you knew what you were doing....

Obviously not :)

2021-03-19 09:57 UTC, t8m commented
This is ready now

2021-03-21 23:10 UTC, slontis commented
Thanks for reviewing. Merged to master.

2021-03-21 23:10 UTC, closed without merging