Increase HKDF_MAXBUF from 1024 to 2048
openssl/openssl pull request #14649
Opened 2021-03-22 22:58 UTC by kaduk

We've encountered some scenarios that need to use more than 1 kB of
data as the HKDF-Expand() "info" argument (which, per RFC 5869,
contains "optional context and application specific information").

Since HKDF_MAXBUF is used to size an array in the HKDF_PKEY_CTX
structure, this adds 1 kB of memory footprint to each EVP_PKEY_CTX
used for HKDF.

2021-03-22 23:00 UTC, kaduk commented
I did not do an in-depth investigation, but I believe that there are some HKDF workflows that don't even use the `HKDF_PKEY_CTX.info` structure member.  Based on what (somewhat cursory) investigation I did, the workflows that do not use the field are short-lived ones, so perhaps the transient additional allocation is not harmful there.

I do, however, welcome opinions on how big the field has to get before we stop inlining it in the `HKDF_PKEY_CTX` and allocate it separately.  2kB is probably getting close...

2021-03-22 23:20 UTC, paulidale approved these changes
I don't see anything in the standard about limiting the size of this value.

2021-03-22 23:27 UTC, kaduk commented
> I don't see anything in the standard about limiting the size of this value.

Right, the standard does not impose any real limit (other than the max capacity of the underlying hash function) on the size here.  Having any limit at all is an implementation choice, and if we wanted to be really flexible we would allocate something on-demand and support extremely large `info` arguments.  But I'm lazy and don't want to do that if there's no real pressing need :)

2021-03-22 23:30 UTC, paulidale commented
Agreed, we can do it once the problem is reported.

2021-03-23 01:17 UTC, slontis requested changes
I went looking for the place that checks the bounds and I dont think it has any :)
If you take a look at the code in kdf_hkdf_set_ctx_params() I don't think this change is sufficient.
This particular line looks bad to me..
````
OSSL_PARAM_get_octet_string(p, (void **)&q, HKDF_MAXBUF - ctx->info_len, &sz))
````
HKDF_MAXBUF - ctx->info_len is passed as a size_t.. If it goes negative then that might not be good :) (Relying on the called function to maybe detect this is not a great idea).

2021-03-24 00:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2021-03-30 20:44 UTC, kaduk commented
> I went looking for the place that checks the bounds and I dont think it has any :)
> If you take a look at the code in kdf_hkdf_set_ctx_params() I don't think this change is sufficient.
> This particular line looks bad to me..
> 
> ```
> OSSL_PARAM_get_octet_string(p, (void **)&q, HKDF_MAXBUF - ctx->info_len, &sz))
> ```
> 
> HKDF_MAXBUF - ctx->info_len is passed as a size_t.. If it goes negative then that might not be good :) (Relying on the called function to maybe detect this is not a great idea).

I think it is actually safe as-is, though it is perhaps a little more reliant on side effects than we might want.
Specifically, the call in `kdf_hkdf_set_ctx_params()` is the only place that writes to it, and it's in a loop that only increments `ctx->info_len` if `OSSL_PARAM_get_octet_string()` succeeded.  So we rely on `OSSL_PARAM_get_octet_string()` to check the max_size, but provided it does so, we will never get to a state with `ctx->info_len > HKDF_MAXBUF`.

@slontis  Do you think I should add another check in the loop anyway?

2021-03-30 22:52 UTC, slontis approved these changes

2021-03-31 00:24 UTC, kaduk commented
Thanks for taking a second look (and it was a good question to ask in the initial review)!
Merged to master, so closing.

2021-03-31 00:24 UTC, closed without merging