Lifecycle fix: gettable -> get & settable -> set
openssl/openssl pull request #14867
Opened 2021-04-14 09:02 UTC by paulidale

Many of the lifecycle calls were gettable/settable rather than get/set.

- [x] documentation is added or updated
- [ ] tests are added or updated

2021-04-14 09:57 UTC, t8m requested changes

2021-04-14 09:57 UTC, t8m commented on doc/man7/life_cycle-kdf.pod
> + EVP_KDF_CTX_get_params                      newed       deriving
IMO this change is incorrect - you have get/set_params above already. The original was IMO correct.

2021-04-14 09:57 UTC, t8m commented on doc/man7/life_cycle-mac.pod
> + EVP_MAC_CTX_set_params                  newed    initialised   updated
This does not look correct either. The original is wrong but the new is wrong either. There should be these 4 functions EVP_MAC_CTX_get/set_params and EVP_MAC_CTX_gettable/settable_params.

2021-04-14 09:57 UTC, t8m commented on doc/man7/life_cycle-rand.pod
> + EVP_RAND_CTX_set_params            newed   instantiated  uninstantiated  freed
The original was correct. And yeah - it is awkward as the EVP_RAND_get/set_ctx_params() does not follow the naming pattern from EVP_MAC and EVP_KDF. But that rename is for a different PR.

2021-04-14 22:59 UTC, paulidale commented
I screwed things up pretty badly.  Should be fixed now.  Only the CTX functions are listed so, e.g., `EVP_MAC_settable_ctx_params` isn't listed since that's not an operation on the CTX.

2021-04-15 03:49 UTC, slontis commented on doc/man7/life_cycle-mac.pod
> +<tr><th style="border:1px solid" align="left">EVP_MAC_CTX_getablet_params</th>
tablet?

2021-04-15 04:06 UTC, paulidale commented on doc/man7/life_cycle-mac.pod
> +<tr><th style="border:1px solid" align="left">EVP_MAC_CTX_getablet_params</th>
That was easy to fix :)

2021-04-15 07:26 UTC, t8m approved these changes

2021-04-16 07:59 UTC, paulidale commented
Merged to master, thanks for the comments.

2021-04-16 07:59 UTC, closed without merging