fixes CVE-2016-6303, avoid overflow
openssl/openssl pull request #15020
Opened 2021-04-25 08:52 UTC by yasong

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2021-04-25 08:55 UTC, beldmit commented on crypto/mdc2/mdc2dgst.c
> +        if (len + i < MDC2_BLOCK) {   //repair CVE-2016-6303, avoid overflow
Could you please use C-style comments here?

2021-04-25 09:00 UTC, beldmit commented on crypto/mdc2/mdc2dgst.c
> +          /* repair CVE-2016-6303, avoid overflow */
Nit: comment is misaligned

2021-04-25 09:22 UTC, beldmit commented
Could you also submit a CLA?

2021-04-25 09:44 UTC, kroeckx commented
This reverses commit 55d83bf7c10c7b205fffa23fa7c3977491e56c07, which is the one that fixes that CVE.

2021-04-25 10:03 UTC, yasong commented
> This reverses commit [55d83bf](https://github.com/openssl/openssl/commit/55d83bf7c10c7b205fffa23fa7c3977491e56c07), which claims to fix that CVE.

Yeah, but I see that the master is not patched

2021-04-25 11:32 UTC, kroeckx commented
It is fixed. I pointed to the commit in master that fixed it. This just reintroduces the problem.

2021-04-26 01:19 UTC, yasong commented
> It is fixed. I pointed to the commit in master that fixed it. This just reintroduces the problem.

I found this [mdc2dgst.c](https://github.com/openssl/openssl/blob/master/crypto/mdc2/mdc2dgst.c) was not fixed. I do not know why.

2021-04-26 08:34 UTC, mattcaswell requested changes
This change is clearly wrong. The original code before your PR is correct and was fixed by the commit that @kroeckx points to. I'm not sure why you are claiming that it wasn't fixed.

2021-04-26 08:52 UTC, t8m commented
@yasong you are probably confused by what the CVE is about and about other constraints of the values in the code. The `i` can have value only between `0` and `MDC2_BLOCK - 1` (included).  So there cannot be an underflow of the unsigned size_t type of the right hand side. On the other hand the original comparison before the CVE fix could overflow on the left hand side because len is unbounded, bounded only by the size_t type range. You're reintroducing the CVE by this PR.

2021-04-27 00:55 UTC, yasong commented
> This change is clearly wrong. The original code before your PR is correct and was fixed by the commit that @kroeckx points to. I'm not sure why you are claiming that it wasn't fixed.



> @yasong you are probably confused by what the CVE is about and about other constraints of the values in the code. The `i` can have value only between `0` and `MDC2_BLOCK - 1` (included). So there cannot be an underflow of the unsigned size_t type of the right hand side. On the other hand the original comparison before the CVE fix could overflow on the left hand side because len is unbounded, bounded only by the size_t type range. You're reintroducing the CVE by this PR.

Thanks, now I see.

2021-04-27 04:25 UTC, slontis commented
Can this be closed?

2021-04-27 07:45 UTC, t8m commented
Closing.

2021-04-27 07:45 UTC, closed without merging