Make SSL_OP_NO_RENEGOTATION enabled by default
openssl/openssl pull request #15051
Opened 2021-04-27 19:28 UTC by richsalz

Changed a bunch of test cases that were depending on that not
being the default.  Added a new option to s_server.

I'm not thrilled with the `-no_reneg` option I added to s_server, but it seemed the cleanest approach.

No new test cases added, since most test (except those explicitly testing various TLS behavior) all worked fine.

2021-04-28 08:01 UTC, mattcaswell requested changes
This PR goes further than the suggested change in #14685. That issue talks about disabling *client initiated* renegotiation on the *server*. This PR disables all renegotiation on both client and server. That might be a breaking change further than intended.

There should also be updates to SSL_CTX_set_options.pod and SSL_CONF_cmd.pod

2021-04-28 18:23 UTC, richsalz commented
> This PR goes further than the suggested change in #14685. That issue talks about disabling _client initiated_ renegotiation on the _server_. This PR disables all renegotiation on both client and server. That might be a breaking change further than intended.

I could not figure out how to do just the server-side, since we don't know it's a server at "new" time.  Do you have a suggestion?  The use-case for client-side renegotiation seems iffy to me these days: step-up crypto is all I can think of (stronger crypto once the session starts, e.g. if using weak crypto and connect to a bank; shades of US export regulations).

> There should also be updates to SSL_CTX_set_options.pod and SSL_CONF_cmd.pod

I don't think so as there are already options there.  What where you thinking of ?

2021-04-28 18:28 UTC, richsalz commented on ssl/ssl_lib.c
> +    ret->options = SSL_OP_NO_RENEGOTIATION;
okay, moved.  updated commit pushed.

2021-04-29 07:32 UTC, mattcaswell commented
> I could not figure out how to do just the server-side, since we don't know it's a server at "new" time. Do you have a suggestion?

Well, even just restricting it to server side only would actually go beyond what #14685 suggests. That particular OP disables *all* reneg. So even if you set that OP only on the server it has the effect of disabling server initiated reneg. One possibility is to implement a new option which *only* prevents client initiated reneg. This way it can be on by default in both client and server - but only has an effect on the server side. If it is a new option it also gives us the opportunity to reverse the wording to state it as an "enable" option, e.g. `SSL_OP_ENABLE_CLIENT_RENEGOTIATION`

> I don't think so as there are already options there. What where you thinking of ?

They need updating to say that the option is enabled by default - so you need to *disable* it if you don't want it. Although if we go with my suggestion of a new OP then the point is moot.

2021-04-29 09:40 UTC, t8m commented
In light of this. Isn't it rather Post 3.0.0 thing?

2021-05-04 21:11 UTC, richsalz commented
It would be easy to do this via a new option, but adding a new option isn't currently possible; see https://github.com/openssl/openssl/issues/15145

2021-05-05 07:39 UTC, mattcaswell commented
> It would be easy to do this via a new option, but adding a new option isn't currently possible; see #15145

As noted in #15145 we still have space for 2 more options.

2021-05-06 18:38 UTC, richsalz commented
Closing in favor of #15184.  Thanks for the pointer on how to do this, @mattcaswell .

2021-05-06 18:38 UTC, closed without merging