Add BIO_new_from_core_bio() to the public API
openssl/openssl pull request #15072
Opened 2021-04-28 14:48 UTC by mattcaswell

Previously the concept of wrapping an OSSL_CORE_BIO in a real BIO was an
internal only concept for our own providers. Since this is likely to be
generally useful, we make it a part of the public API.

Fixes #14409

2021-04-28 14:49 UTC, mattcaswell commented
Note: I've not changed our internal providers to use the public API. Instead they continue to have their own "special" internal version. This is because we "cheat" and do not create a new libctx for the default and base providers, so the public API version won't work there.

2021-04-28 15:25 UTC, t8m commented
CI is relevant

2021-04-28 15:46 UTC, mattcaswell commented
Fixup pushed addressing the CI failure. Also rebased to resolve a conflict with master.

2021-04-29 13:29 UTC, paulidale commented
CIs still relevant

2021-04-29 13:35 UTC, paulidale reviewed
Looks good.

2021-04-29 13:41 UTC, mattcaswell commented
Fixup pushed addressing the CI failure

2021-04-29 14:09 UTC, t8m requested changes
Just some doc nits

2021-04-29 14:09 UTC, t8m commented on doc/man3/BIO_new.pod
> +The BIO_new_ex() function returns a new BIO using method B<type> associated with
Add a HISTORY section?

2021-04-29 14:09 UTC, t8m commented on doc/man3/BIO_s_core.pod
> +=head1 COPYRIGHT
Perhaps also add a HISTORY section?

2021-04-29 14:09 UTC, t8m commented on doc/man3/OSSL_LIB_CTX.pod
> +OSSL_LIB_CTX, OSSL_LIB_CTX_new, OSSL_LIB_CTX_new_from_dispatch,
The HISTORY section should be updated to mention that all the functions were added in 3.0.

2021-04-29 14:09 UTC, t8m commented on doc/man3/OSSL_LIB_CTX.pod
> +one as passed to a provider's OSSL_provider_init function in the B<in> argument.
Nit: `I<in>`

2021-04-29 14:09 UTC, t8m commented on doc/man3/BIO_new.pod
> +the library context B<libctx> (see OSSL_LIB_CTX(3)). The library context may be
`I<libctx>`

2021-04-29 14:09 UTC, t8m commented on doc/man3/BIO_new.pod
> +The BIO_new() is the same as BIO_new_ex() excpet the default library context is
Typo: except

2021-04-29 14:51 UTC, mattcaswell commented
All feedback addressed. Please take another look.

2021-04-29 14:57 UTC, t8m approved these changes

2021-04-30 15:00 UTC, openssl-machine commented
This pull request is ready to merge

2021-05-04 10:38 UTC, t8m commented
@mattcaswell would you merge this? I suppose this will most probably need make update after merge due to changing the FIPS checksum.

2021-05-04 11:03 UTC, mattcaswell commented
> @mattcaswell would you merge this?

Done

> I suppose this will most probably need make update

Yes due to conflicts in libcrypto.num. I resolved during merge.

> after merge due to changing the FIPS checksum.

No, because none of this is inside the FIPS boundary.

2021-05-04 11:03 UTC, closed without merging