Makefile: speed up 'make ordinals' and 'make update'
openssl/openssl pull request #15224
Opened 2021-05-11 11:03 UTC by DDvO

`make ordinals` so far is awkward to use because it unconditionally calls `mknum.pl`, which is very inefficient.
This is particularly annoying if `make update` etc. needs to be called often. 

This PR makes sure that `mknum.pl` gets called only if one of its input files changes.

2021-05-11 13:38 UTC, DDvO commented
It turns out that `make update` still caused `mknum.pl` to be called each time
because `make generate_crypto_objects` re-generated `include/openssl/obj_mac.h` unconditionally.

So I've added a commit such that the crypto objects are (re-)generated only as far as needed.

2021-05-12 06:37 UTC, levitte commented
`make update` should really not need to be called so often...  and wasn't until the checksum stuff was added.  We had a team discussion on that topic yesterday, and I believe there's work going on to separate out the checksum stuff.

2021-05-12 08:05 UTC, DDvO commented
> `make update` should really not need to be called so often... and wasn't until the checksum stuff was added. We had a team discussion on that topic yesterday, and I believe there's work going on to separate out the checksum stuff.

Very good that contributors are going to get relieved from the FIPS checksum updates.

Nevertheless many contributors still need to call `make update`
because it includes also `make ordinals` and `make errors`, 
which are required to update `util/lib{crypto,ssl}.num` and the libcrypto error codes and strings.

2021-05-12 09:01 UTC, paulidale commented
I still like to see this speed up in.  I never remember the individual targets and use `make update` for all.

2021-05-12 09:09 UTC, paulidale reviewed
This looks good to me. I'd like someone who knows the build infrastructure to review too.

2021-05-12 09:34 UTC, DDvO commented
BTW, in the second commit of this PR, which adapt the sub-goals of `generate` 
I kept those sub-goals:
```
          generate_apps generate_crypto_bn generate_crypto_objects \
          generate_crypto_conf generate_crypto_asn1 generate_fuzz_oids
```
in order to make the changes most conservative,
but we could simplify this by removing them and let the `generate` goal directly depend on the relevant input files such as `crypto/objects/objects.txt`.

How if I make this simplification, or is there the need to keep those sub-goal names?

2021-05-24 13:06 UTC, DDvO commented
> This looks good to me. I'd like someone who knows the build infrastructure to review too.

Who of the other @openssl/otc members is willing to do a 2nd review?

2021-06-24 00:06 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2021-06-24 02:52 UTC, levitte requested changes
You forgot `$(SRCDIR)/`....

2021-06-24 02:52 UTC, levitte commented on Configurations/unix-Makefile.tmpl
> +apps/openssl-vms.cnf: apps/openssl.cnf
Here

2021-06-24 02:52 UTC, levitte commented on Configurations/unix-Makefile.tmpl
> +generate_apps: apps/openssl-vms.cnf
Here

2021-06-24 02:52 UTC, levitte commented on Configurations/unix-Makefile.tmpl
> +crypto/bn/bn_prime.h: crypto/bn/bn_prime.pl
Here

2021-06-24 02:52 UTC, levitte commented on Configurations/unix-Makefile.tmpl
> +generate_crypto_bn: crypto/bn/bn_prime.h
Here

2021-06-24 02:52 UTC, levitte commented on Configurations/unix-Makefile.tmpl
> +crypto/conf/conf_def.h: crypto/conf/keysets.pl
Here

2021-06-24 02:52 UTC, levitte commented on Configurations/unix-Makefile.tmpl
> +generate_crypto_conf: crypto/conf/conf_def.h
Here

2021-06-24 02:52 UTC, levitte commented on Configurations/unix-Makefile.tmpl
> +crypto/asn1/charmap.h: crypto/asn1/charmap.pl
Here

2021-06-24 02:52 UTC, levitte commented on Configurations/unix-Makefile.tmpl
> +generate_crypto_asn1: crypto/asn1/charmap.h
Here

2021-06-24 02:52 UTC, levitte commented on Configurations/unix-Makefile.tmpl
> +fuzz/oids.txt: fuzz/mkfuzzoids.pl crypto/objects/obj_dat.h
Here

2021-06-24 02:52 UTC, levitte commented on Configurations/unix-Makefile.tmpl
> +generate_fuzz_oids: fuzz/oids.txt
Here

2021-06-24 02:53 UTC, levitte commented on Configurations/unix-Makefile.tmpl
>  				> fuzz/oids.txt )
These lines are slightly misplaced

2021-06-24 12:58 UTC, DDvO commented
> You forgot `$(SRCDIR)/`....

Thx for pointing this out; fixed all occurrences.

2021-06-24 12:59 UTC, DDvO commented on Configurations/unix-Makefile.tmpl
>  				> fuzz/oids.txt )
Oops, fixed.

2021-06-24 13:17 UTC, richsalz commented
Get rid of the `lint` target while you're at it.

2021-06-24 19:40 UTC, DDvO commented
> Get rid of the `lint` target while you're at it.

Ah, I was not aware that there is a `lint` target!
Why not keep it? I tentatively revived it.

Doing so, I noticed that my Debian does not provide `lint` but I was able to install and use `splint` - does this make sense?
Unfortunately, it produces tons of findings, and after a while it crashes as follows:
```
crypto/asn1/a_dup.c:97:2: *** Internal Bug at constraintGeneration.c:1381:
    llassert failed: exprNode_isDefined(t1) [errno: 25]
     *** Please report bug to submit@bugs.debian.org (via reportbug) ***
       (attempting to continue, results may be incorrect)
*** Segmentation Violation
*** Location (not trusted): crypto/asn1/a_dup.c:97:2
*** Last code point: transferChecks.c:4415
*** Previous code point: transferChecks.c:4002
*** Please report bug to submit@bugs.debian.org (via reportbug)
*** A useful bug report should include everything we need to reproduce the bug.
```

Yet still this way I was able to spot two nits regarding header files; fixed them.

2021-06-24 19:47 UTC, DDvO commented
Handling `lint` inevitably seduced me to add a `check-format:` target :wink:

As expected, also this tool produces an enormous number of findings:
```
37701 (16350 indentation, 8263 directive nesting, 104 syntax, 6214 whitespace, 4365 length, 2405 other)
 issues have been found by ./util/check-format.pl
```

2021-06-24 20:02 UTC, richsalz commented
The lint target does not work and is superseded by warnings the compilers can generate these days; delete it.

2021-06-25 06:30 UTC, DDvO commented
> The lint target does not work and is superseded by warnings the compilers can generate these days; delete it.

I'm not sure myself if keeping the `lint` target makes sense.

`sqlint` gives much more findings than the compilers with the settings that we currently use.
I did not have a close look, 
but part of the findings appear helpful, while many are too pedantic and there may be false positives.

What do others think?

2021-06-25 06:59 UTC, DDvO commented
Carved out yesterday's additions (regarding targets for static analysis tools) to a separate PR:  #15913.

2021-06-25 07:01 UTC, DDvO commented
BTW, yesterday there were two unrelated CI failures like this:
```
Run ilammy/setup-nasm@v1
Downloading binary distribution...
Warning: binaries did not work: FetchError: request to https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip failed, reason: connect ECONNREFUSED 198.137.202.136:443
Downloading source code...
Warning: source code did not work: FetchError: request to https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.gz failed, reason: connect ECONNREFUSED 198.137.202.136:443
Error: could not install NASM: Error: I'm sorry, Dave. I'm afraid I can't do that.
```
I wonder if it makes sense to download and install such tools on each and every CI run.

2021-06-28 09:54 UTC, t8m commented
> I wonder if it is required to download and install such tools on each and every CI run.

This is kind of _official_ way how to use nasm in GitHub Actions CI. So I am not sure there is any reasonable way around that. We certainly do not want to include the binary blobs in our tree.

2021-06-28 10:05 UTC, DDvO commented
> > I wonder if it is required to download and install such tools on each and every CI run.
> 
> This is kind of _official_ way how to use nasm in GitHub Actions CI. So I am not sure there is any reasonable way around that. We certainly do not want to include the binary blobs in our tree.

Is there maybe a way of caching the binary on the system doing the CI runs?

2021-07-29 00:06 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2021-07-29 05:11 UTC, levitte commented
> > > I wonder if it is required to download and install such tools on each and every CI run.
> > 
> > 
> > This is kind of _official_ way how to use nasm in GitHub Actions CI. So I am not sure there is any reasonable way around that. We certainly do not want to include the binary blobs in our tree.
> 
> Is there maybe a way of caching the binary on the system doing the CI runs?

Unfortunately not.  Each job runs a fresh container image with certain pre-installed pieces of software (there is github documentation that tells exactly which they are).  Nasm isn't one of them.

2021-07-29 06:08 UTC, mspncp commented
> > > > I wonder if it is required to download and install such tools on each and every CI run.
> > > 
> > > 
> > > This is kind of _official_ way how to use nasm in GitHub Actions CI. So I am not sure there is any reasonable way around that. We certainly do not want to include the binary blobs in our tree.
> > 
> > 
> > Is there maybe a way of caching the binary on the system doing the CI runs?
> 
> Unfortunately not. Each job runs a fresh container image with certain pre-installed pieces of software (there is github documentation that tells exactly which they are). Nasm isn't one of them.

The best solution might be to use a [customized Docker container for the actions](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action). I don't have much experience with Docker containers in the context of GitHub Actions, but I solved a similar problem (missing tools for pre-receive hooks) on my Company's GitHub Enterprise Server by [creating a customized pre-receive hook environment](https://docs.github.com/en/enterprise-server@3.1/admin/policies/enforcing-policy-with-pre-receive-hooks/creating-a-pre-receive-hook-environment) using Docker. Setting up a standard Alpine Linux container with just a few extra tools preinstalled wasn't too hard, even for someone like me without Docker experience like me. There are examples out there explaining how it's done.

2022-03-15 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 217 days ago

2022-04-15 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 248 days ago

2022-05-16 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 279 days ago

2022-06-16 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 310 days ago

2022-07-17 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 341 days ago

2022-08-17 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 372 days ago

2022-08-17 06:44 UTC, DDvO commented
Rebased to fix merge conflicts

2022-08-17 07:53 UTC, DDvO commented
How to move on with this PR?

2022-08-17 23:48 UTC, paulidale commented
As mentioned, the changes look good to me but I can only do a fairly superficial review.

2022-08-20 07:27 UTC, DDvO commented
Thanks Pauli for your comment.
Who can help out reviewing this?

2022-08-22 01:31 UTC, paulidale commented
@levitte knows the most about this.  I'm not sure who'd be second.

2022-08-22 05:52 UTC, levitte approved these changes
LGTM at this point

2022-08-22 06:58 UTC, t8m approved these changes

2022-08-23 06:53 UTC, DDvO commented
Merged - thanks @levitte, @t8m, @paulidale et al.
How about backporting this to 3.0?

2022-08-23 07:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2022-08-23 07:03 UTC, t8m commented
> How about backporting this to 3.0?

IMO it does not belong there.

2022-08-23 07:07 UTC, DDvO commented
I see, so closing.

2022-08-23 07:08 UTC, closed without merging

2022-08-30 05:04 UTC, levitte commented
Unfortunately, this change has consequences.  I now vaguely recall having tried this exercise years ago, and finding that it doesn't work out so well.

See #19087.

I wish I had remembered this earlier.

2022-09-08 13:35 UTC, t8m commented
Another probable consequence: #19170

2022-09-08 13:35 UTC, t8m commented
Maybe it would be better to revert this?