Add no-banner/enable-banner config option
openssl/openssl pull request #15248
Opened 2021-05-12 14:45 UTC by richsalz

Use it in the automated workflows.

Where do I update things so that the FIPS config/build stuff adds this flag?  Ping @t8m

2021-05-12 14:52 UTC, levitte commented
Not sure I like `no-banner`...  makes it look like a building option like, say, `no-fips`.  I'm pretty sure you now have a macro `OPENSSL_NO_BANNER`, among others :wink:

2021-05-12 15:21 UTC, richsalz commented
Based on your comment, I changed it to `--banner="text..." which I think is better.

2021-05-12 15:32 UTC, levitte requested changes

2021-05-12 15:32 UTC, levitte commented on .github/workflows/ci.yml
> +      run: ./config --baner=Configured --strict-warnings enable-fips && perl configdata.pm --dump
You might want to check your spelling :wink:

2021-05-12 15:32 UTC, levitte commented on Configure
> +print $banner;
A detail, you might want to consider this:

``` perl
$banner .= "\n" unless $banner =~ m|\R$|;
print $banner;
```

This is to make sure that, for example, `--banner=Blah-di-blah` doesn't give you a weird looking prompt on Unixly environments:

``` console
$ ./Configure --banner=Blah-di-blah
...
Blah-di-blah$ [blinking cursor here]
```

2021-05-12 15:40 UTC, richsalz commented
i had already fixed the issues you found, @levitte  Taken out of draft.

2021-05-12 16:29 UTC, levitte approved these changes

2021-05-12 23:06 UTC, slontis approved these changes

2021-05-14 00:00 UTC, openssl-machine commented
This pull request is ready to merge

2021-05-14 06:37 UTC, levitte commented
Merged after a slight edit of the commit message (modified to say `--banner`)

d0364dcc42b151cfc08d860efb15cd48d87302c6 Add --banner config option

2021-05-14 06:37 UTC, closed without merging

2021-05-14 13:58 UTC, richsalz commented
> Merged after a slight edit of the commit message (modified to say --banner)

Oh yeah, thanks.  I realized that the message had become out of date, and then forgot to do anything about it :)