Create symlinks when installing man pages
openssl/openssl pull request #15312
Opened 2021-05-17 16:43 UTC by mattcaswell

In 1.1.1 when installing the man pages we created symlinks to the base
page for all functions described on the page. We need to continue doing
this.

Fixes #14846

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2021-05-17 17:08 UTC, levitte approved these changes

2021-05-17 17:08 UTC, levitte commented
Looked easy enough :-)

2021-05-18 01:46 UTC, slontis commented
The 'out-of-source-and-install' issue looks like it may be relevant.

2021-05-18 01:48 UTC, slontis requested changes
Error needs fixing

2021-05-18 14:15 UTC, mattcaswell commented
Grr. Sometimes the pod files are in the srcdir and sometimes they're in the build dir depending on whether they are generated or not. Fixup pushed.

Please reconfirm.

2021-05-18 16:29 UTC, t8m approved these changes

2021-05-19 17:00 UTC, openssl-machine commented
This pull request is ready to merge

2021-05-20 09:29 UTC, mattcaswell commented
Pushed. I modified the copyright year while merging to only claim copyright for this year.

2021-05-20 09:29 UTC, closed without merging