VMS: don't use app_malloc() in apps/lib/vms_decc_argv.c
openssl/openssl pull request #15368
Opened 2021-05-20 08:41 UTC by levitte

The reason being that it would otherwise force test programs to link
with all of libapps.a, which unfortunately causes multiple symbol
definition issues.

The quick and dirty fix is to use malloc() instead of app_malloc() in
apps/lib/vms_decc_argv.c, and clean up libapps.a later.

-----

This is a quick'n'dirty alternative to #15342

2021-05-20 08:41 UTC, levitte commented
I'm keeping this in draft until I've verified that it works as expected

2021-05-20 09:02 UTC, slontis commented
Is there a reason not to just use OPENSSL_malloc()?  All the frees would be done with OPENSSL_free().

2021-05-20 09:07 UTC, levitte commented
> Is there a reason not to just use OPENSSL_malloc()? All the frees would be done with OPENSSL_free().

I..  haven't tried that, didn't even think of it.  Will do

2021-05-20 11:39 UTC, levitte commented
This is now confirmed to build correctly

2021-05-20 22:49 UTC, slontis commented
I dont see a problem with this approach.. I would not even consider it hacky now.

2021-05-21 01:14 UTC, paulidale requested changes

2021-05-21 01:14 UTC, paulidale commented on apps/lib/vms_decc_argv.c
> +     * We purposefully use malloc() rather than app_malloc() here, to avoid
The comment is now wrong.

2021-05-21 03:22 UTC, levitte commented on apps/lib/vms_decc_argv.c
> +     * We purposefully use malloc() rather than app_malloc() here, to avoid
Fixed

2021-05-21 03:47 UTC, paulidale approved these changes

2021-05-21 03:48 UTC, paulidale commented
Much nicer approach.

2021-05-21 03:55 UTC, levitte commented
> Much nicer approach.

Yeah well, libapps is still of mess...  but at least, we don't need to rush clearing that up

2021-05-21 06:00 UTC, paulidale commented
There is quite a bit of cleanup I'd like to do in apps....

2021-05-21 06:33 UTC, levitte commented
> There is quite a bit of cleanup I'd like to do in apps....

[ahem] I'll raise you one...  I'd like to rebuild it all from scratch, and as a separate project.

2021-05-22 04:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2021-05-22 05:21 UTC, levitte commented
Merged

a066841554bd23281ae4bb48badc088753f734ca VMS: don't use app_malloc() in apps/lib/vms_decc_argv.c

2021-05-22 05:21 UTC, closed without merging