Fix memory leak in OSSL_CMP_CTX
openssl/openssl pull request #15458
Opened 2021-05-25 13:58 UTC by gotthardp

The `ctx->propq` is `strdup`ed, so it must be `free`d too.

2021-05-25 15:12 UTC, t8m requested changes

2021-05-25 16:02 UTC, gotthardp commented on crypto/cmp/cmp_ctx.c
> +    OPENSSL_free((char *)ctx->propq);
OK, done.

2021-05-25 16:10 UTC, t8m approved these changes

2021-05-26 19:12 UTC, kaduk approved these changes

2021-05-27 20:00 UTC, openssl-machine commented
This pull request is ready to merge

2021-05-28 09:11 UTC, levitte commented
CI failure not relevant.  I'm merging this now

2021-05-28 09:13 UTC, levitte commented
Merged

32075a17249636b3e2986a0ac422b1803663ccaa Fix memory leak in OSSL_CMP_CTX

2021-05-28 09:13 UTC, closed without merging