Deprecated SXNET, some old NETSCAPE data types
openssl/openssl pull request #15464
Opened 2021-05-25 16:19 UTC by richsalz

Support for the SXNET and (Thawte Strong Extranet) certificate extension,
the NETSCAPE_CERT_SEQUENCE, NETSCAPE_SPKAC, and NETSCAPE_SPKI datatypes
have been deprecrated.

Fixes #1177, #10668

Deprecate things now so they can be removed when ready.

2021-05-26 20:47 UTC, richsalz commented
Any clues appreciated.  You'd think I would know how to do deprecations by now.

2021-06-02 18:09 UTC, richsalz commented
CI's pass, this is ready for review. It deprecates things that the project will want to remove in the future. From CHANGES:
```
 * Support for the SXNET (Thawte Strong Extranet) certificate extension,
   the NETSCAPE_CERT_SEQUENCE, NETSCAPE_SPKAC, and NETSCAPE_SPKI datatypes
   have been deprecrated.
```

2021-06-02 18:32 UTC, FdaSilvaYY commented on CHANGES.md
> +   have been deprecrated.
typo: deprecrated

2021-06-02 18:35 UTC, richsalz commented on CHANGES.md
> +   have been deprecrated.
typo fixed; fixup commit pushed. thanks!

2021-06-03 09:00 UTC, t8m requested changes

2021-06-03 15:26 UTC, richsalz commented on apps/ca.c
> +#ifndef OPENSSL_NO_DEPRECATED_3_0
No, `OPT_SPKAC` still shows in the enum list, so we need a `case` statement to handle it.  It's similar to how `OPT_ENGINE` is handled, where the enum is present, but the body ends up being no-ops for the `no-engine` config.

I think doing things this way minimizes the ifdef mazes and makes it clear that the code does nothing.  YMMV.

2021-06-03 15:28 UTC, richsalz commented on crypto/pem/pem_all.c
> -                 PEM_STRING_X509, NETSCAPE_CERT_SEQUENCE)
`PEM_STRING_x509` is used in many places. Did you mean something else, like `pkey_get_rsa` etc?

2021-06-03 15:30 UTC, richsalz commented on crypto/asn1/nsseq.c
> +#include "internal/deprecated.h"
Can you explain why the define is better than the header file?  And for bonus credit, when each should be used?
```
; g grep internal/deprecated.h | wc
    329     668   20577
; g grep OPENSSL_SUPPRESS_DEPRECATED | wc
     85     189    5061
```

2021-06-03 15:35 UTC, richsalz commented on doc/man3/X509V3_get_d2i.pod
> +
I have no idea why I did that.  Zombies.  Reverted, updated fixup commit pushed.

2021-06-03 16:01 UTC, t8m commented on crypto/pem/pem_all.c
> -                 PEM_STRING_X509, NETSCAPE_CERT_SEQUENCE)
Just a confusion on my side when skimming through the PR.

2021-06-03 16:01 UTC, t8m commented on apps/ca.c
> +#ifndef OPENSSL_NO_DEPRECATED_3_0
OK

2021-06-03 17:53 UTC, richsalz commented
@t8m: Should I create `crypto/asn1/asn1_depr` which has `t_spki` `x_spki` and `nsseq` ?

2021-06-04 10:39 UTC, t8m commented
> @t8m: Should I create `crypto/asn1/asn1_depr` which has `t_spki` `x_spki` and `nsseq` ?

I do not think it is necessary.

2021-06-04 10:39 UTC, t8m approved these changes

2021-06-08 08:45 UTC, mattcaswell commented
OTC: We won't be doing this for 3.0. Setting the Post 3.0 milestone.

2021-06-09 19:23 UTC, richsalz commented
As this has been moved to post-3.0, please remove the "approved" label; thanks.

2021-09-07 19:36 UTC, closed without merging