Fix up O/S name for AIX so we can correctly skip the CMP http test
openssl/openssl pull request #15469
Opened 2021-05-25 23:03 UTC by jon-oracle

The O/S name for AIX was being incorrectly matched to 'AIX'. I checked the actual value returned on an AIX box:

```
bash-4.2$ perl -e "print \"O/S is: $^O\n\""
O/S is: aix
```

This fits with what is listed in the perl docs here:

https://perldoc.perl.org/perlport#PLATFORMS

It seems the O/S name for most platforms is the string returned by 'uname -a' lowercased, with a few exceptions (MSWin, VMS, MacOS).

- [X] tests are added or updated

2021-05-26 00:56 UTC, slontis reviewed
Thanks Jon - it was on my list..
@levitte does this point to something else being wrong?

2021-05-26 01:02 UTC, paulidale approved these changes

2021-05-26 01:39 UTC, t-j-h commented
Works for me too on current AIX 7.2 system.
Unknown if this has previously been handled differently as it seems strange to pop up now and not earlier.
Now the entirely separate question is why are we skipping this test on AIX itself ... but that isn't what this PR is about.

2021-05-26 01:41 UTC, slontis commented
I put the AIX bit a while ago to try to fix the problem - just didnt get back to fix it..

2021-05-26 01:43 UTC, slontis commented
There are a few other files that do

plan skip_all => 'Test is disabled on AIX' if config('target') =~ m|^aix|;

2021-05-26 01:45 UTC, t-j-h commented
Is there an issue tracking the AIX underlying issue? 
It seems strange to disable tests which should work on all unix-like platforms at least.
And we should have issues tracking that we have done that and look at sorting that out. 
If someone wants to run on a platform where make test doesn't work - that is their choice - but disabling parts of the test suite for a specific platform where they should actually work seems like a rather slippery slope. Again not this PR - hence the approval - but would be good to know there is an issue tracking the AIX-disables-tests mess.

2021-05-26 02:11 UTC, slontis commented
The history of the file will tell you this...

AIX has permission problems of the form:

lsof: can't open /dev/mem: Permission denied
lsof: can't open /dev/kmem: Permission denied

2021-05-26 02:15 UTC, levitte approved these changes

2021-05-26 02:18 UTC, levitte commented
This test recipe has recently been changed not to use lsof...  so it seems to mean that AIX can be rightfully dropped from the skip list.

2021-05-26 02:25 UTC, slontis commented
> This test recipe has recently been changed not to use lsof... so it seems to mean that AIX can be rightfully dropped from the skip list.

Has that been merged - I imagine Jon has not added this just for fun..

2021-05-26 02:38 UTC, levitte commented
> Has that been merged

Yup, was part of #15281, which was merged about two weeks ago.

2021-05-26 02:40 UTC, levitte commented
Now, I don't know if there were *other* reasons why running this recipe on AIX is a bad idea...  but the `lsof` reason is at least gone.

2021-05-27 02:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2021-05-27 11:36 UTC, t8m commented
@t-j-h Did you mean to approve this as just label was changed but formal review approval not done.

2021-05-28 03:30 UTC, slontis requested changes
It appears that the lsof is not a problem now.. There are other problems now on AIX with this test.

2021-06-01 15:03 UTC, t8m commented
@slontis it is unclear to me what is wrong with this PR as it is not changing anything in regards to the CMP on AIX, it just fixes the AIX system name detection. Did you remove the `approval: done` by mistake?

2021-06-01 15:06 UTC, t8m approved these changes

2021-06-01 22:02 UTC, jon-oracle commented
Could you hold off on this PR? 

I'm investigating the actual test failures on AIX and will post another PR soon to fix them up. I'm almost ready so I don't think we'll need to disable this test now.

2021-06-01 22:55 UTC, slontis requested changes
This was disabled on AIX because lsof was causing privilege problems on our machines.
Now that lsof is not being used another problem has occurred that may be fixable. Hence the hold on this PR.

2021-06-01 22:59 UTC, t-j-h commented
lsof is not something that is present on a base standard AIX install so we cannot have tests that depend on it existing that run for that platform. That hasn't changed.

2021-06-01 23:05 UTC, slontis commented
>lsof is not something that is present on a base standard AIX install so we cannot have tests that depend on it existing that run for that platform. That hasn't changed.

See above 'Now that lsof is not being used'.

2021-06-02 03:47 UTC, jon-oracle commented
Closing for now in favor of #15575

2021-06-02 03:47 UTC, closed without merging