Internalise the XXX_get_numbers() calls
openssl/openssl pull request #15564
Opened 2021-06-01 11:45 UTC by paulidale

Fixes #15530

- [x] documentation is added or updated
- [ ] tests are added or updated

2021-06-01 11:56 UTC, t8m requested changes

2021-06-01 11:56 UTC, t8m commented on doc/man3/OSSL_ENCODER.pod
> +ossl_encoder_get0_name() returns the name used to fetch the given I<encoder>.
Uppercase OSSL_ENCODER_get0_name

2021-06-01 11:56 UTC, t8m commented on doc/man3/OSSL_DECODER.pod
> +ossl_decoder_get0_name() returns the name used to fetch the given I<decoder>.
Uppercase OSSL_DECODER_get0_name

2021-06-01 11:58 UTC, paulidale commented on doc/man3/OSSL_ENCODER.pod
> +ossl_encoder_get0_name() returns the name used to fetch the given I<encoder>.
Doh!

Fixed.

2021-06-01 12:06 UTC, t8m approved these changes

2021-06-02 10:47 UTC, paulidale commented
Merged to master, thanks for the reviews.

2021-06-02 10:47 UTC, closed without merging