Add a gettable for provider ciphers to return the EVP_CIPH_RAND_KEY flag
openssl/openssl pull request #15606
Opened 2021-06-03 09:23 UTC by slontis

Fixes #15531

DES and TDES set this flag which could possibly be used by applications.
The gettable cipher param OSSL_CIPHER_PARAM_HAS_RAND_KEY has been added.

Note that EVP_CIPHER_CTX_rand_key() uses this flag.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

2021-06-03 09:37 UTC, paulidale approved these changes

2021-06-03 09:37 UTC, paulidale commented on providers/implementations/include/prov/ciphercommon.h
> +#define PROV_CIPHER_FLAG_VARIABLE_LENGTH  0x0100
I'd have made these 0x4000 and 0x8000 to keep them as far out of the way as possible.  Not a biggie, what's here works.

2021-06-03 09:37 UTC, paulidale commented on test/evp_libctx_test.c
> + * This test makes sure that EVP_CIPHER_CTX_rand_key() works correctly
Full stop at the end of the sentence :)

2021-06-04 10:00 UTC, openssl-machine commented
This pull request is ready to merge

2021-06-04 14:08 UTC, t8m requested changes

2021-06-04 14:08 UTC, t8m commented on test/evp_libctx_test.c
> +#ifndef OPENSSL_NO_DSA
This should be OPENSSL_NO_DES.

2021-06-04 14:08 UTC, t8m commented on test/evp_libctx_test.c
> +#ifndef OPENSSL_NO_DSA
And here as well.

2021-06-05 00:57 UTC, slontis commented on test/evp_libctx_test.c
> +#ifndef OPENSSL_NO_DSA
It is strange that this even passes..

2021-06-07 05:43 UTC, paulidale approved these changes

2021-06-07 09:40 UTC, t8m approved these changes

2021-06-08 05:16 UTC, paulidale commented
Merged.

2021-06-08 05:16 UTC, closed without merging