Clean up the encoder/decoder/loader stores before providers
openssl/openssl pull request #15741
Opened 2021-06-14 13:26 UTC by mattcaswell

We already had the evp method store being cleaned up before the provider
store was. This prevents issues where the method clean up functions cause
providers to clean up, which then needs access to the provider store. We
extend the same thinking to the encoder/decoder/loader stores.

Fixes #15727

2021-06-14 16:32 UTC, t8m approved these changes

2021-06-14 22:44 UTC, paulidale requested changes

2021-06-14 22:44 UTC, paulidale commented on test/provfetchtest.c
> +#undef STORE
This look bogus.

2021-06-14 22:44 UTC, paulidale commented on test/provfetchtest.c
> +static const OSSL_ALGORITHM dummy_store[] = {                         \
Drop the trailing \

2021-06-15 07:19 UTC, mattcaswell commented
Fixup pushed addressing the feedback. Also fixed some dodgy indentation.

@t8m please reconfirm

2021-06-15 07:35 UTC, paulidale approved these changes

2021-06-15 10:01 UTC, t8m approved these changes
Reconfirmed

2021-06-15 10:39 UTC, mattcaswell commented
Windows CI failures do not seem relevant (network issues).

2021-06-15 12:14 UTC, gotthardp commented
It works, but for a RAND provider I am getting a similar error. Should the same be applied to RAND too?

2021-06-15 12:49 UTC, mattcaswell commented
> It works, but for a RAND provider I am getting a similar error. Should the same be applied to RAND too?

Hmmm. That might be a different problem. Could you raise a new issue with the error you see with RAND?

2021-06-15 12:56 UTC, mattcaswell commented
Windows CI build failures are not relevant.

2021-06-16 10:23 UTC, mattcaswell commented
Pushed. Thanks. I fixed the trivial conflict in build.info as part of the merge.

2021-06-16 10:23 UTC, closed without merging