cross-reference the DH and RSA SECLEVEL to level of security mappings
openssl/openssl pull request #15853
Opened 2021-06-21 14:53 UTC by tomato42

Since the DH check is used only in DHE-PSK ciphersuites, it's
easy to miss it when updating the RSA mapping. Add cross-references
so that they remain consistent.

##### Checklist

- [x] documentation is added or updated

2021-06-21 23:17 UTC, paulidale approved these changes

2021-06-22 07:54 UTC, t8m commented
Adding hold to discuss on OTC meeting whether this is sufficient fix or whether we want something that would avoid the data duplication.

2021-06-22 08:40 UTC, paulidale commented
The two instances are in different libraries: one is libcrypto and the other libssl.
Making them common means another public API.

2021-06-22 08:58 UTC, t8m commented
It could be just a macro containing the table initializer in an include/internal header. Making them common means another public API.

2021-06-22 09:24 UTC, t-j-h approved these changes

2021-06-22 09:29 UTC, t8m requested changes

2021-06-22 09:29 UTC, t8m commented on crypto/x509/x509_vfy.c
> +/* note that there's a corresponding minbits_table in ssl/ssl_cert.c
The format of the comment is wrong. It should start with `/*` on a separate line.

2021-06-22 09:29 UTC, t8m commented on ssl/ssl_cert.c
> +    /* note that there's a corresponding minbits_table
Same as above.

2021-06-22 09:30 UTC, t8m commented
> It could be just a macro containing the table initializer in an include/internal header. Making them common means another public API.

This was discussed within OTC and decided to postpone Post 3.0 if someone wants to do that.

2021-06-22 10:02 UTC, t8m commented
@paulidale IMO this hold is not necessary here. This PR is adding a cross-ref comment, which makes sense as a kind of code clarity bug fix. We decided to accept the PR on the OTC (with fix to the comment formatting) and just postpone any possible better fix to the data duplication in the source.

2021-06-22 10:03 UTC, t8m commented
Clearing also the approval because the comments need to be reformatted.

2021-06-22 11:52 UTC, paulidale approved these changes

2021-06-22 12:53 UTC, t8m approved these changes

2021-06-22 12:54 UTC, t8m commented
I assume Tim's approval still holds as just the formatting changed.

2021-06-22 13:09 UTC, t-j-h approved these changes

2021-06-22 13:10 UTC, t-j-h commented
I didn't see a need to clear the approval given it was basically a "nit" change.

2021-06-22 13:26 UTC, t8m commented
I just wanted to avoid merging this by accident without the nit change.

2021-06-22 23:26 UTC, paulidale commented
Merged, thanks for the update.

2021-06-22 23:26 UTC, closed without merging