Ensure ordinals are created during release process
openssl/openssl pull request #15901
Opened 2021-06-24 15:54 UTC by mattcaswell

We introduce a new makefile target "make release-update" that forces
ordinal file renumbering, and also does the fips checksum updates. We
then call that  from the release script.

Fixes #15806

2021-06-24 20:22 UTC, levitte requested changes
This means that we will do the renumber *every* release, even every alpha.  That's a bit brutal, isn't it?  After all, there was a reason for 17213b2ad03fe577c03a3e77142242adde41fa9f, as the sudden numbers caused a number of merge conflicts that were more disruptive than beneficial...

I would be better to do the renumbering under specific conditions.  `dev/release-aux/release-version-fn.sh` serves a few variables, and I would expect that checking if it's the empty string or `"beta"` would be good enough criteria to launch a renumber *separately*...

2021-06-24 20:22 UTC, levitte commented on Configurations/unix-Makefile.tmpl
> +                update-fips-checksums
Hmmmm...

2021-06-24 20:22 UTC, levitte commented on dev/release.sh
> +make release-update >&42
Hmmm.....

2021-06-25 10:23 UTC, mattcaswell commented
I added a check to avoid doing the renumber in an alpha release. Please take another look.

2021-06-26 14:00 UTC, paulidale approved these changes

2021-06-27 15:00 UTC, openssl-machine commented
This pull request is ready to merge

2021-06-28 23:51 UTC, paulidale commented
Merged.

2021-06-28 23:51 UTC, closed without merging