DOC: clarify OPENSSL_API_COMPAT
openssl/openssl pull request #15956
Opened 2021-06-30 04:33 UTC by levitte

Fixes #15928

2021-06-30 05:26 UTC, paulidale approved these changes

2021-06-30 08:47 UTC, t8m requested changes

2021-06-30 08:47 UTC, t8m commented on doc/man7/openssl_user_macros.pod.in
> +If B<OPENSSL_API_COMPAT> is undefined, this default value is be used in its
s/is be used/is used/

2021-06-30 08:57 UTC, levitte commented on doc/man7/openssl_user_macros.pod.in
> +If B<OPENSSL_API_COMPAT> is undefined, this default value is be used in its
Fixed

2021-06-30 09:19 UTC, t8m approved these changes

2021-06-30 10:45 UTC, paulidale approved these changes

2021-06-30 16:46 UTC, kroeckx commented
> Fixes #15928

This does not fix the issue that was reported. The define did
exist by default in 1.1.1, and doesn't in 3.0.

2021-06-30 20:27 UTC, levitte commented
@kroeckx, I saw it as a documentation issue.  It's pretty much undocumented in 1.1.1, and what there is in CHANGES says that it's a macro that the application defines, which *by consequence* means that it may absolutely be undefined.  I see the default definition in 1.1.1 as accidental, not something to be trusted... an implementation detail, if you will.

The modified documentation clarifies this.

2021-06-30 20:29 UTC, levitte commented
Another detail is the different sort of values that `OPENSSL_API_COMPAT` may have in 3.0.  That makes it pretty bad to do easy conditionals with.

2021-07-01 06:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2021-07-01 07:22 UTC, levitte commented
Merged

025312431db8c5cf0c16e1043987a7f0f9e3bf87 DOC: clarify OPENSSL_API_COMPAT

2021-07-01 07:22 UTC, closed without merging