deprecate ERR_GET_FUNC()
openssl/openssl pull request #15955
Opened 2021-06-30 02:26 UTC by paulidale

Deprecate the ERR_GET_FUNC() function.
Change it's return to -1 so it can't accidentally match one of the ERR_F_ macros.
Update documentation to note the deprecation.
Update documentation so it doesn't claim the ERR_GET_ family are macros.

- [x] documentation is added or updated
- [ ] tests are added or updated

Fixes #15946

2021-06-30 03:03 UTC, paulidale commented
@reaperhulk, do the Python tests depend on the function codes?  I can't see anything but I'm not sure how else the CI failure is relevant.

2021-06-30 04:18 UTC, reaperhulk commented
@paulidale Yeah this test asserts on a func code. We've been progressively making our error stack checks less specific to be more resilient but it looks like we'd be best served entirely stripping `ERR_GET_FUNC`.

I can update `cryptography`'s main branch tomorrow and send a PR to openssl bumping to latest, which should unblock this.

2021-06-30 04:22 UTC, paulidale commented
Thanks, that would be perfect.

2021-06-30 04:31 UTC, slontis commented
Shouldnt this have the OTC hold on it also - since the issue has a hold.

2021-06-30 04:38 UTC, levitte approved these changes

2021-06-30 04:38 UTC, slontis requested changes
Add to the 'Deprecated list' in the migration_guide.pod (Somewhere around line 1610)

2021-06-30 05:08 UTC, paulidale commented
Added an entry to the migration guide

2021-06-30 05:10 UTC, slontis commented
LGTM: This should have a OTC hold on it right?

2021-06-30 05:24 UTC, paulidale commented
The issue has one, might as well put one here too.

2021-06-30 08:31 UTC, t8m approved these changes
LGTM to me as well. IMO this is way better than a silent breakage that might happen in applications with what we currently have.

2021-06-30 08:34 UTC, t8m commented
How do we resolve the pyca test breakage though? Maybe temporarily disable the test and wait for the upstream to merge pyca/cryptography#6148

2021-06-30 08:44 UTC, paulidale commented
The pyca change should be in first and then we'll get a [PR to merge](https://github.com/openssl/openssl/pull/15955#issuecomment-871083378) it for our external tests.  This goes in afterwards or we live with it breaking for a short time -- I'd prefer the former.

2021-07-01 06:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2021-07-01 09:26 UTC, romen commented
Uhm, wouldn't it be better to just remove `ERR_GET_FUNC()` completely?

Failures at compile time are more desirable than at run time for this, because of the likelyhood of this function being used mostly in branches never/seldom taken.

I tend to believe that keeping the function (as deprecated) as proposed, but subtly changing its behavior, is not really helping external authors relying on our promise of API stability for 3.0 anyway, that is why I am considering direct removal.

Regarding doing this now, I believe the underlying issue is indeed an API bug, which would warrant an exemption from the beta API freeze, and should definitely go in before final release. (i.e., I would vote +1 in an OTC vote to fix this issue by changing this part of the API at this time)

2021-07-01 09:34 UTC, t8m commented
I agree with @romen that removing the call completely would be also an option and maybe the best one.

2021-07-06 08:32 UTC, mattcaswell commented
OTC have voted for removal

2021-07-06 08:34 UTC, paulidale commented
Closing this, it is not the path forwards.

2021-07-06 08:46 UTC, closed without merging