kdf: add PIN verification key KDF to providers
openssl/openssl pull request #15968
Opened 2021-07-01 04:54 UTC by paulidale

This is in pem/pvkfmt.c currently.  Since it is a KDF, it is better located in a provider -- in this case legacy since it is only used if RC4 is available.

This PR is based on #15967, will need to be rebased after that is merged.

The existing test cases exercise this code sufficiently.

- [x] documentation is added or updated
- [ ] tests are added or updated

2021-09-03 00:25 UTC, paulidale commented
Rebased to current master

2021-09-05 23:21 UTC, paulidale commented
Review required.

2021-09-14 10:44 UTC, paulidale commented
Was kind of hoping for a 3.0.1/3.1 decisions.  Master feels fine for this change.

2021-09-15 10:33 UTC, paulidale commented
Ping for review

2021-09-21 02:36 UTC, paulidale commented
Rebased to master, still awaiting review.

2021-09-24 15:03 UTC, t8m requested changes
Some things to consider. Also should there be a CHANGES.md entry? We have it for other KDFs.
Also, should we have some test cases in evp tests?

2021-09-25 02:58 UTC, paulidale commented
Good feedback @t8m, I'll address net week.

2021-09-25 02:58 UTC, paulidale commented on providers/implementations/kdfs/pvkkdf.c
> +    md = ossl_prov_digest_md(&ctx->digest);
I think that `ossl_prov_digest_md()` should be doing the proper error reporting.  It is used in quite a number of places.

2021-09-25 05:50 UTC, levitte commented on doc/man7/OSSL_PROVIDER-legacy.pod
> +=item PVK KDF
Drop the space

2021-09-26 23:21 UTC, paulidale commented
Feedback addressed, test cases added.

2021-09-27 07:24 UTC, t8m approved these changes

2021-09-28 08:00 UTC, openssl-machine commented
This pull request is ready to merge

2021-09-28 08:10 UTC, paulidale commented
Merged to master, thanks for the reviews.

2021-09-28 08:10 UTC, closed without merging