Fixes ERR_error_string crash
openssl/openssl pull request #16102
Opened 2021-07-16 14:02 UTC by kemaqi

when ret==NULL be assigned will crash. ERR_error_string only provides a recommended cache size to store error information. The cache size should not be passed in. If you need a specific cache to store error information, you can use ERR_error_string_n
##### Checklist

- [x] documentation is added or updated

2021-07-18 17:05 UTC, kaduk commented
Changing the API for public API functions can only be done at a major release boundary.
In this case, I don't think the change should be made at all, as the harm that is being prevented is readily documented and preventable by just using a large-enough buffer even without using the replacement API.  There's not enough justification to require changes in all consuming applications.

2021-07-18 22:56 UTC, paulidale requested changes
We cannot change a public API so close to a release.

2021-09-09 00:06 UTC, openssl-machine commented
This PR has the label 'hold: cla required' and is stale: it has not been updated in 30 days. Note that this PR may be automatically closed in the future if no CLA is provided.  For CLA help see https://www.openssl.org/policies/cla.html

2021-11-08 00:07 UTC, openssl-machine commented
This PR has been closed.  It was waiting for a CLA for 90 days.

2021-11-08 00:07 UTC, closed without merging