Clean up on failed BIO creation
openssl/openssl pull request #16315
Opened 2021-08-16 07:44 UTC by bonniegong

Check the result of BIO_new and clean up when fail

CLA: trivial

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2021-08-16 11:07 UTC, t8m reviewed
This is too significant change for being acceptable with CLA: trivial. Could you please submit a regular CLA?

2021-08-17 10:40 UTC, bonniegong commented
> This is too significant change for being acceptable with CLA: trivial. Could you please submit a regular CLA?

Thank you for informing. I have submitted a CLA just now.

2021-08-18 02:45 UTC, paulidale reviewed
Just code style nit picks.

2021-08-18 02:45 UTC, paulidale commented on apps/s_client.c
> +            if (fbio == NULL)
Blank line before.

2021-08-18 02:45 UTC, paulidale commented on apps/s_client.c
> +            if (fbio == NULL)
Blank line before.

2021-08-18 02:45 UTC, paulidale commented on apps/s_client.c
> +            if (fbio == NULL)
Blank line before.

2021-08-18 02:45 UTC, paulidale commented on apps/s_client.c
> +            if(fbio == NULL)
Blank line before.
Space between `if` and `(`.

2021-08-18 02:45 UTC, paulidale commented on apps/s_client.c
> +            if (fbio==NULL)
Blank line before.
Spaces either side of the `==`.

2021-08-18 02:45 UTC, paulidale commented on apps/s_client.c
> +            if (fbio==NULL)
Blank line before.
Spaces either side of the `==`.

2021-08-18 02:45 UTC, paulidale commented on apps/s_server.c
> +    BIO *BIO = NULL
Blank line after.

2021-08-24 10:14 UTC, t8m requested changes

2021-08-24 10:14 UTC, t8m commented on apps/s_server.c
> +    io = NIO_push(bio, io);
Typo: NIO_push

2021-08-24 10:14 UTC, t8m commented on apps/s_server.c
> +    BIO *bio = NULL;
Please enclose this in `#ifdef CHARSET_EBCDIC` otherwise we get the compilation failure with  -Werror.

2021-09-01 07:33 UTC, t8m approved these changes

2021-09-02 09:40 UTC, paulidale commented
The CI failures are relevant.

2021-09-02 10:18 UTC, t8m commented on apps/s_server.c
> +    BIO *bio = NULL;
This has to be again surrounded with `#ifdef CHARSET_EBCDIC`

2021-10-03 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2021-10-03 09:00 UTC, beldmit commented
Test failures are relevant

2021-11-03 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2021-12-04 00:07 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 30 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2022-01-04 00:07 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 61 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2022-02-02 00:07 UTC, openssl-machine commented
This PR has been closed.  It was waiting for the creator to make requested changes but it has not been updated for 90 days.

2022-02-02 00:07 UTC, closed without merging