Get rid of warn_binary
openssl/openssl pull request #16367
Opened 2021-08-20 14:53 UTC by beldmit

Current implementation of warn_binary introduces a regression
when the content is passed in /dev/stdin as an explicit file name
and reads the file to be processed twice otherwise.

I suggest to reimplement this functionality after 3.0 if necessary.

Fixes #16359

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2021-08-21 07:11 UTC, DDvO requested changes
I do not agree with entirely removing the `warn_binary` function.
Yet sure `stdin` should not be read twice.
Instead, the function can simply check for the input `file` being `/dev/stdin` and return immediately in this case.

2021-08-21 07:18 UTC, beldmit commented
I think no files should be read twice - and check for stdin is not the right way to fix the issue. If we have a really large file, why are we to read it twice? 

The right way looks to me like set some flag about possible binary content during reading the file and report afterwards. But this also looks like a post-3.0 solution

2021-08-21 07:43 UTC, DDvO commented
> I think no files should be read twice - and check for stdin is not the right way to fix the issue. If we have a really large file, why are we to read it twice?

Good point that reading a (large) file twice is not a good solution.

> The right way looks to me like set some flag about possible binary content during reading the file and report afterwards.

Yes.

> But this also looks like a post-3.0 solution

I agree. Please open an issue, pointing to this discussion, such that this point is not forgotten, 
and then I'll be fine with removing the `warn_binary()` function.

2021-08-21 07:52 UTC, beldmit commented
@DDvO, please - #16372

2021-08-21 10:38 UTC, paulidale commented
> Instead, the function can simply check for the input `file` being `/dev/stdin` and return immediately in this case.

This doesn't exist on some platforms.

Reading via a memory BIO and checking the first bytes for binary might be an option.  Otherwise @beldmit's suggestion of a flag that is set when something is encountered (filter BIO perhaps?).  Finally, the command does know if it has been told to read stdin and could skip the check in this case -- not ideal but possibly okay enough.

2021-08-21 11:06 UTC, DDvO approved these changes

2021-08-22 12:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but this PR has failing CI tests.  Once the tests pass it will get moved to 'approval: ready to merge' automatically, alternatively please review and set the label manually.

2021-08-22 12:25 UTC, beldmit commented
Merged. Thanks!

2021-08-22 12:25 UTC, closed without merging