Set default properties for OpenSSL command-line programs
openssl/openssl pull request #16926
Opened 2021-10-27 11:45 UTC by olszomal

OpenSSL command-line programs should set default properties for all future EVP algorithm fetches.
The TLS_CHACHA20_POLY1305_SHA256 ciphersiute is disabled in the FIPS mode, but openssl-ciphers supports this ciphersiute in the FIPS mode:
```
$ openssl ciphers -tls1_3 -s -v -provider fips -propquery fips=yes
TLS_AES_256_GCM_SHA384         TLSv1.3 Kx=any      Au=any   Enc=AESGCM(256)            Mac=AEAD
TLS_CHACHA20_POLY1305_SHA256   TLSv1.3 Kx=any      Au=any   Enc=CHACHA20/POLY1305(256) Mac=AEAD
TLS_AES_128_GCM_SHA256         TLSv1.3 Kx=any      Au=any   Enc=AESGCM(128)            Mac=AEAD
```
Expected result is:
```
$ openssl ciphers -tls1_3 -s -v -provider fips -propquery fips=yes
TLS_AES_256_GCM_SHA384         TLSv1.3 Kx=any      Au=any   Enc=AESGCM(256)            Mac=AEAD
TLS_AES_128_GCM_SHA256         TLSv1.3 Kx=any      Au=any   Enc=AESGCM(128)            Mac=AEAD
```

CLA: regular

2021-11-01 08:02 UTC, t8m requested changes

2021-11-01 08:02 UTC, t8m commented on apps/lib/app_libctx.c
> +    EVP_set_default_properties(libctx, app_propq);
Should the return value be checked here?

2021-11-01 23:44 UTC, paulidale commented
I think it would make more sense to remove `app_propq` and `app_get0_propq()` completely and rely on just the default query being set.  Passing the same thing for the query as what the default query is set to, is harmless but wasteful.

2021-12-11 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2021-12-21 14:35 UTC, t8m commented
I think what @paulidale said above makes sense.

2021-12-23 00:27 UTC, paulidale approved these changes

2022-01-23 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2022-01-27 10:42 UTC, mattcaswell commented
There is a subtle change of behaviour here.

Prior to this PR we pass the prop query directly to all fetches (as is done extensively in the apps, i.e. most places where we call `app_get0_propq`). If there is an existing default prop query picked up from a config file, then it is merged with the fetch specific propq (as supplied to a `-propquery` command line argument) and *both* apply.

After this PR if there is a default prop query picked up from the config file then it is completely overridden by the command line `-propquery` argument. *Only* the command line supplied propquery applies.

This could be breaking.

2022-02-27 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2022-03-30 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 61 days ago

2022-04-30 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 92 days ago

2022-05-03 10:28 UTC, closed without merging

2022-05-03 11:02 UTC, DDvO commented
@olszomal, I wonder why you closed your PR without comment?
Was this by mistake?

2022-05-04 10:42 UTC, olszomal commented
Fixed by #17595