check the return value of BIO_new()
openssl/openssl pull request #17175
Opened 2021-12-01 06:35 UTC by x2018

Check the return value of BIO_new() in t_x509.c:471 & cmp_vfy.c:36 in time to prevent further memory errors.

2021-12-01 06:53 UTC, paulidale approved these changes

2021-12-01 08:10 UTC, t8m requested changes

2021-12-01 08:10 UTC, t8m commented on crypto/x509/t_x509.c
> +            ERR_raise(ERR_LIB_X509, ERR_R_MALLOC_FAILURE);
An error is already raised by  BIO_new in case of malloc failure.

2021-12-01 08:10 UTC, t8m commented on crypto/cmp/cmp_vfy.c
> +        ERR_raise(ERR_LIB_CMP, ERR_R_MALLOC_FAILURE);
Same as below, this is not needed.

2021-12-01 08:12 UTC, x2018 commented on crypto/cmp/cmp_vfy.c
> +        ERR_raise(ERR_LIB_CMP, ERR_R_MALLOC_FAILURE);
ok

2021-12-01 08:19 UTC, t8m approved these changes

2021-12-09 03:34 UTC, slontis approved these changes

2021-12-10 04:00 UTC, openssl-machine commented
This pull request is ready to merge

2021-12-10 04:19 UTC, paulidale approved these changes

2021-12-10 04:28 UTC, paulidale commented
Merged to 3.0 and master, thanks for the contribution.

2021-12-10 04:28 UTC, closed without merging