get_ecdsa_sig_rs_bytes(): free value of d2i_ECDSA_SIG() before return
openssl/openssl pull request #17280
Opened 2021-12-15 09:46 UTC by PeiweiHu

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2021-12-15 10:29 UTC, t8m approved these changes

2021-12-15 11:25 UTC, mattcaswell requested changes

2021-12-15 11:25 UTC, mattcaswell commented on test/acvp_test.c
>          return 0;
Why not just `goto err`?

2021-12-15 11:25 UTC, mattcaswell commented on test/acvp_test.c
>          return 0;
`goto err`

2021-12-16 01:29 UTC, paulidale approved these changes

2021-12-16 10:59 UTC, mattcaswell approved these changes

2021-12-16 11:36 UTC, t8m approved these changes

2021-12-17 02:00 UTC, openssl-machine commented
This pull request is ready to merge

2021-12-17 06:37 UTC, davidben commented
Alternatively, those checks can just be deleted. No successful `d2i_ECDSA_SIG` or `d2i_DSA_SIG` call can produce an object with missing `r` or `s` values. The parameters aren't optional and the function always fills them in:
https://github.com/openssl/openssl/blob/master/crypto/ec/ec_asn1.c#L1226

2021-12-17 16:35 UTC, t8m commented
Merged to master and 3.0 branches. Thank you for your contribution.

2021-12-17 16:35 UTC, closed without merging