Fix compile error when building with no-asm
openssl/openssl pull request #17376
Opened 2021-12-30 04:44 UTC by zorrorffm

The compile error will occurs when OPENSSL_NO_ASM is defined because OPENSSL_armcap_P is invalid in this case.

2021-12-30 10:31 UTC, mattcaswell approved these changes
Looks ok. Which branches does this apply to?

2021-12-30 10:47 UTC, paulidale approved these changes

2021-12-30 13:31 UTC, bernd-edlinger commented on test/rdcpu_sanitytest.c
> +#  if defined(OPENSSL_NO_ASM)
I doubt this is the right approach.
I think the `OPENSSL_cpuid_setup()` above will not be available when
`OPENSSL_CPUID_OBJ` is not defined.

2021-12-30 13:33 UTC, bernd-edlinger requested changes
please use defined(OPENSSL_CPUID_OBJ) as in the case of x86_64 arch

2021-12-31 11:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but this PR has failing CI tests.  Once the tests pass it will get moved to 'approval: ready to merge' automatically, alternatively please review and set the label manually.

2022-01-01 13:55 UTC, zorrorffm commented
> please use defined(OPENSSL_CPUID_OBJ) as in the case of x86_64 arch

That's the correct approach, thanks. I've updated this PR.

2022-01-01 14:34 UTC, bernd-edlinger approved these changes
Thanks,  CI failure is irrelevant.

2022-01-03 11:09 UTC, t8m approved these changes

2022-01-04 01:50 UTC, paulidale approved these changes

2022-01-04 12:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but this PR has failing CI tests.  Once the tests pass it will get moved to 'approval: ready to merge' automatically, alternatively please review and set the label manually.

2022-01-04 15:54 UTC, t8m commented
Merged to master branch. Thank you for your contribution.

2022-01-04 15:54 UTC, closed without merging