free the resource from EVP_MD_CTX_new()
openssl/openssl pull request #17415
Opened 2022-01-05 01:51 UTC by x2018

`hmac` is allcated by `EVP_MD_CTX_new()` at `ssl3_record.c:1413` under condition `!stream_mac`. But there is a potential memory leak of it inside the block `ssl3_record.c:1452`.

2022-01-05 09:15 UTC, t8m requested changes

2022-01-05 09:15 UTC, t8m commented on ssl/record/ssl3_record.c
> +    if (!stream_mac)
There is no need for this `if` as hmac will be NULL otherwise and the EVP_MD_CTX_free() handles NULL gracefully.

2022-01-05 09:51 UTC, t8m approved these changes

2022-01-06 02:14 UTC, paulidale approved these changes

2022-01-07 03:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-01-07 08:52 UTC, t8m commented
Merged to master and 3.0 branches. Thank you for your contribution.

2022-01-07 08:52 UTC, closed without merging