Updates apps/speed.c to use opt_int_arg() to prevent malformed proces…
openssl/openssl pull request #17585
Opened 2022-01-25 13:21 UTC by heavycrystal

…sing of hexadecimal input to some command line options. Updated help to notify the change.

CLA: trivial

In the "openssl speed" CLI, one is able to specify arguments to some options [like -seconds -bytes] in terms of hexadecimal values prefixed by 0x or 0X. These are accepted by the command-line parser as valid arguments as long as the value fits in the prescribed range. However, the actual conversion to an integer takes place via atoi(opt_arg()) which does not handle hexadecimal strings and returns 0 instead. This leads to issues since these options expect positive integers.

This PR replaces all such calls with opt_int_arg() which was already in use in this file. The help text has also been modified to ensure people are aware of the prefix rules surrounding the usage of opt_int_arg() [which calls strtol() internally]

##### Checklist

- [x] documentation is added or updated

2022-01-25 16:19 UTC, t8m commented
I think this is slightly outside of something acceptable with CLA: trivial.

2022-01-25 18:44 UTC, heavycrystal commented
I have sent my ICLA via e-mail.

2022-01-26 00:23 UTC, paulidale commented
I've not seen your ICLA come in yet.

2022-01-26 03:12 UTC, heavycrystal commented
@paulidale It was sent under the name Kevin. Please let me know if I need to contact anyone regarding this.

2022-01-26 03:23 UTC, t-j-h commented
I wouldn't add the "[prefix '0' for base-8, prefix '0x'/'0X' for base-16]" to each of the options myself.

2022-01-26 04:32 UTC, paulidale commented
No sign of your CLA yet.  You should be able to email it to: legal@opensslfoundation.org

2022-01-26 05:13 UTC, heavycrystal commented
@t-j-h would this work better then?

Usage: speed [options] [algorithm...]
All +int options consider prefix '0' as base-8 input, prefix '0x'/'0X' as base-16 input.

...

2022-01-26 15:52 UTC, heavycrystal commented
Reopened to remove CLA hold. I have submitted my ICLA.

2022-01-26 16:31 UTC, t8m commented
Please drop the merge commit. We do not allow merge commits in the repository.

2022-01-26 17:36 UTC, heavycrystal commented
Sorry for the mess, I kind of mucked up my fork by accident and had to rectify it. 

All the changes have been merged into a single commit now.

Sorry for the inconvenience.

2022-02-01 04:02 UTC, paulidale requested changes
One icky style nit.

2022-02-01 04:02 UTC, paulidale commented on apps/speed.c
> +    {OPT_HELP_STR, 1, '-', "Usage: %s [options] [algorithm...]\nAll +int options consider prefix '0' as base-8 input, prefix '0x'/'0X' as base-16 input.\n"},
This line has to be too long.  We wrap at 80 characters currently.  Breaking the string at the new line will help but isn't enough.  It needs a second break unfortunately.  I'd do it at the comma.

2022-02-01 05:03 UTC, heavycrystal commented
I've updated the help text. Please check if it's sufficient @paulidale?

2022-02-01 05:15 UTC, paulidale commented on apps/speed.c
> +    {OPT_HELP_STR, 1, '-', "Usage: %s [options] [algorithm...]\n\
What about:
```c
    {OPT_HELP_STR, 1, '-',
     "Usage: %s [options] [algorithm...]\n"
     "All +int options consider prefix '0' as base-8 input, "
     "prefix '0x'/'0X' as base-16 input.\n"
    },
```

2022-02-01 05:39 UTC, heavycrystal commented on apps/speed.c
> +    {OPT_HELP_STR, 1, '-', "Usage: %s [options] [algorithm...]\n\
Changed.

2022-02-02 02:11 UTC, paulidale approved these changes

2022-02-02 08:57 UTC, t8m approved these changes

2022-02-03 09:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-02-03 13:00 UTC, t8m commented
Merged to master branch. Thank you for your contribution.

2022-02-03 13:00 UTC, closed without merging