evp_test: Add the missing check after calling OPENSSL_strdup and sk_OPENSSL_STRING_new_null
openssl/openssl pull request #17628
Opened 2022-02-02 11:50 UTC by JiangJias

Since the memory allocation may fail, the 'mac_name' and 'controls'
could be NULL.
And the 'mac_name' will be printed in mac_test_run_mac() without check.
Also the result of 'params_n +
sk_OPENSSL_STRING_num(expected->controls)' in
mac_test_run_mac() will be 'params_n - 1' if allocation fails , which
does not make sense.
Therefore, it should be better to check them in order to guarantee the
complete success of initiation.
If fails, we also need to free the 'mdat' to avoid the memory leak.

Signed-off-by: Jiasheng Jiang <jiasheng@iscas.ac.cn>

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2022-02-02 15:25 UTC, t8m requested changes

2022-02-02 15:25 UTC, t8m commented on test/evp_test.c
> +	return 0;
Please do not use tabs for indentation.

2022-02-03 01:23 UTC, JiangJias commented on test/evp_test.c
> +	return 0;
> Please do not use tabs for indentation.

```suggestion
        OPENSSL_free(mdat);
        return 0;
```

2022-02-03 12:33 UTC, t8m approved these changes

2022-02-04 03:07 UTC, paulidale approved these changes

2022-02-05 04:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-02-07 00:25 UTC, paulidale commented
Merged to both branches.  Thanks for the fix.

2022-02-07 00:25 UTC, closed without merging