bio_enc.c: add check for BIO_new_mem_buf
openssl/openssl pull request #17730
Opened 2022-02-18 02:14 UTC by JiangJias

Since the memory allocation may fail, the BIO_new_mem_buf() may
return NULL pointer.
Therefore, it should be better to check it and return error if fails.

Signed-off-by: Jiasheng Jiang <jiasheng@iscas.ac.cn>

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2022-02-18 09:11 UTC, t8m requested changes

2022-02-18 09:11 UTC, t8m commented on test/bio_enc_test.c
> +            return 0;
Same as above

2022-02-18 09:11 UTC, t8m commented on test/bio_enc_test.c
> +            return 0;
Same as above.

2022-02-18 09:27 UTC, JiangJias commented on test/bio_enc_test.c
> +        return 0;
I have noticed that everytime the check fails, like TEST_true() or TEST_uchar_eq(), it just prints the error info and returns error, without any memory free.
Are they needed too?

2022-02-18 09:40 UTC, t8m commented on test/bio_enc_test.c
> +        return 0;
Yes, you need to free the BIO `b`.

2022-02-18 12:23 UTC, t8m approved these changes

2022-02-22 06:00 UTC, paulidale approved these changes

2022-02-23 07:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-02-24 00:24 UTC, paulidale commented
Merged to master and 3.0.  Thanks for these fixes.

2022-02-24 00:24 UTC, closed without merging