Improve documentation of BIO_FLAGS_BASE64_NO_NL flag.
openssl/openssl pull request #17744
Opened 2022-02-21 17:15 UTC by faramir-dev

Fixes #12491.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2022-02-21 17:20 UTC, mattcaswell requested changes

2022-02-21 17:20 UTC, mattcaswell commented on doc/man3/BIO_f_base64.pod
> +For reading it forces the encoder to encode data regardless
The decoder to decode?

2022-02-21 17:20 UTC, mattcaswell commented on doc/man3/BIO_f_base64.pod
> +to contain any newline at all.
Perhaps we should mention in the DESCRIPTION section at the top what the newline rules are, e.g. lines must be less than x characters long before a newline should be present....or something like that?

2022-02-21 23:32 UTC, paulidale commented on doc/man3/BIO_f_base64.pod
> +of newlines. All newlines are ignored and input does not need
_All newlines are ignored and **the** input does not need_

2022-02-21 23:32 UTC, paulidale commented on doc/man3/BIO_f_base64.pod
> +For reading it forces the encoder to encode data regardless
How about **decoder to process the**

2022-02-28 10:56 UTC, mattcaswell approved these changes

2022-02-28 12:10 UTC, t8m commented on doc/man3/BIO_f_base64.pod
> +For reading, it forces the dencoder to process the data regardless
Typo: dencoder -> decoder

2022-03-01 07:53 UTC, t8m approved these changes

2022-03-01 07:54 UTC, t8m commented
@mattcaswell still OK?

2022-03-01 08:48 UTC, mattcaswell approved these changes
Still ok

2022-03-02 12:09 UTC, t8m commented
Merged to master, 3.0, and 1.1.1 branches. Thank you.

2022-03-02 12:09 UTC, closed without merging