Enable openssl req -x509 to create certificates from CSRs
openssl/openssl pull request #17782
Opened 2022-03-01 12:59 UTC by hlandau

`openssl req -x509` has code allowing it to generate certificates from CSRs as a replacement for `openssl x509`, but a bug prevents it from working properly. -CA and -CAkey can now be passed to generate a CA-signed certificate as documented in openssl-req(1).

Regression testing has been added to `openssl req`.

Fixes #17736.

2022-03-01 13:33 UTC, t8m requested changes

2022-03-01 13:33 UTC, t8m commented on apps/req.c
> +        if (CAcert == NULL && pkey == NULL /* can happen only if !newreq */) {
I would actually check for NULL CAkey and not CAcert. And move the comment inside the if block or maybe even drop it altogether as it is misleading.

2022-03-01 13:33 UTC, t8m commented on apps/req.c
> +                " provide both -CA and -CAkey\n");
Actually the CA key can be placed in the same file as the CA certificate so this is not completely correct.

2022-03-01 14:31 UTC, mattcaswell commented
Should there be a negative test where neither "-key" or "-CAkey" is provided?

This is marked for master and 3.0. Is it also relevant for 1.1.1?

2022-03-01 14:34 UTC, t8m commented on apps/req.c
> +        if (CAcert == NULL && pkey == NULL /* can happen only if !newreq */) {
Yes, these are equivalent conditions, testing for CAkey looked a little bit more readable to me however it does not really matter. So you can keep the condition as is.

2022-03-01 14:35 UTC, t8m commented
> This is marked for master and 3.0. Is it also relevant for 1.1.1?

Not relevant for 1.1.1 as the CAkey/CAcert were added in 3.0.

2022-03-01 15:58 UTC, hlandau commented
Updated to tweak message and add a negative test.

2022-03-01 16:32 UTC, t8m approved these changes

2022-03-01 16:35 UTC, mattcaswell approved these changes

2022-03-01 22:36 UTC, paulidale approved these changes

2022-03-03 09:24 UTC, t8m commented
Pushed to master branch. As this does not cherry-pick cleanly, can you please open a new PR against the openssl-3.0 branch?

2022-03-03 09:25 UTC, closed without merging