Add EVP demo for Poly1305 demonstrating Poly1305-AES
openssl/openssl pull request #17796
Opened 2022-03-02 09:52 UTC by hlandau

Fixes #14122.

2022-03-04 01:10 UTC, paulidale approved these changes

2022-03-04 09:38 UTC, t8m requested changes
Would you please consider adding a Makefile similar to the one in cipher?

2022-03-04 09:38 UTC, t8m commented on demos/mac/poly1305.c
> +    if (!EVP_EncryptUpdate(aesctx, composite_key+16, &aes_len, test_n, sizeof(test_n))) {
Nit: spaces around `+`

2022-03-04 10:01 UTC, hlandau commented on demos/mac/poly1305.c
> +    if (!EVP_EncryptUpdate(aesctx, composite_key+16, &aes_len, test_n, sizeof(test_n))) {
Fixed.

2022-03-04 10:01 UTC, hlandau commented
@t8m Done.

2022-03-04 10:32 UTC, t8m approved these changes

2022-03-04 10:32 UTC, t8m commented
@paulidale still OK?

2022-03-04 11:00 UTC, paulidale approved these changes
still good

2022-03-05 12:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but this PR has failing CI tests.  Once the tests pass it will get moved to 'approval: ready to merge' automatically, alternatively please review and set the label manually.

2022-03-06 22:23 UTC, paulidale commented
Merged to both, thanks.

2022-03-06 22:23 UTC, closed without merging