Add EVP demo for X25519 key exchange
openssl/openssl pull request #17799
Opened 2022-03-02 13:15 UTC by hlandau

This offers both a known answer test with fixed keys and also demonstrates a more realistic usage with random keys.

Fixes #14118.

2022-03-02 13:23 UTC, t8m commented
Good work!

I'd suggest refactoring it slightly though so you do not do everything twice. Just split key generation (or key load) and the key exchange into separate functions and call these from main() for peer1 and peer2. This will make the demo even more real-world.

2022-03-02 14:11 UTC, hlandau commented
@t8m How's this?

2022-03-02 14:57 UTC, mattcaswell requested changes

2022-03-02 14:57 UTC, mattcaswell commented on demos/keyexch/x25519.c
> +    local_peer->secret = OPENSSL_zalloc(local_peer->secret_len);
`OPENSSL_malloc` is probably sufficient here

2022-03-02 14:57 UTC, mattcaswell commented on demos/keyexch/x25519.c
> +            &local_peer->secret_len) == 0) {
I would line this up with `ctx`

2022-03-02 15:12 UTC, mattcaswell requested changes

2022-03-02 15:12 UTC, mattcaswell commented on demos/keyexch/x25519.c
> +            kat_privk_data, sizeof(peer1_privk_data));
Sorry didn't spot this on the first run through...I'd split this like so:

```` C
        local_peer->privk =
            EVP_PKEY_new_raw_private_key_ex(libctx, "X25519", propq,
                                            kat_privk_data,
                                            sizeof(peer1_privk_data));
````

We generally try to line things up with the paren. The coding style is a bit vague on this though:

"Statements longer than 80 columns must be broken into sensible chunks, unless exceeding 80 columns significantly increases readability and does not hide information. Descendants are always substantially shorter than the parent and are placed substantially to the right."

There are several other places like this. I'd review all line breaks with this in mind.

2022-03-02 15:37 UTC, t8m requested changes
Nice work! Just a few nits.

2022-03-02 15:37 UTC, t8m commented on demos/keyexch/x25519.c
> +    if (kat_privk_data)
Please always use explicit checks for NULL/nonNULL: `kat_privk_data != NULL`

2022-03-02 15:37 UTC, t8m commented on demos/keyexch/x25519.c
> +            sizeof(local_peer->pubk_data), &pubk_data_len) == 0) {
Nit: Please align with the parenthesis.

2022-03-02 15:37 UTC, t8m commented on demos/keyexch/x25519.c
> +            "yielded wrong length\n");
Nit: Align with the string above or with the parenthesis.

2022-03-02 15:37 UTC, t8m commented on demos/keyexch/x25519.c
> +        remote_peer_pubk_data, 32);
Please align with parenthesis.

2022-03-02 15:48 UTC, hlandau commented
Style fixes pushed.

2022-03-02 15:56 UTC, t8m approved these changes

2022-03-02 15:57 UTC, mattcaswell requested changes
Few more style nits...

2022-03-02 15:57 UTC, mattcaswell commented on demos/keyexch/x25519.c
> +  0x94, 0x3b, 0x01, 0x45, 0xca, 0x19, 0xfe, 0x09
Wrong indentation here (4 spaces)

2022-03-02 15:57 UTC, mattcaswell commented on demos/keyexch/x25519.c
> +            &peer1) == 0)
Missed one

2022-03-02 15:57 UTC, mattcaswell commented on demos/keyexch/x25519.c
> +            &peer2) == 0)
and another

2022-03-02 15:57 UTC, mattcaswell commented on demos/keyexch/x25519.c
> +            peer1.secret_len) != 0) {
and here

2022-03-02 16:03 UTC, hlandau commented
More style fixes.

2022-03-02 16:20 UTC, t8m approved these changes

2022-03-02 16:21 UTC, mattcaswell approved these changes

2022-03-03 17:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but this PR has failing CI tests.  Once the tests pass it will get moved to 'approval: ready to merge' automatically, alternatively please review and set the label manually.

2022-03-04 00:02 UTC, paulidale approved these changes

2022-03-04 00:05 UTC, paulidale commented
Merged to both branches.  Thanks.

2022-03-04 00:05 UTC, closed without merging