Move KU_ macros to the local header file.
openssl/openssl pull request #17980
Opened 2022-03-28 16:10 UTC by faramir-dev

Fixes openssl#17148

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2022-03-28 16:32 UTC, t8m requested changes

2022-03-28 16:32 UTC, t8m commented on crypto/x509/x509_local.h
> +# define KU_DIGITAL_SIGNATURE    0x0080
No, this is a wrong fix. Instead the https://github.com/openssl/openssl/blob/master/include/openssl/x509.h.in#L361 should include openssl/http.h and OCSP_REQ_CTX_nbio_d2i should be replaced with OSSL_HTTP_REQ_CTX_nbio_d2i. (Look at how OCSP_REQ_CTX_nbio_d2i is defined.)

If we avoid including ocsp.h from x509.h there should be no clash when including x509.h.

2022-03-30 07:48 UTC, t8m approved these changes

2022-04-04 04:22 UTC, paulidale approved these changes

2022-04-05 05:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-04-05 07:45 UTC, t8m commented
Reworded the commit message, merged to master and 3.0 branches. Thank you.

2022-04-05 07:45 UTC, closed without merging