Fix -no-tls1_2 in tests
openssl/openssl pull request #18019
Opened 2022-04-01 15:21 UTC by tmshort

Fixed a configuration-related issue in #17952 

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2022-04-05 10:48 UTC, t8m requested changes

2022-04-05 10:48 UTC, t8m commented on test/sslapitest.c
> +        return 1;
Better use `return TEST_skip("TLS 1.2 is disabled.");`

2022-04-06 16:15 UTC, t8m approved these changes

2022-04-07 07:37 UTC, bernd-edlinger approved these changes

2022-04-08 08:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-04-11 15:12 UTC, tmshort commented
Merged to master and 3.0. Trivial merge to 1.1.1, but build fails due to undefined `TEST_skip`. So, this will likely need to be a separate PR.

2022-04-13 17:42 UTC, tmshort commented
Merged to 1.1.1 via #18080.

2022-04-13 17:42 UTC, closed without merging