Add return check of EVP_PKEY_copy_parameters() in ssl_set_cert_and_key()
openssl/openssl pull request #18071
Opened 2022-04-08 14:20 UTC by zhou1615

It seems the return value of EVP_PKEY_copy_parameters() in
ssl_set_cert_and_key() are not checked, and could lead to null pointer dereference in
EVP_PKEY_eq() function.

However those functions are complicated and this fix is suggested by
a static analyzer, so please advise.

2022-04-11 09:58 UTC, t8m requested changes

2022-04-11 09:58 UTC, t8m commented on ssl/ssl_rsa.c
> +                    ERR_raise(ERR_LIB_SSL, rv);
SSL_R_COPY_PARAMETERS_FAILED instead of rv here

2022-04-11 09:58 UTC, t8m commented on ssl/ssl_rsa.c
> +                if (rv != 1) {
You can just use if (!EVP_PKEY_copy_parameters()) - the function should return 1 on success 0 on failure.

2022-04-11 09:58 UTC, t8m commented on ssl/ssl_rsa.c
> +                ERR_raise(ERR_LIB_SSL, rv);
Same comments as above.

2022-04-11 16:38 UTC, zhou1615 commented on ssl/ssl_rsa.c
> +                ERR_raise(ERR_LIB_SSL, rv);
> Same comments as above.

All fixed

2022-04-12 07:20 UTC, t8m approved these changes

2022-05-13 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2022-05-13 06:44 UTC, beldmit approved these changes
LGTM

2022-05-14 07:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-05-16 08:44 UTC, t8m commented
Merged to master and openssl-3.0 branches. Thank you for your contribution.

2022-05-16 08:44 UTC, closed without merging