Use subject name of ecdsa01RootCaCert as in issuer if CA is available.
openssl/openssl pull request #18129
Opened 2022-04-19 07:44 UTC by faramir-dev

Fixes openssl#16080.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2022-04-19 19:57 UTC, kaduk commented
Without commenting on the actual code changes, I don't think that the string "ecdsa01RootCaCert" is the right text for the commit message.  Maybe "x509: use actual issuer name if a CA is used"?

2022-04-20 08:25 UTC, t8m requested changes

2022-04-20 08:25 UTC, t8m commented on apps/x509.c
> -            goto end;
Keep this call as is, please, as in case `-CA` is not used there will be no issuer set.

2022-04-20 08:25 UTC, t8m commented on apps/x509.c
> +        goto end;
Just move this inside the above if and you do not need to have the issuer_cert variable.

2022-04-22 21:43 UTC, kaduk approved these changes
This codebase is structured quite poorly for maintainability...but it looks like this change should be okay.

2022-04-23 22:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-04-25 12:02 UTC, t8m commented
Merged to 1.1.1 branch. Thank you.

2022-04-25 12:02 UTC, closed without merging