Prefer GNU init/destructor mechanism to be used for FIPS self tests
openssl/openssl pull request #18147
Opened 2022-04-22 02:20 UTC by jon-oracle

I've run across a problem on HP-UX where builds using gcc fail to run the init/cleanup functions. It seems that the compiler does not recognise the platform-specific #pragma init/fini statements.

By moving around the order of checks to ensure the __GNUC__ check is done first the build now works. If using the HP compiler the build/test also works fine.

I have checked that this mechanism works for gcc builds on AIX and Solaris also.

2022-04-22 09:38 UTC, t8m commented
Please avoid the merge commits. Drop it and rebase the branch against current master.

2022-04-22 09:40 UTC, t8m requested changes

2022-04-22 09:40 UTC, t8m commented on providers/fips/self_test.c
Please drop this extra empty line.

2022-04-22 09:40 UTC, t8m commented on providers/fips/self_test.c
> +
Please drop this extra empty line

2022-04-23 07:10 UTC, jon-oracle commented
Rebased and fixed up review comment.

2022-04-25 10:03 UTC, t8m commented on providers/fips/self_test.c
You've still kept two empty lines after removal of this block.

2022-04-25 10:54 UTC, mattcaswell approved these changes

2022-04-26 07:21 UTC, t8m approved these changes

2022-04-26 07:21 UTC, t8m commented
@mattcaswell I assume it is still OK.

2022-04-27 08:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-04-27 08:09 UTC, t8m commented
Merged to master and 3.0 branches. Thank you for your contribution.

2022-04-27 08:09 UTC, closed without merging