Exclude unix sockets using NO_SYS_UN_H
openssl/openssl pull request #18256
Opened 2022-05-05 16:51 UTC by maxbachmann

This replaces the usage of `#ifdef AF_UNIX` in bio/* with `#ifndef NO_SYS_UN_H`. This is already set for the systems we currently undefine `AF_UNIX` on.

##### Checklist

2022-05-06 07:48 UTC, t8m commented
I am not sure this is a right fix, at least it is no straightforwardly clear

2022-05-06 10:01 UTC, maxbachmann commented
My assumption was that since we do not include `<sys/un.h>` on the same platforms:
https://github.com/openssl/openssl/blob/a381897470f5c6ac2f4e71f48d33d71cde7873dd/include/internal/sockets.h#L19-L25
where `<sys/un.h>` which includes `sockaddr_un`. So currently we set `NO_SYS_UN_H` to prevent the inclusion of `<sys/un.h>` and then later undef `AF_UNIX` to prevent us from using `sockaddr_un`.

2022-05-06 13:06 UTC, t8m commented
Hmm, but there might be other systems that do not define AF_UNIX but are not covered by the cases where we define NO_SYS_UN_H in the sockets.h.

Is this PR fixing a concrete issue or what is the purpose?

2022-05-06 13:19 UTC, maxbachmann commented
> Hmm, but there might be other systems that do not define AF_UNIX but are not covered by the cases where we define NO_SYS_UN_H in the sockets.h.

Is there any reason to import `<sys/un.h` when `AF_UNIX` is not defined?

> Is this PR fixing a concrete issue or what is the purpose?

I am working on an OS, which defines `AF_UNIX`, but does not support unix sockets. Currently this would require me to patch the source files, while with this change I can directly pass `NO_SYS_UN_H` into my build system.

Another way would be to add something like `OPENSSL_NO_UNIX_SOCK`, which gets defined on `OPENSSL_SYS_WINDOWS` and `OPENSSL_SYS_VMS`, which feels a bit more official than `NO_SYS_UN_H`.

2022-05-06 13:28 UTC, t8m commented
> Is there any reason to import `<sys/un.h` when `AF_UNIX` is not defined?

You've misunderstood. There is no reason for that, but what I am saying is that the NO_SYS_UN_H is defined in sockets.h only in two particular cases but there might be other targets that weren't defining AF_UNIX and your PR would break these.

> Another way would be to add something like `OPENSSL_NO_UNIX_SOCKETS`, which gets defined on `OPENSSL_SYS_WINDOWS` and `OPENSSL_SYS_VMS`.

OK, then do it. Put it at the end of sockets.h and also define it when AF_UNIX is not defined. (Also do not forget to check whether OPENSSL_NO_UNIX_SOCKETS is already defined.)

2022-05-06 15:04 UTC, t8m requested changes
Just minor nits.

2022-05-06 15:04 UTC, t8m commented on include/internal/sockets.h
> +#   if (!defined NO_SYS_UN_H) && (defined AF_UNIX) && (!defined OPENSSL_NO_UNIX_SOCK)
Please use the same style of using parentheses here as in other cases in this source file. `!defined(NO_SYS_UN_H) &&...`

2022-05-06 15:04 UTC, t8m commented on include/internal/sockets.h
> +#  if (!defined AF_UNIX) || defined NO_SYS_UN_H
Same as above.

2022-05-06 15:13 UTC, maxbachmann commented on include/internal/sockets.h
> +#   if (!defined NO_SYS_UN_H) && (defined AF_UNIX) && (!defined OPENSSL_NO_UNIX_SOCK)
I updated them accordingly

2022-05-06 15:18 UTC, t8m approved these changes

2022-05-06 15:21 UTC, rsbeckerca commented
This appears to build correctly on NonStop. However, other independent issues are preventing the build from completing.

2022-06-06 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2022-07-07 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 61 days ago

2022-07-07 00:10 UTC, paulidale approved these changes

2022-07-08 01:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-07-08 04:09 UTC, paulidale commented
Merged, thanks for the contribution.

2022-07-08 04:09 UTC, closed without merging