Exclude IPv6 code using OPENSSL_USE_IPV6 instead of AF_INET6
openssl/openssl pull request #18250
Opened 2022-05-05 08:00 UTC by maxbachmann

This replaces the usage of `#ifdef AF_INET6` in `bio/*` with `#if OPENSSL_USE_IPV6`. By default this still uses `AF_INET6`, but it allows the exclusion of all IPv6 related code by setting `OPENSSL_USE_IPV6=0`.

##### Checklist

2022-05-05 10:16 UTC, levitte approved these changes

2022-05-05 10:18 UTC, levitte commented
For this to be merged into our source, you either need to add a trailer `CLA: trivial` to your commit message (make sure to separate it from the rest of the message with an empty line), or [submit a signed CLA](https://www.openssl.org/policies/cla.html)

2022-05-05 10:37 UTC, maxbachmann commented
I did just submit a signed CLA. I would like to make the same change in openssl 1.1.1. Should I open a separate PR for this, or are changes between the 1.1.1 and master branch synced in some way?

2022-05-05 10:40 UTC, levitte commented
> I would like to make the same change in openssl 1.1.1. Should I open a separate PR for this, or are changes between the 1.1.1 and master branch synced in some way?

If it cherry-picks cleanly, we'll do it. If not, then another PR will be necessary

2022-05-05 12:00 UTC, t8m approved these changes

2022-05-05 15:43 UTC, bernd-edlinger requested changes
I think this will trigger a warning if OPENSSL_USE_IPV6 is not defined,
there are lots of examples where we have ifdef OPENSSL_NO_xxx,
so I would suggest to use ifdef OENSSL_NO_IPV6 or soimilar

2022-05-05 15:52 UTC, bernd-edlinger commented
Ah okay thanks for pointing that out.

2022-05-05 15:53 UTC, bernd-edlinger approved these changes

2022-05-09 00:06 UTC, paulidale commented
Merged, thanks for the contribution.

2022-05-09 00:06 UTC, closed without merging