mkdef.pl: Add cmd-line flag to differentiate shared libs and DSO.
openssl/openssl pull request #18284
Opened 2022-05-10 18:44 UTC by faramir-dev

Fixes openssl#16984.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2022-05-10 18:48 UTC, levitte commented
This too, please:

``` diff
diff --git a/Configurations/descrip.mms.tmpl b/Configurations/descrip.mms.tmpl
index c202bd4431..eb00587528 100644
--- a/Configurations/descrip.mms.tmpl
+++ b/Configurations/descrip.mms.tmpl
@@ -981,7 +981,7 @@ EOF
               ? '' : ' --case-insensitive';
           return <<"EOF";
 $target : $gen0 $deps $mkdef
-       \$(PERL) $mkdef$ord_ver --ordinals $gen0 --name $ord_name "--OS" "VMS"$case_insensitive > $target
+       \$(PERL) $mkdef$ord_ver --type $args{intent} --ordinals $gen0 --name $ord_name "--OS" "VMS"$case_insensitive > $target
 EOF
       } elsif (platform->isasm($args{src})) {
           #
```

2022-05-11 06:24 UTC, levitte commented on util/mkdef.pl
> +die "Argument type must be equal to 'lib' or 'dso'"
Nit: I would say `"--type argument must be 'lib' or 'dso'"`

2022-05-11 07:40 UTC, t8m commented
I suppose the intent can be also shlib?

2022-05-11 07:42 UTC, paulidale commented
The CI failures might be relevant.  There are a lot of them.

2022-05-11 08:22 UTC, levitte requested changes

2022-05-11 08:22 UTC, levitte commented on util/mkdef.pl
> +           'type'       => \$type,
This isn't quite right, and is the reason for the build failures.

```suggestion
           'type=s'     => \$type,
```

2022-05-11 08:39 UTC, levitte commented
> I suppose the intent can be also shlib?

The type string passed is 'lib', even though it's for a shared library.  I'm not entirely sure why that choice was made...  it may have to do with the .ld file being produced through a different build.info mechanism in earlier OpenSSL versions.  There have been some adjustments and cleanups since 1.1.0...

2022-05-11 16:32 UTC, faramir-dev commented
@t8m It has been rebased.

2022-05-12 06:02 UTC, t8m approved these changes

2022-05-12 06:22 UTC, levitte approved these changes

2022-05-13 07:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-05-13 08:40 UTC, t8m commented
Merged to master and 3.0 branches. Thank you.

2022-05-13 08:40 UTC, closed without merging