Add d2i_PUBKEY_ex_fp and d2i_PUBKEY_ex_bio
openssl/openssl pull request #18427
Opened 2022-05-30 04:45 UTC by slontis

Add variants of d2i_PUBKEY_fp and d2i_PUBKEY_bio that pass a library context.

This also fixes some incorrect i2d documentation.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

2022-05-30 05:13 UTC, t-j-h commented
How does the test actually test that the libctx is used for anything - i.e. the purpose of the variant of the function?

2022-05-30 05:26 UTC, slontis commented
> How does the test actually test that the libctx is used for anything - i.e. the purpose of the variant of the function?

The test setup loads the NULL provider into the default library context. If you dont use the mainctx it will fall over.

2022-06-30 00:07 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2022-07-07 14:30 UTC, t8m approved these changes
Approved assuming CI passes.

2022-07-08 01:41 UTC, slontis commented
Windows was failing due to an applink error. Only change was to test/build.info

2022-07-08 02:00 UTC, slontis commented
@paulidale have you seen this error before in the non-caching?

2022-07-08 07:00 UTC, t8m commented
> @paulidale have you seen this error before in the non-caching?

This is #18631 - unfortunately we do not know what is causing the failure.

2022-07-08 07:01 UTC, t8m approved these changes

2022-07-08 08:19 UTC, hlandau requested changes

2022-07-08 08:19 UTC, hlandau commented on doc/man3/d2i_PrivateKey.pod
> +i2d_PrivateKey(),  i2d_PublicKey() and i2d_KeyParams()return the number of
extra space after comma, missing space after )

2022-07-11 11:07 UTC, t8m approved these changes

2022-07-12 08:45 UTC, hlandau approved these changes

2022-08-12 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2022-08-16 06:37 UTC, t8m commented
Unfortunately there are conflicts now, can you please rebase @slontis ?

2022-08-17 07:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2022-09-13 12:53 UTC, hlandau commented
Still OK

2022-10-27 03:47 UTC, slontis commented
Rebased to fix merge conflicts..

2022-10-27 09:55 UTC, t8m approved these changes

2022-10-27 13:25 UTC, hlandau approved these changes

2022-10-28 14:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-11-02 10:28 UTC, t8m commented
Merged to master branch. However the doc fix commit would cherry-pick cleanly to 3.0/3.1 branches. If @hlandau and @slontis agrees I'll cherry-pick it there.

Keeping this open for now.

2022-11-07 18:10 UTC, t8m commented
Cherry-picked the doc fix commit to 3.0 and 3.1 branches. Closing.

2022-11-07 18:10 UTC, closed without merging