Update SIV mode documentation
openssl/openssl pull request #18485
Opened 2022-06-06 15:49 UTC by tmshort

Fixes #18440

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

2022-06-07 01:20 UTC, paulidale approved these changes

2022-06-07 01:24 UTC, t-j-h commented on doc/man3/EVP_EncryptInit.pod
> +the cipher text. Instead, it is stored as the tag within the EVP_CIPHER_CTX.
"the the" -> "the"

2022-06-07 10:07 UTC, mattcaswell requested changes

2022-06-07 18:27 UTC, tmshort commented on doc/man3/EVP_EncryptInit.pod
> +that the plain text and cipher text lengths are the identical.
That's what I get from changing around the wording at the last minute.

2022-06-07 18:29 UTC, tmshort commented
ping @mattcaswell @t8m

2022-06-08 01:31 UTC, slontis approved these changes

2022-06-08 02:19 UTC, paulidale approved these changes

2022-06-08 06:41 UTC, t8m approved these changes

2022-06-09 03:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-06-09 03:30 UTC, paulidale commented
Merged, thanks!

2022-06-09 03:30 UTC, closed without merging