Fix coverity 1506297 & 1506298: negative returns
openssl/openssl pull request #18587
Opened 2022-06-17 01:05 UTC by paulidale

Two more that had previously been ignored.

2022-06-17 06:31 UTC, t8m requested changes

2022-06-17 06:31 UTC, t8m commented on crypto/dh/dh_ameth.c
> +    if (dplen < 0) {
why not <= 0? IMO 0 bytes private key does not make any sense.

2022-06-17 06:31 UTC, t8m commented on crypto/dsa/dsa_ameth.c
> +    if (dplen < 0) {
Same as above.

2022-06-20 06:44 UTC, t8m approved these changes

2022-06-30 01:42 UTC, paulidale commented
Ping @openssl/committers for second review

2022-06-30 02:25 UTC, slontis commented
In dh_pub_encode() it frees the ptr also - not sure if there is a reason for this..

2022-06-30 02:28 UTC, paulidale commented
> In dh_pub_encode() it frees the ptr also - not sure if there is a reason for this.

Huh?  This isn't about that function.

2022-06-30 02:42 UTC, slontis commented
> > In dh_pub_encode() it frees the ptr also - not sure if there is a reason for this.
> 
> Huh? This isn't about that function.

dh_pub_encode != dh_priv_encode (Just saying they have different patterns in the err: blocks)

2022-06-30 05:53 UTC, slontis approved these changes

2022-07-01 06:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-07-01 06:37 UTC, closed without merging