Correctly handle a retransmitted ClientHello
openssl/openssl pull request #18654
Opened 2022-06-24 11:23 UTC by mattcaswell

If we receive a ClientHello and send back a HelloVerifyRequest, we need
to be able to handle the scenario where the HelloVerifyRequest gets lost
and we receive another ClientHello with the message sequence number set to
0.

Fixes https://github.com/openssl/openssl/issues/18635

2022-06-24 11:29 UTC, mattcaswell commented
Note there is a trivial conflict when cherry-picking back to 1.1.1 which I will fix during merge.

2022-06-27 06:48 UTC, t8m approved these changes

2022-08-18 15:04 UTC, mattcaswell commented
I rebased this to resolve a conflict with master.

Still looking for a second reviewer. Ping @openssl/committers.

2022-08-18 15:12 UTC, t8m approved these changes

2022-09-18 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2022-09-20 13:19 UTC, hlandau requested changes

2022-09-20 13:19 UTC, hlandau commented on ssl/statem/statem_dtls.c
> +                 * retranmission of the original ClientHello
nit: typo, retransmission

2022-09-20 13:28 UTC, mattcaswell commented
@hlandau Typo fixed. Please take another look.

2022-09-20 16:34 UTC, t8m approved these changes

2022-09-20 16:36 UTC, t8m commented
Meanwhile the 1.1.1 got to the state when only security fixes are supposed to be done there.

2022-09-20 19:14 UTC, hlandau approved these changes

2022-09-20 19:14 UTC, hlandau commented
Does this go to 1.1.1?

2022-09-21 09:23 UTC, mattcaswell commented
> Does this go to 1.1.1?

No - its not a security fix. Removing the 1.1.1 branch label.

2022-09-21 20:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2022-09-22 11:21 UTC, hlandau commented
It's now been more than 24 hours. Merging.

2022-09-22 11:30 UTC, hlandau commented
Merged to master and 3.0. Thank you.

A merge conflict while cherry picking to 3.0 was deemed trivial enough to fix during merging. (Adjacent line to a changed line had changed so the diff algorithm wasn't happy, but no actual diff changes.)

2022-09-22 11:30 UTC, closed without merging