Fix memory leak in EVP_PKEY_get1_encoded_public_key.
openssl/openssl pull request #18739
Opened 2022-07-07 05:17 UTC by slontis

Occurs if a failure happens after the malloc call in the second call to
EVP_PKEY_get_octet_string_param().

Detected by PR #18355

Some calling code assumes that nothing is allocated in the returned
pointer if there was a failure. Other calling code always trys freeing.
The third case is in ecdh_cms_encrypt() where it does not check the
return value. I am assuming this change is ok since the legacy path in
EVP_PKEY_get1_encoded_public_key() also does not return the pointer on
failure.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2022-07-07 06:33 UTC, hlandau requested changes

2022-07-07 06:33 UTC, hlandau commented on crypto/evp/p_lib.c
> +        *ppub = 0;
Please use NULL here?

2022-07-08 00:09 UTC, slontis commented on crypto/evp/p_lib.c
> +        *ppub = 0;
Updated

2022-07-08 06:57 UTC, t8m approved these changes

2022-07-08 08:21 UTC, hlandau approved these changes

2022-07-09 09:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-07-12 06:39 UTC, hlandau commented
Merged to master and 3.0. Thank you.

2022-07-12 06:39 UTC, closed without merging