Check that IV length is not less than zero
openssl/openssl pull request #18922
Opened 2022-08-01 09:25 UTC by beldmit

As EVP_CIPHER_CTX_get_iv_length indicates failure with -1, this error
should be processed. Also the result of this function shouldn't be
assigned to an unsigned variable.

Reviewed-by: Paul Dale <pauli@openssl.org>
Reviewed-by: Tomas Mraz <tomas@openssl.org>
Reviewed-by: Hugo Landau <hlandau@openssl.org>
(Merged from https://github.com/openssl/openssl/pull/18891)

Signed-off-by: Dmitry Belyavskiy <beldmit@gmail.com>

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2022-08-01 09:26 UTC, beldmit commented
Backport of #18891 to openssl 3.0

2022-08-01 09:42 UTC, t8m approved these changes
Approved, assuming CI passes

2022-08-01 09:57 UTC, mattcaswell requested changes

2022-08-01 09:57 UTC, mattcaswell commented on ssl/record/rec_layer_s3.c
> +                return -1;
`goto err`?

2022-08-01 10:04 UTC, beldmit commented on ssl/record/rec_layer_s3.c
> +                return -1;
Probably yes

2022-08-01 10:32 UTC, beldmit commented on ssl/record/rec_layer_s3.c
> +                return -1;
Done, thanks!

2022-08-01 10:51 UTC, mattcaswell approved these changes

2022-08-01 10:51 UTC, mattcaswell commented
@t8m please reconfirm

2022-08-01 11:28 UTC, t8m approved these changes

2022-08-02 12:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-08-02 12:40 UTC, beldmit commented
Merged. Thanks!

2022-08-02 12:40 UTC, closed without merging