CRMF: add missing check and API function; clean up `X509{,_REQ}_check_private_key()`
openssl/openssl pull request #18930
Opened 2022-08-01 19:54 UTC by DDvO

* add missing CRMF API function `OSSL_CRMF_CERTTEMPLATE_get0_publicKey()`
* CRMF: make `create_popo_signature()` check that pubkey and pkey match

The latter has a prerequisite:

* X509: clean up implementation of `X509{,_REQ}_check_private_key()` and its doc

On this occasion, constify `X509_REQ_get0_pubkey()` and `X509_REQ_check_private_key()`.

2022-08-15 12:10 UTC, DDvO commented
Ping for reviews

2022-08-16 14:51 UTC, t8m requested changes

2022-08-16 14:51 UTC, t8m commented on doc/man3/X509_check_private_key.pod
> +So they also return success if if I<pkey> is a matching public key.
Typo: if if

2022-08-16 18:25 UTC, DDvO commented on doc/man3/X509_check_private_key.pod
> +So they also return success if if I<pkey> is a matching public key.
Oops, fixed.

2022-08-17 08:01 UTC, t8m approved these changes

2022-08-23 07:13 UTC, DDvO commented
Asking @openssl/committers for 2nd review.

2022-08-24 08:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-08-24 09:29 UTC, DDvO commented
Merged - thanks @t8m and @beldmit

2022-08-24 09:30 UTC, closed without merging