Fixes for TFO Tests in ASAN build
openssl/openssl pull request #18979
Opened 2022-08-10 16:08 UTC by juergenchrist

ASAN reports a heap overflow and a leak when running tfo tests.

The heap overflow might be spurious (not sure what the C standard says to that case), but we can simply fix that by using the correct member of a union instead of copying all bytes of said union including bytes that might not belong to the structure written into the union.

The leak is due to a missing freeaddrinfo call.

2022-08-11 08:36 UTC, mattcaswell requested changes

2022-08-11 08:36 UTC, mattcaswell commented on test/bio_tfo_test.c
> +    if (ai)
Please make this:
```suggestion
    if (ai != NULL)
```

2022-08-11 08:36 UTC, mattcaswell commented
What branches does this apply to?

2022-08-11 08:47 UTC, juergenchrist commented
> What branches does this apply to?

Found it on master.  Did not check other branches.  But I do not think this needs to be backported.

2022-08-11 08:49 UTC, juergenchrist commented on test/bio_tfo_test.c
> +    if (ai)
Done.

2022-08-11 09:31 UTC, mattcaswell approved these changes

2022-08-11 14:01 UTC, tmshort approved these changes
LGTM Thanks!

2022-08-11 14:03 UTC, tmshort commented
> > What branches does this apply to?
> 
> Found it on master. Did not check other branches. But I do not think this needs to be backported.

TFO was not ported to 3.0

2022-08-12 15:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2022-08-12 15:19 UTC, mattcaswell commented
Pushed. Thanks.

2022-08-12 15:19 UTC, closed without merging