Coverity times
openssl/openssl pull request #19004
Opened 2022-08-16 01:15 UTC by paulidale

Various TLS time_t use fixes for problems that will happen when the low 32 bits of time_t rolls over.

I've flagged this for all supported branches but it might be better to refactor master to use OSSL_TIME instead of persisting with time_t.  That's too much change for 3.0 and 1.1.1.

2022-08-16 21:30 UTC, kaduk reviewed
It's interesting how little overlap there is with #17701, #17786, or #17778.
This does introduce an incompatible change in the cookie format, so cookies received across a software upgrade would not be accepted.  This is probably uninteresting, given how cookies are used (whereas for session tickets it would be a bigger deal!), but I wanted to confirm that you'd thought about it before hitting 'approve'.

2022-08-16 21:56 UTC, paulidale commented
This isn't attempting to fix all of the y2038 problems but it should help with some.  There will be more required :cry:

I did dig into the cookies a bit and I think it's okay except, as you noted, across software upgrades.  Is this better or worse than rejecting cookies issued during the window of failure?  I think it's better, but it's not clear cut.  A move to OSSL_TIME would likely break cookies again, assuming that that is stored in the cookie instead of the time_t value.

2022-08-16 22:09 UTC, kaduk requested changes
Looking at the cookie usage a bit more, you do need to update `MAX_COOKIE_SIZE` and the associated comment.
Bumping `COOKIE_STATE_FORMAT_VERSION` would alleviate basically all of my (nascent) concerns.  I think it would mean dropping connection attempts across the software upgrade, but the alternative is a lot harder to analyze and ensure the safety of.

2022-08-16 22:15 UTC, paulidale commented
Okay, made those changes.  Thanks for the suggestion.

2022-08-16 22:29 UTC, kaduk approved these changes
Thanks for the update.
I'm okay with this and can tolerate the expansion of the cookie size.  That seems like the main lingering risk/concern, but we can always make a future change to optimize its encoding if it becomes an issue.

2022-08-17 10:43 UTC, mattcaswell approved these changes

2022-08-18 11:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-08-18 22:41 UTC, paulidale commented
Merged to master.
Merged everything bar the cookie change to 3.0 and 1.1.1.  They lack the 8 byte helper functions.

2022-08-18 22:41 UTC, closed without merging