Restructure the TLS write record layer into the new architecture
openssl/openssl pull request #19198
Opened 2022-09-12 15:42 UTC by mattcaswell

This moves the write side of the TLS record layer into the new architecture to mirror the earlier refactoring done on the read side. The refactoring is not yet complete - however this PR is considered to be at a suitable mid-point to allow review. Still to be done:
* Move the "crypto" code for each of the TLS protocol versions into the write record layer. At the moment we "cheat" and use the old "enc" and "mac" functions.
* Move the DTLS code into the new architecture
* Resolve a number of outstanding "TODO" items
* Numerous other cleanups

2022-09-14 07:13 UTC, mattcaswell commented
CIs are now green, so I've taken this out of draft. Ping for reviews.

2022-09-20 18:12 UTC, hlandau requested changes
Aside from one nit, I don't see any issues.

2022-09-21 09:38 UTC, mattcaswell commented
@hlandau typo fixed - please take another look.

2022-09-21 09:46 UTC, hlandau approved these changes

2022-09-22 08:54 UTC, levitte requested changes
There are a couple of spots where I ask for small bits of refactoring.
The mindset is refactoring incrementally, just stuff that you're editing anyway, nothing more.  We might do well to apply that mindset, 'cause it's unlikely that we'll ever get to separate refactoring jobs.

2022-09-22 08:54 UTC, levitte commented on ssl/record/methods/ktls_meth.c
>             return OSSL_RECORD_RETURN_NON_FATAL_ERR;
Shouldn't the return line be re-indented as well?

2022-09-22 08:54 UTC, levitte commented on ssl/record/methods/tls_common.c
> +                           + SSL3_RT_MAX_COMPRESSED_OVERHEAD)
Thus `+` lines look misaligned by one space

2022-09-22 08:54 UTC, levitte commented on ssl/record/methods/tls_common.c
> +                           + SSL3_RT_MAX_COMPRESSED_OVERHEAD)
Same thing below...

2022-09-22 08:54 UTC, levitte commented on ssl/record/methods/tls_common.c
> +
??? Spurious extra lines

2022-09-22 08:54 UTC, levitte commented on ssl/record/methods/tls_common.c
> +            }
This brace is misaligned

2022-09-22 08:54 UTC, levitte commented on ssl/record/methods/tls_common.c
> +            }
A few misaligned lines here

2022-09-22 08:54 UTC, levitte commented on ssl/record/methods/tls_common.c
> +            goto err;
You can drop the braces around `RLAYERfatal(...);`

2022-09-22 08:54 UTC, levitte commented on ssl/record/methods/tls_common.c
> +                    goto err;
You can drop the braces around `RLAYERfatal(...);`

2022-09-22 08:54 UTC, levitte commented on ssl/record/methods/tls_common.c
> +                goto err;
You can drop the braces around `RLAYERfatal(...);`

2022-09-22 08:54 UTC, levitte commented on ssl/record/methods/tls_multib.c
> +        )
Is this condition a block copy from somewhere?  The way things are aligned, it's quite hard to read the logic...

2022-09-22 08:54 UTC, levitte commented on ssl/record/methods/tls_multib.c
> +        )
Ah, now I see where it's copied from...  so pre-existing, yeahok.  Would you mind making it a bit cleaner still?

2022-09-22 08:54 UTC, levitte commented on ssl/record/rec_layer_s3.c
>               (s->mode & SSL_MODE_ENABLE_PARTIAL_WRITE))) {
Since you're editing this bit anyway, mind refactoring it to break line before the logic operators?

2022-09-22 08:54 UTC, levitte commented on ssl/record/rec_layer_s3.c
> +            } else if (s->options & SSL_OP_IGNORE_UNEXPECTED_EOF) {
Didn't we say that this sort of condition should be an explicit comparison, i.e. `((s->options & SSL_OP_IGNORE_UNEXPECTED_EOF) != 0)`?  Would you mind refactoring it?

2022-09-22 08:54 UTC, levitte commented on ssl/t1_enc.c
> +                                        m, comp)) {
The arguments look a bit weirdly misaligned here

2022-09-22 08:54 UTC, levitte commented on ssl/tls13_enc.c
> +                : OSSL_RECORD_PROTECTION_LEVEL_APPLICATION);
These two lines look misaligned by one space

2022-09-22 11:14 UTC, hlandau approved these changes
Still OK

2022-09-22 11:14 UTC, mattcaswell commented
@levitte all your feedback has been addressed in fixup commits. Please take another look.

2022-09-22 11:15 UTC, levitte approved these changes

2022-09-23 12:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-09-23 14:01 UTC, mattcaswell commented
Pushed! Thanks for your reviews!

2022-09-23 14:01 UTC, closed without merging