OSSL_PROVIDER_set_default_search_path() return value
openssl/openssl pull request #19239
Opened 2022-09-19 07:08 UTC by olszomal

`OSSL_PROVIDER_set_default_search_path()` returns `int` value type according to this definition:
```
int OSSL_PROVIDER_set_default_search_path(OSSL_LIB_CTX *, const char *path);
```
CLA: trivial

2022-09-19 08:25 UTC, levitte approved these changes

2022-09-19 08:39 UTC, t8m requested changes
One nit. OK with CLA: trivial.

2022-09-19 08:39 UTC, t8m commented on doc/man3/OSSL_PROVIDER.pod
>                                              const char *path);
Please align this indentation with the opening parentheses.

2022-09-19 14:51 UTC, t8m approved these changes
Still OK with cla: trivial.
@levitte can you reconfirm please?

2022-09-22 03:47 UTC, paulidale approved these changes

2022-09-22 03:48 UTC, paulidale commented
agreed trivial

2022-09-23 04:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2022-09-23 04:15 UTC, paulidale commented
Merged, thanks for the contribution.

2022-09-23 04:15 UTC, closed without merging