Add documentation for the OPENSSL_gmtime functions
openssl/openssl pull request #19257
Opened 2022-09-21 18:07 UTC by tmshort

##### Checklist

- [X] documentation is added or updated
- [ ] tests are added or updated

2022-09-22 01:06 UTC, paulidale approved these changes
One suggestion which is optional.

2022-09-22 01:06 UTC, paulidale commented on doc/man3/OPENSSL_gmtime.pod
> +structures B<from> and B<to>. The difference in days is placed into B<pday>,
B<*pday> perhaps?
Likewise B<*psec>.

Not sure either way.

2022-09-22 08:28 UTC, t8m requested changes

2022-09-22 08:28 UTC, t8m commented on doc/man3/OPENSSL_gmtime.pod
> +It is an error to call OPENSSL_gmtime() with B<result> equal to NULL. The
Please use `I<>` when referencing the parameters instead of bold everywhere in the manpage.

2022-09-22 13:57 UTC, t8m approved these changes

2022-09-22 23:02 UTC, paulidale approved these changes

2022-09-24 00:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-09-26 06:58 UTC, hlandau commented
Merged to master and 3.0. Thank you.

2022-09-26 06:58 UTC, closed without merging