quic: Define SHUT_RD|SHUT_WR for Windows
openssl/openssl pull request #19308
Opened 2022-09-29 23:00 UTC by kiyolee

WIN32 defines `how` options for `shutdown()` in their own way.
This fix defines `SHUT_RD` and `SHUT_RD` based on WIN32 equivalents.

CLA: trivial

##### Checklist

2022-10-04 12:16 UTC, hlandau approved these changes

2022-10-05 07:20 UTC, paulidale requested changes

2022-10-05 07:20 UTC, paulidale commented on ssl/quic/quic_rx_depack.c
> +#ifndef SHUT_RD
Indentation nit.  This should be formatted as:

```c
#ifdef _WIN32
# ifndef SHUT_RD
#  define SHUT_RD SD_RECEIVE
# endif
# ifndef SHUT_WR
#  define SHUT_WR SD_SEND
# endif
# ifndef SHUT_RDWR
#  define SHUT_RDWR SD_BOTH
# endif
#endif
```

2022-10-05 07:28 UTC, levitte commented
Wait, hold on...  we already use `SHUT_RD` in apps/lib/http_server.c, and as far as I can tell, it builds fine.  So maybe this is about including the right header?  Could this be resolved by including "internal/sockets.h"?

2022-10-05 07:29 UTC, levitte commented
Side note: it seems we have no Windows build with `enable-quic`...  we probably should

2022-10-05 08:37 UTC, t8m commented
Closing this PR as it is incorrect.

2022-10-05 08:37 UTC, closed without merging

2022-10-05 09:24 UTC, kiyolee commented
> Wait, hold on... we already use `SHUT_RD` in apps/lib/http_server.c, and as far as I can tell, it builds fine. So maybe this is about including the right header? Could this be resolved by including "internal/sockets.h"?

The code path in http_server.c which involves `SHUT_RD` is not applicable to Windows. (NO_FORK and hence *NO* HTTP_DEAMON)
`SHUT_RD` is not defined in "internal/sockets.h" either.

2022-10-05 09:52 UTC, levitte commented
> > Wait, hold on... we already use `SHUT_RD` in apps/lib/http_server.c, and as far as I can tell, it builds fine. So maybe this is about including the right header? Could this be resolved by including "internal/sockets.h"?
> 
> The code path in http_server.c which involves `SHUT_RD` is not applicable to Windows. (NO_FORK and hence _NO_ HTTP_DEAMON) `SHUT_RD` is not defined in "internal/sockets.h" either.

Yup, I found that out just now.  I'm incorporating the definitions into "internal/sockets.h" in #19345 as we speak.
Thank you for making us look, and for the suggested change, albeit slightly misplaced!

2022-10-08 03:44 UTC, wan7teen-ping commented
Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g

Pada Jum, 30 Sep 2022, 7:01 AM Kelvin Lee ***@***.***>
menulis:

> WIN32 defines how options for shutdown() in their own way.
> This fix defines SHUT_RD and SHUT_RD based on WIN32 equivalents.
>
> CLA: trivial
> Checklist
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/openssl/openssl/pull/19308
> Commit Summary
>
>    - 8782e4a
>    <https://github.com/openssl/openssl/pull/19308/commits/8782e4ade24ae018e28e1655b99fe10dbb1782c5>
>    quic: Define SHUT_RD|SHUT_WR for Windows
>
> File Changes
>
> (1 file <https://github.com/openssl/openssl/pull/19308/files>)
>
>    - *M* ssl/quic/quic_rx_depack.c
>    <https://github.com/openssl/openssl/pull/19308/files#diff-38c7635c72a873d4d53258267676d04ecf7b625177964441ec808e8f3765ce7e>
>    (12)
>
> Patch Links:
>
>    - https://github.com/openssl/openssl/pull/19308.patch
>    - https://github.com/openssl/openssl/pull/19308.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openssl/openssl/pull/19308>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APESUCXYG3SFED3KAUXQXYTWAYNT5ANCNFSM6AAAAAAQZHHERQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>