Fix usage of custom EVP_CIPHER objects
openssl/openssl pull request #19300
Opened 2022-09-29 11:23 UTC by mattcaswell

If a custom EVP_CIPHER object has been passed to EVP_CipherInit() then it
should be used in preference to a fetched cipher.

We also fix a possible NULL pointer deref in the same code for digests.

If the custom cipher passed to EVP_CipherInit() happens to use NID_undef
(which should be a discouraged practice), then in the previous
implementation this could result in the NULL cipher being fetched and
hence NULL encryption being unexpectedly used.

CVE-2022-3358

Fixes #18970

Note that this has been assessed as a low severity security issue. As per our policy, since it is low, it is being fixed in public and will be included in the next release.

We also fix a bug where the cleanup function for an EVP_CIPHER was not always being called when it should, which was highlighted by writing the test for the original issue.

2022-09-29 13:45 UTC, t8m requested changes

2022-09-29 13:45 UTC, t8m commented on crypto/evp/evp_enc.c
> +        if (ctx->cipher->cleanup && !ctx->cipher->cleanup(ctx))
Nit: `ctx->cipher->cleanup != NULL`

2022-09-29 13:45 UTC, t8m commented on test/evp_extra_test.c
> +        return 1;
Maybe `return TEST_skip("Non-default libctx");` ?

2022-09-29 13:54 UTC, mattcaswell commented
Feedback addressed.

2022-09-29 14:06 UTC, togtalk commented
Yes nice please share

2022-09-29 14:44 UTC, t8m approved these changes

2022-09-29 23:16 UTC, paulidale approved these changes

2022-09-29 23:16 UTC, paulidale commented on test/evp_extra_test.c
> +               /*
Is the indentation off here?

2022-09-30 04:19 UTC, levitte commented on test/evp_extra_test.c
> +               /*
Yes it is

2022-10-01 00:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-10-03 00:47 UTC, paulidale commented
Needs an indentation fix before merge.

2022-10-03 14:18 UTC, mattcaswell commented
Pushed to master and 3.0. I fixed the indentation issue during merge. There was a trivial conflict cherry-picking to 3.0 that I also resolved during the merge.

2022-10-03 14:18 UTC, closed without merging