Convert the TLSv1.3 crypto code and KTLS to use the new write record layer
openssl/openssl pull request #19343
Opened 2022-10-04 16:16 UTC by mattcaswell

This is built on top of #19217 and includes those commits. This converts the TLSv1.3 code and all remaining KTLS code to use the new write record layer.

2022-10-05 15:35 UTC, mattcaswell commented
I've now taken this PR out of draft. It has been rebased to pull in all the commits from #19217 which have now been merged and all CI runs are passing (except 1 which appears to be due to a temporary network glitch and not related to this PR).

Ping for review!

2022-10-06 09:26 UTC, hlandau requested changes

2022-10-06 09:26 UTC, hlandau commented on ssl/record/methods/tls_common.c
> +                                            thiswr->length - origlen,
nit: argument indentation

2022-10-06 10:30 UTC, mattcaswell commented
@hlandau - fixup applied following your feedback. Please take another look.

2022-10-06 10:56 UTC, hlandau approved these changes

2022-10-07 13:32 UTC, t8m approved these changes
Great!

2022-10-08 03:32 UTC, wan7teen-ping commented
Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g

Pada Rab, 5 Okt 2022, 12:17 AM Matt Caswell ***@***.***>
menulis:

> This is built on top of #19217
> <https://github.com/openssl/openssl/pull/19217> and includes those
> commits. This converts the TLSv1.3 code and all remaining KTLS code to use
> the new write record layer.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/openssl/openssl/pull/19343
> Commit Summary
>
>    - 7e5e373
>    <https://github.com/openssl/openssl/pull/19343/commits/7e5e3739e6b0ffd27db55767f514956ed4e36c62>
>    Convert the TLSv1.0/1.1/1.2 crypto code to use the new write record layer
>    - 234f4de
>    <https://github.com/openssl/openssl/pull/19343/commits/234f4de4d8f77a411717d187131193373e95e1c6>
>    Enable the ability to query the COMP_METHOD being used in the record layer
>    - 6364b0b
>    <https://github.com/openssl/openssl/pull/19343/commits/6364b0b526090ce52f4d8359c8b67f0f9f9a00fd>
>    Move the SSLv3 crypto code into the new record layer
>    - 9939d82
>    <https://github.com/openssl/openssl/pull/19343/commits/9939d82ebe8f4e5824187092dd29bb28e8ca3ac9>
>    fixup! Convert the TLSv1.0/1.1/1.2 crypto code to use the new write record
>    layer
>    - f20689d
>    <https://github.com/openssl/openssl/pull/19343/commits/f20689d7243d3ec0f7cf0db9c162a36ecf2e7e5b>
>    fixup! Convert the TLSv1.0/1.1/1.2 crypto code to use the new write record
>    layer
>    - 8bfee1b
>    <https://github.com/openssl/openssl/pull/19343/commits/8bfee1bfaab0d39d76f742d8a39582d53ee34ce7>
>    Convert the TLSv1.3 crypto code to the new write record layer
>    - 85536e7
>    <https://github.com/openssl/openssl/pull/19343/commits/85536e7f5895f078b66dc1a07c4a1c8b793b166e>
>    Remove most of the DTLS special casing from the write record code
>    - 5b42e72
>    <https://github.com/openssl/openssl/pull/19343/commits/5b42e721ecd1b890d00d773142553ae40c2a1acd>
>    Remove some unneeded usage of the SSL_CONNECTION object
>    - 14588f4
>    <https://github.com/openssl/openssl/pull/19343/commits/14588f4dede42254f20e95e9a80559c7d951f522>
>    Remove enc_write_state
>    - 3b69480
>    <https://github.com/openssl/openssl/pull/19343/commits/3b69480dae43979913ec3d3693bafebe5a7865c7>
>    Use the configured max_send_fragment value in the write record layer
>    - cc7b8ff
>    <https://github.com/openssl/openssl/pull/19343/commits/cc7b8ff4b45d03b752dddd7b7b5c5cf35abcb3fa>
>    Remove an old TODO from the code
>    - ef4dcfe
>    <https://github.com/openssl/openssl/pull/19343/commits/ef4dcfedc740bc752a39f457f1972db6e4fa155d>
>    Defer write buffer and WPACKET allocation/initialisation to protocol code
>    - 0f065e3
>    <https://github.com/openssl/openssl/pull/19343/commits/0f065e3b41aeb73f9ac9503b130376d254f4704e>
>    Abstract out the record type processing
>    - eb44de3
>    <https://github.com/openssl/openssl/pull/19343/commits/eb44de3ef1a0f93b46b00f01cb715a41e39a77d5>
>    Defer record header preparation to the protocol methods
>    - c9d43c0
>    <https://github.com/openssl/openssl/pull/19343/commits/c9d43c0ffffc900236688458624e8797933c5a1c>
>    Don't check whether we are using KTLS before calling the cipher function
>    - 52533e8
>    <https://github.com/openssl/openssl/pull/19343/commits/52533e869af40faf787bde9508c25b5209c21085>
>    Move record padding out of tls_common.c
>    - de35626
>    <https://github.com/openssl/openssl/pull/19343/commits/de35626bfaa9edac0fe7cd6e620d443cc119028c>
>    Add a prepare for encryption step
>    - 1f20ba6
>    <https://github.com/openssl/openssl/pull/19343/commits/1f20ba69641ff3bc112ef2576572a844dc3f829f>
>    Add a post encryption processing step
>    - 4dc59e6
>    <https://github.com/openssl/openssl/pull/19343/commits/4dc59e609ae41ac6048cfbb73b683d5db40ffd22>
>    Remove ktls specific code from tls_setup_write_buffers
>    - 7acee5d
>    <https://github.com/openssl/openssl/pull/19343/commits/7acee5d27c974c4135a86d87c82a26df1241c7fe>
>    Introduce a step to prepare the BIO before writing
>
> File Changes
>
> (24 files <https://github.com/openssl/openssl/pull/19343/files>)
>
>    - *M* ssl/record/methods/dtls_meth.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-efd767ec66667ad0146364241371a012b9c9dc7aea1a4ae75b6277a63951ea38>
>    (13)
>    - *M* ssl/record/methods/ktls_meth.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-496118932e0c0b35b7c75a4491926685f30541f8d33249ce16f5e33e088994ca>
>    (253)
>    - *M* ssl/record/methods/recmethod_local.h
>    <https://github.com/openssl/openssl/pull/19343/files#diff-a7ef685f185f1b464e45fdfdd6d6094467b937116982bff1bfda8d095aef16bd>
>    (116)
>    - *M* ssl/record/methods/ssl3_meth.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-bf410ae4a5cd41e1132c3096034473de50423911defe70e5ac1a2ee3f9f2476f>
>    (26)
>    - *M* ssl/record/methods/tls13_meth.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-ce8869e17e3fa1e242f095c16608dbc3b1ecbfb06c5a4fc81260f9ba20ab1a8e>
>    (87)
>    - *M* ssl/record/methods/tls1_meth.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-b690295d2d76037198ffed06a160c81b44828486b4f64ce79a350ec5c2835604>
>    (153)
>    - *M* ssl/record/methods/tls_common.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-b5b63207653b4ce9b3774a7c3cfaa40652709026bc66b89d73d15db01d470972>
>    (710)
>    - *M* ssl/record/methods/tls_multib.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-3adc154938830d20bf5b4d4d34efbac6060b9db61e7ef3acb1a639c29d16292a>
>    (33)
>    - *M* ssl/record/methods/tlsany_meth.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-99880ff262f81128eb3cfec02f1966d0ff9e1daa252b8393fb6908b45c9dd7ae>
>    (29)
>    - *M* ssl/record/rec_layer_s3.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-9ad003bc718a126e8376b7542b345cb18ac87cc757304951bbac5f5579d2fbdd>
>    (23)
>    - *M* ssl/record/record.h
>    <https://github.com/openssl/openssl/pull/19343/files#diff-637cea17f0f75cf41cba2307a82b25337c68c5bf4cd4249501d13166058d7a21>
>    (4)
>    - *M* ssl/record/recordmethod.h
>    <https://github.com/openssl/openssl/pull/19343/files#diff-6d9aeb2675f3631544c5288f3d243ea918e8e6dc61382362f4533575686b6e7e>
>    (11)
>    - *M* ssl/record/ssl3_record.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-a4131b6fe8ab7af35f45112ef26d47767c8b35f76466c1468e8cad0f381d1ef8>
>    (157)
>    - *M* ssl/s3_enc.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-9650049bc30d581121a65f68353b47a1394e1b403e3c08e1c19734311fadd18c>
>    (53)
>    - *M* ssl/s3_lib.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-ad6a9d097fbc92d94fab7df63a551ed8c3b923e1c2142a6e003fb4c09a773844>
>    (4)
>    - *M* ssl/ssl_lib.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-38e1eecb6013c2fe8bf194e5020ce1afd6e31c371d7849e041464ad822fe745b>
>    (9)
>    - *M* ssl/ssl_local.h
>    <https://github.com/openssl/openssl/pull/19343/files#diff-6e1fe8a18fd92c9d48804e59ce4a34f73da70c1e57afb422ed856540fb1f82e7>
>    (12)
>    - *M* ssl/statem/extensions.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-ae4256c73de799669abb0fdd1949f03b2d29a8c8b428caa013ce3a8ec0fea137>
>    (12)
>    - *M* ssl/statem/statem.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-60de92d6080d89f09d3e501f29fe58b59f9a0d023554fe1cdf5583bee22deefb>
>    (3)
>    - *M* ssl/statem/statem.h
>    <https://github.com/openssl/openssl/pull/19343/files#diff-5091c93ca556f5e0884432915b099bf1da88911a146db343eaf754ce279c3458>
>    (10)
>    - *M* ssl/statem/statem_clnt.c
>    <https://github.com/openssl/openssl/pull/19343/files#diff-d31fea45b0617f395f40b055ea91c58e5adb62423cb7afce81720a0a447208b9>
>    (25)
>    - *M* ssl/t1_enc.c
>    <https:// [...]

2022-10-08 14:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-10-12 14:54 UTC, mattcaswell commented
Pushed. Thanks.

2022-10-12 14:54 UTC, closed without merging