openssl list: Fix help text about -cipher-algorithms option
openssl/openssl pull request #19370
Opened 2022-10-10 13:35 UTC by faramir-dev

Fixes openssl#19133

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

2022-10-10 23:09 UTC, paulidale approved these changes

2022-10-19 15:35 UTC, mattcaswell requested changes

2022-10-19 15:35 UTC, mattcaswell commented on apps/list.c
> +     "List of symetric cipher algorithms"},
typo: symmetric

2022-10-19 15:35 UTC, mattcaswell commented on doc/man1/openssl-list.pod.in
> +Display a list of symetric cipher, digest, kdf and mac algorithms.
symmetric

2022-10-21 07:06 UTC, paulidale commented
Still good.  I can't spell today :disappointed:

2022-10-21 16:05 UTC, t8m approved these changes

2022-10-22 17:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but this PR has failing CI tests.  Once the tests pass it will get moved to 'approval: ready to merge' automatically, alternatively please review and set the label manually.

2022-10-24 07:52 UTC, mattcaswell approved these changes

2022-10-24 10:05 UTC, hlandau commented
Merged to master and 3.0. Thank you.

2022-10-24 10:05 UTC, closed without merging