Finer grained error records for provider load/init failures
openssl/openssl pull request #19419
Opened 2022-10-16 05:58 UTC by levitte

Saying that init failed when for failure to load a provider module as
well as for the init function not being present as well as the init
function being called and failing is confusing.  Separating the three
cases so that they record different errors will make it easier to
determine causes of failure.

2022-10-16 05:59 UTC, levitte commented
I consider this a bug, which is why I'm targetting both master and 3.0.

2022-10-16 08:14 UTC, beldmit approved these changes
LGTM

2022-10-17 06:25 UTC, levitte commented
Had we had this done earlier, issues like #19368 would have been answered much much quicker.

2022-10-17 09:05 UTC, mattcaswell approved these changes
Approved at least for master - pending the OTC discussion for whether this is ok for 3.0 or not.

2022-10-17 14:06 UTC, t8m commented
I agree that this is rather a bug than feature because the consequence is inability to properly diagnose a common failure.

2022-10-17 14:13 UTC, t8m requested changes

2022-10-18 03:06 UTC, slontis reviewed
Could you possibly reword the first sentence of this commit. Your sentence about things being confusing is confusing :)

2022-10-18 05:48 UTC, levitte commented
> Could you possibly reword the first sentence of this commit. Your sentence about things being confusing is confusing :)

In a way, that's kinda appropriate, no? 😆 

But yeah ok, I'll give that a go

2022-10-18 06:18 UTC, levitte commented
> > Could you possibly reword the first sentence of this commit. Your sentence about things being confusing is confusing :)
> 
> In a way, that's kinda appropriate, no? laughing
> 
> But yeah ok, I'll give that a go

Done.

2022-10-18 06:20 UTC, levitte commented on crypto/provider_core.c
> +                       "name=%s, provider has no provider init function");
Fixed

2022-10-18 06:20 UTC, levitte commented on crypto/provider_core.c
> +            ERR_raise(ERR_LIB_CRYPTO, ERR_R_DSO_LIB);
`prov->name` added

2022-10-18 10:29 UTC, t8m approved these changes

2022-10-18 10:30 UTC, t8m commented
@mattcaswell @beldmit still OK?

2022-10-18 10:34 UTC, mattcaswell approved these changes
Still ok. Subject to the OTC discussion about whether this should go back to 3.0 or not.

2022-10-20 15:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but this PR has failing CI tests.  Once the tests pass it will get moved to 'approval: ready to merge' automatically, alternatively please review and set the label manually.

2022-10-20 16:13 UTC, levitte commented
Merged to master:

2d23ba14630551ee347acafcab81fa1a290c6504 Finer grained error records for provider load/init failures

2022-10-20 16:14 UTC, levitte commented
Waiting for OTC approval to cherry-pick 2d23ba14630551ee347acafcab81fa1a290c6504 to 3.0.

2022-10-25 09:32 UTC, t8m commented
**OTC: This is a bug fix so it is OK for all branches.**

2022-10-25 11:11 UTC, levitte commented
Cheery-picked to 3.0:

840a82982976a0ee4336a3ee0dc4f389aac14b01 Finer grained error records for provider load/init failures

2022-10-25 11:21 UTC, levitte commented
Cherry-picked to 3.1:

22b486e2ac07463b29755fb227a913f09bddc5d2 Finer grained error records for provider load/init failures

2022-10-25 11:21 UTC, closed without merging

2022-10-25 16:19 UTC, kaend commented
Fails to build with `no-dso`
`/Configure no-dso mingw64 && make`

```
crypto/provider_core.c:912:44: error: 'ERR_R_DSO_LIB' undeclared (first use in this function); did you mean 'ERR_R_DSA_LIB'?
  912 |             ERR_raise_data(ERR_LIB_CRYPTO, ERR_R_DSO_LIB,
      |                                            ^~~~~~~~~~~~~
      |                                            ERR_R_DSA_LIB
```