Add thread pool design document (phase 1)
openssl/openssl pull request #19455
Opened 2022-10-20 15:51 UTC by hlandau

This is a successor to #18864 which includes only the parts which are for current implementation in the OpenSSL codebase and for which there appears to be broad consensus. My intention is that we should be able to merge this soon, as the applicable implementing code has already been approved.

The remaining unmerged parts of #18864 remain a proposal available for comment. Therefore, I've converted that to a draft and ask for reviews of this PR instead.

2022-10-21 09:31 UTC, mattcaswell requested changes

2022-10-21 09:31 UTC, mattcaswell commented on doc/designs/thread-api.md
> + * used.
This text should perhaps be updated since the custom thread spawner/manual thread method do not exist anymore in this version of the doc

2022-10-21 09:31 UTC, mattcaswell commented on doc/designs/thread-api.md
> +convenience function will also be provided to give a good ballpark figure:
Shouldn't this text be deleted now?

2022-10-21 09:31 UTC, mattcaswell commented on doc/designs/thread-api.md
> +but for which OpenSSL lacks the necessary OS support.
This needs updating

2022-10-21 09:45 UTC, hlandau commented
Updated.

2022-10-21 14:35 UTC, t8m approved these changes

2022-10-26 08:07 UTC, paulidale approved these changes

2022-10-27 09:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but this PR has failing CI tests.  Once the tests pass it will get moved to 'approval: ready to merge' automatically, alternatively please review and set the label manually.

2022-11-14 08:00 UTC, hlandau commented
I do not think the CIs are relevant.

2022-11-14 11:21 UTC, t8m commented
Merged to master branch. Thank you.

2022-11-14 11:21 UTC, closed without merging