Fix PEM PKEY export leak on error path and avoid segfault if PKEY is NULL
openssl/openssl pull request #19536
Opened 2022-10-29 15:32 UTC by mbroz

These two patches fix
 - a leak on PEM_write_bio_PrivateKey_traditional error patch (easily detectable with valgrind or address sanitizer).
 - check if EVP_PKEY is NULL and avoids segfault

Found by this (simplified) testcase:
```
#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/evp.h>

int main(int arc, char **argv)
{
	EVP_PKEY *pkey = NULL;
	EVP_PKEY_CTX *genctx = NULL;
	BIO *bio = NULL;

	bio = BIO_new_fp(stdout, BIO_NOCLOSE);
	if (!bio) {
		printf("BIO_new_fp failed\n");
		goto out;
	}

	genctx = EVP_PKEY_CTX_new_from_name(NULL, "ED448", NULL);
	if (!genctx) {
		printf("EVP_PKEY_CTX_new_from_name failed\n");
		goto out;
	}

	if (EVP_PKEY_keygen_init(genctx) != 1) {
		printf("EVP_PKEY_keygen_init failed\n");
		goto out;
	}

	if (EVP_PKEY_generate(genctx, &pkey) != 1) {
		printf("EVP_PKEY_generate failed\n");
		goto out;
	}

	/* Check leak in traditional output */
	PEM_write_bio_PrivateKey(bio, pkey, NULL, NULL, 0, 0, NULL);
	PEM_write_bio_PrivateKey_traditional(bio, pkey, NULL, NULL, 0, 0, NULL);

	/* Try pkey = NULL */
	PEM_write_bio_PrivateKey(bio, NULL, NULL, NULL, 0, 0, NULL);
	PEM_write_bio_PrivateKey_traditional(bio, NULL, NULL, NULL, 0, 0, NULL);

out:
	EVP_PKEY_CTX_free(genctx);
	EVP_PKEY_free(pkey);
	BIO_free_all(bio);

	return 0;
}
```

- [x] tests are added or updated

2022-10-31 09:07 UTC, mbroz commented
Hm, should I send CLA docs, or this is a trivial change?

2022-10-31 14:43 UTC, t8m commented
> Hm, should I send CLA docs, or this is a trivial change?

Please send ICLA and possibly CCLA if this was done as part of an employment. This is outside of CLA: trivial limits.

2022-10-31 14:48 UTC, t8m requested changes

2022-10-31 14:48 UTC, t8m commented on crypto/pem/pem_pkey.c
> +    if (x && (x->ameth == NULL || x->ameth->priv_encode != NULL))
use `x != NULL`

2022-10-31 14:48 UTC, t8m commented on crypto/pem/pem_pkey.c
> +    if (!x)
Please use `x == NULL`

2022-10-31 15:06 UTC, mbroz commented
> > Hm, should I send CLA docs, or this is a trivial change?
> 
> Please send ICLA and possibly CCLA if this was done as part of an employment. This is outside of CLA: trivial limits.

OK, I have already sent it, thanks.

2022-10-31 15:11 UTC, mbroz commented
CLA should be solved, I'll close & reopen this PR to clear the flag.

2022-10-31 15:19 UTC, t8m approved these changes

2022-11-09 16:21 UTC, t8m commented
ping for second review

2022-11-09 16:25 UTC, beldmit approved these changes
LGTM

2022-11-10 17:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but this PR has failing CI tests.  Once the tests pass it will get moved to 'approval: ready to merge' automatically, alternatively please review and set the label manually.

2022-11-10 17:12 UTC, t8m commented
Merged to master, 3.1, and 3.0 branches. Thank you for your contribution.

2022-11-10 17:12 UTC, closed without merging