ossl_pool_acquire_entropy: use get_time_stamp() not clock_gettime()
openssl/openssl pull request #19590
Opened 2022-11-02 20:41 UTC by millert

The get_time_stamp() function returns an unsigned 64-bit time stamp using, in order of preference, clock_gettime(), gettimeofday() or time().  This fixes a build issue on systems that either don't provide clock_gettime(), or only provide it with -lrt.

CLA: trivial

2022-11-02 20:52 UTC, kroeckx approved these changes

2022-11-02 20:53 UTC, kroeckx commented
Unrelated to the PR itself, I think only taking 8 bit might not do anything on some systems and always return 0. It's probably better to use 32 bit.

2022-11-03 01:01 UTC, paulidale approved these changes

2022-11-03 01:15 UTC, paulidale requested changes
Thinking further, **this entire approach is bad, very bad**.

Falling back to `time(2)` is going to _remove any and all security_ in the RNG output.  The one second granularity isn't going to produce meaningful entropy and this is being accessed in a tightish loop trying to find entropic bytes.  The most likely outcome is one byte repeated across the entire output.  The other outcome is an single increment in the output.  You'll end up with something OpenSSL thinks is random but which is almost completely deterministic.

@kroeckx, the rationale for the lowest eight bits is because this is repeated several times and they are the bits that _might_ be changing.  Using higher order bits is bad since they'll be unchanging but will still be considered to be entropy.  Better might be to XOR all of the returned bytes into one and use that.  However, is it worthwhile?  We're dealing with a low quality entropy source here.  IMO, the best option would be to simply not do this and try to find another entropy source on the devices in question.

Generating a compile error for machines that can't produce meaningful entropy is reasonable IMO.  It might be better to have something like this instead:
```c
#  ifndef CLOCK_REALTIME
#   error "System timers are insufficient to seed random number generator."
#  endif
```

2022-11-03 01:40 UTC, millert commented
I agree that using time() is terrible but using tv_usec from gettimeofday() is probably not much worse than tv_nsec from clock_gettime() on a lot of systems.  The only way time() is even used is if clock_gettime() or gettimeofday() fail, which is unlikely.

2022-11-03 02:15 UTC, paulidale commented
`getimeofday(2)` ought to be good enough but the fallback could drop back to `time(2)` which _must never_ happen.

Put another way: `get_time_stamp()` is not fit for purpose here.

The best approach is find something else that is random on the system.
A high resolution timer is a poor second unless a lot of care is taken.
Reading timers like this and using them directly as entropy is something that is not generally done.
I'll note that timers _can_ be used as an entropy source but it doesn't look remotely like the code here.

2022-11-03 11:57 UTC, t8m commented
This code is OPENSSL_SYS_VOS specific. Are these systems not having clock_gettime()?

2022-11-03 13:54 UTC, closed without merging