Cleanup : directly include of `internal/nelem.h` when required.
openssl/openssl pull request #19721
Opened 2022-11-19 17:54 UTC by FdaSilvaYY

And so clean a few useless includes

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2022-11-20 20:21 UTC, paulidale approved these changes

2022-11-20 20:37 UTC, romen requested changes
The failure is relevant: the `#include` should be added in `engines/e_devcrypto.c`

2022-11-21 08:10 UTC, FdaSilvaYY commented
> The failure is relevant: the `#include` should be added in `engines/e_devcrypto.c`

Oups, will fix it tonight.

2022-11-21 23:01 UTC, paulidale approved these changes

2022-11-22 16:26 UTC, t8m approved these changes

2022-11-23 17:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-11-23 17:19 UTC, t8m commented
Merged to master and 3.1 branches. Thank you for your contribution.

2022-11-23 17:19 UTC, closed without merging