Implement the QUIC-TLS handshake
openssl/openssl pull request #19748
Opened 2022-11-23 16:39 UTC by mattcaswell

This PR builds on #19703 and so includes all the commits from there. The first commit relevant to this PR is "Create the SSL object for QUIC-TLS"

With this PR we replace the dummy handshake from #19703 with a real TLS handshake.

Using this code it is possible to interoperate with a real external QUIC implementation. I've tested this against the picoquic sample server. The picoquic sample server expects to receive a filename from the client, followed by a FIN on the stream, and it then sends back the contents of the file to the client. I had to hack the sample server to not expect the FIN because we don't currently have an API for signalling FIN. The rest of the sample server was unmodified.

This PR does not include any tests for the same reason that #19703 doesn't, i.e. we can't currently create full connections internally to run them in a test because we have no server. We need #19734 for that. Once that is in I expect us to start expanding the testing.

2022-11-23 16:39 UTC, mattcaswell commented
Marked as draft until #19703 is merged.

2022-11-23 19:44 UTC, kroeckx commented
Running the fuzzer from #19743 on top of this, directly generates a memory leak
```
==3704920==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 136 byte(s) in 1 object(s) allocated from:
    #0 0x562e10ad79ce in malloc (/home/kurt/openssl/openssl/fuzz/quic-client+0x48d9ce) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #1 0x562e10fbfc6b in CRYPTO_malloc /home/kurt/openssl/openssl/crypto/mem.c:196:11
    #2 0x562e10fbfdc0 in CRYPTO_zalloc /home/kurt/openssl/openssl/crypto/mem.c:216:11
    #3 0x562e10e137f0 in BIO_new_ex /home/kurt/openssl/openssl/crypto/bio/bio_lib.c:83:16
    #4 0x562e10e13d28 in BIO_new /home/kurt/openssl/openssl/crypto/bio/bio_lib.c:121:12
    #5 0x562e10d86261 in ossl_quic_tls_tick /home/kurt/openssl/openssl/ssl/quic/quic_tls.c:640:24
    #6 0x562e10d51f9f in ossl_quic_channel_start /home/kurt/openssl/openssl/ssl/quic/quic_channel.c:1387:10
    #7 0x562e10bf6f7b in ensure_channel_and_start /home/kurt/openssl/openssl/ssl/quic/quic_impl.c:612:13
    #8 0x562e10bf6696 in ossl_quic_do_handshake /home/kurt/openssl/openssl/ssl/quic/quic_impl.c:654:10
    #9 0x562e10b8003e in SSL_do_handshake /home/kurt/openssl/openssl/ssl/ssl_lib.c:4535:16
    #10 0x562e10b15eed in FuzzerTestOneInput /home/kurt/openssl/openssl/fuzz/quic-client.c:100:13
    #11 0x562e10b14e64 in LLVMFuzzerTestOneInput /home/kurt/openssl/openssl/fuzz/driver.c:28:12
    #12 0x562e10b2d1e3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e31e3) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #13 0x562e10b2c909 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e2909) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #14 0x562e10b2e4e8 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e44e8) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #15 0x562e10b2e9d2 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e49d2) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #16 0x562e10b1c6e2 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4d26e2) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #17 0x562e10b161b2 in main (/home/kurt/openssl/openssl/fuzz/quic-client+0x4cc1b2) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #18 0x7ff17cd67189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

Indirect leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x562e10ad79ce in malloc (/home/kurt/openssl/openssl/fuzz/quic-client+0x48d9ce) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #1 0x562e10fbfc6b in CRYPTO_malloc /home/kurt/openssl/openssl/crypto/mem.c:196:11
    #2 0x562e10fbfdc0 in CRYPTO_zalloc /home/kurt/openssl/openssl/crypto/mem.c:216:11
    #3 0x562e10ff8bef in CRYPTO_THREAD_lock_new /home/kurt/openssl/openssl/crypto/threads_none.c:24:17
    #4 0x562e10e13972 in BIO_new_ex /home/kurt/openssl/openssl/crypto/bio/bio_lib.c:96:17
    #5 0x562e10e13d28 in BIO_new /home/kurt/openssl/openssl/crypto/bio/bio_lib.c:121:12
    #6 0x562e10d86261 in ossl_quic_tls_tick /home/kurt/openssl/openssl/ssl/quic/quic_tls.c:640:24
    #7 0x562e10d51f9f in ossl_quic_channel_start /home/kurt/openssl/openssl/ssl/quic/quic_channel.c:1387:10
    #8 0x562e10bf6f7b in ensure_channel_and_start /home/kurt/openssl/openssl/ssl/quic/quic_impl.c:612:13
    #9 0x562e10bf6696 in ossl_quic_do_handshake /home/kurt/openssl/openssl/ssl/quic/quic_impl.c:654:10
    #10 0x562e10b8003e in SSL_do_handshake /home/kurt/openssl/openssl/ssl/ssl_lib.c:4535:16
    #11 0x562e10b15eed in FuzzerTestOneInput /home/kurt/openssl/openssl/fuzz/quic-client.c:100:13
    #12 0x562e10b14e64 in LLVMFuzzerTestOneInput /home/kurt/openssl/openssl/fuzz/driver.c:28:12
    #13 0x562e10b2d1e3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e31e3) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #14 0x562e10b2c909 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e2909) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #15 0x562e10b2e4e8 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e44e8) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #16 0x562e10b2e9d2 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e49d2) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #17 0x562e10b1c6e2 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4d26e2) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #18 0x562e10b161b2 in main (/home/kurt/openssl/openssl/fuzz/quic-client+0x4cc1b2) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #19 0x7ff17cd67189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: 140 byte(s) leaked in 2 allocation(s).
```

2022-11-23 19:49 UTC, kroeckx commented
Running it over 438 files, I get:
```
Direct leak of 8580512 byte(s) in 63092 object(s) allocated from:
    #0 0x55b3e615c9ce in malloc (/home/kurt/openssl/openssl/fuzz/quic-client+0x48d9ce) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #1 0x55b3e6644c6b in CRYPTO_malloc /home/kurt/openssl/openssl/crypto/mem.c:196:11
    #2 0x55b3e6644dc0 in CRYPTO_zalloc /home/kurt/openssl/openssl/crypto/mem.c:216:11
    #3 0x55b3e64987f0 in BIO_new_ex /home/kurt/openssl/openssl/crypto/bio/bio_lib.c:83:16
    #4 0x55b3e6498d28 in BIO_new /home/kurt/openssl/openssl/crypto/bio/bio_lib.c:121:12
    #5 0x55b3e640b261 in ossl_quic_tls_tick /home/kurt/openssl/openssl/ssl/quic/quic_tls.c:640:24
    #6 0x55b3e63d6f9f in ossl_quic_channel_start /home/kurt/openssl/openssl/ssl/quic/quic_channel.c:1387:10
    #7 0x55b3e627bf7b in ensure_channel_and_start /home/kurt/openssl/openssl/ssl/quic/quic_impl.c:612:13
    #8 0x55b3e627b696 in ossl_quic_do_handshake /home/kurt/openssl/openssl/ssl/quic/quic_impl.c:654:10
    #9 0x55b3e620503e in SSL_do_handshake /home/kurt/openssl/openssl/ssl/ssl_lib.c:4535:16
    #10 0x55b3e619aeed in FuzzerTestOneInput /home/kurt/openssl/openssl/fuzz/quic-client.c:100:13
    #11 0x55b3e6199e64 in LLVMFuzzerTestOneInput /home/kurt/openssl/openssl/fuzz/driver.c:28:12
    #12 0x55b3e61b21e3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e31e3) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #13 0x55b3e61b1909 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e2909) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #14 0x55b3e61b34e8 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e44e8) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #15 0x55b3e61b39d2 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e49d2) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #16 0x55b3e61a16e2 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4d26e2) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #17 0x55b3e619b1b2 in main (/home/kurt/openssl/openssl/fuzz/quic-client+0x4cc1b2) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #18 0x7f3941367189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

Indirect leak of 252368 byte(s) in 63092 object(s) allocated from:
    #0 0x55b3e615c9ce in malloc (/home/kurt/openssl/openssl/fuzz/quic-client+0x48d9ce) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #1 0x55b3e6644c6b in CRYPTO_malloc /home/kurt/openssl/openssl/crypto/mem.c:196:11
    #2 0x55b3e6644dc0 in CRYPTO_zalloc /home/kurt/openssl/openssl/crypto/mem.c:216:11
    #3 0x55b3e667dbef in CRYPTO_THREAD_lock_new /home/kurt/openssl/openssl/crypto/threads_none.c:24:17
    #4 0x55b3e6498972 in BIO_new_ex /home/kurt/openssl/openssl/crypto/bio/bio_lib.c:96:17
    #5 0x55b3e6498d28 in BIO_new /home/kurt/openssl/openssl/crypto/bio/bio_lib.c:121:12
    #6 0x55b3e640b261 in ossl_quic_tls_tick /home/kurt/openssl/openssl/ssl/quic/quic_tls.c:640:24
    #7 0x55b3e63d6f9f in ossl_quic_channel_start /home/kurt/openssl/openssl/ssl/quic/quic_channel.c:1387:10
    #8 0x55b3e627bf7b in ensure_channel_and_start /home/kurt/openssl/openssl/ssl/quic/quic_impl.c:612:13
    #9 0x55b3e627b696 in ossl_quic_do_handshake /home/kurt/openssl/openssl/ssl/quic/quic_impl.c:654:10
    #10 0x55b3e620503e in SSL_do_handshake /home/kurt/openssl/openssl/ssl/ssl_lib.c:4535:16
    #11 0x55b3e619aeed in FuzzerTestOneInput /home/kurt/openssl/openssl/fuzz/quic-client.c:100:13
    #12 0x55b3e6199e64 in LLVMFuzzerTestOneInput /home/kurt/openssl/openssl/fuzz/driver.c:28:12
    #13 0x55b3e61b21e3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e31e3) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #14 0x55b3e61b1909 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e2909) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #15 0x55b3e61b34e8 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e44e8) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #16 0x55b3e61b39d2 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e49d2) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #17 0x55b3e61a16e2 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4d26e2) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #18 0x55b3e619b1b2 in main (/home/kurt/openssl/openssl/fuzz/quic-client+0x4cc1b2) (BuildId: 5a5b45545fc0d2d017f6256424523e5f6de90053)
    #19 0x7f3941367189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: 8832880 byte(s) leaked in 126184 allocation(s).
```

2022-11-23 20:01 UTC, mattcaswell commented
> Running the fuzzer from https://github.com/openssl/openssl/pull/19743 on top of this, directly generates a memory leak

Thanks. Fixup for that pushed.

2022-11-23 20:34 UTC, kroeckx commented
It's now running against this branch. The memory leak is gone. But it still doesn't seem to find much coverage.

2022-11-23 21:06 UTC, kroeckx commented
After setting up alpn, I get:
```
==3726176==ERROR: AddressSanitizer: heap-use-after-free on address 0x60d000002118 at pc 0x55ae19d83923 bp 0x7ffd13940dc0 sp 0x7ffd13940db8
READ of size 4 at 0x60d000002118 thread T0
    #0 0x55ae19d83922 in BIO_free_all /home/kurt/openssl/openssl/crypto/bio/bio_lib.c:861:18
    #1 0x55ae19ae0370 in ossl_ssl_connection_free /home/kurt/openssl/openssl/ssl/ssl_lib.c:1434:5
    #2 0x55ae19ad4d0b in SSL_free /home/kurt/openssl/openssl/ssl/ssl_lib.c:1341:9
    #3 0x55ae19b5a54e in ossl_quic_free /home/kurt/openssl/openssl/ssl/quic/quic_impl.c:168:5
    #4 0x55ae19ad4d0b in SSL_free /home/kurt/openssl/openssl/ssl/ssl_lib.c:1341:9
    #5 0x55ae19a7e0b2 in FuzzerTestOneInput /home/kurt/openssl/openssl/fuzz/quic-client.c:110:5
    #6 0x55ae19a7ce64 in LLVMFuzzerTestOneInput /home/kurt/openssl/openssl/fuzz/driver.c:28:12
    #7 0x55ae19a95233 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e3233) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #8 0x55ae19a94959 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e2959) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #9 0x55ae19a96538 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e4538) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #10 0x55ae19a96a22 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e4a22) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #11 0x55ae19a84732 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4d2732) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #12 0x55ae19a7e202 in main (/home/kurt/openssl/openssl/fuzz/quic-client+0x4cc202) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #13 0x7fd35ec46189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #14 0x7fd35ec46244 in __libc_start_main csu/../csu/libc-start.c:381:3
    #15 0x55ae199bcb80 in _start (/home/kurt/openssl/openssl/fuzz/quic-client+0x40ab80) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)

0x60d000002118 is located 88 bytes inside of 136-byte region [0x60d0000020c0,0x60d000002148)
freed by thread T0 here:
    #0 0x55ae19a3f722 in __interceptor_free (/home/kurt/openssl/openssl/fuzz/quic-client+0x48d722) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #1 0x55ae19f281f5 in CRYPTO_free /home/kurt/openssl/openssl/crypto/mem.c:277:5
    #2 0x55ae19d7c514 in BIO_free /home/kurt/openssl/openssl/crypto/bio/bio_lib.c:152:5
    #3 0x55ae19d83965 in BIO_free_all /home/kurt/openssl/openssl/crypto/bio/bio_lib.c:863:9
    #4 0x55ae19ae02fb in ossl_ssl_connection_free /home/kurt/openssl/openssl/ssl/ssl_lib.c:1432:5
    #5 0x55ae19ad4d0b in SSL_free /home/kurt/openssl/openssl/ssl/ssl_lib.c:1341:9
    #6 0x55ae19b5a54e in ossl_quic_free /home/kurt/openssl/openssl/ssl/quic/quic_impl.c:168:5
    #7 0x55ae19ad4d0b in SSL_free /home/kurt/openssl/openssl/ssl/ssl_lib.c:1341:9
    #8 0x55ae19a7e0b2 in FuzzerTestOneInput /home/kurt/openssl/openssl/fuzz/quic-client.c:110:5
    #9 0x55ae19a7ce64 in LLVMFuzzerTestOneInput /home/kurt/openssl/openssl/fuzz/driver.c:28:12
    #10 0x55ae19a95233 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e3233) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #11 0x55ae19a94959 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e2959) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #12 0x55ae19a96538 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e4538) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #13 0x55ae19a96a22 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e4a22) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #14 0x55ae19a84732 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4d2732) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #15 0x55ae19a7e202 in main (/home/kurt/openssl/openssl/fuzz/quic-client+0x4cc202) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #16 0x7fd35ec46189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

previously allocated by thread T0 here:
    #0 0x55ae19a3f9ce in malloc (/home/kurt/openssl/openssl/fuzz/quic-client+0x48d9ce) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #1 0x55ae19f27deb in CRYPTO_malloc /home/kurt/openssl/openssl/crypto/mem.c:196:11
    #2 0x55ae19f27f40 in CRYPTO_zalloc /home/kurt/openssl/openssl/crypto/mem.c:216:11
    #3 0x55ae19d7b970 in BIO_new_ex /home/kurt/openssl/openssl/crypto/bio/bio_lib.c:83:16
    #4 0x55ae19d7bea8 in BIO_new /home/kurt/openssl/openssl/crypto/bio/bio_lib.c:121:12
    #5 0x55ae19cee2e1 in ossl_quic_tls_tick /home/kurt/openssl/openssl/ssl/quic/quic_tls.c:644:25
    #6 0x55ae19cb9fef in ossl_quic_channel_start /home/kurt/openssl/openssl/ssl/quic/quic_channel.c:1387:10
    #7 0x55ae19b5efcb in ensure_channel_and_start /home/kurt/openssl/openssl/ssl/quic/quic_impl.c:612:13
    #8 0x55ae19b5e6e6 in ossl_quic_do_handshake /home/kurt/openssl/openssl/ssl/quic/quic_impl.c:654:10
    #9 0x55ae19ae808e in SSL_do_handshake /home/kurt/openssl/openssl/ssl/ssl_lib.c:4535:16
    #10 0x55ae19a7df3f in FuzzerTestOneInput /home/kurt/openssl/openssl/fuzz/quic-client.c:102:13
    #11 0x55ae19a7ce64 in LLVMFuzzerTestOneInput /home/kurt/openssl/openssl/fuzz/driver.c:28:12
    #12 0x55ae19a95233 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e3233) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #13 0x55ae19a94959 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e2959) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #14 0x55ae19a96538 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e4538) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #15 0x55ae19a96a22 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4e4a22) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #16 0x55ae19a84732 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/kurt/openssl/openssl/fuzz/quic-client+0x4d2732) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #17 0x55ae19a7e202 in main (/home/kurt/openssl/openssl/fuzz/quic-client+0x4cc202) (BuildId: 6f7fb1f4fd3b87c0a28a54662f8c6588078fd477)
    #18 0x7fd35ec46189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: heap-use-after-free /home/kurt/openssl/openssl/crypto/bio/bio_lib.c:861:18 in BIO_free_all
Shadow bytes around the buggy address:
  0x0c1a7fff83d0: 00 00 00 00 00 00 00 00 00 00 00 00 fa fa fa fa
  0x0c1a7fff83e0: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c1a7fff83f0: 00 00 00 00 00 00 fa fa fa fa fa fa fa fa 00 00
  0x0c1a7fff8400: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c1a7fff8410: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
=>0x0c1a7fff8420: fd fd fd[fd]fd fd fd fd fd fa fa fa fa fa fa fa
  0x0c1a7fff84 [...]

2022-11-24 10:26 UTC, mattcaswell commented
> After setting up alpn, I get:

My fixup wasn't quite right. I've made another attempt. I've also rebased it to pick up the latest version of #19703.

2022-11-24 10:49 UTC, kroeckx commented
It's running without problem now, but probably still not finding much
coverage. Will try to look at it soon.

2022-11-24 10:52 UTC, mattcaswell commented
Pushed another couple of fixups. Mostly fixing some cosmetic issues, but also fixing a missing call to `BIO_set_retry_write()`.

2022-11-24 11:17 UTC, hlandau requested changes
Looks pretty good.

2022-11-24 11:17 UTC, hlandau commented on ssl/quic/quic_tls.c
> +    if (!ossl_assert(rl->recread = 1) || !ossl_assert(rl == rechandle)) {
typo: `=` instead of `==` here

2022-11-24 11:17 UTC, hlandau commented on ssl/quic/quic_tls.c
> +            * For the purposes of the callback we "pretend" to be normal TLS,
nit: Comment alignment

2022-11-24 11:17 UTC, hlandau commented on ssl/quic/quic_tls.c
> +            * We assume that buflen is always <= UINT16_MAX. Since this is
nit: Comment alignment

2022-11-24 11:18 UTC, hlandau commented
A lot less changes than I was expecting. Nice to see the record layer refactor paid off.

2022-11-24 13:13 UTC, kroeckx commented
Currently don't see anything obvious why it's not doing anything useful,
but I can also not see it actually processing any data. It seems
ossl_quic_do_handshake() just says it wants data but doesn't do anything
with what it got.

2022-11-24 13:15 UTC, mattcaswell commented
> Currently don't see anything obvious why it's not doing anything useful,
but I can also not see it actually processing any data. It seems
ossl_quic_do_handshake() just says it wants data but doesn't do anything
with what it got.

Do you have sample case where you think it should be doing something but it doesn't? I could take a look in the debugger and try and figure out where things goes wrong.

2022-11-24 13:18 UTC, mattcaswell commented
Fixup addressing Hugo's comment pushed.

2022-11-24 13:51 UTC, kroeckx commented
> Do you have sample case where you think it should be doing something but it doesn't? I could take a look in the debugger and try and figure out where things goes wrong.

Clearly I don't have files that provide any coverage, which is the whole point. But after running hours, it should have find something. After 5 seconds it stops finding things. And I'm not sure what I'm doing wrong.

2022-11-24 14:08 UTC, kroeckx commented
If I limit my filesize to 9 bytes, I can reach all the coverage
edges, so I'm clearly not doing anything useful.

2022-11-29 13:59 UTC, mattcaswell commented
I've now rebased this on top of PR #19734 (QUIC Test Server and Basic Echo Test) instead of #19703, and extended it with an additional commit to supply the required test server support. So the basic echo test now creates an actual QUIC connection with a TLS based handshake.

2022-12-30 00:09 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 30 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2023-01-20 09:15 UTC, mattcaswell commented
I've rebased this now that #19734 has been merged. It is now ready for review.

2023-01-20 09:38 UTC, hlandau commented
ubsan CI is relevant.

2023-01-20 09:40 UTC, mattcaswell commented
> ubsan CI is relevant.

Fixed (hopefully).

2023-01-20 14:50 UTC, mattcaswell commented
The one CI failure is not relevant. Ping for reviews.

2023-01-20 16:12 UTC, t8m requested changes
Just nits, otherwise LGTM.

2023-01-23 12:43 UTC, hlandau requested changes
Just a few nits and I'll approve. Overall surprisingly clean and easy to review. It's nice how easy this integration ended up being.

2023-01-23 12:43 UTC, hlandau commented on ssl/quic/quic_tls.c
> +        dummyrec[3] = (unsigned char)((template->buflen >> 8) &0xff);
nit: space after &, likewise for the next line

2023-01-23 12:43 UTC, hlandau commented on ssl/quic/quic_tls.c
> +        dummyrec[3] = (unsigned char)((*datalen >> 8) &0xff);
nit: space after &, etc.

2023-01-23 14:11 UTC, mattcaswell commented on ssl/ssl_local.h
> -#  define SSL_CONNECTION_GET_SSL(sc) ((sc)->user_ssl)
No. I've removed it.

2023-01-23 14:12 UTC, mattcaswell commented
@t8m and @hlandau - Fixup pushed addressing the nits. I've also added a commit to remove the `user_ssl` field which is now no longer used. Please take another look.

2023-01-23 14:14 UTC, hlandau approved these changes

2023-01-23 14:16 UTC, t8m approved these changes
Approved assuming there are no relevant CI failures.

2023-01-24 15:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but this PR has failing CI tests.  Once the tests pass it will get moved to 'approval: ready to merge' automatically, alternatively please review and set the label manually.

2023-01-24 17:32 UTC, mattcaswell commented
The 2 CI failures are unrelated.

Pushed. Thanks for the reviews.

2023-01-24 17:32 UTC, closed without merging