Fix treatment of BUILD_METADATA
openssl/openssl pull request #19815
Opened 2022-12-02 06:11 UTC by levitte

According to documentation [^1], the BUILD_METADATA from VERSION.dat should
be prefixed with a plus sign when used.  It is given this treatment in
Configure, but not in all other scripts that use VERSION.dat directly.
This change fixes that.

2022-12-02 06:12 UTC, levitte commented
I can only assume that no one noticed because no one has used the BUILD_METADATA capability yet.

2022-12-02 11:51 UTC, t8m approved these changes

2022-12-02 11:52 UTC, t8m commented
I am not sure this can be called a bug fix. However it definitely makes sense to have this fixed on 3.1 as well.

2022-12-02 14:36 UTC, levitte commented
I don't know what else you'd call it.

2022-12-06 13:43 UTC, tmshort requested changes

2022-12-06 13:43 UTC, tmshort commented on dev/release-aux/release-version-fn.sh
> +    if [ -n "$PRE_RELEASE_TAG" ]; then _PRE_RELEASE_TAG="+${PRE_RELEASE_TAG}"; fi
Here the prefix for `PRE_RELEASE_TAG` is a `"+"`. Earlier (line 58) a `"-"` is used.

2022-12-06 22:51 UTC, paulidale approved these changes

2022-12-07 04:10 UTC, tmshort approved these changes
LGTM

2022-12-07 04:12 UTC, paulidale commented
Is a unit test for this possible?

We really should have a build that exercises this functionality.
It doesn't seem like a stretch to include such in one of our CI loops.

2022-12-07 23:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2022-12-08 06:24 UTC, closed without merging