Change HKDF to alloc the info buffer.
openssl/openssl pull request #19923
Opened 2022-12-16 02:41 UTC by slontis

Fixes #19909

I have enforced a maximum bound still but it is much higher. Note also that TLS13 still uses the 2048 buffer size.

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

2022-12-16 10:00 UTC, hlandau requested changes
One nit, otherwise looks good.

2022-12-20 07:41 UTC, hlandau approved these changes

2022-12-20 09:23 UTC, t8m approved these changes

2022-12-21 10:00 UTC, openssl-machine commented
This pull request is ready to merge

2022-12-22 11:27 UTC, t8m commented
Merged to master, 3.1, and 3.0 branches. Thank you.

2022-12-22 11:27 UTC, closed without merging