Docs: Move deprecated ECDSA_ functions into a separate file.
openssl/openssl pull request #19936
Opened 2022-12-20 05:59 UTC by slontis

Fixes #19829

Examples added for setting/getting ECDSA SIG related r and s values

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

2022-12-20 09:33 UTC, t8m commented on doc/man3/ECDSA_SIG_new.pod
> +Extract signature 'r' and 's' values from a ECDSA 'signature'
`an ECDSA I<signature> of size I<signaturelen>`

2022-12-20 09:34 UTC, t8m commented on doc/man3/ECDSA_SIG_new.pod
> +Extract signature 'r' and 's' values from a ECDSA 'signature'
Also I'd use italics for r and s.

2022-12-20 09:38 UTC, t8m requested changes

2022-12-20 09:38 UTC, t8m commented on doc/man3/ECDSA_SIG_new.pod
> + ECDSA_SIG_free(obj);
You're freeing the object that owns the r and s values. Perhaps add a comment that they should not be used from here on?

2022-12-20 09:38 UTC, t8m commented on doc/man3/ECDSA_SIG_new.pod
> +in OpenSSL 3.2.
IMO this note is unnecessary. Just delete the section.

2022-12-21 07:50 UTC, hlandau approved these changes

2022-12-21 08:56 UTC, t8m approved these changes

2022-12-22 09:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but this PR has failing CI tests.  Once the tests pass it will get moved to 'approval: ready to merge' automatically, alternatively please review and set the label manually.

2022-12-22 11:29 UTC, t8m commented
Merged to master, 3.1, and 3.0 branches. Thank you.

2022-12-22 11:29 UTC, closed without merging