Correct property EBNF for unquoted strings
openssl/openssl pull request #20023
Opened 2023-01-11 00:41 UTC by paulidale

Replacing #19998.

This is the minimal change.  It would be prudent for unquoted strings to be less liberal in what is allowed to permit future expansions.  The question then becomes what?

- [x] documentation is added or updated
- [ ] tests are added or updated

2023-01-11 04:24 UTC, slontis commented
Is it possible to add a test?

2023-01-11 05:37 UTC, paulidale commented
Testing what exactly?  There are tests for unquoted strings already and this is in no way changing the behaviour of the code -- it's purely the grammar.

2023-01-11 07:08 UTC, levitte commented
Of course you can add a test or two!  #19998 did exactly that.  Negative tests (tests meant to fail) wouldn't be a bad idea, for example.

2023-01-11 07:12 UTC, levitte reviewed
... one might wonder about PropertyName too...

2023-01-11 07:12 UTC, levitte commented on crypto/property/properties.ebnf
> +UnquotedString ::= [A-Z] [^{space},]+
Only upper case?  I ask, because NumberLiteral specifies A-F *and* a-f...

2023-01-11 07:12 UTC, levitte commented on doc/man7/property.pod
> + UnquotedString ::= [A-Z] [^{space},]+
Same thing here

2023-01-11 10:45 UTC, levitte commented
Having tried to use this spec, and having a re-read of them now, I find them increasingly hard to follow.  For example, the way they are written, it looks like only upper case characters are allowed for property names, 'cause the number literal explicitly specifies both `A-F` and `a-f`, indicating to me that letters are case sensitive (which they are in most EBNFs, but not in ABNF).

So we end up with a spec that leaves room for trial and error, or has anyone who wants to know the *actual* rules to find the source and read that instead.  That's exactly what I had to do when a `x.author=@levitte` in my provider sent it tumbling into a chaos of errors.

2023-01-11 10:55 UTC, levitte requested changes
Please add a reference to the EBNF grammar in `doc/man7/property.pod`.  `crypto/property/properties.ebnf` mentions https://bottlecaps.de/rr/ui, that should be in the public docs.

2023-01-11 10:57 UTC, levitte requested changes
Please change all `A-F` to `A-Fa-f` where that's not already the case.  The EBNF grammar that you have used considers letter case sensitive as far as I can tell.

2023-01-11 10:58 UTC, levitte commented
WIth those two changes, I'll be satisfied enough

2023-01-12 00:48 UTC, paulidale commented
There is no benefit adding a link to the grammar in crypto/property.  The two grammars are completely identical.  Instead I've removed the duplication and left the documentation as the canonical reference.

2023-01-15 23:04 UTC, paulidale commented
Negative test added.

2023-01-17 22:32 UTC, paulidale commented
Ping for review

2023-01-18 03:15 UTC, slontis approved these changes
Should this also have a ref to the EBNF standard being used.. (There seem to be multiple of them).

2023-01-18 06:05 UTC, levitte commented
> Should this also have a ref to the EBNF standard being used.. (There seem to be multiple of them).

Yup. That was one of my change requests:

https://github.com/openssl/openssl/pull/20023#pullrequestreview-1243695382

2023-01-18 07:04 UTC, paulidale commented
Link to definition of EBNF added FWIW.

2023-01-18 17:20 UTC, hlandau approved these changes

2023-01-18 21:42 UTC, levitte approved these changes

2023-01-19 22:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but this PR has failing CI tests.  Once the tests pass it will get moved to 'approval: ready to merge' automatically, alternatively please review and set the label manually.

2023-01-19 23:17 UTC, paulidale commented
Merged.

2023-01-19 23:17 UTC, closed without merging