Modify API X509_STORE_CTX_get_current_cert() in document text
openssl/openssl pull request #20038
Opened 2023-01-13 02:02 UTC by NorthHill-16

Modify the documentation text of X509_STORE_CTX_get_current_cert(), the previous text is misleading and vague.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2023-01-13 10:23 UTC, t8m approved these changes
OK with CLA: trivial.

@vdukhovni Are you OK with the improved text?

2023-01-13 21:59 UTC, vdukhovni requested changes

2023-01-13 21:59 UTC, vdukhovni commented on doc/man3/X509_STORE_CTX_get_error.pod
> +I<ctx>. If error occurred, the current certificate will be the one
```suggestion
I<ctx>. If an error occurred, the current certificate will be the one
```

2023-01-13 21:59 UTC, vdukhovni commented on doc/man3/X509_STORE_CTX_get_error.pod
> +that is most closely related to error, or possibly NULL if no such
```suggestion
that is most closely related to the error, or possibly NULL if no such
```

2023-01-13 23:10 UTC, NorthHill-16 commented
Changes are pushed

2023-01-14 00:31 UTC, vdukhovni approved these changes

2023-01-16 09:50 UTC, t8m approved these changes

2023-01-17 10:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-01-17 11:45 UTC, t8m commented
Merged to master, 3.1, and 3.0 branches. Thank you for your contribution.

2023-01-17 11:45 UTC, closed without merging