Add notes about ignoring initialization failures on contexts
openssl/openssl pull request #20136
Opened 2023-01-25 09:16 UTC by t8m

Fixes #20130

##### Checklist

- [x] documentation is added or updated

2023-01-25 09:45 UTC, paulidale requested changes

2023-01-25 09:45 UTC, paulidale commented on doc/man3/EVP_DigestSignInit.pod
> +Ignoring failure of EVP_DigestSignInit() and EVP_DigestSignInit_ex() functions
Ignore failure returns from

2023-01-25 09:45 UTC, paulidale commented on doc/man3/EVP_DigestInit.pod
> +Ignoring failure of EVP_DigestInit_ex(), EVP_DigestInit_ex2(), or
Ignoring failure returns from

2023-01-25 09:45 UTC, paulidale commented on doc/man3/EVP_DigestVerifyInit.pod
> +Ignoring failure of EVP_DigestVerifyInit() and EVP_DigestVerifyInit_ex() functions
Same here and elsewhere

2023-01-25 10:03 UTC, t8m commented
@paulidale fixup pushed

2023-01-25 10:50 UTC, mattcaswell approved these changes

2023-01-25 10:57 UTC, beldmit approved these changes
LGTM.

I'd added smth like "may cause application crash" or "may cause sending plain text data" (for ciphers), but don't think it's crucial.

2023-01-26 17:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-01-27 11:58 UTC, t8m commented
Merged to master, 3.1, and 3.0 branches. Thank you for the reviews.

2023-01-27 11:58 UTC, closed without merging