Update documentation for ChaCha20-poly1305 relating to setting the IV
openssl/openssl pull request #20152
Opened 2023-01-27 03:59 UTC by slontis

length.

It is not recommended to set the value to less than 12 bytes. In OpenSSL 3.0 and later setting the value will result in an error.

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

2023-01-27 09:34 UTC, bernd-edlinger commented on doc/man3/EVP_EncryptInit.pod
> +Warning: Setting the length to values less than 12 will produce an error in OpenSSL
maybe use the same term as the previous sentence "Setting a nonce of less than 12 bytes"

2023-02-27 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2023-03-30 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 61 days ago

2023-04-25 22:23 UTC, t-j-h approved these changes

2023-04-26 12:46 UTC, hlandau requested changes

2023-04-26 12:46 UTC, hlandau commented on doc/man3/EVP_EncryptInit.pod
>  in length.
nit: Blank line here?

2023-05-27 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2023-06-27 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 61 days ago

2023-07-28 00:09 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 30 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2023-08-28 00:09 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 61 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2023-09-26 00:09 UTC, openssl-machine commented
This PR has been closed.  It was waiting for the creator to make requested changes but it has not been updated for 90 days.

2023-09-26 00:09 UTC, closed without merging