Use $config{build_file} instead of $target{build_file}
openssl/openssl pull request #20173
Opened 2023-01-30 12:59 UTC by levitte

If the user specifies an alternative build file than the default, this
alternative is recorded in $config{build_file}, not $target{build_file}.
Therefore, the former should be used, leaving the latter as a mere default.

This is a bug.  While fixing it, document it better too.

2023-01-30 13:24 UTC, t8m approved these changes

2023-01-30 13:36 UTC, levitte commented
This should cherry-pick nicely to 3.1 and 3.0.  1.1.1 requires a
separate PR.

2023-01-30 14:14 UTC, mattcaswell requested changes

2023-01-30 14:14 UTC, mattcaswell commented on INSTALL.md
> +writing `Configurations/build.ninja.tmpl` and the configure with `BUILDFILE`
typo: then configure

2023-01-30 14:34 UTC, levitte commented
#20174 is the corresponding change for 1.1.1.  It's more or less the same, minus documentation (which is different, and interestingly enough more complete for this stuff)

2023-01-30 14:38 UTC, ajkhoury commented
There is still a slight issue with this fix, the outputted files are still named as defined by ` $target{build_file}`. You still need to change one reference in `configdata.pm.in`: https://github.com/openssl/openssl/blob/master/configdata.pm.in#L94

2023-01-30 14:38 UTC, mattcaswell submitted a review, later dismissed

2023-01-30 14:39 UTC, mattcaswell commented
I assume @t8m's approval still holds since it was a trivial fix up.

2023-01-30 14:40 UTC, ajkhoury requested changes
Need to update reference here as well: https://github.com/openssl/openssl/blob/master/configdata.pm.in#L94

2023-01-30 17:42 UTC, levitte commented
> Need to update reference here as well: https://github.com/openssl/openssl/blob/master/configdata.pm.in#L94

Oh!  Right you are

2023-01-30 17:44 UTC, levitte commented
Unfortunately, that means re-approvals are needed

2023-01-30 17:54 UTC, mattcaswell approved these changes

2023-01-30 17:54 UTC, mattcaswell approved these changes

2023-01-30 18:57 UTC, ajkhoury approved these changes

2023-01-30 19:58 UTC, t8m approved these changes

2023-01-31 20:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-02-01 07:31 UTC, t8m commented
Merged to master, 3.1, and 3.0 branches. Thank you.

2023-02-01 07:31 UTC, closed without merging