Fix incomplete error check on BIO_set_accept_name()
openssl/openssl pull request #20206
Opened 2023-02-03 12:49 UTC by nielsdos

BIO_set_accept_name() can return error values -1 and 0 according to my analysis tool and the documentation. Documentation says a value of 1 indicates success. Currently, only an error value != 0 is checked which erroneously interprets a -1 error return value as success. Fix it by changing the check condition.

CLA: trivial

Please note that I found this using a static analysis tool I am developing at the moment. It could therefore be a false positive bug. I manually reviewed the case to be extra sure that it is a real bug.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2023-02-03 15:35 UTC, t8m requested changes
Please use `> 0` condition instead.

2023-02-03 15:46 UTC, nielsdos commented
Updated the check condition, thanks for reviewing.

2023-02-03 15:50 UTC, t8m approved these changes

2023-02-05 23:19 UTC, paulidale approved these changes

2023-02-07 00:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-02-08 14:43 UTC, tmshort commented
Merged to `master`, `openssl-3.1` and `openssl-3.0`. Thank you for your contribution!

2023-02-08 14:43 UTC, closed without merging