Sync CHANGES.md and NEWS.md with 3.0.8 release
openssl/openssl pull request #20228
Opened 2023-02-07 16:23 UTC by t8m

##### Checklist

- [x] documentation is added or updated

2023-02-07 17:01 UTC, mattcaswell requested changes

2023-02-07 17:01 UTC, mattcaswell commented on CHANGES.md
> +[CVE-2022-2097]: https://www.openssl.org/news/vulnerabilities.html#CVE-2022-2274
Copy & paste error here (2097 vs 2274)

2023-02-07 17:01 UTC, mattcaswell commented on NEWS.md
> +[CVE-2022-2097]: https://www.openssl.org/news/vulnerabilities.html#CVE-2022-2274
Same error here

2023-02-08 07:43 UTC, t8m commented on CHANGES.md
> +[CVE-2022-2097]: https://www.openssl.org/news/vulnerabilities.html#CVE-2022-2274
Hmm, this is in 3.0 branch as well. I'll use a separate commit for that so it can be cherry-picked.

2023-02-08 07:48 UTC, t8m commented
The second commit needs to be cherry-picked to 3.0 branch.

2023-02-08 08:33 UTC, paulidale approved these changes

2023-02-08 09:55 UTC, mattcaswell commented
CI failure is unexpected - but unrelated to this PR.

2023-02-08 09:56 UTC, mattcaswell approved these changes

2023-02-09 11:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but this PR has failing CI tests.  Once the tests pass it will get moved to 'approval: ready to merge' automatically, alternatively please review and set the label manually.

2023-02-11 14:05 UTC, t8m commented
Merged to master and 3.1 and the second commit to 3.0 as well. Thank you for the reviews.

2023-02-11 14:05 UTC, closed without merging