Avoid use of _umul128 on Windows ARM64 (VC-WIN64-ARM)
openssl/openssl pull request #20235
Opened 2023-02-08 00:13 UTC by jbekkema

_umul128 is unavailable for ARM64 when building using Visual Studio, causing a linker failure when attempting to build for VC-WIN64-ARM. This limits the use of _umul128 to AMD64 builds.

This applies to both OpenSSL 3.0 and OpenSSL 1.1.1.

CLA: trivial

2023-02-08 00:22 UTC, paulidale commented
The `CLA: trivial` needs to be in the commit body on a line by itself.  `git commit --amend` and `git push -f` recommended.

2023-02-08 00:23 UTC, paulidale approved these changes
Happy to call this trivial.

2023-02-08 06:53 UTC, levitte approved these changes

2023-02-08 07:04 UTC, beldmit commented
CI failure seems irrelevant but needs to be fixed.

Do we consider this fix as urgent?

2023-02-08 07:04 UTC, beldmit approved these changes
LGTM

2023-02-08 07:55 UTC, t8m commented
> Do we consider this fix as urgent?

It is not a CI breakage, so no, not urgent.

2023-02-08 07:57 UTC, t8m commented
We can amend the commit message when merging. I am OK with CLA: trivial for this.

2023-02-08 07:57 UTC, t8m approved these changes

2023-02-08 08:04 UTC, t8m commented
@paulidale There is no VC-WIN64-ARM target on 1.0.2. I do not think this needs to be backported there.

2023-02-08 08:06 UTC, paulidale commented
x86 Win has the same problem.  So does ARM32 Win.

2023-02-08 08:10 UTC, paulidale commented
Yes, x86 32 bit is okay.  My mistake.  This only impacts AARCH64.

2023-02-08 12:27 UTC, tomato42 requested changes
r-, the correct fix is to change the code to use `__umulh` instead

2023-02-08 13:17 UTC, tomato42 commented
I've proposed an alternative fix in #20244

2023-02-08 15:36 UTC, slproweb commented
@tomato42 This pull request that specifically and narrowly includes one supported/adopted platform and thus keeping other platforms from attempting to use an unsupported intrinsic is, IMO, the better, more immediate solution to getting the build fixed and working even if it doesn't result in the most performant solution.  This minor change has also already been signed off on.  I think getting the build working for the target is a higher priority while performance related adjustments like your proposed change can be applied in a future release.

2023-02-08 15:46 UTC, tomato42 commented
@slproweb: I'm the original author of the buggy code. The proper fix, that handles both X64 and ARM64 is not really complex, and the difference in performance of the fallback code vs native instructions is a factor of 5 to 10 (if ARM64 is anything like x86_64 CPUs), you _really_ don't want to use it.

2023-02-09 07:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2023-02-09 08:16 UTC, MonkeybreadSoftware approved these changes
Works for us.

2023-02-12 08:39 UTC, mattcaswell commented
Looks like #20244 has been merged in preference. Closing this.

2023-02-12 08:39 UTC, closed without merging