Provide clarification of the necessary names of provided algorithms
openssl/openssl pull request #20422
Opened 2023-03-02 13:24 UTC by beldmit

A follow-up to #20412

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2023-03-02 13:42 UTC, levitte commented on doc/man3/OSSL_ALGORITHM.pod
> +the developers aren't obliged to provide anythings besides short name.
This basically repeats a lot of the text that's already here, does it not?

I was under the impression that you mostly wanted to make the last paragraph (quoted here) stronger, did I misunderstand?

> It's recommended to make sure that the corresponding **OSSL_ALGORITHM**'s *algorithm_names* include known names as well as the OID itself in canonical decimal text form.  That should cover all scenarios.

2024-04-30 14:55 UTC, t8m requested changes

2024-04-30 14:55 UTC, t8m commented on doc/man3/OSSL_ALGORITHM.pod
> +sinonym for two or more different algorithms), the behavior is not defined.
Typo synonym.

2024-07-01 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 61 days ago

2024-08-01 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 92 days ago

2024-09-01 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 123 days ago

2024-10-03 00:08 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 30 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2024-11-03 00:08 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 61 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2024-12-02 00:08 UTC, openssl-machine commented
This PR has been closed.  It was waiting for the creator to make requested changes but it has not been updated for 90 days.

2024-12-02 00:08 UTC, closed without merging