fips: Use salt >= 16 bytes in PBKDF2 selftest
openssl/openssl pull request #20429
Opened 2023-03-03 11:36 UTC by neverpanic

NIST SP 800-132 [\[1\]][1] section 5.1 says "[t]he length of the randomly-generated portion of the salt shall be at least 128 bits", which implies that the salt for PBKDF2 must be at least 16 bytes long (see also Appendix A.2.1).

The FIPS 140-3 IG [\[2\]][2] section 10.3.A requires that "the lengths and the properties of the Password and Salt parameters, as well as the desired length of the Master Key used in a CAST shall be among those supported by the module in the approved mode."

As a consequence, the salt length in the self test must be at least 16 bytes long for FIPS 140-3 compliance. Switch the self test to use the only test vector from RFC 6070 that uses salt that is long enough to fulfil this requirement. Since RFC 6070 does not provide expected results for PBKDF2 with HMAC-SHA256, use the output from [\[3\]][3], which was generated with python cryptography, which was tested against the RFC 6070 vectors with HMAC-SHA1.

 [1]: https://doi.org/10.6028/NIST.SP.800-132
 [2]: https://csrc.nist.gov/CSRC/media/Projects/cryptographic-module-validation-program/documents/fips%20140-3/FIPS%20140-3%20IG.pdf
 [3]: https://github.com/brycx/Test-Vector-Generation/blob/master/PBKDF2/pbkdf2-hmac-sha2-test-vectors.md

##### Checklist

- [ ] ~documentation is added or updated~
- [x] tests are added or updated

2023-03-03 13:25 UTC, beldmit approved these changes
LGTM

2023-03-05 20:43 UTC, paulidale commented
pycrypto uses OpenSSL underneath doesn't it?

What about repurposing one of the test vectors from `test/recipes/30-test_evp_data/evpkdf_pbkdf2.txt`?

2023-03-05 21:15 UTC, neverpanic commented
> pycrypto uses OpenSSL underneath doesn't it?
> 
> What about repurposing one of the test vectors from `test/recipes/30-test_evp_data/evpkdf_pbkdf2.txt`?

Any reason why those would be more trustworthy?

In fact, I'm using exactly the vector that's in that file at line 95, except with truncated output: https://github.com/openssl/openssl/blob/master/test/recipes/30-test_evp_data/evpkdf_pbkdf2.txt#L95-L100

2023-03-05 23:23 UTC, paulidale approved these changes

2023-03-05 23:24 UTC, paulidale commented
I'm not sure of their provenance but if they weren't generated using OpenSSL, I'd consider them a better test than using vectors generated by the code under test.

2023-03-06 18:50 UTC, t8m requested changes

2023-03-06 18:50 UTC, t8m commented on providers/fips/self_test_data.inc
> + * which ran these test vectors with SHA-256. */
Please fix the comment formatting - beginning and end of comment should be on a separate line.

2023-03-07 08:27 UTC, slontis commented
3.0 also?

2023-03-07 09:10 UTC, paulidale commented
This isn't required for 3.0 but should be harmless to include (famous last words).

2023-03-07 12:10 UTC, t8m approved these changes

2023-03-07 12:11 UTC, t8m commented
@paulidale @beldmit the comment formatting was fixed, please reapprove.

I assume there is no need to restart the 24 h wait for this style nit fix.

2023-03-07 12:21 UTC, beldmit commented
I confirm reapproval

2023-03-07 17:29 UTC, t8m commented
Merged to master and 3.1 branches. Thank you for your contribution.

2023-03-07 17:29 UTC, closed without merging