QUIC User Datagram Injection
openssl/openssl pull request #20451
Opened 2023-03-07 19:10 UTC by hlandau

This adds a function which can be used to inject datagrams manually into a QUIC connection as though they were received from the network.

cc @t-j-h

2023-03-08 10:30 UTC, hlandau commented
Updated.

2023-03-15 01:49 UTC, paulidale approved these changes
Two trivial adjustments, approved when addressed.

2023-03-15 01:49 UTC, paulidale commented on doc/man3/SSL_inject_net_dgram.pod
> +Copyright 2000-2023 The OpenSSL Project Authors. All Rights Reserved.
Just _2023_ here.

2023-03-15 01:49 UTC, paulidale commented on test/quic_tserver_test.c
> +         * datagrams..
Single full stop

2023-03-15 10:56 UTC, t8m requested changes

2023-03-15 10:56 UTC, t8m commented on doc/man3/SSL_inject_net_dgram.pod
> +=head1 COPYRIGHT
A HISTORY section is missing.

2023-03-20 16:27 UTC, hlandau commented
Updated.

2023-03-20 22:07 UTC, paulidale approved these changes

2023-03-21 23:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-03-21 23:14 UTC, paulidale commented
Merged.

2023-03-21 23:14 UTC, closed without merging