UI code style cleanup
openssl/openssl pull request #2047
Opened 2016-12-08 17:02 UTC by levitte

##### Checklist

- [x] CLA is signed

##### Description of change

Mostly condition check changes.

2016-12-08 17:03 UTC, levitte commented
@richsalz, I think you're interested in this.

2016-12-08 17:07 UTC, richsalz requested changes

2016-12-08 17:07 UTC, richsalz commented on crypto/ui/ui_lib.c
> +            if (strchr(cancel_chars, *p) != 0) {
NULL not zero.

2016-12-08 17:07 UTC, richsalz commented on crypto/ui/ui_lib.c
>      else
remove the else.  or consider the ?: operator.

2016-12-08 17:07 UTC, richsalz commented on crypto/ui/ui_lib.c
>      else
remove the else. or consider the ?: operator.

2016-12-08 17:07 UTC, richsalz commented on crypto/ui/ui_lib.c
> +    if (method != NULL)
you know what i'm going to say.

2016-12-08 17:50 UTC, levitte commented
All done

2016-12-08 18:02 UTC, richsalz approved these changes

2016-12-08 18:38 UTC, levitte commented
Merged

2016-12-08 18:38 UTC, closed without merging

2016-12-08 19:17 UTC, levitte commented
Merged

2016-12-23 20:10 UTC, KjellKod commented
@levitte, I am curious. As I am going through the openssl git history for pull request I only see pull requests that are closed. Your comment implies that this was merged but the pull request shows only that it was closed. 

I'm not sure how git is used in the OpenSSL project but it, at least to me, makes it hard for an outsider to see what pull requests are merged vs just closed. Or am I missing something obvious?

2016-12-23 20:18 UTC, levitte commented
@KjellKod github isn't really our main repo, even though we work with PRs.  Furthermore, we add a few lines in all the commits to indicate who reviewed, as well as what pull request they came from.  Have a look at 120fb9e43656e1801c75a4fbb7c178ebec9bac18 as an example.  This particular pull ended up as the mentioned commit for the master branch, e01cee6d8fbba09dc811af91a5e24dab95fc66a1 in 1.1.0 and 59ba83c9897b1ed311aa16cb1f575ffae4650068 in 1.0.2.

2016-12-23 21:31 UTC, KjellKod commented
Thanks