Update documentation to reflect new Windows on Arm configurations.
openssl/openssl pull request #20525
Opened 2023-03-16 13:31 UTC by everton1984

Two new configuration targets were added for Windows on Arm but the documentation is not reflecting it. This patch hopefully fixes this.

2023-03-16 14:17 UTC, t8m requested changes
Please split the long lines.

2023-03-16 15:50 UTC, everton1984 commented on NOTES-WINDOWS.md
> +    - `perl Configure VC-CLANG-WIN64-CLANGASM-ARM` if you want Windows on ARm (win-arm64)
Done! Thanks a lot for the comments.

2023-03-16 15:58 UTC, t8m approved these changes

2023-03-16 17:18 UTC, tom-cosgrove-arm approved these changes
LGTM

2023-03-20 13:44 UTC, t8m commented
Merged to master branch. Thank you for your contribution.

2023-03-20 13:44 UTC, closed without merging