Add simple interoperability test with Cloudflare quiche
openssl/openssl pull request #20527
Opened 2023-03-16 17:26 UTC by t8m

This is an external test which requires recursive checkout of the cloudflare-quiche submodule.

We simply run a client against the example quiche-server serving HTTP/0.9 requests.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2023-03-17 09:20 UTC, mattcaswell requested changes

2023-03-17 09:20 UTC, mattcaswell commented on test/quic_client_test.c
> +    int c_fd = -1;
`int c_fd = INVALID_SOCKET;`

2023-03-17 09:20 UTC, mattcaswell commented on test/quic_client_test.c
> +    if (c_fd >= 0)
`if (c_fd != INVALID_SOCKET)`

2023-03-19 22:52 UTC, paulidale approved these changes
One nit.

2023-03-19 22:52 UTC, paulidale commented on test/quic_client_test.c
> + * Copyright 2022 The OpenSSL Project Authors. All Rights Reserved.
2023

2023-03-20 13:59 UTC, t8m commented
@mattcaswell @paulidale fixup pushed

2023-03-20 15:06 UTC, mattcaswell approved these changes

2023-03-21 23:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-03-21 23:13 UTC, paulidale commented
Merged.

2023-03-21 23:13 UTC, closed without merging