Disable policy tree test if preconditions are not right
openssl/openssl pull request #20572
Opened 2023-03-22 01:11 UTC by paulidale

no-ec and no-bulk both break the test.

- [ ] documentation is added or updated
- [x] tests are added or updated

2023-03-22 09:40 UTC, bernd-edlinger commented
1.1.1 does not have no-bulk, and with no-ec all tests are passed.

2023-03-22 10:53 UTC, t8m requested changes

2023-03-22 10:53 UTC, t8m commented on test/recipes/80-test_policy_tree.t
> +plan skip_all => "No bulk encryption support" if disabled("bulk");
no-bulk by itself does not mean anything but it implies disabling multiple other things, one of them being ec and that's the reason why the no-bulk builds are broken. So please drop this line.

2023-03-22 11:27 UTC, t8m commented
Not mine :grin:

2023-03-23 08:01 UTC, t8m approved these changes
OK with urgent

2023-03-23 08:02 UTC, t8m commented
ping for second review. This needs to be merged ASAP.

2023-03-23 08:53 UTC, slontis approved these changes

2023-03-23 09:10 UTC, paulidale commented
Merged to all branches.

2023-03-23 09:10 UTC, closed without merging