fix non-fetchable hashes in openssl dgst -list
openssl/openssl pull request #20651
Opened 2023-03-30 11:42 UTC by GauriSpears

`openssl dgst -engine gost -list` doesn't show hashes added by gost-engine because they are not supported by EVP_MD_fetch and EVP_get_digestbyname should be used instead. Another example of this issue has been fixed in https://github.com/openssl/openssl/pull/12689
By the way, `openssl enc -engine gost -list` works correctly.

2023-04-12 06:54 UTC, paulidale approved these changes

2023-04-12 10:41 UTC, paulidale commented
I'm okay with trivial.

2023-04-12 11:41 UTC, t8m requested changes

2023-04-12 11:41 UTC, t8m commented on apps/dgst.c
> +    {
Style nit: This needs to be at the previous line

2023-04-13 09:37 UTC, t8m approved these changes
OK with CLA: trivial.

2023-04-13 09:38 UTC, t8m commented
@paulidale please reconfirm

2023-04-13 10:03 UTC, paulidale commented
Confirmed.  I don't feel that reconfirmation is necessary for a trivial reformatting like this.

2023-04-14 12:41 UTC, t8m commented
Squashed and merged to master, 3.1, and 3.0 branches. Thank you for your contribution.

2023-04-14 12:41 UTC, closed without merging