psk_client_cb honor the hint, GH #20785
openssl/openssl pull request #20787
Opened 2023-04-20 10:44 UTC by rurban

- [ ] documentation is added or updated
- [ ] tests are added or updated

2023-04-20 13:32 UTC, t8m commented on doc/man3/SSL_CTX_set_psk_client_callback.pod
> +"Client_identity" string is used then instead.
IMO this is wrong place - you're changing s_client and that's where the documentation should be amended.

2023-04-21 09:16 UTC, t8m commented on test/ssl_old_test.c
> +    ret = BIO_snprintf(identity, max_identity_len, "%s", hint ? hint : "Client_identity");
Use `hint != NULL` as condition and split the long line please.

2023-04-21 10:28 UTC, t8m commented
@mattcaswell Do you think this is worth CHANGES.md entry?

2023-04-25 06:56 UTC, t8m commented
@rurban please do not rebase the PR unless there is a merge conflict.

2023-04-25 06:56 UTC, t8m commented
ping @mattcaswell for opinion on this and whether CHANGES.md entry is warranted.

2023-04-25 07:13 UTC, rurban commented
Tomas: Sorry. I disabled now automatic force pushes of rebased branches, which I already PR'd.

2023-04-25 10:02 UTC, rurban commented
The one failing CI job needs to be re-started. External network error

2023-05-26 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2023-06-26 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 61 days ago

2023-07-27 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 92 days ago

2023-08-27 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 123 days ago

2023-09-27 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 154 days ago

2023-11-26 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2023-12-27 00:10 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 61 days ago

2024-01-27 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 92 days ago

2024-02-27 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 123 days ago

2024-03-29 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 154 days ago

2024-04-29 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 185 days ago

2024-05-13 10:49 UTC, mattcaswell requested changes

2024-05-13 10:49 UTC, mattcaswell commented on apps/s_client.c
> +    ret = BIO_snprintf(identity, max_identity_len, "%s", used_hint);
This is not correct. The hint is a hint sent from the server to the client to help the client decide which identity to use. It is not typically supposed to be used *as* the identity itself.

From RFC4279:
> Both clients and servers may have pre-shared keys with several
   different parties.  The client indicates which key to use by
   including a "PSK identity" in the ClientKeyExchange message (note
   that unlike in [SHAREDKEYS], the session_id field in ClientHello
   message keeps its usual meaning).  To help the client in selecting
   which identity to use, the server can provide a "PSK identity hint"
   in the ServerKeyExchange message.

2024-06-13 00:09 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 30 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2024-06-13 08:30 UTC, closed without merging