Fixes documentation regarding options -no_ssl3, -no_tls1, -no_tls1_1, -no_tls1_2, -no_tls1_3
openssl/openssl pull request #20815
Opened 2023-04-23 20:49 UTC by rkarmaka98

Fixes #19014 no_* options clarification in Documentation in the man page. As no_* options don't support on s_time and ciphers commands.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2023-04-23 21:31 UTC, rkarmaka98 commented
I agree that it is a trivial change.

2023-04-23 21:39 UTC, rkarmaka98 commented
I agree that it is a trivial change.

2023-04-23 21:49 UTC, rkarmaka98 commented
@t8m https://github.com/openssl/openssl/issues/19014#issuecomment-1217864612

2023-04-24 09:48 UTC, t8m requested changes

2023-04-24 09:48 UTC, t8m commented on doc/man1/openssl.pod
> +B<no_*> options doesnot work on B<s_time>,B<ciphers> commands but works with
Typo: `do not`

Add a space after comma.

Typo: 'work'

2023-04-24 09:48 UTC, t8m commented on doc/man1/openssl.pod
> +command such as B<s_client>.
Better would be `B<s_client> and B<s_server> commands`.

2023-04-24 15:10 UTC, t8m approved these changes

2023-04-24 15:10 UTC, t8m commented
OK with CLA: trivial

2023-04-26 04:39 UTC, closed without merging