Prevent a fuzzing timeout in the conf fuzzer
openssl/openssl pull request #20839
Opened 2023-04-26 14:23 UTC by mattcaswell

The fuzzer was creating a config file with large numbers of includes which are expensive to process. However this should not cause a security issue, and should never happen in normal operation so we can ignore it.

Fixes ossfuzz issue 57718.

2023-04-26 14:31 UTC, mattcaswell commented
See openssl/fuzz-corpora#6

2023-04-26 16:44 UTC, t8m requested changes

2023-04-26 16:44 UTC, t8m commented on crypto/conf/conf_def.c
> +                 * sources. We just set an aribtrary limit on the allowed
Typo: arbitrary

2023-04-27 01:59 UTC, paulidale approved these changes
With the typo fix.

2023-04-28 10:10 UTC, mattcaswell commented
I've rebased this, fixed the typo, and updated the corpora submodule to bring in the relevant fuzz testcase.

@t8m - please take another look
@paulidale - please reconfirm

2023-04-28 10:13 UTC, t-j-h approved these changes

2023-04-28 12:33 UTC, t8m approved these changes

2023-04-29 13:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-05-01 09:59 UTC, mattcaswell commented
Just wainting on https://github.com/openssl/fuzz-corpora/pull/8 to merge before merging this one.

2023-05-02 02:31 UTC, paulidale commented
still good, although there is a conflict now.

2023-05-02 10:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2023-05-08 09:43 UTC, mattcaswell commented
Pushed master/3.1/3.0. I resolved the minor conflict with the submodule hash during merge. I did not cherry-pick back to 3.1/3.0 the submodule change because that submodule does not exist in 3.1/3.0.

2023-05-08 09:43 UTC, closed without merging