QUIC: Rename SSL_tick, SSL_get_tick_timeout
openssl/openssl pull request #20879
Opened 2023-05-03 18:29 UTC by hlandau

Built on top of MSMT PR.

```
9a3f93ddfb QUIC: Update documentation to reflect compatibility of DTLS APIs
12e12b4ec4 QUIC APL: Allow DTLSv1 APIs to be used for compatibility
3d1142a376 QUIC: Update documentation for SSL_get_event_timeout
5dfa5ae60e QUIC APL: Change SSL_get_event_timeout API design
b4976d91bb QUIC: Rename SSL_tick, SSL_get_tick_timeout
8ec61607a8 QUIC Documentation: Rename SSL_tick, SSL_get_tick_timeout
```

2023-05-08 09:58 UTC, mattcaswell commented
Needs updating how that #20580 has merged.

2023-05-09 13:47 UTC, hlandau commented
Built on MSST so will wait until that's merged.

2023-05-18 11:51 UTC, hlandau commented
Sorry, typo - this is built on MSMT.

2023-05-24 09:45 UTC, hlandau commented
Rebased and ready for review.

2023-05-24 12:23 UTC, mattcaswell requested changes
Needs yet another rebase!

2023-05-24 12:23 UTC, mattcaswell commented on doc/man3/SSL_get_event_timeout.pod
> +SSL_get_event_timeout - determine when an SSL object next needs to be ticked
Rephrase "needs to be ticked", since we're not using the tick terminology any more.

2023-05-24 12:23 UTC, mattcaswell commented on doc/man3/SSL_get_event_timeout.pod
> +zero and I<*is_infinite> is set to 0.
"set to zero" is slightly confusing since `tv` points to a struct type not an integer type.

2023-05-24 12:23 UTC, mattcaswell commented on doc/man3/SSL_get_rpoll_descriptor.pod
> +SSL_get_event_timeout(3) (if any) expires
Should be enclosed in `L<>`

2023-05-24 12:23 UTC, mattcaswell commented on ssl/quic/quic_impl.c
> +/* SSL_handle_events; handles events by ticking the reactor. */
perhaps rephrase by avoid the word "ticking"

2023-05-24 12:23 UTC, mattcaswell commented on ssl/quic/quic_impl.c
> + * should be ticked by the application by calling SSL_handle_events(). tv is set
ticked?

2023-05-24 15:09 UTC, hlandau commented
Updated.

2023-05-26 08:49 UTC, mattcaswell requested changes

2023-05-26 08:49 UTC, mattcaswell commented on doc/man3/DTLSv1_handle_timeout.pod
> +L<SSL_handle_events(3)> supersedes all use cases for this this function and may
typo: this this

2023-05-26 08:49 UTC, mattcaswell commented on doc/man3/SSL_handle_events.pod
> +calls to L<SSL_get_event_timeout(3)>; ticking is not performed automatically by
ticking?

2023-05-26 08:49 UTC, mattcaswell commented on doc/man3/SSL_handle_events.pod
> +that this is different to QUIC which also performs ticking implicitly; see
ticking?

2023-05-26 09:54 UTC, hlandau commented
Updated.

2023-05-26 10:17 UTC, mattcaswell approved these changes

2023-05-26 10:18 UTC, mattcaswell commented
@t8m please reconfirm after the latest change

2023-05-26 10:20 UTC, t8m approved these changes

2023-05-26 10:21 UTC, t-j-h commented
It wouldn't hurt in all the test programs to check the return code from SSL_handle_events but approved with or without that haven't been dealt with.

2023-05-26 10:22 UTC, t8m commented
> It wouldn't hurt in all the test programs to check the return code from SSL_handle_events but approved with or without that haven't been dealt with.

That could be a separate PR

2023-05-27 11:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2023-05-29 06:55 UTC, t8m commented
Merged to master branch. Thank you!

2023-05-29 06:55 UTC, closed without merging