QUIC Conformance Updates: Key Update
openssl/openssl pull request #21029
Opened 2023-05-23 12:01 UTC by hlandau

QUIC conformance updates in the area of key updates. This clears the conformance board for RFC 9001 s. 6.

Built on top of the SSL_tick rename PR.

```
15e290d546 QUIC: Test key update works correctly
57a97dc129 QUIC CHANNEL: Optimise key update using ACKs
b505ba2a5c QUIC: Add internal APIs for white-box testing of key update
26c5b45834 QUIC CHANNEL: Enforce the RX packet forgery limit
e717de7400 QUIC RXDP: Strictly enforce ACK PNs with regard to TX key epochs
8e62246a35 QUIC CHANNEL: Ensure new packets aren't enforced with old keys
1678db040c QUIC CHANNEL: Handle key updates correctly
43fc073ae3 QUIC TXP: Make TXP use time callback correctly
f27a84c5ed QUIC APL: Correct implementation of time callback override
32753e6d06 QUIC RX: Support reporting the key epoch a packet was received with
fc29444df2 QUIC TXP: Allow callbacks on ACK transmission
57465179d7 QUIC TXP: Allow next PN to be used to be queried
f0bb2ee9a9 QUIC RX: Refactor key update callback to provide PN
5eb2f0c05e QUIC TXP: Remove TX key update handling from TXP
a856e12317 QUIC TXP: Refactor status output to use an extensible structure
22532dd043 QUIC ACKM: Allow largest acked PN to be queried
8498334fa8 QUIC WIRE: Utility function to determine if PN is in an ACK frame
02ca5a2382 QUIC Glossary: TXKU, RXKU, KU
```

2023-05-24 17:24 UTC, hlandau commented
Rebased

2023-05-30 07:19 UTC, hlandau commented
Rebased

2023-05-31 14:40 UTC, mattcaswell requested changes

2023-05-31 14:40 UTC, mattcaswell commented on ssl/quic/quic_channel.c
> +
Spurious blank line inserted here

2023-05-31 14:40 UTC, mattcaswell commented on ssl/quic/quic_channel.c
> +static void ch_rxku_tick(QUIC_CHANNEL *ch)
Is tick the right name here?

2023-06-01 14:41 UTC, t8m requested changes
Just very minor nits. Good work!

2023-06-01 14:41 UTC, t8m commented on ssl/quic/quic_record_rx.c
>          return;
I assume `returns 0` in the comment refers to the ossl_qrl_enc_level_set_key_update() function return. Would it make sense to change the comment to : `We are already in RXKU, so we don't call callback again.`

2023-06-12 12:42 UTC, hlandau commented on ssl/quic/quic_channel_local.h
> +    uint64_t                        txku_threshold_override;
Good point, I'll wire this up.

2023-06-12 13:14 UTC, hlandau commented
Updated.

2023-06-13 10:30 UTC, mattcaswell approved these changes

2023-06-15 23:27 UTC, paulidale commented
Merged.

2023-06-15 23:27 UTC, paulidale approved these changes

2023-06-15 23:27 UTC, closed without merging