doc: update FIPS provider version information
openssl/openssl pull request #21060
Opened 2023-05-25 22:03 UTC by paulidale

With 3.0.8 validated, we need to note this in the documentation.

Counterpart of #21049 for 3.0.x

- [x] documentation is added or updated
- [ ] tests are added or updated

2023-05-26 06:57 UTC, t8m approved these changes

2023-05-29 00:35 UTC, paulidale commented
Second review required.

2023-05-29 14:16 UTC, levitte approved these changes

2023-05-30 11:45 UTC, t8m requested changes

2023-05-30 11:45 UTC, t8m commented on doc/man7/OSSL_PROVIDER-FIPS.pod
> +
I would just remove this.

2023-05-30 11:45 UTC, t8m commented on doc/man7/fips_module.pod
> +
And this.

2023-05-31 00:15 UTC, paulidale commented
Ping @openssl/committers for second review please.

2023-05-31 07:41 UTC, t8m approved these changes

2023-06-01 06:19 UTC, paulidale commented
Merged, thanks for the reviews.

2023-06-01 06:19 UTC, closed without merging