QUIC: CID conformance
openssl/openssl pull request #21078
Opened 2023-05-30 01:01 UTC by paulidale

- [ ] documentation is added or updated
- [ ] tests are added or updated

2023-05-30 06:27 UTC, t8m requested changes

2023-05-30 07:03 UTC, paulidale commented on ssl/quic/quic_channel.c
> +    if (new_remote_seq_num - new_retire_prior_to > 1) {
It's going to need reworking once we properly support connections.  I'd prefer to leave until then.

2023-05-30 07:21 UTC, t8m approved these changes

2023-05-30 07:59 UTC, paulidale commented on ssl/quic/quic_channel.c
> +            return;
I just removed the check -- we can't validate out of order packet seq_no increase by one IMO.
We also don't send new CID packets, so there is nothing needed for this.

2023-05-31 00:16 UTC, paulidale commented
Ping @openssl/committers for second review please.

2023-05-31 20:10 UTC, t8m commented on ssl/quic/quic_channel.c
> +    if (new_retire_prior_to - ch->cur_retire_prior_to > 10) {
Yes, it is, see the code above.

2023-06-01 07:24 UTC, paulidale commented
Merged, thanks for the comments

2023-06-01 07:24 UTC, closed without merging