CMP: support securely getting root CA cert update
openssl/openssl pull request #21129
Opened 2023-06-05 21:14 UTC by DDvO

This pertains to the CMP API, app, doc, and tests.

The CMP client may send a `genm` request message with infoType `id-it-rootCaCert` (using option `-infotype rootCaCert`)
for retrieving any available root CA cert update, which the server provides in a `genp`  response message with infoType `id-it-rootCaKeyUpdate`.
The client verifies any obtained updated root CA cert, using the transition certificate `newWithOld` etc. as defined in RFC 4210 section 4.4, and saves it in file given with `-newwithnew`.
The transition certificates `newWithOld` and e `oldWithNew`, as far as provided, are optionally saved as well.

This PR also includes related improvements as separate commits:
* CMP app and API doc: add note on critical server auth on receiving trust anchor certs
* CMP doc: various small corrections, mostly on PBM vs. MAC-based protection
* rename `OSSL_CMP_get{,1}_caCerts` and improve `OSSL_CMP_exec_certreq.pod`
* APPS `load_key_certs_crls()`: improve error string macro `FAIL_NAME`

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

2023-06-06 07:34 UTC, t8m commented
Would some of the documentation updates be applicable to stable branches?

2023-06-06 09:10 UTC, DDvO commented
Yes. I will provide respektive backports.

2023-06-06 17:56 UTC, DDvO commented
> Yes. I will provide respective backports.

Done in #21138

2023-07-04 06:30 UTC, DDvO commented
Thank you @t8m for your yesterday's quick review of #21116.
Can you please also resume reviewing this PR soon?
This feature is high on our (Siemens) CMP priority list.

2023-07-11 06:50 UTC, DDvO commented
Rebased to fix a simple merge conflict in the docs.

Can we please get this PR forward soon, such that it will make it into 3.2?

2023-07-11 20:17 UTC, t8m requested changes
One minor nit

2023-07-12 07:44 UTC, DDvO commented on test/recipes/80-test_cmp_http.t
> +    if disabled("ecx"); # EDDSA test key material in Mock/newWithNew.pem
> disabled("ec") implies disabled("ecx")

Yes, but according to my experience not the other way round.
Yesterday, after rebasing, I got a CI failure for `no-ecx` on a test case involving the mentioned EDDSA cert:
https://github.com/openssl/openssl/actions/runs/5516732133/jobs/10058437759?pr=21129
So I added `if disabled("ecx")` and the failure disappeared.
Thus I believe both exclusions are needed, at least for the current state of the exclusion mechanism.

2023-07-12 11:28 UTC, t8m commented on test/recipes/80-test_cmp_http.t
> +    if disabled("ecx"); # EDDSA test key material in Mock/newWithNew.pem
No, they aren't. You just leave `disabled("ecx")` and remove the `disabled("ec")`.

2023-07-12 14:31 UTC, DDvO commented on test/recipes/80-test_cmp_http.t
> +    if disabled("ecx"); # EDDSA test key material in Mock/newWithNew.pem
Indeed, due to the implication already present.
Done.

2023-07-12 14:38 UTC, t8m approved these changes

2023-07-14 03:05 UTC, paulidale commented on doc/man3/OSSL_CMP_exec_certreq.pod
> +The I<newWithNew> certificate is meant to be certificate that will be trusted.
meant to be **a** certificate

2023-07-14 06:58 UTC, DDvO commented on doc/man1/openssl-cmp.pod.in
> +The newWithNew certificate is meant to be certificate that will be trusted.
Oops, fixed, also in `OSSL_CMP_exec_certreq.pod`.

2023-07-14 06:59 UTC, DDvO commented on doc/man1/openssl-cmp.pod.in
> +When a client obtains from a CMP server CA certificates that it is going to
done

2023-07-14 06:59 UTC, DDvO commented on doc/man3/OSSL_CMP_exec_certreq.pod
> +As far as the I<newWithOld> and I<oldWithNew> output parameters are not NULL,
done

2023-07-14 07:05 UTC, paulidale approved these changes

2023-07-15 08:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-07-16 22:48 UTC, paulidale commented
Merged.

2023-07-16 22:48 UTC, closed without merging