Partially revert #18070 (Add support for Windows CA certificate store)
openssl/openssl pull request #21190
Opened 2023-06-13 09:52 UTC by hlandau

As discussed at OTC. Blocker for 3.2. I kept and tweaked the documentation and the store itself.

2023-06-13 11:20 UTC, t8m requested changes

2023-06-13 11:20 UTC, t8m commented on doc/man3/X509_get_default_cert_file.pod
> +default. This is ambiguous. For example, specifying a value of
There is duplicate `by default` in this sentence. Looks awkward to me.

2023-06-13 11:20 UTC, t8m commented on CHANGES.md
> +   expected to be loaded by default in the next minor release of OpenSSL.
Perhaps better to say - expected to be loaded by default in future.

2023-06-13 11:20 UTC, t8m commented on doc/man3/X509_get_default_cert_file.pod
> +Copyright 2023 The OpenSSL Project Authors. All Rights Reserved.
2022-2023?

2023-06-14 07:42 UTC, hlandau commented
Updated.

2023-06-14 07:44 UTC, t8m approved these changes

2023-06-14 07:46 UTC, paulidale approved these changes

2023-06-14 09:24 UTC, levitte approved these changes

2023-06-14 09:50 UTC, mattcaswell approved these changes

2023-06-15 08:02 UTC, paulidale commented
Merged.

2023-06-15 08:02 UTC, closed without merging