feat: add missing pki / pmi extension object identifiers
openssl/openssl pull request #21232
Opened 2023-06-18 18:07 UTC by JonathanWilbur

I know there is aversion among OpenSSL maintainers for including new object identifiers in OpenSSL's embedded database, but:

1. I plan (if not others as well) to submit PRs for OpenSSL to support some, if not all, of these extensions, and
2. These object identifiers are specified in ITU Recommendation X.509 (2019), so I think these object identifiers are exceptionally worthy of inclusion in the internal database, even if the extensions are never fully implemented or supported.

2023-06-23 12:49 UTC, t8m requested changes
The CI failure is relevant.

2023-06-27 07:54 UTC, t8m approved these changes

2023-06-27 22:43 UTC, paulidale approved these changes

2023-06-28 23:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-06-28 23:30 UTC, paulidale commented
Merged, thanks for the contribution.

2023-06-28 23:30 UTC, closed without merging