`EVP_PKEY_{en,de}capsulate.pod`: fix glitches and add some detail and hints
openssl/openssl pull request #21397
Opened 2023-07-07 15:36 UTC by DDvO

SSIA

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

2023-07-07 16:05 UTC, DDvO commented
Ouch, many (clearly unrelated) CI failures.
Hope this will get resolved QUIC-kly.

2023-07-10 01:15 UTC, paulidale approved these changes

2023-07-10 14:44 UTC, t8m requested changes

2023-07-10 15:50 UTC, DDvO commented on doc/man3/EVP_PKEY_decapsulate.pod
> +Note that I<ctx> is usually is produced using L<EVP_PKEY_CTX_new_from_pkey(3)>,
fixed

2023-07-10 16:26 UTC, t8m approved these changes

2023-07-10 16:44 UTC, DDvO commented
Thanks @paulidale and @t8m for your swift approvals.
Pauli, could you please re-confirm after the nit fix.

2023-07-12 01:57 UTC, paulidale approved these changes

2023-07-13 05:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-07-13 09:33 UTC, DDvO commented
Merged to master, 3.0, and 3.1.
Thanks @t8m and @paulidale for your quick approvals.

2023-07-13 09:35 UTC, closed without merging