ms\applink.c: Option to suppress includes
openssl/openssl pull request #21556
Opened 2023-07-25 22:04 UTC by ideafarm

Define APPLINK_NOiNCLUDES to suppress includes.  This is useful when the symbols in applink.c must be modified in order to use wrappers.  The latter is needed when the compiler uses a default calling convention other than cdecl for its C library functions.  (E.g. Open Watcom.)

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2023-07-26 08:32 UTC, mattcaswell requested changes

2023-07-26 08:32 UTC, mattcaswell commented on ms/applink.c
> +#ifndef APPLINK_NOiNCLUDES
The mixed case looks very strange to me. I would just call this `APPLINK_NO_INCLUDES`

2023-07-27 21:31 UTC, ideafarm commented
Thank you, Mr. Caswell. Good catch.

------- Original Message -------
On Wednesday, July 26th, 2023 at 1:32 AM, Matt Caswell ***@***.***> wrote:

> @mattcaswell requested changes on this pull request.
>
> ---------------------------------------------------------------
>
> In [ms/applink.c](https://github.com/openssl/openssl/pull/21556#discussion_r1274565805):
>
>> @@ -34,9 +34,12 @@
>  #define APPLINK_MAX     22      /* always same as last macro */
>
>  #ifndef APPMACROS_ONLY
> +
> +#ifndef APPLINK_NOiNCLUDES
>
> The mixed case looks very strange to me. I would just call this APPLINK_NO_INCLUDES
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/openssl/openssl/pull/21556#pullrequestreview-1547118949), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAXLIOUYWRPD5YHL2G6WCILXSDI2HANCNFSM6AAAAAA2XWEKS4).
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-07-28 07:57 UTC, mattcaswell approved these changes
Approved.

This PR has merge commits which we do not allow, but that can be resolved by whoever commits this on push to the repo.

2023-07-28 16:20 UTC, ideafarm commented
I apologize for screwing this contribution up. It is my lifetime first opensource contribution and I don't really understand the process.

I understand you to be saying that someone else can fix this and that you do not need me to do anything else. Let me know if you need me to do something.
------- Original Message -------
On Friday, July 28th, 2023 at 12:57 AM, Matt Caswell ***@***.***> wrote:

> @mattcaswell approved this pull request.
>
> Approved.
>
> This PR has merge commits which we do not allow, but that can be resolved by whoever commits this on push to the repo.
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/openssl/openssl/pull/21556#pullrequestreview-1551565362), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAXLIOWTZEU4C2LVE43NLTTXSNWFZANCNFSM6AAAAAA2XWEKS4).
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-07-28 18:15 UTC, closed without merging

2023-07-28 18:57 UTC, ideafarm commented
Please reject PR #21556. I just deleted and reforked and redid the same changes and made a new PR: https://github.com/openssl/openssl/pull/21595.

------- Original Message -------
On Friday, July 28th, 2023 at 9:20 AM, Wo'O Ideafarm publication delayed 4 yrs (not private) ***@***.***> wrote:

> I apologize for screwing this contribution up. It is my lifetime first opensource contribution and I don't really understand the process.
>
> I understand you to be saying that someone else can fix this and that you do not need me to do anything else. Let me know if you need me to do something.
> ------- Original Message -------
> On Friday, July 28th, 2023 at 12:57 AM, Matt Caswell ***@***.***> wrote:
>
>> @mattcaswell approved this pull request.
>>
>> Approved.
>>
>> This PR has merge commits which we do not allow, but that can be resolved by whoever commits this on push to the repo.
>>
>> —
>> Reply to this email directly, [view it on GitHub](https://github.com/openssl/openssl/pull/21556#pullrequestreview-1551565362), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAXLIOWTZEU4C2LVE43NLTTXSNWFZANCNFSM6AAAAAA2XWEKS4).
>> You are receiving this because you authored the thread.Message ID: ***@***.***>