QUIC: Assorted Tests 1, Connection Closure Reason
openssl/openssl pull request #21565
Opened 2023-07-26 17:13 UTC by hlandau

Built on miscellaneous conformance updates PR. New commits in this PR:

This also finally wires up the connection closure reason string in the API.

```
eb52c1fa33 QUIC TEST: Connection closure reason testing
4f04df9e8f QUIC APL/CHANNEL: Wire up connection closure reason
d70e7982b7 QUIC TEST: Test repeated HANDSHAKE_DONE, non-minimal encoding
d6d619f475 QUIC TEST: Test NEW_CONN_ID frames
b503c93c80 QUIC TEST: Test malformed crypto stream data, excess buffering
a5b6c6be70 QUIC TEST: Ensure bogus BLOCKED frames are ignored
422bcecf36 QUIC TEST: Ensure PATH_RESPONSE is ignored
126e28a7f8 QUIC TEST: Test ACK frame generation
9f6aa9c751 QUIC TEST: Ensure PING causes ACK generation
e0113e80f3 QUIC TEST: Fault Injection: PADDING
```

Fixes https://github.com/openssl/project/issues/75
Fixes https://github.com/openssl/project/issues/77
Fixes https://github.com/openssl/project/issues/81
Fixes https://github.com/openssl/project/issues/82
Fixes https://github.com/openssl/project/issues/86
Fixes https://github.com/openssl/project/issues/85

More tests to come.

2023-07-27 10:30 UTC, hlandau commented
```
2ca869eb88 fixup! QUIC TEST: RESET_STREAM, STOP_SENDING
16de4a7b01 QUIC TEST: RESET_STREAM, STOP_SENDING
e20794c546 fixup! QUIC TEST: Connection closure reason testing
```

Fixes https://github.com/openssl/project/issues/80

2023-07-27 15:45 UTC, hlandau commented
Added coverity fixes (see https://github.com/openssl/project/issues/108)

2023-07-28 12:42 UTC, h-vetinari commented
> Fixes https://github.com/openssl/project/issues/75
> Fixes https://github.com/openssl/project/issues/77
> Fixes https://github.com/openssl/project/issues/81
> Fixes https://github.com/openssl/project/issues/82
> Fixes https://github.com/openssl/project/issues/86
> Fixes https://github.com/openssl/project/issues/85
> Fixes https://github.com/openssl/project/issues/80

Is there a compelling reason for not keeping the issue tracking public?

2023-07-28 16:49 UTC, hlandau commented
> > Fixes [openssl/project#75](https://github.com/openssl/project/issues/75)
> > Fixes [openssl/project#77](https://github.com/openssl/project/issues/77)
> > Fixes [openssl/project#81](https://github.com/openssl/project/issues/81)
> > Fixes [openssl/project#82](https://github.com/openssl/project/issues/82)
> > Fixes [openssl/project#86](https://github.com/openssl/project/issues/86)
> > Fixes [openssl/project#85](https://github.com/openssl/project/issues/85)
> > Fixes [openssl/project#80](https://github.com/openssl/project/issues/80)
> 
> Is there a compelling reason for not keeping the issue tracking public?

We only just created this issue tracking repository. We intend to make it public soon. It is absolutely the intention that this become public.

2023-07-28 16:49 UTC, hlandau commented
CI does not appear relevant.

2023-08-02 14:44 UTC, mattcaswell commented
Can this be rebased?

2023-08-02 19:51 UTC, hlandau commented
Done.

2023-08-04 13:41 UTC, mattcaswell commented
Seems to be lots of failing CIs.

2023-08-04 14:56 UTC, mattcaswell requested changes

2023-08-08 13:42 UTC, mattcaswell commented
Needs a rebase

2023-08-09 10:05 UTC, t8m requested changes

2023-08-09 10:23 UTC, mattcaswell approved these changes
I'm ok with this subject to @t8m's comments being addressed/responded to

2023-08-09 16:49 UTC, hlandau commented on ssl/quic/quic_channel.c
> +            --l;
`l + 1` on the subsequent line could overflow.

An application could pass a `SIZE_MAX` reason string. Absurd perhaps, but I think it's strange to make this code less correct.

2023-08-09 16:51 UTC, hlandau commented
Updated

2023-08-09 16:52 UTC, t8m approved these changes

2023-08-10 07:28 UTC, mattcaswell approved these changes

2023-08-10 07:28 UTC, mattcaswell commented
Just reconfirming my approval following the trivial fix. I consider the 24 hour timer to have started from  @t8m's approval.

2023-08-10 17:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2023-08-10 17:19 UTC, hlandau commented
Merging now.

2023-08-10 17:38 UTC, hlandau commented
Merged to master. Thanks for the reviews.

2023-08-10 17:38 UTC, closed without merging