CMP: add support for offline requests
openssl/openssl pull request #21660
Opened 2023-08-04 21:19 UTC by DDvO

This is helpful in situations where a CMP client does not (yet) have an online connection to its PKI services.
The client dumps its request message using.`-reqout` to a file without attempting to contact a server.
Later the client, or even some other machine not having access to the private key to be certified
(which usually is needed for the proof of possession), can take up request message using `-reqin` and send it out.
Upon receiving the response, it can check the certificate in the response
by matching the certified public key with the public key in the request message file.

To this end,
* `apps/cmp`: add `-reqout_only` option for dumping/saving just the initial CMP request message, 
which is like `-reqout` but does not contact any server
* `apps/cmp`: extend documentation and diagnostics for using `-reqin` in special situations
*  `apps/cmp`: improve `-reqin` option to read fallback public key from first request message file given; to this end:
* `crypto/cmp/cmp_msg.c`: add `OSSL_CMP_MSG_get0_certreq_publickey()` and fix a coding style nit

On this occasion, refactor `apps/cmp.c` a little to fix some coding style nits and for more convenient source-level debugging (by factoring out the first loop over the CLI arguments to a helper function `handle_opts_upfront()`).

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

2023-09-04 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2023-09-26 06:45 UTC, DDvO commented
Rebased to fix trivial merge conflict in `apps/cmp.c`.

2023-10-27 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2023-11-27 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 61 days ago

2023-12-22 07:07 UTC, DDvO commented
rebased to fix merge conflicts

2024-01-17 15:41 UTC, DDvO commented
Rebased again to fix merge conflicts.

Can we please get this done now as well?

2024-01-17 17:35 UTC, DDvO commented
Rebased to fix further merge conflict

2024-02-02 19:03 UTC, t8m requested changes
Just 3 minor things

2024-02-02 19:03 UTC, t8m commented on crypto/cmp/cmp_msg.c
> +            return 0;
`return NULL;`

2024-02-02 19:32 UTC, DDvO commented on apps/cmp.c
> +        return 0; /* in any case, stop at this point, not contacting server */
Oops, fixed.

2024-02-02 19:32 UTC, DDvO commented on crypto/cmp/cmp_msg.c
> +            return 0;
Fixed as well.

2024-02-05 09:05 UTC, t8m commented on crypto/err/openssl.txt
> +CMP_R_UNEXPECTED_SENDER:106:unexpected sender
Hmm, OK. Although numbers are cheap :grin:

2024-02-05 09:05 UTC, t8m approved these changes

2024-02-07 08:01 UTC, DDvO commented
Thank you Tomas for reviewing and approving this.

Asking @openssl/committers for 2nd review.

2024-02-23 09:18 UTC, DDvO commented
Ping @openssl/committers for 2nd review.

2024-03-01 15:44 UTC, DDvO commented
@openssl/committers could anyone please give his blessing,
such that this makes it into 3.3, after already waiting in here since August.

2024-03-01 16:40 UTC, beldmit approved these changes
I don't understand the purpose of the code but have overall impression it is in a good shape

2024-03-06 07:52 UTC, DDvO commented
Merged - thanks a lot @t8m and @beldmit for your reviews

2024-03-06 07:52 UTC, closed without merging