Only add jdkTrustedKeyUsage attr. to chain cert. in PKCS12
openssl/openssl pull request #21816
Opened 2023-08-23 07:53 UTC by mdavidsaver

Allows `openssl pkcs12 ...` to produce PKCS12 files which produce almost identical output from java `keytool`, and are usable with at least one java application.

Following the round-trip and comparison process outlined in #21791.  The resulting diff of `keytool -v -list` output for the `-alias server1` entry is identical, showing the full chain of trust `rootCA -> intermediateCA -> server1`.  The other two entries differ by not having friendlyName attributes, which does not seem to have any functional effect.

2023-08-23 13:10 UTC, mattcaswell requested changes

2023-08-23 13:11 UTC, mattcaswell commented
Please can you submit a CLA?

https://www.openssl.org/policies/cla.html

2023-09-23 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2023-10-24 00:09 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 30 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2023-10-24 07:50 UTC, t8m commented
@nhorman this might be of an interest? Should this or something similar be done?

2023-10-24 08:11 UTC, nhorman commented
I _think_ (need to look at this more closely), but with the recent changes in #22215  this change appears to be obviated.  I say that because the changes in #22215 alter pcks12 behavior such that, when --jdktrust is asserted, --nokeys is implied, meaning any bag added to the pkcs12 file will necessarily be a certbag rather than a keybag.  Adding this of course won't hurt anything, but I don't believe its necessecary

2023-11-24 00:09 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 30 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2023-12-12 11:24 UTC, nhorman commented
These changes are obviated by https://github.com/openssl/openssl/issues/22215 and https://github.com/openssl/openssl/pull/23005 , closing

2023-12-12 11:24 UTC, closed without merging