QUIC: Run multistream tests in blocking mode as well
openssl/openssl pull request #21827
Opened 2023-08-24 09:38 UTC by hlandau

This expands the multistream test to run everything in both blocking and non-blocking mode using the same set of scripts. This should dramatically increase our test coverage for our APIs in blocking mode.

Internally this works by spinning up an extra thread to tick the TSERVER so that we can enter a blocking call in the main thread.

Built on the WAIT_PEER PR.

2023-08-24 12:21 UTC, t8m commented
CI still relevant

2023-08-24 12:31 UTC, hlandau commented
Yeah, I'm investigating.

2023-08-25 19:58 UTC, hlandau commented
This is due to our Windows code not having an implementation of `ossl_crypto_condvar_broadcast`. I'm working on a fix.

2023-08-28 06:53 UTC, trixieboyle commented
> This expands the multistream test to run everything in both blocking and non-blocking mode using the same set of scripts. This should dramatically increase our test coverage for our APIs in blocking mode.
> 
> Internally this works by spinning up an extra thread to tick the TSERVER so that we can enter a blocking call in the main thread.
> 
> Built on the WAIT_PEER PR.

Tammy Boyle

2023-08-30 08:18 UTC, hlandau commented
Updated and rebased, CI passing, ready for review.

This adds a new Win32 pre-Vista condition variable emulation algorithm, and tests on Windows are now passing.

2023-09-04 14:09 UTC, mattcaswell commented
Needs another rebase

2023-09-04 14:15 UTC, hlandau commented
Rebased

2023-09-04 16:31 UTC, mattcaswell requested changes

2023-09-04 16:32 UTC, mattcaswell commented
Hmmm....is CI failure relevant?

2023-09-04 16:53 UTC, hlandau commented
> Hmmm....is CI failure relevant?

It doesn't look like it.

Updated.

2023-09-04 19:01 UTC, t8m approved these changes

2023-09-05 07:14 UTC, mattcaswell approved these changes

2023-09-06 09:33 UTC, hlandau commented
Merged to master. Thanks for the reviews.

2023-09-06 09:33 UTC, closed without merging