Store delete - 2nd attempt
openssl/openssl pull request #21901
Opened 2023-08-30 13:20 UTC by beldmit

An alternative to #21869

The objects to be deleted are identified by URI

- [X] documentation is added or updated
- [X] tests are added or updated

2023-08-30 13:22 UTC, beldmit commented
@levitte I didn't find how to make the code less clumsy when passing ui_method/ui_data (the PW callback struct is not an option, I think, and a dummy context is also not the best option).

The open question is whether we need to pass the params to the delete function.

2023-08-30 13:23 UTC, beldmit commented
@simo5 could you please take a look?

2023-08-30 13:51 UTC, simo5 commented
You need to provide a password callback to the store, I need it to be able to delete objects form pkcs#11.

2023-08-30 13:56 UTC, beldmit commented
@simo5 is ui_method/ui_data not enough?

2023-08-30 14:02 UTC, simo5 commented
I never dealt with it in the provider that I recall, the rest of the STORE API provides a pwd callback though, I would like consistency.

2023-08-30 14:06 UTC, beldmit commented
@levitte what is the best way then? Dummy store context?

2023-08-31 09:41 UTC, beldmit commented
@simo5 I inherited an approach from #20131. 
@levitte ready for review, I think.

2023-09-13 08:39 UTC, levitte requested changes
One code style nit.  Otherwise, I like what I see

2023-09-13 08:39 UTC, levitte commented on include/openssl/core_dispatch.h
> +                    OSSL_PASSPHRASE_CALLBACK *pw_cb, void *pw_cbarg))
```suggestion
OSSL_CORE_MAKE_FUNC(int, store_delete,
                    (void *provctx, const char *uri, const OSSL_PARAM params[],
                     OSSL_PASSPHRASE_CALLBACK *pw_cb, void *pw_cbarg))
```

2023-09-13 08:47 UTC, beldmit commented on include/openssl/core_dispatch.h
> +                    OSSL_PASSPHRASE_CALLBACK *pw_cb, void *pw_cbarg))
Fixed and pushed. Thanks!

2023-09-13 10:03 UTC, levitte approved these changes
This is clear, this is neat.  Yup!

2023-09-13 10:05 UTC, beldmit commented
I kindly ask @openssl/committers for the 2nd approval

2023-09-13 10:30 UTC, levitte commented
Actually, @openssl/otc.  I want another OTC pair of eyes on this

2023-09-13 11:32 UTC, t8m approved these changes

2023-09-14 12:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-09-15 08:31 UTC, beldmit commented
Merged. Thanks for the reviews!

2023-09-15 08:34 UTC, closed without merging