Bind provider search property to ssl object
openssl/openssl pull request #21961
Opened 2023-09-05 00:34 UTC by wbeck10

The SSL_CTX is created with the library context which can contain multiple providers.
At this stage the SSL_CTX object contains the provider query parameter and all the settings for SSL connection.

It makes sense for developer to create a SSL_CTX early at the application entry and apply all the settings before creating the SSL object. However, it can be the case that the app needs to toggle between provider preference when creating SSL objects.
This pull request will add the possibility to bind the provider query parameter to the SSL object by using a new SSL_new_ex API.
During the SSL connection, the provider query parameter from the SSL object will be used when set otherwise the SSL_CTX provider query parameter will be used (which is the current way).

2023-09-05 01:45 UTC, paulidale requested changes

2023-09-05 01:45 UTC, paulidale commented on ssl/ssl_rsa.c
> +    if (ssl && ssl->propq)
Please include the `!= NULL` for each as per coding style.

2023-09-05 01:45 UTC, paulidale commented on ssl/t1_trce.c
> +    if (ssl && ssl->propq)
Please include the `!= NULL` for each as per style guide.

2023-09-05 01:45 UTC, paulidale commented on ssl/ssl_lib.c
> +    if (ret)
Just drop this, SSL_free handles NULL correctly.

2023-09-05 01:45 UTC, paulidale commented on ssl/ssl_local.h
> +      (s != NULL ? (s->propq ? s->propq : s->ctx->propq) : NULL)
Missing `!= NULL`

2023-09-05 01:45 UTC, paulidale commented on ssl/ssl_local.h
> +          SSL_CONNECTION_GET_SSL(spq)->propq : SSL_CONNECTION_GET_CTX(spq)->propq) : NULL)
The indention here is quite off and it's fairly complicated.
Maybe consider making this a function and spreading everything nicely?

2023-09-05 01:45 UTC, paulidale commented on ssl/ssl_lib.c
> +SSL *SSL_new_ex(SSL_CTX *ctx, const char* propq)
Is this better than introducing another call to set this?
That's how a lot of the other SSL settings that also exist in the SSL_CTX are implemented.

2023-09-05 01:46 UTC, paulidale commented
This needs documentation and possibly a test case.

2023-09-06 04:26 UTC, wbeck10 commented
> This needs documentation and possibly a test case.

Documentation and test case added.

2023-09-06 09:16 UTC, t8m commented on test/sslapitest.c
> +                                                        TLS1_2_VERSION)))
Why is the test limiting the TLS versions?

2023-09-06 09:17 UTC, t8m commented on test/sslapitest.c
> +    ADD_ALL_TESTS(test_ssl_new_ex, 2);
If the test did not limit the TLS versions it could be outside any ifndefs

2023-09-06 09:30 UTC, t8m requested changes
I did not do a complete review yet - these are from the first look.

2023-09-06 09:30 UTC, t8m commented on ssl/ssl_lib.c
> +    }
I do not think it does what you comment here about. `SSL_CONNECTION_GET_SSL()` basically cannot return NULL unless ssl_conn is NULL.

Also the multiline comment must start with `\*` on a separate line.

2023-09-06 09:30 UTC, t8m commented on ssl/ssl_rsa.c
> +    const char* propq = NULL;
Nit: space before `*` not after

2023-09-06 09:41 UTC, mattcaswell commented
I question the premise behind this PR.

There are numerous things pre-fetched and cached in the `SSL_CTX`. This means that some things will have been fetched using the propq associated with the `SSL_CTX` and somethings will be fetched using the propq from the `SSL`. This is quite confusing for any developer.

I think over time we should potentially look at doing more of that to the point where there are no fetches at all done at the `SSL` level. By adding this API we actually restrict our future options for caching more things in the SSL_CTX. Suddenly such a change would become "breaking" for applications that relied on this API.

I am placing on OTC hold on this.

2023-09-06 09:41 UTC, mattcaswell commented
**OTC Question: Do we want this API?**

2023-09-06 23:01 UTC, wbeck10 commented
The reason for this PR is to used different provider preference when creating an SSL connection.
The SSL_CTX has a lot of parameters to be set. For a developer, it is not convenient to cache all the settings and then create a SSL_CTX (with preferred provider query) shortly before creating a connection. It is more convenient to create a global SSL_CTX and set directly the parameter to it. It is quite possible that the underlying lib ctx provider store contains multiple providers. I believe, that some user may want to choose the preferred provider per SSL connection.

To solve this problem, this PR binds the provider query to the SSL object. If the SSL provider query is set, then it will use this when fetching a digest or cipher, otherwise it would be the provider query from the SSL_CTX. 
 
There is no API available to clone a SSL_CTX (I believe), besides, I think the SSL_CTX takes quite a lot of memory as well.  Maybe the ssl_st structure is not the right place to put provider query in, please suggest how it can be done and if defining the provider query per SSL connection makes sense or not.

2023-09-06 23:04 UTC, paulidale commented
This PR isn't achieving what you want.  As @mattcaswell noted, lots of things are prefetched and cached at the SSL_CTX level.  This includes all the TLS related algorithms e.g.  Subsequently setting the property query on the SSL object is not going to regenerate this cache, so it will be the same as if you were fetching using the old query.

2023-09-06 23:14 UTC, wbeck10 commented
Is it maybe possible to split the configuration part of an SSL_CTX into a new structure and allow SSL_CTX to be generated with the new configuration structure?

2023-09-07 08:56 UTC, t8m commented
I could also see SSL_CTX_dup being implemented if that would help. Given refcounting it probably would not be memory-intensive that much.

2023-09-12 08:24 UTC, t8m commented
**OTC: This API cannot be added as is.**

As SSL_CTX can contain fetched algorithms, keys, or other things that depend on property query, it would be inconsistent to try to override the propq on SSL_new(). Could you please give us more information about the architecture of the application where having separate SSL_CTX objects for separate propqueries is infeasible.

2023-09-15 11:28 UTC, ifranzki commented
While reading this another idea came to my mind. Not sure if this would help @wbeck10 with what he is trying to solve though....

I think it would be beneficial if one could create an SSL context with not just one property query argument.
Currently, `SSL_CTX_new_ex()` takes exactly one property query, which is then used for every crypto operation that is done with this SSL context.

There are use cases, where one might want to use different providers for the different operations that are performed during SSL/TLS handshake and data exchange.

For example, I would like to use a HSM/PKCS#11 based provider for the signature operation during TLS handshake, but would like to use the default provider for the key exchange operations and the data encryption. 

Rational behind this: The private key of the TLS server (or even client) is the identity of the server, and thus should be HSM protected. I would like to use an HSM/PKCS#11 based key for that, so the signature operations would need to use a HSM/PKCS#11 based provider. However, for the ephemeral ECDH key exchange and the symmetric session key a clear key implementations (i.e. the default provider) is good enough. The short lived (ephemeral) keys do not need to be HSM protected. 

Currently, with just one property query for the SSL context, when we use an EC based cipher suite with ECDSA for signatures, and ECDHE key exchange, it will most likely use the same provider for ECDSA and ECDH.

Keep in mind that doing a HSM/PKCS#11 based ECDH is very hard (or even impossible) because a HSM/PKCS#11 based ECDH operation with a non-extractable EC private key typically results in a non-extractable HSM/PKCS#11 based ECDH symmetric key object as well. So without the support for opaque symmetric keys (aka SKEY - discussed elsewhere already), one needs to do tricks to be able to use a HSM/PKCS#11 provider to secure a TLS handshake with a HSM/PKCS#11 based ECDSA step but a clear key ECDH key exchange step. 

I could think of and `SSL_CTX_new_ex2()` function that takes 2  (or even more) property queries. One for the signature operations, another one for the key exchange operations, and maybe a 3rd for the symmetric encryption operations. 

If the SSL context caches the providers used, then I guess it should need to cache separate instances for signature, key exchange and symmetric (possibly a 4th one for digests, etc....)

This is of curse not fully thought through, but I guess you get the idea.

2023-09-25 01:05 UTC, wbeck10 commented
Hi t8m,

Sorry for the late reply, I was in holiday.
The reason we need the provider property bind to SSL object is following:
Our application can have different provider added before establishing a SSL connection.
In our case it is an internal developed CNG (Windows trust store) provider and a P11 provider.
Both providers are added in the library context.
After that, a global SSL_CTX is generated to be used as an object that can store all the SSL_CTX settings like cipher suites, timeout and so forth.
When trying to make an SSL connection, it is known at this point that we want to use for example the CNG provider but unfortunately the provider parameter is defined in the SSL_CTX.

Start App
 |
\/
Create library context and add default, Cng and P11 providers
 |
\/
Create global SSL_CTX (to store SSL settings)
 |
\/
Set some SSL CTX settings
 |
\/
Create SSL object to make SSL connection


We thinking as well to create multiple SSL connection in multithreads with different provider preferences which I think would require having the SSL_CTX generated per thread (I don’t think SSL_CTX is thread safe, isn’t it?).

So the basic problem is the configuration that is currently enclosed in the SSL_CTX.
I think, if I can implement an SSL_CTX_dup and set the provider parameter for each SSL_CTX duplicate, that would work for us.  

Any thought?

2023-10-16 01:29 UTC, wbeck10 commented
Another pull request is created to go with the SSL_CTX_dup way.
(https://github.com/openssl/openssl/pull/22395)

2023-11-16 00:10 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 30 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2023-12-17 00:10 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 61 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2024-01-15 00:09 UTC, openssl-machine commented
This PR has been closed.  It was waiting for the creator to make requested changes but it has not been updated for 90 days.

2024-01-15 00:09 UTC, closed without merging