QUIC: Wire SSL_net_(read|write)_desired for TLS/DTLS
openssl/openssl pull request #21979
Opened 2023-09-06 07:05 UTC by hlandau

2023-09-06 09:35 UTC, t8m approved these changes

2023-09-06 09:36 UTC, t8m commented
Should this be reflected in manual pages?

2023-09-06 10:37 UTC, paulidale approved these changes

2023-09-06 10:50 UTC, mattcaswell commented
Needs a documentation update. The man page for these functions says "These functions are not supported on non-QUIC SSL objects."

2023-09-06 10:51 UTC, mattcaswell commented
Should there be a test for this?

2023-09-13 09:19 UTC, mattcaswell commented
Ping?? This seems fairly urgent?

2023-09-13 12:48 UTC, hlandau commented
Updated

- Implement SSL_get_[rw]poll_descriptor for SSL/DTLS as simple BIO passthrough
- Add tests
- Update documentation

2023-09-13 15:22 UTC, t8m submitted a review, later dismissed

2023-09-13 15:23 UTC, t8m commented
@hlandau CI is relevant

2023-09-14 08:03 UTC, hlandau commented
CI passing

2023-09-14 08:04 UTC, t8m approved these changes

2023-09-14 08:36 UTC, mattcaswell requested changes

2023-09-14 08:36 UTC, mattcaswell commented on doc/man3/SSL_get_rpoll_descriptor.pod
> +respective read and write BIOs configured on the SSL object.
"respectively on the respective" sounds a bit odd

2023-09-14 08:57 UTC, hlandau commented
Updated.

2023-09-14 09:04 UTC, mattcaswell approved these changes

2023-09-14 09:05 UTC, mattcaswell commented
@t8m please reconfirm

2023-09-14 09:29 UTC, t8m approved these changes

2023-09-19 11:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-09-20 01:20 UTC, paulidale approved these changes

2023-09-20 01:20 UTC, paulidale commented
Merged, thanks.

2023-09-20 01:20 UTC, closed without merging