Add a test for using a PSK with QUIC
openssl/openssl pull request #22011
Opened 2023-09-07 16:54 UTC by mattcaswell

Check that we can set and use a PSK when establishing a QUIC connection.

Fixes https://github.com/openssl/project/issues/83

This also fixes a bug in the `SSL_CIPHER_find()` function which crashed when passed a QUIC SSL object.

2023-09-08 02:12 UTC, paulidale commented on test/helpers/ssltestlib.c
> +        0x2c, 0x2d, 0x2e, 0x2f /* SHA384_DIGEST_LENGTH bytes */
Consider moving the length in the declaration?  That is:
```c
const unsigned char key[SHA384_DIGEST_LENGTH] = {
```
and drop this comment.

The compiler can then do some checking for us.

2023-09-08 07:43 UTC, hlandau requested changes

2023-09-08 07:43 UTC, hlandau commented on ssl/quic/quic_local.h
> +                ssl3_get_cipher_by_char, \
I suppose this is needed to make SSL_CIPHER_find work.

However we only support a restricted set of ciphersuites for QUIC &mdash; specifically AES-128-GCM, AES-256-GCM and ChaCha20-Poly1305. Do we need to use a custom implementation that restricts what can be retrieved here?

Adding a test that e.g. CCM cannot be retrieved via SSL_CIPHER_find might be nice while we are here.

2023-09-08 10:51 UTC, t8m approved these changes

2023-09-08 10:52 UTC, mattcaswell commented
@hlandau - feedback addressed. Please take another look.

2023-09-10 21:42 UTC, paulidale approved these changes

2023-09-11 06:50 UTC, hlandau approved these changes

2023-09-11 22:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-09-12 13:31 UTC, t8m commented
Merged to the master branch. Thank you.

2023-09-12 13:31 UTC, closed without merging