UII updates
openssl/openssl pull request #2204
Opened 2017-01-10 08:10 UTC by levitte

##### Checklist

- [x] CLA is signed

##### Description of change

- constify the input parameter to UI method getters.  *This is ABI compatible, it merely makes an already existing practice explicit*
- add space for an application data field in the UI structure, and functionality to access it.
- add a UI_METHOD wrapper for the PEM password callback, for applications that need to pass the latter to an interface that takes a UI_METHOD.
- document UI utility functions

2017-01-10 13:41 UTC, richsalz requested changes
any reason why not to use the standard EXDATA ?

2017-01-10 13:56 UTC, levitte commented
> any reason why not to use the standard EXDATA ?

not really, just that it escaped my mind.  Will fix

2017-01-10 18:03 UTC, kaduk commented on doc/man3/UI_UTIL_read_pw.pod
> +NUL byte.
Maybe "trailing NUL", "NUL terminator", or "terminating NUL byte"?  No real preference from me, though.

2017-01-10 21:24 UTC, kroeckx commented
Please propose some policy about which changes are allowed in public headers.

2017-01-10 21:25 UTC, kroeckx commented
Is there a reason this isn't tested?

2017-01-10 21:36 UTC, levitte commented
> Please propose some policy about which changes are allowed in public headers.

Do these suffice? They say nothing about headers and everything about backward ABI compatibility. 

https://www.openssl.org/docs/faq.html#MISC8
https://www.openssl.org/policies/releasestrat.html

The assumption is that as long as the API doesn't break applications and ABI compatibility is maintained, we should be fine.

2017-01-10 21:37 UTC, levitte commented
> Is there a reason this isn't tested?

I'm writing a test, will show up in a commit in a couple of hours.

2017-01-10 21:37 UTC, levitte commented on doc/man3/UI_UTIL_read_pw.pod
> +NUL byte.
Thanks. Will change

2017-01-10 23:19 UTC, levitte commented
I've made a number of updates:

- changed the UI_METHOD app data to be an ex_data field (ping @richsalz)
- added a test program that tests the UI_METHOD wrapper as well as the method already tested through the `openssl` command.  This simplified the UI test recipe.

2017-01-11 03:17 UTC, richsalz approved these changes
Looks okay to me.

2017-01-11 12:51 UTC, levitte commented
Pushed a couple of fixes for the travis build issues

2017-01-11 17:17 UTC, levitte commented
Builds are passing now.  @richsalz, would you mind reconfirming?

2017-01-11 17:25 UTC, richsalz commented
sure, +1

2017-01-11 17:27 UTC, levitte commented
Perfect.  Thanks.  Merged

2017-01-11 17:27 UTC, closed without merging