Fix coverity alert on use of uninitialised data
openssl/openssl pull request #22103
Opened 2023-09-14 14:30 UTC by levitte

This sequence triggers that sort of alert, on the ossl_blake2s_init() call:

    BLAKE2S_PARAM P;

    ossl_blake2s_param_init(&P);
    return ossl_blake2s_init(C, &P);

It's a false positive, but it's understandable that coverity doesn't catch
this.

2023-09-14 14:33 UTC, mattcaswell approved these changes

2023-09-14 14:33 UTC, levitte commented
From commentary, I realise that the description isn't quite right.  Fixing.

2023-09-14 14:34 UTC, t8m approved these changes

2023-09-14 14:37 UTC, levitte commented
New description

2023-09-14 14:38 UTC, tom-cosgrove-arm approved these changes
LGTM

2023-09-14 23:49 UTC, paulidale requested changes
I don't think this it a good fix.  It leaves the possibility of a surprise for a programmer in the future.

First up why initialise the structure passed to `ossl_blake2s_param_init()` which does everything correctly & doesn't read anything before writing?

More importantly, I think we should make `ossl_blake2b_param_init()` initialise the structure without inspecting it's contents.

As far as I can tell, the only place that passes a non-zero structure in is `ossl_blake2b512_init()` and it could set the digest length, if required, after calling `ossl_blake2b_param_init()`.  This would avoid pollution of what should be a straightforward initialisation function.

If that's not suitable, instead add an argument to `ossl_blake2b_param_init()` specifying the digest length (0 meaning default).

2023-09-17 23:53 UTC, levitte commented
@paulidale, I agree a lot with what you're saying, *especially* re that `ossl_blake2b_param_init()` inspects the param structure.  That change came with 786b9a8d3f8e203c5536e36b9a9bab83bde0311a.  I've been trying to unravel what that change does, to try and make it... cleaner, shall we say?  But it turns out to be quite an effort (I made an, attempt, but it turned out not to be good enough).

So perhaps the answer is to reject this PR and start over with a bigger effort.  The way I was thinking was to have this quick fix (hack) to silence coverity, and take on a cleanup when there's time allocated for that.

2023-09-18 00:43 UTC, paulidale commented
I hesitate to put "quick fixes" in in anticipation of "doing the right thing later".  It rarely happens in my experience.

Adding a digest length argument to `ossl_blake2b_param_init()` looks pretty reasonable to me and doesn't smell like being a "quick fix".

2023-09-18 00:43 UTC, paulidale commented
Still, happy to go any way here.

2023-10-04 15:43 UTC, mattcaswell commented
In an attempt to unstick this I have a proposed alternative fix in #22282

2023-10-04 21:28 UTC, closed without merging

2023-10-04 21:28 UTC, paulidale commented
I much prefer the other which has the required approvals.