Use the untrusted server certificate chain to create a valid certificate ID for OCSP_request
openssl/openssl pull request #22192
Opened 2023-09-26 11:18 UTC by olszomal

The `openssl server` command-line tool does not use the untrusted certificate chain for building OCSP requests.

Let's consider the following `openssl s_server` options:
```
-cert infile
	The certificate to use.
-cert_chain
	A file or URI of untrusted certificates to use when attempting to build the certificate chain related to the certificate specified via the -cert option.
-CAfile file
	A file of trusted certificates.
```

An issuer certificate is required to create an OCSP_CERTID structure. This ID is placed in the OCSP request.
The issuer certificate can be untrusted, although any issuer can be designated as a trusted root authority.

Start the OCSP responder:
```
openssl ocsp -port 19254 -index index.txt -rsigner ocsp.pem -CA intermediateCA.pem
```

The following doesn't work but it should:
```
openssl s_server -accept 4433 -cert server.pem -cert_chain intermediateCA.pem -status_verbose
Using default temp DH parameters
ACCEPT
cert_status: callback called
cert_status: AIA URL: http://127.0.0.1:19254/ocsp
cert_status: Can't retrieve issuer certificate.
(...)
```

The following workaround works, but it requires trusting an untrusted certificate:
```
openssl s_server -accept 4433 -cert server.pem -CAfile intermediateCA.pem -status_verbose
Using default temp DH parameters
ACCEPT
cert_status: callback called
cert_status: AIA URL: http://127.0.0.1:19254/ocsp
cert_status: ocsp response sent:
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: C = PL, O = Stunnel Developers, OU = Intermediate CA, CN = Intermediate CA
    Produced At: Sep 15 12:07:08 2023 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: 48BDDBF0D915E576EE31434E57A6FAA988FADEB2
      Issuer Key Hash: AF74BB9A5BBE5FAF4650E3D0F6FE4F49DB3DBADA
      Serial Number: 3168B44D3E67DA3B9D7A7B40E08793F616EEF669
    Cert Status: good
    This Update: Sep 15 12:07:08 2023 GMT
	(...)
```

This PR enables the untrusted server certificate chain to find the issuer certificate.
```
openssl s_server -accept 4433 -cert server.pem -cert_chain intermediateCA.pem -status_verbose 
Using default temp DH parameters
ACCEPT
cert_status: callback called
cert_status: AIA URL: http://127.0.0.1:19254/ocsp
cert_status: ocsp response sent:
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: C = PL, O = Stunnel Developers, OU = Intermediate CA, CN = Intermediate CA
    Produced At: Sep 15 12:08:46 2023 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: 48BDDBF0D915E576EE31434E57A6FAA988FADEB2
      Issuer Key Hash: AF74BB9A5BBE5FAF4650E3D0F6FE4F49DB3DBADA
      Serial Number: 3168B44D3E67DA3B9D7A7B40E08793F616EEF669
    Cert Status: good
    This Update: Sep 15 12:08:46 2023 GMT
	(...)
```

2023-10-18 10:13 UTC, mtrojnar commented
@t8m Are you sure this was correctly triaged as a feature?  Without this PR, `openssl server` fails to build OCSP requests for non-trivial certificate chains.

2023-10-18 14:56 UTC, t8m commented
Yeah, I stand by it. @openssl/otc anybody from OTC disagrees?

2023-11-18 00:10 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2023-11-18 00:21 UTC, t-j-h commented
@t8m is correct in my view to see this as a feature request - we don't document that we use the cert_chain in OCSP contexts - if we did document that and it did not work it would be a defect - but I don't read the documentation (such as it is) as indicating that this should be expected to work.

Adding support for this makes sense and it would need to have some tests added so we ensure we don't inadvertently break it in subsequent releases.

2023-11-18 00:22 UTC, t-j-h commented
@t8m why tests-exempted here - I'd expect some exercise of the new capability to be added as a test ...

2023-11-20 09:39 UTC, t8m commented
@olszomal Would you be able to write a test?

2023-11-20 09:43 UTC, t8m commented
> @t8m why tests-exempted here - I'd expect some exercise of the new capability to be added as a test ...

I assumed that for an external contributor it would be a quite non-trivial exercise to write a proper test recipe for this. I assumed it would take much more work than the bug fix itself. We allow exempting tests when disproportionate amount of work is needed for them. We can as well set `tests: deferred` and write the test ourselves - would for example @jamuir be willing to write it?

2023-11-20 10:53 UTC, mtrojnar commented
> @olszomal Would you be able to write a test?

I only found one test involving s_server: https://github.com/openssl/openssl/blob/cf6342bc024868f5a55f2225f2e083415fb1329a/test/recipes/82-test_tfo_cli.t
I guess the best person to write another similar test would be someone who is already fluent in perl.

2023-11-20 15:29 UTC, jamuir commented
> We can as well set `tests: deferred` and write the test ourselves - would for example @jamuir be willing to write it?

Yes, if needed I can write a test.

2023-11-20 15:55 UTC, t8m requested changes
One nit

2023-11-20 15:55 UTC, t8m commented on apps/s_server.c
> +        if (!X509_name_cmp(X509_get_issuer_name(x), X509_get_subject_name(issuer)))
Please use `X509_name_cmp() == 0`. We use boolean ops only on true/false return values.

2023-11-21 17:13 UTC, t8m requested changes
Last two nits and I'll approve I promise.

2023-11-21 17:13 UTC, t8m commented on apps/s_server.c
> +    if (chain) {
I am sorry for not noticing this before - this also needs to be `chain != NULL` according to our code style guide.

2023-11-21 17:13 UTC, t8m commented on apps/s_server.c
> +        if (X509_name_cmp(X509_get_issuer_name(x), X509_get_subject_name(issuer)) == 0)
Could you please also split this line at the comma?

2023-11-22 09:07 UTC, t8m approved these changes

2023-12-07 09:04 UTC, olszomal commented
@jamuir In the [stunnel ](https://github.com/mtrojnar/stunnel/tree/master/tests/certs)repository on GitHub, there is a script that generates certificates along with configuration files. The certificate file names have been changed for the above example.
```
$ ./maketestcert.sh 
$ cp server_cert.pem server.pem
$ cp interCA_ocsp.pem ocsp.pem
```
Authority Info Access is set:
`authorityInfoAccess             = OCSP;URI:http://127.0.0.1:19254/ocsp`

2023-12-18 22:06 UTC, jamuir commented
Thanks, @olszomal , for providing those files.

I have been able to reproduce the original issue and verify your fix.

When testing, there are three parties to consider:

```
tls client <---> tls server <---> ocsp responder 
```
I initiate the flow to `ocsp responder` from `tls client` using

```
openssl s_client -status ...
```
The flag `-status` is used to tell `tls server` that `tls client` wants ocsp data.

The tcp-fast-open test that mtrojnar pointed to (`82-test_tfo_cli.t`) checks messages written to the console by `s_server` and `s_client`.

I will do something similar, but possibly just for `s_server`.  We should see `cert_status: ocsp response sent:` and `OCSP Response Data:` written to the console by `s_server` when ocsp data is successfully relayed to `tls client`.

2023-12-20 05:34 UTC, jamuir commented
see #23101 .

2024-01-04 14:38 UTC, mattcaswell requested changes

2024-01-04 14:38 UTC, mattcaswell commented on apps/s_server.c
> +        issuer = sk_X509_value(chain, 0);
Why are you only looking at the first cert in the stack? Surely the issuer could be anywhere in the stack?

2024-01-05 14:09 UTC, t8m approved these changes

2024-02-05 10:47 UTC, mtrojnar commented
Do I correctly understand that this PR is ready for merging?

2024-02-05 15:53 UTC, mattcaswell requested changes
I might have expected to see some s_server documentation changes to explain how the intermediate certs affect this

2024-02-08 14:50 UTC, t8m approved these changes

2024-02-12 09:42 UTC, t8m commented
ping @mattcaswell  for re-review

2024-02-25 22:24 UTC, t8m commented
Ping for second review

2024-03-12 13:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-03-12 13:03 UTC, t8m commented
Merged to the master branch. Thank you for your contribution.

2024-03-12 13:03 UTC, closed without merging

2024-04-03 16:26 UTC, martinRa2 commented
Hello, 
I maintain the PR #20945 . I have integrated your changes into it. 

@olszomal it would be great if you could have a look if your code was successfully integrated into the PR.