Add testing of bitflips in packet headers
openssl/openssl pull request #22267
Opened 2023-10-03 15:20 UTC by t8m

A new type of noise is introduced in the noisy dgram bio filter.

##### Checklist

- [x] tests are added or updated

2023-10-03 15:20 UTC, t8m commented
This needs to be rebased after #22243 is merged.

2023-10-03 15:51 UTC, mattcaswell requested changes

2023-10-03 15:51 UTC, mattcaswell commented on test/helpers/noisydgrambio.c
> +        *flip_offset = test_random() % (25 * (1 + long_header));
25 seems quite a magic number here?

2023-10-03 15:51 UTC, mattcaswell commented on test/helpers/noisydgrambio.c
> +    /* None of these border conditions should not happen but check them anyway */
Typo: None of these border conditions should happen

2023-10-03 15:55 UTC, mattcaswell commented
> This needs to be rebased after https://github.com/openssl/openssl/pull/22243 is merged.

Care will need to be taken when rebasing. Flipped bits will (presumably) cause the datagram to be dropped, so we will need to back off that type of noise too.

2023-10-04 01:24 UTC, paulidale approved these changes
With @mattcaswell's suggestions taken.

2023-10-04 07:25 UTC, mattcaswell commented
This needs a rebase now that #22243 has been merged.

2023-10-04 10:08 UTC, t8m commented
Rebased and @mattcaswell comments addressed.

Please reconfirm.

2023-10-04 10:08 UTC, t8m commented on test/helpers/noisydgrambio.c
> +        *flip_offset = test_random() % (25 * (1 + long_header));
I've added a comment.

2023-10-04 10:17 UTC, mattcaswell submitted a review, later dismissed

2023-10-04 10:23 UTC, mattcaswell commented
The no-cmp runchecker CI failure is relevant

2023-10-04 13:51 UTC, mattcaswell commented
CI failure is still happening

2023-10-04 15:39 UTC, t8m commented on test/helpers/quictestlib.c
> +        (void)BIO_ctrl(sbio, BIO_CTRL_NOISE_BACK_OFF, 0, NULL);
Yep

2023-10-04 15:57 UTC, mattcaswell approved these changes
Approved subject to the CI passing this time!

2023-10-04 17:01 UTC, t8m commented
> Approved subject to the CI passing this time!

It passed!

2023-10-04 23:07 UTC, paulidale approved these changes

2023-10-06 00:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-10-06 08:25 UTC, t8m commented
Merged to the master branch. Thank you for the reviews.

2023-10-06 08:25 UTC, closed without merging