Avoid using gets as an argument name in a prototype
openssl/openssl pull request #22316
Opened 2023-10-09 08:33 UTC by t8m

This otherwise breaks compilation of applications using ssl.h on MingW.

Fixes #22296

2023-10-09 08:34 UTC, levitte approved these changes

2023-10-09 08:56 UTC, mattcaswell approved these changes

2023-10-09 20:56 UTC, paulidale approved these changes

2023-10-10 07:25 UTC, mspncp requested changes
Im not convinced that it is a good idea to rush in an ad-hoc fix for a compiler problem reported by a user #22296 based on suspicions only, without fully investigating the true cause, as suggested by @nhorman in https://github.com/openssl/openssl/issues/22296#issuecomment-1751350436.

The function prototype, as it is currently, was added in 2016 (commit a146ae55ba479a5c7aa2a6afba1b2b93102a152c) and no problems where reported in the last seven years. Also, function parameter names don't collide with global symbols. The issue smells like some preprocessor \#define polluting the global namespace. Theoretically, it might even be a define somewhere in application headers. So unless proven guilty, we shouldn't fix anything.


```
Author: Matt Caswell <matt@openssl.org>
Date:   Tue Mar 22 09:21:29 2016 +0000

    Make BIO opaque
    
    Move the the BIO_METHOD and BIO structures into internal header files,
    provide appropriate accessor methods and update all internal code to use
    the new accessors where appropriate.
    
    Reviewed-by: Richard Levitte <levitte@openssl.org>
```

2023-10-10 07:27 UTC, mspncp commented
Placing a hold on it to wait for the outcome of discussion #22317.

2023-10-10 07:33 UTC, t8m commented
It is a define in some of the headers pulled in by the application compiled on MingW that breaks the compilation. As this is a trivial and safe fix I do not see a need to hold it.

2023-10-10 07:41 UTC, mspncp commented
> It is a define in some of the headers pulled in by the application compiled on MingW that breaks the compilation. As this is a trivial and safe fix I do not see a need to hold it.

And this is proven by what? [By renaming "gets" to "gets2"](https://github.com/openssl/openssl/issues/22296#issuecomment-1751771701)?

2023-10-10 08:34 UTC, levitte commented
> > It is a define in some of the headers pulled in by the application compiled on MingW that breaks the compilation. As this is a trivial and safe fix I do not see a need to hold it.
> 
> And this is proven by what? [By renaming "gets" to "gets2"](https://github.com/openssl/openssl/issues/22296#issuecomment-1751771701)?

Yes?  What else would you guess it is, if a rename works?

2023-10-10 09:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2023-10-10 09:05 UTC, mspncp commented
> > And this is proven by what? [By renaming "gets" to "gets2"](https://github.com/openssl/openssl/issues/22296#issuecomment-1751771701)?
> 
> Yes? What else would you guess it is, if a rename works?

I am not doubting the collision, I am just not convinced that the problem is caused by the system headers and not by the application. Moreover, how does the "\#define"-hypothesis explain the fact, that the compiler is missing a closing `)` before the `;` ?

```
c:\openssl-3.2.0-alpha2\include/openssl/bio.h:993:29: error: expected ')' before ';' token
993 | int (*gets) (BIO , char , int));
```

Basing a fix on assumptions only and fixing a symptom without fully understanding the cause just adds unnecessary quirks to the code base.

I would prefer to see some evidence from the reporter first to confirm the hypothesis:

- locate the problematic \#define in the system headers
- show us the preprocessor output

2023-10-24 09:17 UTC, t8m commented
**OTC: closing this for now as we did not get an evidence of this being a general problem on the MingW platform.**

2023-10-24 09:31 UTC, t-j-h approved these changes

2023-10-24 09:32 UTC, kroeckx approved these changes

2023-10-25 08:55 UTC, closed without merging

2023-10-25 08:55 UTC, mattcaswell commented
Pushed to master/3.1/3.0.