Don't allow renegotiation for DTLS 1.3
openssl/openssl pull request #22362
Opened 2023-10-12 11:56 UTC by fwh-dc

2024-04-04 17:04 UTC, t8m approved these changes

2024-04-05 07:11 UTC, mattcaswell commented on apps/include/s_apps.h
> +    ((SSL_is_dtls(s) && SSL_version(s) > DTLS1_3_VERSION) \
What about DTLS1_BAD_VER?

2024-04-09 11:54 UTC, fwh-dc commented on apps/include/s_apps.h
> +    ((SSL_is_dtls(s) && SSL_version(s) > DTLS1_3_VERSION) \
Good catch!

2024-04-15 10:44 UTC, mattcaswell approved these changes

2024-04-15 10:45 UTC, mattcaswell requested changes

2024-04-15 10:45 UTC, mattcaswell commented on apps/include/s_apps.h
> +                         || SSL_version(s) == DTLS1_BAD_VER) \
paren mismatch here??

2024-04-15 13:29 UTC, t8m approved these changes

2024-04-15 13:36 UTC, mattcaswell approved these changes
CI failure is not relevant

2024-04-16 14:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-04-16 14:39 UTC, closed without merging