Update thread_win.c to support Embarcadero's clang based compilers
openssl/openssl pull request #22361
Opened 2023-10-12 11:34 UTC by gcardi

##### Checklist

To support Embarcadero's clang-based compilers the following code was added to the file crypto/thread/arch/thread_win.c just before function void ossl_crypto_mem_barrier(void).

```cpp
#if defined(__BORLANDC__) && defined(__clang__) && defined(_WIN32) 
__forceinline void MemoryBarrier(void)
{
    long barrier;
    __asm {
        xchg barrier, eax
    }
}
#endif
```

Without this change, library creation fails because it cannot find the _MemoryBarrier function,

2023-10-12 12:44 UTC, mspncp commented
Thanks for your contribution, @gcardi! 

Instead of just repeating your patch in the description, it would be helpful if you could provide some background information, since we know little about the embarcadero context.  E.g.,

- What is the original error and in which context does it occur?
- Does embarcadereo also have C/C++ toolchains or does the problem occur in some Delphi wrapper around OpenSSL?
- Why does the MemoryBarrier have to be implemented by the Application/Library? Shouldn't it be a compiler intrinsic or a library function of the embarcadero framework?  A [quick search](https://www.google.com/search?q=embarcadero+MemoryBarrier) only revealed that there is some  [System.MemoryBarrier](https://docwiki.embarcadero.com/Libraries/Sydney/en/System.MemoryBarrier) intrinsic in embarcadero Delphi.

Please also note, that in order to accept the pull request, you need to sign and send us a [Contributor License Agreement (CLA)](https://www.openssl.org/policies/cla.html).

2023-10-12 13:03 UTC, gcardi commented
> * What is the original error and in which context does it occur?

It's a linker error: 

```
Error: Unresolved external '_MemoryBarrier' referenced from C:\USERS\GIULIANO\DOCUMENTS\EMBARCADERO\STUDIO\PROJECTS\OPENSSL_BCC32\CRYPTO\THREAD\ARCH\LIBCRYPTO-SHLIB-THREAD_WIN.OBJ
Error: Unable to perform link
```

It occurred building the library with 

```
make -N
```

> * Does Embarcadereo also have C/C++ toolchains or does the problem occur in some Delphi wrapper around OpenSSL?

I honestly don't know. I tend to use Delphi as little as possible.

> * Why does the MemoryBarrier have to be implemented by the Application/Library? Shouldn't it be a compiler intrinsic or a library function of the Embarcadero framework?  A [quick search](https://www.google.com/search?q=embarcadero+MemoryBarrier) only revealed that there is some  [System.MemoryBarrier](https://docwiki.embarcadero.com/Libraries/Sydney/en/System.MemoryBarrier) intrinsic in Embarcadero Delphi.
> 

If I am not mistaken, the OpenSSL library is written in pure C. Or am I wrong? To consume objects or generally code written Delphi you have to use either Delphi itself or C++, to my knowledge. I don't think you can easily link Delphi code from a C codebase with C++Builder, unless that code is compiled into a dynamic library (DLL). But I could be wrong.

> Please also note, that in order to accept the pull request, you need to sign and send us a [Contributor License Agreement (CLA)](https://www.openssl.org/policies/cla.html).

Just done.

Regards

2023-10-13 11:11 UTC, t8m requested changes
We will need a CLA signed.

2023-10-13 11:11 UTC, t8m commented on crypto/thread/arch/thread_win.c
> +// To support Embarcadero's clang based compilers
Please do not use C++ style comments.

2023-10-13 19:16 UTC, gcardi commented
From: Tomáš Mráz 
Sent: Friday, October 13, 2023 1:12 PM
To: openssl/openssl 
Cc: Giuliano Cardinali ; Mention 
Subject: Re: [openssl/openssl] Update thread_win.c to support Embarcadero's clang based compilers (PR #22361)

@t8m requested changes on this pull request.

>We will need a CLA signed.

Already sent


--------------------------------------------------------------------------------

In crypto/thread/arch/thread_win.c:

> @@ -32,6 +32,17 @@ static unsigned __stdcall thread_start_thunk(LPVOID vthread)
     return 0;
 }
 
+// To support Embarcadero's clang based compilers
>Please do not use C++ style comments.

Ok

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-15 15:39 UTC, nhorman commented on crypto/thread/arch/thread_win.c
> +// To support Embarcadero's clang based compilers
There also appears to be an issue with the use of the ' character in the comment, see
https://github.com/openssl/openssl/actions/runs/6507478087/job/17674975217?pr=22361

2023-10-15 15:58 UTC, nhorman commented
I'm a bit unsure on this.  From what I read here:
https://learn.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-memorybarrier
MemoryBarrier is a windows platform macro defined in winnt.h
So normally we pull that in by including windows.h in thread_win.c, which (at least on the msys clang and mingw64 platforms get the definition via windows.h->windef.h->winnt.h

If embarcaderos compiler somehow has a different header structure, wouldn't it be better to do something like this in thread_win.c:
```
#if defined(OPENSSL_THREADS_WINNT)
# include <process.h>
# include <windows.h>
+#if defined(__BORLANDC__) && defined(__clang__) && defined(_WIN32) 
+#include <winnt.h>
+#endif
```

Rather than redefining the function to something else (winnt.h defined MemoryBarrier as __mm_fence), while this implementation does an xchng.  The former serializes all memory operations, while I think the latter only guarantees that reads/writes to the desitnation address are serialized)

2023-10-15 16:23 UTC, closed without merging