Fix ssl_lib functions for dtls 1.3
openssl/openssl pull request #22378
Opened 2023-10-13 09:34 UTC by fwh-dc

2024-03-22 05:21 UTC, fwh-dc commented
CI failures are not relevant

2024-04-04 16:31 UTC, t8m requested changes

2024-04-04 16:31 UTC, t8m commented on ssl/ssl_lib.c
> +    if (!(SSL_CONNECTION_IS_TLS13(sc) || SSL_CONNECTION_IS_DTLS13(sc))) {
Needs rebase to use the new macro.

2024-04-25 13:10 UTC, fwh-dc commented on ssl/ssl_lib.c
> +    if (sc->version != TLS1_3_VERSION && sc->version != DTLS1_3_VERSION)
I'm not sure actually it is a different check:

```
# define SSL_CONNECTION_IS_TLS13(s) (!SSL_CONNECTION_IS_DTLS(s) \
    && SSL_CONNECTION_GET_SSL(s)->method->version >= TLS1_3_VERSION \
    && SSL_CONNECTION_GET_SSL(s)->method->version != TLS_ANY_VERSION)
```

But I am not sure if will work anyways? I can give it a try.

2024-04-25 13:12 UTC, fwh-dc commented on ssl/ssl_lib.c
> +    if (sc->version != TLS1_3_VERSION && sc->version != DTLS1_3_VERSION)
Otherwise I make the check nicer by checking on a `version1_3` variable.

2024-04-25 13:18 UTC, t8m commented on ssl/ssl_lib.c
> +    if (sc->version != TLS1_3_VERSION && sc->version != DTLS1_3_VERSION)
Ah, you're right that checks the method version.

2024-04-25 13:24 UTC, t8m approved these changes

2024-04-29 13:25 UTC, t8m approved these changes

2024-04-29 13:39 UTC, mattcaswell approved these changes

2024-04-30 14:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-04-30 14:37 UTC, t8m commented
Merged to the feature branch. Thank you for your contribution.

2024-04-30 14:37 UTC, closed without merging