Fixup of general tls record parsing functions for dtls 1.3
openssl/openssl pull request #22376
Opened 2023-10-13 08:08 UTC by fwh-dc

2024-03-22 08:10 UTC, fwh-dc commented
Ci failures look irrelevant

2024-04-04 16:27 UTC, t8m requested changes

2024-04-04 16:27 UTC, t8m commented on ssl/record/methods/tls_common.c
> +        if ((rl->version == TLS1_3_VERSION || rl->version == DTLS1_3_VERSION) && rl->enc_ctx != NULL) {
Please split the line

2024-04-08 13:08 UTC, t8m approved these changes

2024-04-25 10:25 UTC, mattcaswell approved these changes

2024-04-25 12:54 UTC, t8m approved these changes
@mattcaswell please reconfirm

2024-04-25 13:00 UTC, mattcaswell approved these changes

2024-04-26 15:26 UTC, t8m commented
Merged to the feature branch. Thank you for your contribution.

2024-04-26 15:26 UTC, closed without merging