Support TLS1.3 sigalg logic in DTLS1.3
openssl/openssl pull request #22380
Opened 2023-10-13 11:10 UTC by fwh-dc

2024-03-21 14:48 UTC, fwh-dc commented
@t8m This is ready for review. Would you please add labels to reflect that? Thanks!

2024-04-04 16:39 UTC, t8m requested changes
Needs rebase to apply the version macro

2024-04-19 12:28 UTC, t8m approved these changes

2024-04-19 12:37 UTC, mattcaswell approved these changes

2024-04-20 13:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-04-22 08:42 UTC, mattcaswell commented
Pushed. I squashed the two commits together.

2024-04-22 08:42 UTC, closed without merging