Ignore retry packets that arrive too late
openssl/openssl pull request #22411
Opened 2023-10-17 15:40 UTC by mattcaswell

RFC 9000 s 17.2.5.2 says

> After the client has received and processed an Initial or Retry packet
> from the server, it MUST discard any subsequent Retry packets that it
> receives.

We were checking for multiple Retry packets, but not if we had already processed an Initial packet.

Fixes the assertion failure noted in
https://github.com/openssl/openssl/pull/22368#issuecomment-1765618884

2023-10-17 15:43 UTC, hlandau requested changes

2023-10-17 15:43 UTC, hlandau commented on ssl/quic/quic_channel.c
> +        if ((ch->el_discarded & (1U << QUIC_ENC_LEVEL_INITIAL)) != 0)
Use `ch->have_received_enc_pkt` instead

This will not handle cases where we have received an Initial packet but not dropped the Initial EL yet

2023-10-17 15:51 UTC, mattcaswell commented
Fixup pushed. Please take another look.

2023-10-17 15:52 UTC, hlandau approved these changes

2023-10-19 09:54 UTC, t8m commented
Merged to the master branch. Thank you.

2023-10-19 09:54 UTC, closed without merging