Use dtls1.3 cryptographic label prefix
openssl/openssl pull request #22416
Opened 2023-10-18 08:03 UTC by fwh-dc

2023-12-18 13:43 UTC, mattcaswell requested changes

2023-12-18 13:43 UTC, mattcaswell commented on ssl/tls13_enc.c
> +    // TODO: Should we support DTLS labels from here? This interface is only used by QUIC.
I'd say there is no need at this point. Maybe just write a comment saying we only support TLSv1.3 and not DTLSv1.3 in this function (nit: use `/* ... */` not `//` style comments.)

2024-01-18 00:09 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 30 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2024-02-18 00:08 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 61 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2024-03-18 00:09 UTC, openssl-machine commented
This PR has been closed.  It was waiting for the creator to make requested changes but it has not been updated for 90 days.

2024-03-21 10:42 UTC, fwh-dc commented
@mattcaswell fixed

2024-03-22 08:14 UTC, fwh-dc commented
CI looks irrelevant

2024-03-25 17:49 UTC, t8m approved these changes

2024-03-26 13:46 UTC, mattcaswell approved these changes

2024-03-27 14:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-03-28 14:30 UTC, mattcaswell commented
Pushed to the feature/dtls-1.3 branch. I squashed the last commit into the previous one

2024-03-28 14:30 UTC, closed without merging