rand: add callbacks to cleanup the user entropy resp. nonce
openssl/openssl pull request #22423
Opened 2023-10-18 14:41 UTC by mspncp

The `get_user_{entropy,nonce}` callbacks were add recently to the dispatch table in commit 4cde7585ce8e. Instead of adding corresponding `cleanup_user_{entropy,nonce}` callbacks, the `cleanup_{entropy,nonce}` callbacks were reused. This can cause a problem in the case where the seed source is replaced by a provider: the buffer gets allocated by the provider but cleared by the core.

2023-10-18 14:56 UTC, mspncp commented on crypto/rand/prov_seed.c
> +}
Without the changes from #22394, the implementations  of  `ossl_rand_cleanup_user_nonce` and `ossl_rand_cleanup_nonce`  are identical. It's important however, that both callbacks exist.

Now  #22394 will depend on this pull request to be merged first.

2023-10-18 15:35 UTC, t8m requested changes
One small doc fix is needed, other than that LGTM.

2023-10-18 15:45 UTC, mspncp commented on doc/man7/provider-base.pod
> +is passed in B<buf> and its length in B<len>.
I just noticed that I forgot to push the latest version of my branch. Let me push it first (it's a plain rebase on master) and then I'll address your request.

![grafik](https://github.com/openssl/openssl/assets/11467854/7ae67708-fc9c-49a5-ad0a-ebced359e7a3)

2023-10-18 15:48 UTC, mspncp commented on doc/man7/provider-base.pod
> +is passed in B<buf> and its length in B<len>.
done

2023-10-18 15:57 UTC, t8m commented
Ping for second review. This needs to go in before the release of 3.1.4.

2023-10-20 08:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-10-20 08:56 UTC, mattcaswell commented
Pushed to master and 3.1

2023-10-20 08:56 UTC, closed without merging

2023-10-22 20:13 UTC, paulidale commented
I don't understand the problem here.  Well I do understand the issue but am not sure if it's possible to encounter it in reality.

2023-10-22 21:10 UTC, mspncp commented
I would expect problems on Windows if the provider links to a different crt library than libcrypto. 

On Linux it's probably not such a big problem iiuc, because all binaries tend to use the same libc.

2023-10-22 22:19 UTC, paulidale commented
I'm more thinking along the lines of the provider replacing the seed src will implement correctly paired functions.  If the new callbacks are available, the old ones will not be used so the clearing and freeing will be consistent.  Likewise if only the old are implemented.  Getting a mismatch seems tricky.

2023-10-22 22:55 UTC, paulidale commented
I don't think this was required.  The memory in all cases is being allocated and freed by libcrypto, not a provider.  This is true even if the provider implements its own seed source.

These functions are callbacks from the provider to the core libcrypto, that they then might call into a provider is moot because the allocations happen before then.

2023-10-23 00:35 UTC, paulidale commented
With #22394, this becomes necessary however.