Provide (de)serialisation for big-endian targets, allowing for use of Solinas' nistp implementations
openssl/openssl pull request #22445
Opened 2023-10-20 03:36 UTC by rohanmclure

Provide a series of fallback routines for big-endian targets, and in doing so, extend support for the ecp_nistp{224,256,384,521}.c implementations for NIST curves to BE.

The only little-endian specific components to each of these files is the serialisation/deserialisation logic to/from precomputation tables, whose entries are stored as little-endian byte arrays. Provide bi-endian fallback routines, providing adapters for big-endian systems. These routines may be somewhat naive, but (de)serialisation does not occur in a hot path and so should suffice for now.

2023-10-20 03:39 UTC, rohanmclure commented
Added Signed-off-by to the final, revert commit. Should fix CLA problems.

2023-10-20 11:10 UTC, t8m commented
@rohanmclure we have rohanmclure@linux.ibm.com in the CLA database. Should we add also rmclure@linux.ibm.com ?

2023-10-22 22:51 UTC, rohanmclure commented
> @rohanmclure we have [rohanmclure@linux.ibm.com](mailto:rohanmclure@linux.ibm.com) in the CLA database. Should we add also [rmclure@linux.ibm.com](mailto:rmclure@linux.ibm.com) ?

[rmclure@linux.ibm.com](mailto:rmclure@linux.ibm.com) would be ideal, thank you.

2023-11-23 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2023-12-24 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 61 days ago

2023-12-24 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 61 days ago

2024-01-24 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 92 days ago

2024-02-24 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 123 days ago

2024-03-26 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 154 days ago

2024-04-03 15:24 UTC, t8m commented
Could we add `enable-ec_nistp_64_gcc_128` to one of the big endian targets in .github/workflows/cross-compiles.yml ? Or even add a new target? Perhaps s390x build would be the one? Or we could add ppc64 cross compile target?

2024-04-11 05:33 UTC, rohanmclure commented
Hi @t8m, thanks for following this PR up. I'm afraid I'll be to respond to this request, but others will be attending to it to provide BE workflows upstream. Thought I would just give an expectation of how this particular PR is likely to progress in the next while. Thanks.

2024-05-12 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2024-06-12 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 61 days ago

2024-07-12 16:23 UTC, t8m requested changes
This looks good apart from the nits.

Perhaps you could add `enable-ec_nistp_64_gcc_128` to this line: https://github.com/openssl/openssl/blob/e8c7febc8f1b0ef9e5b62b0944748d2830b1a0b4/.github/workflows/cross-compiles.yml#L112 to test it?

2024-07-12 16:23 UTC, t8m commented on crypto/ec/ec_local.h
> +        b = 8*(i % limb_width);
Style nit: add spaces around `*`

2024-07-12 16:23 UTC, t8m commented on crypto/ec/ec_local.h
> +        mask = ((uint64_t) 0xff) << b;
Style nit, no space after cast

2024-07-12 16:23 UTC, t8m commented on crypto/ec/ec_local.h
> +        b = 8*(i % limb_width);
as above

2024-07-12 16:23 UTC, t8m commented on crypto/ec/ec_local.h
> +        byte = in[i] & (i+1 == num_bytes ? MASK(input_bits - 8*(num_bytes-1))
Please add spaces around `+`, `-` and `*`

2024-07-12 16:23 UTC, t8m commented on crypto/ec/ec_local.h
> +        out[i / limb_width] |= ((uint64_t) byte) << b;
As above

2024-07-12 16:23 UTC, t8m commented on crypto/ec/ecp_nistp224.c
> +    ec_nistp_pre_comp_serialize(out, in, 56/8, 28);
Please add spaces around `/`

2024-07-12 16:23 UTC, t8m commented on crypto/ec/ec_local.h
> +#undef CEIL_DIV
Nit: indent by one space after `#`

2024-07-12 16:23 UTC, t8m commented on crypto/ec/ec_local.h
> +#define MASK(n) ((((uint64_t) 1) << (n)) - 1)
Nit add space after `#`

2024-07-12 16:23 UTC, t8m commented on crypto/ec/ecp_nistp521.c
> +#define TOP(l, n) ((l) & ((((uint64_t) 1) << (n)) - 1) << (64-(n))) >> (64-(n))
Nit: add space after `#` and around `-`. Remove it after cast.

2024-07-12 16:23 UTC, t8m commented on crypto/ec/ecp_nistp521.c
> +    }
Nit add spaces around binary operators

2024-07-12 16:23 UTC, t8m commented on crypto/ec/ecp_nistp521.c
> +    ec_nistp_pre_comp_serialize(out, tmp, 64/8, 66);
As above

2024-07-12 16:23 UTC, t8m commented on crypto/ec/ecp_nistp521.c
> +#undef MASK
Please add space after `#`

2024-08-12 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2024-10-10 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2024-11-10 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 61 days ago

2024-12-11 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 92 days ago

2025-01-11 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 123 days ago

2025-02-11 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 154 days ago

2025-03-14 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 185 days ago

2025-04-14 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 216 days ago

2025-05-15 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 247 days ago

2025-06-15 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 278 days ago

2025-06-16 08:07 UTC, t8m commented
@dannytsen Any chance of taking over this work?

2025-06-16 14:57 UTC, dannytsen commented
@t8m This isn't planned.  So, we can close this PR.  Thanks.

2025-06-16 15:33 UTC, closed without merging