Create a rudimentary symbol scanning script
openssl/openssl pull request #22478
Opened 2023-10-23 16:56 UTC by nhorman

We would like to be able to log and audit the symbols we use in openssl so that we might catch when a new platform symbols is referecned

Add such a script (just on unix platforms for now) that gathers the used symbols not belonging to libcrypto or libssl, and compare it to a prior known set of used symbols.  Error out if a new symbol is found

Add this script to the static analysis workflow in CI to capture newly introduced platform symbols

Fixes #22330

2023-10-26 03:14 UTC, slontis commented on util/checkplatformsyms.pl
> +# Copyright 2006-2020 The OpenSSL Project Authors. All Rights Reserved.
Update copyright..

2023-10-26 17:56 UTC, t8m commented
I think this is good enough for start. We can improve this later if needed.

2023-10-26 17:56 UTC, t8m approved these changes

2023-10-26 17:58 UTC, t8m approved these changes

2023-10-27 10:48 UTC, hlandau requested changes
One nit, otherwise looks good

2023-10-27 10:48 UTC, hlandau commented on util/checkplatformsyms.pl
> +		open($OBJFH, "$cmd|") or die "Cannot opern process: $!";
nit: open

2023-10-28 05:41 UTC, thesamesam commented
Might be worth looking at `abidiff` and the other tools from libabigail at some point.

2023-10-30 10:18 UTC, t8m approved these changes
Please use `git commit --fixup` instead of force pushes when fixing things from reviews.

2023-10-31 13:20 UTC, hlandau approved these changes

2023-10-31 13:23 UTC, hlandau commented
> Might be worth looking at `abidiff` and the other tools from libabigail at some point.

Thanks for the suggestion! I wasn't aware of these tools. I've created an issue #22571.

2023-11-01 14:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2023-11-01 15:33 UTC, t8m commented
Merged to the master branch. Thank you.

2023-11-01 15:33 UTC, closed without merging