quic: documentation and demo nits
openssl/openssl pull request #22483
Opened 2023-10-24 01:20 UTC by jamuir

The code for the quic demos (under `demos/guide`) is discussed in the
guide as modifications of `tls-client-block.c` (a tls demo).  Drop unneeded assignments to `ret` in the quic code so it better matches the tls code.

Also fix a couple of minor typos.

this is part of openssl/project#253

##### Checklist

- [ x] documentation is added or updated

2023-10-24 04:11 UTC, paulidale approved these changes

2023-10-24 04:46 UTC, paulidale approved these changes

2023-10-24 05:14 UTC, jamuir commented
Thanks, Pauli.

2023-10-24 06:32 UTC, t8m requested changes
Just a minor nit.

2023-10-24 06:32 UTC, t8m commented on demos/guide/quic-multi-stream.c
> +         * Create a UDP socket. We could equally use non-OpenSSL calls such
an UDP...

2023-10-24 06:39 UTC, paulidale commented on demos/guide/quic-multi-stream.c
> +         * Create a UDP socket. We could equally use non-OpenSSL calls such
"a UDP" reads better to me at least.

2023-10-24 07:18 UTC, t8m commented on demos/guide/quic-multi-stream.c
> +         * Create a UDP socket. We could equally use non-OpenSSL calls such
OK then.

2023-10-24 07:18 UTC, t8m approved these changes

2023-10-24 07:33 UTC, hlandau approved these changes

2023-10-24 07:34 UTC, hlandau commented
Good work.

2023-10-24 16:53 UTC, mattcaswell approved these changes

2023-10-25 08:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2023-10-25 08:45 UTC, mattcaswell commented
Pushed.

2023-10-25 08:45 UTC, closed without merging

2023-10-25 16:25 UTC, jamuir commented
Thanks, Matt.