Fixes an issue where:
openssl/openssl pull request #22482
Opened 2023-10-23 22:20 UTC by dtzimmerman

When using speed option -async_jobs n (n > 1), loopargs[i].sig* params are only set for the first instance, and subsequent instances are NULL or Invalid.

This ultimately causes a failure in SIG_sign_loop() when app_malloc() is called to allocate zero bytes.

Test with:
	openssl speed -async_jobs 2 -seconds 1 rsa2048

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2023-10-23 22:34 UTC, paulidale approved these changes
Nice catch

2023-10-24 07:46 UTC, ifranzki commented
This is also fixed in the 2nd commit of  https://github.com/openssl/openssl/pull/22399 . There are actually 2 places where the `break` needs to be replaced by a `continue`.

2023-10-24 07:52 UTC, mspncp requested changes
> Nice catch

Agreed. I just have an editorial request: your subject line (`Fixes an issue where:`) is not very informative in a `git log --oneline`. Would you mind changing it to something like the following?

    openssl speed: fix uninitialized parameters when using `-async_jobs`
    
    When using speed option -async_jobs n (n > 1), loopargs[i].sig* params
    are only set for the first instance, and subsequent instances are NULL or Invalid.
    
    This ultimately causes a failure in SIG_sign_loop() when app_malloc() is
    called to allocate zero bytes.
    
    Test with:
            openssl speed -async_jobs 2 -seconds 1 rsa2048

2023-10-24 07:55 UTC, mspncp commented
> I just have an editorial request

If you are not familiar with how you can amend your commit message and force-push the change, just post the desired subject line here, I can change the commit message for you.

2023-10-24 08:49 UTC, mspncp commented
Sorry @ifranzki, I did not read your first reply properly.

2023-10-24 08:53 UTC, mspncp commented
Closed as duplicate of #22399. Thanks for your fix nevertheless, @dtzimmerman!

2023-10-24 08:53 UTC, closed without merging

2023-10-24 09:01 UTC, ifranzki commented
Funny, this bug was there since end of last year, and now 2 people find it almost at the same time ;-)