Fix custom IV length issues
openssl/openssl pull request #22507
Opened 2023-10-25 16:12 UTC by kjackiewicz

Fix custom IV length issues in authenticated encryption/decryption (GCM & CCM)

This PR provides tests and fixes for  #22469

##### Checklist
- [ ] documentation is added or updated
- [x] tests are added or updated

2023-10-25 16:18 UTC, kjackiewicz commented
I've already submitted the ICLA.

2023-10-25 20:20 UTC, paulidale commented
You we flagged as waiting for CCLA confirmation.  Until we receive a CCLA from your company that lists you, this cannot be accepted.

2023-10-25 20:22 UTC, paulidale commented
This was fixed as part of CVE-2023-5363 which was released for 3.0 and 3.1 earlier this week.

2023-11-02 09:01 UTC, t8m requested changes

2023-11-02 09:01 UTC, t8m commented on providers/implementations/ciphers/ciphercommon_gcm.c
>  }
This could be potentially an API break.

2023-11-03 12:39 UTC, t8m commented
This should be fixed now. If there is anything remaining please open a new PR.

2023-11-03 12:39 UTC, closed without merging