Numerous documentation tweaks and improvements
openssl/openssl pull request #22505
Opened 2023-10-25 12:14 UTC by mattcaswell

Updates to various README files - in part inspired by @jamuir's experience described in https://github.com/openssl/project/issues/253

2023-10-25 12:38 UTC, t8m commented
CI is relevant

2023-10-25 12:49 UTC, t8m requested changes

2023-10-25 12:49 UTC, t8m commented on README-QUIC.md
> +[openssl-quic(7) manual page]: https://www.openssl.org/docs/manmaster/man7/openssl-quic.html
A duplicate of line 74

2023-10-25 12:49 UTC, t8m commented on README-QUIC.md
> +  [ossl-guide-introduction(7) manual page] for the index.
`[OpenSSL Guide]` is an existing link but `[ossl-guide-introduction(7) manual page]` does not exist? But they would be supposedly the same links?

2023-10-25 12:49 UTC, t8m commented on README-QUIC.md
> +  for these can be [found in the source tree under `demos\guide`](./demos/guide/).
`demos/guide` would be better wouldn't it?

2023-10-25 12:49 UTC, t8m commented on README-QUIC.md
> +HTTP/3). IANA matains a standard list of [ALPN ids] that can be used.
Typo: maintains

2023-10-25 12:49 UTC, t8m commented on README.md
> +for the TLS (formerly SSL), DTLS and QUIC (client side only) protocols.
maybe:  `currently client side only`

2023-10-25 15:33 UTC, mattcaswell commented
All feedback addressed. Please take another look.

2023-10-25 18:22 UTC, jamuir commented on README-QUIC.md
> +For a more comprehensive overview of OpenSSL's QUIC implementation, see the
I think this sentence reads better if it does not start in the same way as the previous sentence.

maybe reword and drop "more":  "For a comprehensive overview...."

2023-10-25 18:23 UTC, jamuir commented on README.md
> +  the QUIC (client side only) version 1 protocol ([RFC 9000]).
should we say "currently client side only" as before?

2023-10-26 10:08 UTC, mattcaswell commented
Latest round of feedback addressed. Please take another look.

2023-10-26 10:43 UTC, hlandau approved these changes

2023-10-26 12:46 UTC, t8m approved these changes

2023-10-27 13:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-10-30 07:55 UTC, hlandau commented
Merged to master and 3.2. Thank you.

2023-10-30 07:55 UTC, closed without merging