Prepare for 3.3
openssl/openssl pull request #22525
Opened 2023-10-26 15:00 UTC by levitte

This was forgotten during the release of 3.2 beta 1

2023-10-26 15:03 UTC, mattcaswell approved these changes

2023-10-26 15:06 UTC, hlandau approved these changes

2023-10-26 15:29 UTC, t8m requested changes

2023-10-26 15:29 UTC, t8m commented on CHANGES.md
> +
You need to add a new section.

2023-10-26 15:29 UTC, t8m commented on NEWS.md
> +
Same here

2023-10-26 15:33 UTC, hlandau approved these changes

2023-10-26 15:33 UTC, mattcaswell approved these changes

2023-10-26 15:33 UTC, t8m approved these changes

2023-10-26 20:59 UTC, paulidale approved these changes

2023-10-27 16:03 UTC, mattcaswell commented
Pushed.

2023-10-27 16:03 UTC, closed without merging