QUIC SRTM: Add stateless reset token manager
openssl/openssl pull request #22612
Opened 2023-11-03 12:26 UTC by hlandau

Another self-contained component which has come out of the server refactoring work, a requirement for proper handling of stateless resets once the refactor is done.

Includes test and fuzzer.

This can go into 3.3 as it is self-contained and harmless if unused.

2023-11-03 12:31 UTC, hlandau commented
It seems a little odd that we build the fuzzers when we don't have `-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION`.

2023-11-03 12:37 UTC, hlandau commented
tsan failure is a false alarm/stochastic failure in quicapitest and unrelated.

2023-11-03 14:53 UTC, kroeckx commented
This is missing a test/recipes/99-fuzz_* file to run over the fuzz corpus

2023-11-03 17:21 UTC, mattcaswell requested changes

2023-11-03 17:52 UTC, hlandau commented on ssl/quic/quic_srtm.c
> +     * doesn't hurt.
Sure, I don't mind.

2023-11-03 18:17 UTC, hlandau commented on ssl/quic/quic_srtm.c
> +    if (prev_p != NULL)
I mean, I suppose technically we can have `*prev_p` be undefined if no item is found. But I see no harm in clearing it in this case also.

2023-11-03 18:18 UTC, hlandau commented on ssl/quic/quic_srtm.c
> + * unchanged).
This was originally attempted but didn't really prove suitable. The singly-linked design was chosen for a reason and avoids additional allocations which would be required in a design based on ossl_list.

2023-11-03 18:19 UTC, hlandau commented
Updated.

2023-11-06 08:51 UTC, paulidale reviewed
This seems to be duplicating a lot of the SRT code in quic_channel.c.
Is the latter is going to be refactored as part of this PR?

2023-11-06 16:10 UTC, hlandau commented
> This seems to be duplicating a lot of the SRT code in quic_channel.c. Is the latter is going to be refactored as part of this PR?

Yes.

This is coming out of the server refactor, which (as documented in the server API PR) refactors a lot of stuff in `QUIC_CHANNEL` into a separate `QUIC_PORT` object. The stateless reset code had to be temporarily cut out of that to make that work, and since a `QUIC_PORT` multiplexes multiple `QUIC_CHANNEL` objects it's basically necessary to implement the routing of this in a proper way now to get back to where we were.

2023-11-06 16:15 UTC, hlandau commented on ssl/quic/quic_srtm.c
> + * The O(n) insert and lookup performance is tolerated on the basis that the
SRTs being sent in sequence number order doesn't imply that they're received in sequence number order. Packet reordering can occur.

This code already conducts a sorted insert so I think what you are describing matches the code here.

>Why would we ever want to search for the SRT via a list when we can use the hash table?

I'm not sure I follow. The SRTs are always looked up via a hashtable (items_rev). There can be multiple identical SRTs.

2023-11-06 19:59 UTC, paulidale commented on ssl/quic/quic_srtm.c
> + * unchanged).
??? What extra allocations?  ossl_list doesn't do any.

2023-11-06 20:00 UTC, paulidale commented on ssl/quic/quic_srtm.c
> +    SRTM_ITEM                   *next_by_seq_num;     /* SORT BY seq_num DESC */
It might be best to implement a singly linked list as part of list.h.
That's my longer term intention.

2023-11-07 13:53 UTC, hlandau commented on ssl/quic/quic_srtm.c
> + * unchanged).
If you use ossl_list you have to store the list head structure somewhere. LHASH doesn't support that, it only stores a pointer. Which means you'd have to allocate an entire separate bookkeeping structure just to store the list head structure. You can't "fake" the list head structure at the time you call ossl_list either because the tail pointer is unknown.

Hence why a singly-linked list was chosen; it allows you to use the LHASH entry as a head pointer and avoids storing a tail pointer, which isn't necessary in this circumstance. It avoids managing allocation of an entirely new class of object just to store a listhead.

Making a singly-linked list header is definitely of potential interest, but since a major reason to use singly-linked lists instead of doubly-linked lists is because of the flexibility it creates in situations like this, it would need to be designed for flexible use cases like these. You can't have a general "remove" method or similar without knowing the previous item in the list, so designing a good API is harder and I don't believe full "API opacity" is as viable as for the doubly-linked case as exemplified by list.h.

It would also be nice to have a internal hashtable data structure someday to replace LHASH which supports "intrusive" allocation (much like our list.h or, for example, boost::intrusive). It would need to support multiple hashtables for the same object type but with different keys/hash/compare functions.

2023-11-09 16:19 UTC, mattcaswell approved these changes

2023-11-13 17:51 UTC, t8m requested changes

2023-11-13 17:51 UTC, t8m commented on ssl/quic/quic_srtm.c
> +}
We should really use AES-128-ECB here with a random key generated on SRTM init as the block size is the same as the SRT length. It is faster and guaranteed to be a permutation.

2023-11-13 17:51 UTC, t8m commented on ssl/quic/quic_srtm.c
> +            lh_SRTM_ITEM_insert(srtm->items_fwd, new_head);
This does not seem to be resolved?

2023-11-14 10:51 UTC, hlandau commented on ssl/quic/quic_srtm.c
> +}
Makes sense. OK.

2023-11-14 13:21 UTC, t8m approved these changes

2023-11-20 12:03 UTC, mattcaswell approved these changes

2023-11-21 13:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-11-23 14:46 UTC, hlandau commented
Merged to master. Thanks for the reviews.

2023-11-23 14:46 UTC, closed without merging