Fix bug in priority queue remove function
openssl/openssl pull request #22646
Opened 2023-11-06 20:45 UTC by paulidale

The short circuit in the remove function when the element is the last in the heap, failed to add the removed slot back to the freelist.

Fixes #22644

- [ ] documentation is added or updated
- [x] tests are added or updated

2023-11-06 20:49 UTC, hlandau requested changes
Approved with nit fixed

2023-11-06 20:49 UTC, hlandau commented on test/priority_queue_test.c
> +            || !TEST_ptr(ossl_pqueue_INFO_pop(pq)))     // crash if bug present
nit: C99 comment

2023-11-06 20:54 UTC, paulidale commented on test/priority_queue_test.c
> +            || !TEST_ptr(ossl_pqueue_INFO_pop(pq)))     // crash if bug present
Your comment grrr :(
Fixed.

2023-11-06 20:55 UTC, hlandau approved these changes

2023-11-07 10:15 UTC, mattcaswell approved these changes

2023-11-08 11:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-11-08 11:09 UTC, hlandau commented
Merged to master and 3.2. Thank you.

2023-11-08 11:09 UTC, closed without merging