Introduce option allowing TLS 1.3 server to prefer psk_ke over psk_dhe_ke
openssl/openssl pull request #22794
Opened 2023-11-21 23:20 UTC by minichma

Introduce option `SSL_OP_PREFER_NO_DHE_KEX`, which allows configuring a TLS1.3 server to prefer session resumption using PSK-only key exchange over PSK with DHE, if both are available. The option is ignored unless PSK-only is explicitly allowed via `SSL_OP_ALLOW_NO_DHE_KEX`.

* Config option name: `PreferNoDHEKEX`
* Server flag: `prefer_no_dhe_kex`

This PR addresses #22783.

##### Checklist
- [x] documentation is added or updated
- [x] tests are added or updated

##### ToDo
- [ ] add version of first release to the HISTORY section of `SSL_CONF_cmd.pod`.

2023-11-22 09:02 UTC, t8m requested changes
Good work. Could you please add CHANGES.md entry?

2023-11-22 09:02 UTC, t8m commented on ssl/statem/extensions_srvr.c
> +        /* If we're doing PSK ('hit') but the client doesn't support psk-dhe,
Nit: Multiline comments need to start with `/*` and end with `*/` on separate lines.

2023-11-22 09:02 UTC, t8m commented on ssl/statem/extensions_srvr.c
> +        /* If both, psk_ke and psk_dh_ke are available, we do psk_dh_ke and
As above

2023-11-22 17:23 UTC, minichma commented
@t8m Thank you! Improved as suggested. As the doc build complained about docs missing in `openssl-s_(server|client).pod` I added the options there as well (and in `perlvars.pm` too). However, as the option is ignored on the client (which _could_ change in the future though), I'm not sure it is a good idea to add it to the client docs. What do you think? How would I remove it from the client docs without the linter complaining?

Btw, the CLA is on its way.

2023-11-22 18:03 UTC, t8m commented
I would keep it at the client docs. However you also need to add the description for the new command line options in SSL_CONF_cmd.pod around line 98.

2023-11-23 10:12 UTC, mattcaswell approved these changes
LGTM

2023-11-23 13:53 UTC, minichma commented
@t8m I closed and reopened the PR to get rid of the 'CLA missing' tag. I've added the changelog in anticipation of version 3.3. Anything else missing from my side?

2023-11-23 14:01 UTC, t8m approved these changes

2023-11-23 14:02 UTC, t8m commented
> @t8m I closed and reopened the PR to get rid of the 'CLA missing' tag. I've added the changelog in anticipation of version 3.3. Anything else missing from my side?

Nope, this is good as is.

2023-11-24 15:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2023-11-24 15:09 UTC, closed without merging

2023-11-24 15:09 UTC, mattcaswell commented
Pushed. Thanks!