DTLS1.3: Fix comment for ssl connection version field
openssl/openssl pull request #22937
Opened 2023-12-04 13:29 UTC by fwh-dc

2024-03-21 14:49 UTC, fwh-dc commented
@t8m This is ready for review. Would you please add labels to reflect that? Thanks!

2024-04-04 16:37 UTC, t8m approved these changes

2024-05-05 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2024-05-13 09:07 UTC, mattcaswell requested changes

2024-05-13 09:07 UTC, mattcaswell commented on ssl/ssl_local.h
>       * protocol version (one of SSL2_VERSION, SSL3_VERSION, TLS1_VERSION,
Really we should drop `SSL2_VERSION` since this is no longer supported. Also this list seems to omit TLS1_1_VERSION which should be there.

2024-05-14 13:35 UTC, t8m approved these changes

2024-05-15 13:44 UTC, mattcaswell approved these changes

2024-05-16 14:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-05-16 16:28 UTC, t8m commented
Merged to the feature branch. Thank you for your contribution.

2024-05-16 16:28 UTC, closed without merging