Adds design document for DTLS 1.3 implementation documentation
openssl/openssl pull request #23041
Opened 2023-12-14 10:07 UTC by fwh-dc

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2023-12-18 11:18 UTC, mattcaswell approved these changes
Nice work!

2024-01-18 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2024-02-18 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 61 days ago

2024-03-20 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 92 days ago

2024-04-04 17:00 UTC, t8m commented
The check_docs CI failure is relevant.

2024-04-09 14:31 UTC, t8m approved these changes

2024-04-09 14:31 UTC, t8m commented
@mattcaswell please reconfirm

2024-04-15 16:12 UTC, davidben commented
A few TLSWG threads to call to your attention. As we've been reviewing the documents, we noticed a few hiccups in parts of the protocol:
https://mailarchive.ietf.org/arch/msg/tls/6y8wTv8Q_IPM-PCcbCAmDOYg6bM/
https://mailarchive.ietf.org/arch/msg/tls/3IEIzc2ssdkZbyYEXIvz6t3ZhbI/
https://mailarchive.ietf.org/arch/msg/tls/_ku3-YDcroNmG_QKZsYTtqYzC0M/
https://mailarchive.ietf.org/arch/msg/tls/GYX_teYy5CTFiGCBgbQJQwv_Fj4/

(Thoughts welcome on the TLSWG list.)

2024-05-14 13:53 UTC, t8m approved these changes

2024-05-14 13:53 UTC, t8m commented
doc check CI is relevant

2024-05-15 10:11 UTC, t8m approved these changes

2024-05-15 14:13 UTC, mattcaswell requested changes
Looks good just one very minor typo

2024-05-16 18:36 UTC, fwh-dc commented on doc/designs/dtlsv1_3/dtlsv1_3-main.md
> +This enforced by the macro `SSL_CONNECTION_MIDDLEBOX_IS_ENABLED(sc)`.
Fixed!

2024-05-24 06:21 UTC, fwh-dc commented
ping @mattcaswell

2024-05-29 14:10 UTC, mattcaswell approved these changes

2024-05-30 15:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-05-30 16:26 UTC, closed without merging

2024-05-30 16:26 UTC, t8m commented
Squashed and merged to the feature branch. Thank you for your contribution.