Check appropriate OSSL_PARAM_get_* functions for NULL
openssl/openssl pull request #23083
Opened 2023-12-18 15:57 UTC by nhorman

The base type OSSL_PARAM getters will NULL deref if they are initalized as null.  Add NULL checks for those parameters that have no expectation of returning null (int32/64/uint32/64/BN).  Other types can be left as allowing NULL, as a NULL setting may be meaningful (string, utf8str, octet string, etc).

##### Checklist
- [x] tests are added or updated

2023-12-19 07:53 UTC, t8m requested changes
One trivial nit

2023-12-19 07:53 UTC, t8m commented on test/params_api_test.c
> +    if (!TEST_int_eq(test_param_type_null(&param),1))
Nit: space after `,`

2023-12-19 08:37 UTC, tom-cosgrove-arm commented
Is it reasonable to set `data` to `NULL` when `data_type` says it's an integer? If yes, this is okay. If not, then it seems reasonable for these to fault on null-pointer access.

2023-12-19 14:13 UTC, nhorman commented
@tom-cosgrove-arm I believe so, yes.  We have a specific error condition that can be raised when the data type doesn't match the data stored in param (CRYPTO_R_PARAM_NOT_INTEGER_TYPE).  I could envision this being used to construct a parameter list of a given length that is filled out at a later time

2023-12-19 16:10 UTC, nhorman commented on test/params_api_test.c
> +    if (!TEST_int_eq(test_param_type_null(&param),1))
fixed

2023-12-19 16:16 UTC, t8m approved these changes

2024-01-04 11:47 UTC, mattcaswell approved these changes

2024-01-04 12:34 UTC, levitte requested changes
Please be consistent.  The change of `OSSL_PARAM_get_BN` paves the way

2024-01-04 12:34 UTC, levitte commented on crypto/params.c
> +    }
This should be `err_null_argument`

2024-01-04 12:34 UTC, levitte commented on crypto/params.c
> +    }
Should be `err_null_argument`

2024-01-04 12:34 UTC, levitte commented on crypto/params.c
> +    }
Should be `err_null_argument`

2024-01-04 12:34 UTC, levitte commented on crypto/params.c
> +    }
Should be `err_null_argument`

2024-01-04 12:34 UTC, levitte commented on crypto/params.c
> +    }
Should be `err_null_argument`

2024-01-04 12:34 UTC, levitte commented on crypto/params.c
> +    }
Should be `err_null_argument`

2024-01-05 12:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-01-05 14:06 UTC, t8m commented
This needs an update based on @levitte's review.

2024-01-06 19:18 UTC, nhorman commented on crypto/params.c
> +    }
fixed

2024-01-06 19:18 UTC, nhorman commented on crypto/params.c
> +    }
fixed

2024-01-06 19:18 UTC, nhorman commented on crypto/params.c
> +    }
fixed

2024-01-06 19:18 UTC, nhorman commented on crypto/params.c
> +    }
fixed

2024-01-06 19:18 UTC, nhorman commented on crypto/params.c
> +    }
fixed

2024-01-06 19:18 UTC, nhorman commented on crypto/params.c
> +    }
fixed

2024-01-07 10:23 UTC, levitte approved these changes

2024-01-09 14:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-01-09 15:59 UTC, t8m commented
Merged to the master and 3.2 branches. This does not apply to 3.1 and 3.0 cleanly, please make a separate PR.

2024-01-09 15:59 UTC, closed without merging