Add 'no-quicserver' option to disable building QUIC server utility.
openssl/openssl pull request #23149
Opened 2023-12-25 12:06 UTC by AenBleidd

This utility isn't required when building library only, but before this PR there was no way to disable its build.

##### Checklist

- [x] documentation is added or updated

2023-12-25 12:08 UTC, AenBleidd commented
ICLA has been signed and sent

2023-12-27 07:55 UTC, InfoHunter commented
It seems the `quicserver.c` file is a temporary one and it will be removed. So I am not sure if it's worth a disable option or not.

2023-12-27 07:57 UTC, AenBleidd commented
@InfoHunter, currently this file is the part of the 3.2.0 release, and it is a reason of the failed build on the old Android NDK: https://github.com/microsoft/vcpkg/issues/35792

2023-12-27 07:58 UTC, AenBleidd commented
If there is a better way to disable the build of this file - please let me know, and I'll prepare another PR

2023-12-27 10:13 UTC, t8m commented
This is a wrong fix for the https://github.com/microsoft/vcpkg/issues/35792. Is vcpkg configuring OpenSSL with `no-apps` ? If not, then it must be possible to link the quicserver the same way as openssl app is linked. Otherwise we should just make the quicserver not built with no-apps.

2023-12-27 11:07 UTC, AenBleidd commented
@t8m, yes, there is a possibility to configure OpenSSL with `no-apps` using vcpkg. Unfortunately, currently when configuring OpenSSL with `no-apps`, `quicserver` is still building, and it's not using the correct variables to be successfully built with the older NDK.
What is the best way to proceed here?
Should I provide a PR to not build `quicserver` with `no-apps` specified?

2023-12-27 12:03 UTC, t8m commented
@AenBleidd I mean - if you build without no-apps, does the openssl command build fine? If so, it must be possible to make the quicserver to link the same way as the openssl command.

2023-12-27 12:10 UTC, AenBleidd commented
@t8m, if I build with 'no-apps' everything builds fine except quicserver. It's broken (I assume because of the tool chain and/or CC flags not passed properly, but I haven't digged so deep).
If this is a temporary utility and it's gonna be removed as @InfoHunter told - I see no reason to fix its build, it's better to not build it when 'no-apps' flag is specified (as it's done in my last commit).

2023-12-27 13:08 UTC, t8m requested changes

2023-12-27 13:08 UTC, t8m commented on CHANGES.md
> + * Disable building QUIC server utility when OpenSSL is configured with
Add an empty line above

2023-12-27 15:46 UTC, t8m commented
Please drop the merge commit and force push.

2023-12-27 17:36 UTC, t8m approved these changes
OK with CLA: trivial

2023-12-28 08:14 UTC, InfoHunter commented
> If this is a temporary utility and it's gonna be removed as @InfoHunter told - I see no reason to fix its build, it's better to not build it when 'no-apps' flag is specified (as it's done in my last commit).

Yes. The `quicserver` should be a part of OpenSSL apps, either inside `s_server` or standalone. Now it's more reasonable to link it with the `no-apps` option, as in your last commit. And this makes it easier in the future to move this temp utility to a real feature of OpenSSL apps.

2023-12-28 08:15 UTC, InfoHunter approved these changes

2023-12-29 09:00 UTC, openssl-machine commented
This pull request is ready to merge

2023-12-29 10:37 UTC, t8m commented
Merged to the master and 3.2 branches. Thank you for your contribution.

2023-12-29 10:37 UTC, closed without merging