DTLS 1.3: Update protocol_version.pm
openssl/openssl pull request #23242
Opened 2024-01-09 06:22 UTC by fwh-dc

- [x] tests are added or updated

2024-01-09 12:17 UTC, mattcaswell requested changes

2024-01-09 12:17 UTC, mattcaswell commented on test/ssl-tests/protocol_version.pm
> +            "name" => "resumption-with-hrr",
Don't we want a different name here?

2024-01-09 16:42 UTC, fwh-dc commented on test/ssl-tests/protocol_version.pm
> +            "name" => "resumption-with-hrr",
You are right. I'll fix that!

2024-02-09 00:08 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 30 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2024-03-11 00:09 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 61 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2024-04-04 16:57 UTC, t8m commented
The CI is relevant.

2024-05-05 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2024-05-10 13:47 UTC, t8m approved these changes

2024-05-15 13:47 UTC, mattcaswell approved these changes

2024-05-16 14:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-05-19 08:46 UTC, shahsb approved these changes
LGTM!

2024-05-19 08:48 UTC, shahsb commented
IMO, at the end, when we're ready, we should squash all commits into a single one. So that in future if need arises to revert something, that really helps. Thanks!

2024-05-20 10:01 UTC, t8m commented
@shahsb As the commits are `fixup!` commits they will be squashed automatically when merging.

2024-05-20 10:03 UTC, t8m commented
Merged to the feature branch. Thank you for your contribution.

2024-05-20 10:03 UTC, closed without merging