Remove receiving of unused return value
openssl/openssl pull request #23277
Opened 2024-01-12 09:18 UTC by JohnnySavages

Found by Linux Verification Center (linuxtesting.org) with SVACE.

CLA: trivial

2024-01-12 09:47 UTC, t8m approved these changes
OK with CLA: trivial

2024-01-12 12:29 UTC, nhorman requested changes

2024-01-12 12:29 UTC, nhorman commented on apps/s_time.c
> -    i = (int)((long)time(NULL) - finishtime + maxtime);
you need to remove the declaration of i from the function as well, now that its not used anywhere, or you will get a build break when compiling with --strict-warnings

2024-01-13 13:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-01-15 16:20 UTC, t8m commented
Merged to the master branch. Thank you for your contribution.

2024-01-15 16:20 UTC, closed without merging