Added configuration for Embarcadero-Borland Clang Compiler 64 and rename BC-32 to BCC-32
openssl/openssl pull request #23333
Opened 2024-01-18 15:04 UTC by GermanAizek

2024-01-18 15:42 UTC, t8m requested changes

2024-01-18 15:42 UTC, t8m commented on Configurations/50-cppbuilder.conf
> +                                "_freea=free", "_setmode=setmode"),
Why are the _malloca and _freea aliases needed? I hope we are not using these functions anywhere in the code.

2024-01-18 15:42 UTC, t8m commented on Configurations/50-cppbuilder.conf
> +    "BCC-32" => {
I would not rename it, or rather make the old name be an alias of the new one.

2024-01-18 15:44 UTC, t8m commented
We will need a CLA to be signed to be able to accept this contribution. Could you please follow: https://www.openssl.org/policies/cla.html

2024-01-23 15:06 UTC, closed without merging

2024-01-23 15:13 UTC, GermanAizek commented
Close PR and migrate to here: https://github.com/openssl/openssl/pull/23377