Use 64-bit connection epoch for dtls1.3 and do not allow it to wrap.
openssl/openssl pull request #23553
Opened 2024-02-12 13:08 UTC by fwh-dc

Dependent on:
https://github.com/openssl/openssl/pull/23229

2024-02-14 03:13 UTC, slontis commented on ssl/record/rec_layer_d1.c
> +        if (s->rlayer.d->r_conn_epoch == 0) {
NIT: remove {} on single liners.. Same comment applies on line 685-687

2024-04-04 16:48 UTC, t8m requested changes

2024-04-04 16:48 UTC, t8m commented on ssl/record/rec_layer_d1.c
> +int dtls1_increment_epoch(SSL_CONNECTION *s, int rw)
As you are adding a return value, could you please adjust the existing callers to check it?

2024-05-10 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2024-05-10 05:14 UTC, davidben commented
Do note this discussion from the TLSWG https://mailarchive.ietf.org/arch/msg/tls/6y8wTv8Q_IPM-PCcbCAmDOYg6bM/

2024-06-10 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2024-07-11 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 61 days ago

2024-08-11 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 92 days ago

2024-10-10 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2024-11-10 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 61 days ago

2024-12-11 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 92 days ago

2025-01-11 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 123 days ago

2025-02-11 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 154 days ago

2025-03-14 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 185 days ago

2025-04-14 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 216 days ago

2025-05-15 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 247 days ago

2025-06-15 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 278 days ago

2025-07-16 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 309 days ago

2025-08-16 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 340 days ago

2025-09-16 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 371 days ago

2025-10-17 00:10 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 402 days ago

2025-11-17 00:10 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 433 days ago

2025-12-18 00:10 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 464 days ago

2025-12-18 10:18 UTC, t8m commented
@fwh-dc What is the status of this PR, please?

2025-12-18 18:58 UTC, fwh-dc commented
I'll close this as I wont be spending time on it. Maybe @rsith71 can have a look at how 64-bit epochs are handled. My recollection is that there's an internal 16 bit counter, which needs to be updated to 64 bit and then there are some check for rollover that need to be added.

2025-12-18 18:58 UTC, closed without merging