Brotli: Don't leave errors behind if loading library failed.
openssl/openssl pull request #23577
Opened 2024-02-13 20:35 UTC by sebastianas

If brolti support is dynamic then it is loaded at runtime and may fail if the library is not available. The library can be loaded even if the user did not ask for it, for instance via SSL_CTX_new_ex() -> ossl_comp_has_alg().
Leaving an error record can have other side effects if the user is poping the stack and notices and aborts due it.

Use ERR_set_mark()/ ERR_pop_to_mark() to avoid leaving marks if library loading failed.

Fixes: #23558

2024-02-14 03:04 UTC, slontis reviewed
This doesnt seem quite right since
(1) The brotli code for loading was based off the other files i.e zlib and zstd which have almost identical code, so applying the change to just 1 seems inconsistent
(2) In the case where it returns 0 it should not be removing errors, if it does it in the case where it returns 1 then that is ok. (So you would need to use clear_mark).
(3) Depending on (2) it may indicate that this is not the appropriate place to do the error handling (it may be that the caller i.e. ossl_comp_alg() is a better place to handle this).

2024-02-14 20:22 UTC, sebastianas commented
On 2024-02-13 19:04:25 [-0800], Shane wrote:
> This doesnt seem quite right since
> (1) The brotli code for loading was based off the other files i.e zlib
> and zstd which have almost identical code, so applying the change to
> just 1 seems inconsistent

I am aware of this and mentioned in #23558 that I would follow up on the
other two once we settled on something here.

> (2) In the case where it returns 0 it should not be removing errors,
> if it does it in the case where it returns 1 then that is ok. (So you
> would need to use clear_mark).

I'm not following here. In ossl_comp_brotli_init() I'm setting a marker
and before return (regardless if sucessfull or not) I'm clearing the
marker again. So the error code is no leaking to the caller.
If I am not removing any errors that occured in the process, why do it?

> (3) Depending on (2) it may indicate that this is not the appropriate
> place to do the error handling (it may be that the caller i.e.
> ossl_comp_alg() is a better place to handle this). 

That is probably the debate.
Pushing the mark/clear to ossl_comp_has_alg() would require to audit
more places wheather or not an error is okay or not and
ossl_comp_has_alg() has no idea either so it will its caller. That would
not only require touch more users but also do this push/pop thingy each
time the request happens. Doing it in ossl_comp_brotli_init() (and for
the other algos, too) would limit it one invocation only and only if it
is really needed.

Also if brotli is not enabled at build-time, then there will be no error
at all.

Sebastian

2024-02-14 22:59 UTC, slontis commented
What I was trying to indicate was - A function MAY return an error on the error stack if it fails (returns 0), but it should not return something on the error stack if it passes (returns 1).
If a caller ignores the return result being zero then that is where the issue is.
If the error stack is not useful in ANY situation where it can be called from then your approach would be ok.

2024-02-15 17:04 UTC, sebastianas commented
On 2024-02-14 14:59:59 [-0800], Shane wrote:
> What I was trying to indicate was - A function MAY return an error on
> the error stack if it fails (returns 0), but it should not return
> something on the error stack if it passes (returns 1).
> If a caller ignores the return result being zero then that is where
> the issue is.
> If the error stack is not useful in ANY situation where it can be
> called from then your approach would be ok.

I think I understood. Let's see ;)

Sebastian

2024-02-15 17:20 UTC, sebastianas commented
hold on for a sec

2024-02-15 17:51 UTC, sebastianas commented
okay, all good.

2024-02-16 00:21 UTC, slontis commented
Do the above changes address your problem?

2024-02-16 15:59 UTC, t8m requested changes
You have the ERR_pop_to_mark() and ERR_clear_last_mark() inverted. The mark needs to be cleared if we are returning an error from the functions. But errors need to be popped out of the queue up to mark if we are returning success.

2024-02-16 17:42 UTC, sebastianas commented
On 2024-02-15 16:21:16 [-0800], Shane wrote:
> Do the above changes address your problem?

Yes.

Sebastian

2024-02-16 17:46 UTC, sebastianas commented
On 2024-02-16 07:59:32 [-0800], Tomáš Mráz wrote:
> @t8m requested changes on this pull request.
> 
> You have the ERR_pop_to_mark() and ERR_clear_last_mark() inverted. The
> mark needs to be cleared if we are returning an error from the
> functions. But errors need to be popped out of the queue up to mark if
> we are returning success.

No, this doesn't work then.

SSL_CTX_new_ex() -> ossl_comp_has_alg() asks for all compressions. I
have selected brotli-dynamic at compile time and libbrotli is not
installed. So DSO_load() fails rightfully and SSL_CTX_new_ex() does not
not return an error. And then dovecot notices later an error on stack
and aborts. Supressing the error here avoids the problem. Doing it as
you suggested "leaks" the error again.

Sebastian

2024-02-18 18:38 UTC, t8m commented
> No, this doesn't work then.

Then this is a wrong fix and something else must be done because clearing the error stack and returning an error return (0) is wrong. The error stack cleanup must be done at some further level up where the error returned is being ignored.

Or, alternatively, we should never return 0 from these init functions.

2024-03-20 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2024-05-05 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2024-06-06 00:08 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 30 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2024-07-07 00:08 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 61 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2024-08-05 00:08 UTC, openssl-machine commented
This PR has been closed.  It was waiting for the creator to make requested changes but it has not been updated for 90 days.

2024-08-05 00:08 UTC, closed without merging