fix error: relocation truncated to fit: R_RISCV_JAL against symbol.
openssl/openssl pull request #23617
Opened 2024-02-17 22:44 UTC by xicilion

This pr is used to fix link errors in the aes assembly algorithm under riscv64.

---
The following message is reported when connecting under riscv64:
```
/works/fibjs/bin/Linux_riscv64_release/libopenssl.a(aes-riscv64.s.o): in function `.Ltmp14':
(.text+0x946): relocation truncated to fit: R_RISCV_JAL against symbol `AES_set_encrypt_key' defined in .text section in /works/fibjs/bin/Linux_riscv64_release/libopenssl.a(aes-riscv64.s.o)
```
---
##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

2024-02-19 10:53 UTC, t8m approved these changes
This would be acceptable with CLA: trivial but you can also submit a regular CLA. https://www.openssl.org/policies/cla.html

2024-02-26 09:26 UTC, xicilion commented
Is there any additional work that needs to be done on this PR?

2024-03-28 00:09 UTC, openssl-machine commented
This PR has the label 'hold: cla required' and is stale: it has not been updated in 30 days. Note that this PR may be automatically closed in the future if no CLA is provided.  For CLA help see https://www.openssl.org/policies/cla.html

2024-04-02 14:52 UTC, t8m commented
@xicilion Could you please update the commit message to include `CLA: trivial` on a separate line in the commit message body?

`git commit --amend ; git push --force` should help.

2024-04-17 11:55 UTC, xicilion commented
This PR has been waiting too long........
:<

2024-04-17 14:38 UTC, t8m approved these changes

2024-04-22 09:00 UTC, tom-cosgrove-arm commented
> Though it is still acceptable as it is just one-shot and no other code uses `t0`

Why not add it to the registers that are given Perl names as `$scratch` or something like that?

2024-04-23 02:33 UTC, ZenithalHourlyRate commented
> > Though it is still acceptable as it is just one-shot and no other code uses `t0`
> 
> Why not add it to the registers that are given Perl names as `$scratch` or something like that?

Actually, registers that are given Perl names are declared using `use_reg`, which will record currently used register and then `save_regs` would handle the caller/callee issue. In other words, the semantic requires that registers from this interface should be used only after `save_regs`.

Now I suggest just adding a comment.

```
la      t0,AES_set_encrypt_key # caller-saved register, safe to use
jalr    ra,t0
```

Which corresponds to the above line, where `$KEYP` is a callee-saved register and it is ad-hoc saved.

```
sd      $KEYP,0(sp) # We need to hold onto this!
```

Otherwise the code would become

```
$code .= save_regs();
...
la      $scratch,AES_set_encrypt_key # caller-saved register
jalr    ra,$scratch
...

```

2024-04-26 16:14 UTC, xicilion commented
Thanks for the review, so shall we add a comment line to the original PR?

2024-05-27 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2024-06-27 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 61 days ago

2024-06-27 08:54 UTC, bernd-edlinger requested changes

2024-06-27 08:54 UTC, bernd-edlinger commented on crypto/aes/asm/aes-riscv64.pl
> +    jalr    ra,t0
try `call AES_set_encrypt_key` instead,
so the linker will detect if a temporary register is necessary,
based on the address distance.

2024-07-28 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2024-08-28 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 61 days ago

2024-09-28 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 92 days ago

2024-10-29 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 123 days ago

2024-11-29 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 154 days ago

2024-12-30 00:09 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 185 days ago

2025-01-30 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 216 days ago

2025-03-02 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 247 days ago

2025-04-19 00:09 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 30 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2025-05-20 00:08 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 61 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2025-06-18 00:09 UTC, openssl-machine commented
This PR has been closed.  It was waiting for the creator to make requested changes but it has not been updated for 90 days.

2025-06-18 00:09 UTC, closed without merging