Fix a memory leak on successful load of CRL
openssl/openssl pull request #23695
Opened 2024-02-27 14:25 UTC by beldmit

Fixes #23693

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

2024-02-27 14:44 UTC, beldmit commented
I'm not sure the failure is relevant

2024-02-27 18:28 UTC, shahsb approved these changes

2024-02-29 05:47 UTC, mattcaswell approved these changes

2024-02-29 05:48 UTC, mattcaswell commented
Actually - should we have some kind of test for this?

2024-02-29 10:17 UTC, t8m commented
Yeah there could be a test that would detect this with MSAN.

2024-02-29 10:54 UTC, beldmit commented
Do you have an idea where to add it?

2024-02-29 11:03 UTC, bernd-edlinger commented
Simply hijack the test that was introduced by #22885

2024-02-29 15:17 UTC, beldmit commented
Tests are added, I lift the hold.

2024-02-29 15:54 UTC, beldmit commented
The failures seem irrelevant

2024-03-01 00:29 UTC, mattcaswell requested changes

2024-03-01 00:29 UTC, mattcaswell commented on test/x509_load_cert_file_test.c
> +    if (crl && !TEST_true(X509_load_crl_file(lookup, crl, X509_FILETYPE_PEM)))
`crl != NULL`

2024-03-01 09:54 UTC, beldmit commented on test/x509_load_cert_file_test.c
> +    if (crl && !TEST_true(X509_load_crl_file(lookup, crl, X509_FILETYPE_PEM)))
Done, thanks!

2024-03-01 14:39 UTC, beldmit commented
The failure seems irrelevant

2024-03-04 08:24 UTC, mattcaswell approved these changes

2024-03-06 09:17 UTC, beldmit commented
Ping @openssl/committers for the 2nd review

2024-03-07 10:09 UTC, beldmit commented
Applied to master, doesn't cherry-pick clean to 3.2. Fixup TBD

2024-03-07 10:42 UTC, beldmit commented
Thanks for the review!

2024-03-07 10:42 UTC, closed without merging