Update Documentation for EVP_DigestSign, EVP_DigestVerify.
openssl/openssl pull request #23834
Opened 2024-03-14 06:00 UTC by slontis

Fixes #23075

In OpenSSL 3.2 EVP_DigestSign and EVP_DigestVerify were changed so that a flag is set once these functions do a one-shot sign or verify operation. This PR updates the documentation to match the behaviour.

Investigations showed that prior to 3.2 different key type behaved differently if multiple calls were done.

By accident X25519 and X448 would produce the same signature, but ECDSA and RSA remembered the digest state between calls, so the signature was different when multiple calls were done.

Because of this undefined behaviour something needed to be done, so keeping the 'only allow it to be called once' behaviour seems a reasonable approach.

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

2024-03-14 06:01 UTC, slontis commented
Pauli I could not see these in the lifecycle pods..
Looks like this is out of scope here :)

2024-03-14 07:11 UTC, levitte approved these changes

2024-03-14 09:10 UTC, t8m requested changes

2024-03-14 09:10 UTC, t8m commented on doc/man3/EVP_DigestSignInit.pod
> +passing I<sig> as non NULL), unless the B<EVP_MD_CTX> is reinitialising by
reinitialising ->reinitialised

2024-03-18 01:42 UTC, nhorman approved these changes

2024-03-18 14:41 UTC, t8m approved these changes

2024-03-19 15:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-04-04 06:40 UTC, t8m commented
Merged to the master, 3.3 and 3.2 branches. Thank you for your contribution.

2024-04-04 06:40 UTC, closed without merging