follow up change on PR #23781
openssl/openssl pull request #23837
Opened 2024-03-14 09:42 UTC by Sashan

CHanges in this PR were prompted by @DDvO comments.

##### Checklist

- [ x] documentation is added or updated
- [ x] tests are added or updated

2024-03-14 09:49 UTC, tom-cosgrove-arm approved these changes
LGTM

2024-03-14 10:13 UTC, t8m commented
> Might be an idea to have a more informative title for the PR?

Also the commit message should primarily describe the changes in the commit in the subject. Why you're doing it should be eventually in the commit message body.

2024-03-14 10:14 UTC, t8m approved these changes

2024-03-14 10:31 UTC, DDvO commented
Thanks @Sashan for this follow-up.
I just wonder why you left the double `mock_args.content_type = "text/plain";` in http_test.c ?

2024-03-14 10:35 UTC, DDvO requested changes
Please also remove the needless double assignment I mentioned.
and improve the commit message as requested by @t8m.

2024-03-14 10:43 UTC, t8m commented
> I just wonder why you left the double `mock_args.content_type = "text/plain";` in http_test.c ?

I see it is removed by the patch

2024-03-14 10:48 UTC, DDvO commented
> > I just wonder why you left the double `mock_args.content_type = "text/plain";` in http_test.c ?
> 
> I see it is removed by the patch

Ah, so I must have overlooked this - sorry for the confusion.

2024-03-14 11:21 UTC, Sashan commented
fixed comment in this PR

2024-03-15 10:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2024-03-15 10:25 UTC, tom-cosgrove-arm commented
Whoever merges might want to tidy up the commit message a bit

2024-03-15 10:38 UTC, t8m commented
Commit message reworded and merged to the master branch. Thank you.

2024-03-15 10:38 UTC, closed without merging