posix_async: FreeBSD also defines {make|swap|get|set}context
openssl/openssl pull request #23885
Opened 2024-03-18 18:30 UTC by bsdimp

FreeBSD also defines {make|swap|get|set}context for backward compatibility, despite also exposing POSIX_VERSION 200809L in FreeBSD 15-current.

Note: There's no fallback for _POSIX_VERSION 200809 without these routines, so maybe that should be a #error?

FreeBSD currently defines _POSIX_VERSION to be 200112, but I'm changing that to 200809L and noticed this issue. Either definition will work with this #ifdef, and FreeBSD has supported 200112L level since about 2004 if I'm reading the logs right, so ~20 years, so that's sufficient.

##### Checklist

2024-03-18 18:36 UTC, t8m commented
This would be acceptable with CLA: trivial. Can you please amend the commit to add `CLA: trivial` on a separate line in the commit message body?

2024-03-24 09:38 UTC, bsdimp commented
> This would be acceptable with CLA: trivial. Can you please amend the commit to add `CLA: trivial` on a separate line in the commit message body?

You bet.

2024-03-25 10:36 UTC, mattcaswell approved these changes
Agree trivial

2024-03-25 10:38 UTC, mattcaswell commented
>Note: There's no fallback for _POSIX_VERSION 200809 without these routines, so maybe that should be a #error?

ascync_local.h includes async_win.h, async_posix.h and async_null.h. If by the time we get to async_null.h we don't have a definition for `ASYNC_ARCH` then we automatically fallback to the null implementation.

2024-03-25 12:08 UTC, bsdimp commented
> > Note: There's no fallback for _POSIX_VERSION 200809 without these routines, so maybe that should be a #error?
> 
> ascync_local.h includes async_win.h, async_posix.h and async_null.h. If by the time we get to async_null.h we don't have a definition for `ASYNC_ARCH` then we automatically fallback to the null implementation.

When I added this on FreeBSD, it was because there were undefined symbols....

2024-03-25 12:25 UTC, bsdimp commented
Can someone help me understand the two failures? They make no sense to me.

2024-03-25 12:49 UTC, mattcaswell commented
These are intermittent test failures we are currently experiencing (being investigated by @nhorman) - so unrelated to this PR. You can ignore them.

2024-03-25 12:50 UTC, mattcaswell commented
> When I added this on FreeBSD, it was because there were undefined symbols....

Hmmm. That is unexpected.

2024-03-25 16:35 UTC, t8m requested changes
Please avoid <TAB> characters. Keep the indentation by spaces only.

2024-03-25 16:50 UTC, bsdimp commented
> Please avoid TAB characters. Keep the indentation by spaces only.

Your CI should catch that, not people... 
But whatever, it's what emacs does by default...  I can fix it and push though....

2024-03-25 17:22 UTC, bsdimp commented
> > When I added this on FreeBSD, it was because there were undefined symbols....
> 
> Hmmm. That is unexpected.

`ld.lld: error: undefined reference due to --no-allow-shlib-undefined: async_local_cleanup`

is the error that I get during FreeBSD's buildworld.

2024-03-25 17:52 UTC, t8m approved these changes
OK with CLA: trivial

2024-03-25 18:19 UTC, nhorman commented
how is it that only async_local_cleanup isn't getting defined?  Thats not a posix api, thats the openssl library wrapper we have around the posix api, and its defined for all of async_posix/async_win/async_null.

Its interesting that in the posix/null cases, its defined as an empty function.  I wonder if the bsd compiler is doing something odd here

2024-03-26 18:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2024-04-04 06:45 UTC, t8m commented
Merged to the master branch. Thank you for your contribution.

2024-04-04 06:45 UTC, closed without merging