Avoid NULL pointer dereference
openssl/openssl pull request #23918
Opened 2024-03-21 13:17 UTC by rkrejci

Function `readbuffer_gets()` misses some of the initial checks of its arguments. Not checking them can lead to later NULL pointer dereferences.

The checks are now unified with the checks in the `readbuffer_read()` function.

Fixes #23915

2024-03-25 08:33 UTC, rkrejci commented
> Please, if you are able, sign and submit a cla so that we can accept your pr. Thank you

ICLA was sent, but will see how it will go with updating CCLA :(

2024-04-25 00:09 UTC, openssl-machine commented
This PR has the label 'hold: cla required' and is stale: it has not been updated in 30 days. Note that this PR may be automatically closed in the future if no CLA is provided.  For CLA help see https://www.openssl.org/policies/cla.html

2024-05-26 00:09 UTC, openssl-machine commented
This PR has the label 'hold: cla required' and is stale: it has not been updated in 61 days. Note that this PR may be automatically closed in the future if no CLA is provided.  For CLA help see https://www.openssl.org/policies/cla.html

2024-05-27 12:38 UTC, nhorman commented
@rkrejci I just checked, and your employer hasn't updated the ccla schedule with your name yet.  Could you please reach out to them to get that done?  Thank you

2024-06-06 07:47 UTC, t8m requested changes
IMO this would be acceptable with `CLA: trivial` so please amend the commit message to contain `CLA: trivial` on a separate line if you agree.

2024-06-06 07:47 UTC, t8m commented on crypto/bio/bf_readbuff.c
> +    if ((ctx == NULL) || (b->next_bio == NULL))
Please remove the extra parentheses.

2024-06-06 09:00 UTC, rkrejci commented on crypto/bio/bf_readbuff.c
> +    if ((ctx == NULL) || (b->next_bio == NULL))
Done, thanks.

2024-06-06 09:01 UTC, rkrejci commented
> IMO this would be acceptable with `CLA: trivial` so please amend the commit message to contain `CLA: trivial` on a separate line if you agree.

I agree, thank you!

2024-07-07 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2024-07-07 16:26 UTC, tom-cosgrove-arm approved these changes
Okay with trivial

2024-07-08 03:02 UTC, paulidale approved these changes
okay with trivial

2024-07-08 17:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-07-08 19:56 UTC, t8m commented
Merged to all the active branches. Thank you for your contribution.

2024-07-08 19:56 UTC, closed without merging