Osx threadfix
openssl/openssl pull request #23967
Opened 2024-03-25 13:28 UTC by nhorman

test build for debugging, as local operation on the development m1 doesn't reproduce failure

2024-03-25 22:33 UTC, slontis commented
Is there some way of limiting the number of writes instead of doing this?

2024-03-25 22:54 UTC, nhorman commented
sure, but that runs a bit counter to the purpose of the test, they idea (in part) was to not only test the sanity of rw and rcu locks, but to provide a level of performance comparison.

What we could do is, instead of wrapping, when we hit MAX_ULLONG, just leave the counter there so that we never tripped over the wrapping case.  Would that be acceptable?

2024-03-26 04:10 UTC, t-j-h commented
If you are running over the end of the unsigned long long then you need to implement a "carry" into another variable (perhaps even another unsigned long long) each time you reach the wrapping point. That does sound like overkill for this context - but I also find the implementation here more than a little strange.

2024-03-26 07:53 UTC, t8m commented
@nhorman I do not believe a wrap around 2^64 bit value is happening here. Or, the starting point was not a zero value. If the test run for 1000 seconds (which it is not running) it would mean doing 18 milions iterations in every nanosecond - that's obviously impossible. There must be some other issue in play.

2024-03-26 08:35 UTC, kroeckx commented
If we're worried for a wrap around at 2^64, why not clear the first bit?

2024-03-26 10:58 UTC, t8m requested changes

2024-03-26 10:58 UTC, t8m commented on test/threadstest.c
> +#ifndef OPENSSL_SYS_MACOSX
Nit: space after `#` - applies to all other places where `#ifdef/#endif` was added

2024-03-26 10:59 UTC, nhorman commented
Based on OTC discussion, for the purposes of the beta release, since we are not yet using rcu, I've updated this PR to disable the rcu torture test on macosx.  Will re-enable prior to introduction of usage post release

2024-03-26 11:15 UTC, t8m approved these changes

2024-03-26 11:16 UTC, t8m commented
OK with urgent

2024-03-26 13:53 UTC, mattcaswell approved these changes
Approved. I have one minor comment - but approved either way.

Agree urgent.

2024-03-26 13:53 UTC, mattcaswell commented on test/threadstest.c
> -
This blank line removal looks odd. In my mind it is better with it.

2024-03-26 14:43 UTC, nhorman commented
merged to master and 3.3

2024-03-26 14:43 UTC, closed without merging