document change of -verify behavior
openssl/openssl pull request #23983
Opened 2024-03-27 09:52 UTC by vladak

Follow up to PR #23773

2024-03-27 11:12 UTC, t8m requested changes

2024-03-27 11:12 UTC, t8m commented on doc/man1/openssl-crl.pod.in
> +Since OpenSSL 3.3, the B<-verify> will exit with 1 on failure.
Nit: Either remove `the` or add `option`, please.

2024-03-27 11:12 UTC, t8m commented on doc/man1/openssl-req.pod.in
> +Since OpenSSL 3.3, the B<-verify> will exit with 1 on failure.
Same as above.

2024-03-27 13:24 UTC, t8m approved these changes

2024-03-27 14:36 UTC, vt-alt commented
Btw, for gost-engine tests `openssl crl` was not called with `-verify` but still returns failure.
```
 test -skip {![file exists test.crl]} "Verifying corrupted CRL" {
        makeFile "badcrl.pem" [hackPem "\01\x1E" [getFile test.crl] "\01\0"]
        grep verify [openssl "crl -in badcrl.pem -noout -CAfile $::test::ca/cacert.pem"]
 } -1 "verify failure"
```

2024-03-28 08:30 UTC, tom-cosgrove-arm approved these changes

2024-03-29 09:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-03-29 11:49 UTC, vt-alt commented
> Btw, for gost-engine tests `openssl crl` was not called with `-verify` but still returns failure.

It's not stated that `-verify` option is default and `crl` exits with failure even without `-verify` option so the proposed text is not entirely correct. Or there will be third PR to correct this?

2024-04-02 16:43 UTC, t8m commented
Merged to the master and 3.3 branches. Thank you for your contribution.

2024-04-02 16:43 UTC, closed without merging

2024-04-02 16:48 UTC, vt-alt commented
Thanks for the reply. (But why someone should send another PR and not the original PR author correct theirs? Like in any normal review cycle. Of course who am I to criticize, but these two last PRs just make me curious of OTC review process.)

2024-04-02 16:50 UTC, t8m commented
@vt-alt The fact that in openssl crl `-verify` is implied by some other options is not really related to this PR. It also belongs to all branches.

I've opened: https://github.com/openssl/openssl/pull/24024