OSSL_STORE: Windows: use system certificates storage as default store
openssl/openssl pull request #24218
Opened 2024-04-20 00:06 UTC by yjh-styx

don't change X509_get_default_cert_dir - it used as default directory also (by_dir.c:91)

CLA: trivial

2024-04-20 18:28 UTC, shahsb requested changes

2024-04-20 18:28 UTC, shahsb commented on crypto/x509/by_store.c
> +#ifndef _WIN32
Could you please make it positive instead of negative?

#ifdef _WIN32

it helps improve readability. Thanks!

2024-04-22 18:22 UTC, t8m commented
Please do not add merge commits. Instead if there are conflicts, please rebase and force-push.

2024-04-29 08:09 UTC, hlandau commented
I don't think this is adequate. See https://github.com/openssl/openssl/pull/21190 for the history. This was already done and had to be reverted.

2024-05-30 00:09 UTC, openssl-machine commented
This PR is waiting for the creator to make requested changes but it has not been updated for 30 days.  If you have made changes or commented to the reviewer please make sure you re-request a review (see icon in the 'reviewers' section).

2024-05-30 12:01 UTC, nhorman commented
This PR is waiting for you to make requested changes @yjh-styx .  I will close this as inactive if there is no activity in another 30 days.

2024-05-30 13:48 UTC, yjh-styx commented
Could you clarify please what changes have been requested from my side?

2024-05-30 14:57 UTC, nhorman commented
@yjh-styx see comment [here](https://github.com/openssl/openssl/pull/24218#issuecomment-2082117262)

2024-05-30 19:09 UTC, yjh-styx commented
Sorry, but I don't understand exactly what changes are required of me.
The link you provide points to a discussion about the reasons for "not entering" a similar (as intended) PR in version 3.2.
If you wanted to say that this PR also requires some changes in the documentation, then I won't be of any help here (my English is not enough for this). If there were any other changes in mind, please clarify which ones specifically.

2024-05-31 12:13 UTC, t8m commented
We basically dispute the possibility to make the winstore a default store on Windows until the problems discussed here: https://github.com/openssl/openssl/pull/24170#issuecomment-2060870356 are resolved.

2024-05-31 15:59 UTC, yjh-styx commented
If a link to this discussion had been given as a reason for refusing this PR, I would have understood. But I don't understand what changes are required from me based on it.

Before the advent of the winstore mechanism, almost everyone using openssl to work with certificates in Windows wrote cycles for fetching certificates from regisytry and filling ossl-store with a simple filter like:
  (pCtx->dwCertEncodingType & PKCS_7_ASN_ENCODING) == PKCS_7_ASN_ENCODING
and it worked quietly on a bunch of machines for years.
Now (in version 3) your team has a winstore mechanism and I made a patch
using it (without asking the question "how and why you implemented it").

The discussion you link to may be the basis for demands for changes to
winstore, but as it follows:
"This PR is waiting for you to make requested changes"
[?https://github.com/openssl/openssl/pull/24218#issuecomment-2139402884](url)
What changes exactly are expected _from me_?

2024-06-03 06:45 UTC, t8m commented
I am closing the PR as I do not expect you will be implementing the missing bits in winstore.

2024-06-03 06:45 UTC, closed without merging