ssl_sess.c: deprecate SSL_SESSION_get_time/SSL_SESSION_set_time
openssl/openssl pull request #24307
Opened 2024-04-30 11:25 UTC by kanavin

Fixes: #23648

2024-04-30 13:56 UTC, kanavin commented
Signed CLA sent by email as specified in https://www.openssl.org/policies/cla.html

2024-05-17 08:13 UTC, kanavin commented
CLA issue fixed, please re-trigger the CI.

2024-05-17 09:00 UTC, t8m commented
This is strange. The CI failure is relevant but I do not see what is causing it.

2024-05-17 09:02 UTC, mattcaswell requested changes
Probably this should have an entry in CHANGES.md. We should also update the documentation to show that these are deprecated (in the same style as we have done other deprecations in the docs)

2024-05-17 09:08 UTC, t8m commented
> This is strange. The CI failure is relevant but I do not see what is causing it.

Ah, this is most probably caused by using the OSSL_DEPRECATEDIN...FOR() macro instead of just OSSL_DEPRECATED_IN_... macro. The parser updating the .num files would have to be changed. Please use just OSSL_DEPRECATED_IN_....

2024-05-17 09:13 UTC, kanavin commented
> > This is strange. The CI failure is relevant but I do not see what is causing it.
> 
> Ah, this is most probably caused by using the OSSL_DEPRECATEDIN...FOR() macro instead of just OSSL_DEPRECATED_IN_... macro. The parser updating the .num files would have to be changed. Please use just OSSL_DEPRECATED_IN_....

But that doesn't include a message advising what to use instead. You ok with that?

2024-05-17 09:16 UTC, mattcaswell commented
Ah, yeah `OSSL_DEPRECATEDIN..FOR()` is quite a new addition

> The parser updating the .num files would have to be changed.

We should really do that

2024-05-17 09:24 UTC, kanavin commented
I'm also baffled by the other fail as the lines don't match to where I think the problem is:
```
sslapitest.c
..\test\sslapitest.c(9380): error C2220: the following warning is treated as an error
..\test\sslapitest.c(9380): warning C4244: 'function': conversion from 'time_t' to 'long', possible loss of data
..\test\sslapitest.c(9387): warning C4244: 'function': conversion from 'time_t' to 'long', possible loss of data
..\test\sslapitest.c(9394): warning C4244: 'function': conversion from 'time_t' to 'long', possible loss of data
```

The culprit I believe is:
```
void SSL_CTX_flush_sessions(SSL_CTX *ctx, long tm);
```

I guess SSL_CTX_flush_sessions_ex is needed as well?

2024-05-17 09:30 UTC, mattcaswell commented
> I'm also baffled by the other fail as the lines don't match to where I think the problem is:

That's github playing tricks on you. When the CI runs it automatically merges your PR against the latest master and tests the resulting code. Most likely there have been changes in sslapitest.c on master since you opened this PR which have shifted the line numbers. The problem is definitely the 3 `SSL_CTX_flush_sessions` calls.

2024-05-17 09:34 UTC, kanavin commented
So should SSL_CTX_flush_sessions_ex() introduction be a separate PR or can I bundle that here?

2024-05-17 10:19 UTC, t8m commented
> So should SSL_CTX_flush_sessions_ex() introduction be a separate PR or can I bundle that here?

IMO you can bundle it here (in a separate commit for clarity).

2024-05-17 11:02 UTC, mattcaswell commented
> The parser updating the .num files would have to be changed.

This seems to fix it. @kanavin - do you want to incorporate that into this PR?

```` diff
diff --git a/util/perl/OpenSSL/ParseC.pm b/util/perl/OpenSSL/ParseC.pm
index 661bd11818..f7f8a5827e 100644
--- a/util/perl/OpenSSL/ParseC.pm
+++ b/util/perl/OpenSSL/ParseC.pm
@@ -266,9 +266,15 @@ my @opensslchandlers = (
     { regexp   => qr/OSSL_DEPRECATEDIN_\d+_\d+(?:_\d+)?\s+(.*)/,
       massager => sub { return $1; },
     },
+    { regexp   => qr/OSSL_DEPRECATEDIN_\d+_\d+(?:_\d+)?_FOR<<<.*>>>(.*)/,
+      massager => sub { return $1; },
+    },
     { regexp   => qr/(.*?)\s+OSSL_DEPRECATEDIN_\d+_\d+(?:_\d+)?\s+(.*)/,
       massager => sub { return "$1 $2"; },
     },
+    { regexp   => qr/(.*?)\s+OSSL_DEPRECATEDIN_\d+_\d+(?:_\d+)?_FOR<<<.*>>>(.*)/,
+      massager => sub { return "$1 $2"; },
+    },
 
     #####
     # Core stuff
````

2024-05-17 11:13 UTC, kanavin commented
> > The parser updating the .num files would have to be changed.
> 
> This seems to fix it. @kanavin - do you want to incorporate that into this PR?
> 
> ```diff
> diff --git a/util/perl/OpenSSL/ParseC.pm b/util/perl/OpenSSL/ParseC.pm
> index 661bd11818..f7f8a5827e 100644
> --- a/util/perl/OpenSSL/ParseC.pm
> +++ b/util/perl/OpenSSL/ParseC.pm
> @@ -266,9 +266,15 @@ my @opensslchandlers = (
>      { regexp   => qr/OSSL_DEPRECATEDIN_\d+_\d+(?:_\d+)?\s+(.*)/,
>        massager => sub { return $1; },
>      },
> +    { regexp   => qr/OSSL_DEPRECATEDIN_\d+_\d+(?:_\d+)?_FOR<<<.*>>>(.*)/,
> +      massager => sub { return $1; },
> +    },
>      { regexp   => qr/(.*?)\s+OSSL_DEPRECATEDIN_\d+_\d+(?:_\d+)?\s+(.*)/,
>        massager => sub { return "$1 $2"; },
>      },
> +    { regexp   => qr/(.*?)\s+OSSL_DEPRECATEDIN_\d+_\d+(?:_\d+)?_FOR<<<.*>>>(.*)/,
> +      massager => sub { return "$1 $2"; },
> +    },
>  
>      #####
>      # Core stuff
> ```

Yes, of course. Thanks!

2024-05-17 11:56 UTC, kanavin commented
Alright, I hopefully have addressed both CI fails and review comments.

2024-05-17 13:34 UTC, mattcaswell requested changes

2024-05-17 13:34 UTC, mattcaswell commented on include/openssl/ssl.h.in
> +void SSL_CTX_flush_sessions(SSL_CTX *ctx, time_t tm);
I think you mean SSL_CTX_flush_sessions_ex

2024-05-20 07:24 UTC, t8m commented
**OTC: Do we want to deprecate SSL_SESSION_get_time()/SSL_SESSION_set_time()/SSL_CTX_flush_sessions() in 3.4 or at some later point?**

2024-05-28 08:57 UTC, t8m commented
**OTC: We are OK with deprecating these functions in 3.4.**

2024-05-28 10:44 UTC, mattcaswell approved these changes

2024-05-28 11:44 UTC, t8m approved these changes

2024-05-29 12:18 UTC, mattcaswell commented
Ah....there's actually a problem with the review of this which I didn't spot until `addrev` complained when adding the reviewed-by headers prior to merge. I cannot review because I contributed one of the commits (or rather I can review and approve the commits I didn't author, but not the one I did).

@nhorman or @levitte - could you provide the missing review?

2024-05-29 12:59 UTC, nhorman approved these changes

2024-05-30 14:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-05-30 16:33 UTC, t8m commented
Merged to the master branch. Thank you for your contribution.

2024-05-30 16:33 UTC, closed without merging