Set the server sig algs before calling the session_secret_cb
openssl/openssl pull request #24309
Opened 2024-04-30 15:04 UTC by mattcaswell

Setting the server sig algs sets up the certificate "s3->tmp.valid_flags".
These are needed when calling ssl3_choose_cipher() which can happen
immediately after calling the session_secret_cb

Fixes https://github.com/openssl/openssl/issues/24213

The sessions_secret_cb was undocumented and untested - so we also add a test case and add a man page for it.

2024-04-30 15:34 UTC, nhorman approved these changes

2024-05-01 10:26 UTC, mattcaswell commented
> CI is relevant

Fixed (hopefully)

2024-05-01 12:23 UTC, nhorman approved these changes

2024-05-01 13:02 UTC, beldmit approved these changes
LGTM

2024-05-01 13:47 UTC, t8m requested changes
Just one doc style nit.

2024-05-01 13:47 UTC, t8m commented on doc/man3/SSL_set_session_secret_cb.pod
> +argument that was provided to the original SSL_set_session_secret_cb() call.
Please use `I<argument>` and `B<SSL_SESSION>` in this text.

2024-05-02 15:46 UTC, t8m approved these changes

2024-05-02 15:46 UTC, t8m commented
@beldmit @nhorman please reconfirm

2024-05-02 15:56 UTC, beldmit commented
My approval persists

2024-05-02 15:59 UTC, nhorman commented
Approval holds

2024-05-06 08:45 UTC, t8m commented
Merged to the master, 3.3 and 3.2 branches. Thank you.

2024-05-06 08:45 UTC, closed without merging