update configurable sigalgs documentation for providers
openssl/openssl pull request #24499
Opened 2024-05-27 06:24 UTC by baentsch

Since OpenSSL 3.2, providers can change the list of supported TLS signature algorithms. This documentation update makes this explicit providing reference to the mechanism.

This may be made even more clear by referencing the `openssl list -signature-algorithms` command -- but I'm unsure whether this is desirable in this section of the documentation. Glad to update the PR if anyone thinks so.

2024-05-27 08:55 UTC, mattcaswell requested changes
Looks good. One very minor nit.

2024-05-27 08:55 UTC, mattcaswell commented on doc/man3/SSL_CONF_cmd.pod
> +B<signature_scheme>. For the default providers shipped with OpenSSL,B<algorithm>
nit: missing space after `,`

2024-05-27 09:10 UTC, baentsch commented on doc/man3/SSL_CONF_cmd.pod
> +B<signature_scheme>. For the default providers shipped with OpenSSL,B<algorithm>
fixed. Plus two further typos fixed.

2024-05-27 09:14 UTC, mattcaswell approved these changes

2024-05-28 02:56 UTC, tmshort approved these changes
LGTM

2024-05-28 18:02 UTC, shahsb approved these changes

2024-05-29 03:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-05-29 07:40 UTC, t8m commented
Squashed and merged to the master, 3.3 and 3.2 branches. Thank you for your contribution.

2024-05-29 07:40 UTC, closed without merging