DTLS 1.3: Run 70-test_tls13alerts.t with dtls
openssl/openssl pull request #24525
Opened 2024-05-29 09:05 UTC by fwh-dc

##### Checklist
- [x] tests are added or updated

2024-06-04 13:08 UTC, fwh-dc commented
@t8m @mattcaswell This one is ready for review.

2024-06-05 13:47 UTC, t8m requested changes

2024-06-06 08:25 UTC, t8m commented on test/recipes/70-test_tls13hrr.t
> +        skip "TODO: When ECX is disabled running this test with DTLS will hang"
@fwh-dc This seems still outstanding. Please do not use plain TODO.

2024-06-10 13:07 UTC, t8m approved these changes

2024-06-11 11:33 UTC, vdukhovni approved these changes
LGTM, with perhaps a minor nit (debug printf?)

2024-06-11 11:33 UTC, vdukhovni commented on test/recipes/70-test_tls13hrr.t
> +            printf("FWH:: askldj");
Is this `printf` residual debugging?

2024-06-12 07:43 UTC, vdukhovni approved these changes

2024-06-17 08:40 UTC, t8m approved these changes

2024-06-18 09:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-06-18 10:03 UTC, t8m commented
Merged to the feature branch. Thank you for your contribution.

2024-06-18 10:03 UTC, closed without merging