feat: add delegatedNameConstraints and holderNameConstraints exts
openssl/openssl pull request #24664
Opened 2024-06-17 21:43 UTC by JonathanWilbur

Adds support for the `delegatedNameConstraints` and `holderNameConstraints` X.509v3 extensions, as specified in ITU-T Recommendation X.509 for usage in attribute certificates. Both of these extensions have the same syntax as the `nameConstraints` syntax already supported by OpenSSL, so I added both of these extensions to `v3_ncons.c`, as is customary with other extensions of like syntax.

##### Checklist
- [x] tests are added or updated

2024-06-17 22:50 UTC, JonathanWilbur commented
I believe the test failure is specious and has nothing to do with my PR.

2024-06-18 10:21 UTC, t8m requested changes

2024-06-18 10:21 UTC, t8m commented on test/certs/ext-delegatedNameConstraints.pem
> +-----END CERTIFICATE-----
Please add an EOL

2024-06-18 10:21 UTC, t8m commented on test/certs/ext-holderNameConstraints.pem
> +-----END CERTIFICATE-----
Same as above

2024-06-18 11:00 UTC, JonathanWilbur commented on test/certs/ext-delegatedNameConstraints.pem
> +-----END CERTIFICATE-----
Fixed.

2024-06-18 12:13 UTC, JonathanWilbur commented
Feedback addressed and ready for review.

2024-06-18 13:45 UTC, t8m approved these changes

2024-06-18 15:11 UTC, JonathanWilbur commented
@nhorman Would you be interested in reviewing this one?

2024-06-18 17:36 UTC, nhorman approved these changes

2024-06-20 17:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-06-20 17:59 UTC, t8m commented
Squashed and merged to the master branch. Thank you for your contribution.

2024-06-20 17:59 UTC, closed without merging