feat: add acceptablePrivilegePolicies and acceptableCertPolicies exts
openssl/openssl pull request #24663
Opened 2024-06-17 18:26 UTC by JonathanWilbur

This PR implements the `acceptablePrivilegePolicies` and `acceptableCertPolicies` extensions defined in ITU-T Recommendation X.509 for use in attribute certificates.

Their syntax is the same as `extendedKeyUsage`, so I lumped them in with that file, as is done for other extensions of like syntax elsewhere, but I would be happy to break it out if requested. I also didn't include tests because it seems like a trivial PR. Just for safety, I did manually test once with certificates I created. I would be happy to add tests as well as the certs.

2024-06-17 18:31 UTC, nhorman commented
@JonathanWilbur I'm sorry I don't have it in front of me, please let the issue number you were doing this work against so we can link it here please

2024-06-17 18:35 UTC, JonathanWilbur commented
Oh, I don't think there is an issue for it. Do you want me to make one? This is a standard extension defined in X.509 itself, so I think there's good cause to support it.

2024-06-17 18:37 UTC, nhorman commented
No, thats fine, I just remember seeing your name as I was triaging our issue list and thought this one related to one of the issue, if there is no issue, thats fine

2024-06-17 18:40 UTC, JonathanWilbur commented
I am working on another PR to implement `holderNameConstraints`, which has the same syntax as `nameConstraints`, and I planned to put the extension in the `nameConstraints` file (`v3_ncons.c`) as done in [this fork PR](https://github.com/TrustedComputingGroup/openssl/pull/17/files). Is this still acceptable, or do I need to put all extensions in separate files from here on out?

2024-06-17 18:50 UTC, nhorman commented
I think thats up to you.  Creating separate PRs for different extensions makes logical sense to me from a review standpoint, but if adding multiple extensions have some logical connection, thats fine too

2024-06-24 20:24 UTC, JonathanWilbur commented
I added tests after all.

2024-06-24 21:21 UTC, nhorman commented
It looks like you have a merge commit in here. Can you rebase to eliminate that please?

2024-06-24 23:31 UTC, JonathanWilbur commented
Okay, I rebased and force-pushed.

2024-06-25 07:33 UTC, nhorman approved these changes

2024-06-25 08:58 UTC, t8m requested changes

2024-06-25 08:58 UTC, t8m commented on test/certs/ext-acceptableCertPolicies.pem
> +-----END CERTIFICATE-----
Please add EOL at the end of the file.

2024-06-25 08:58 UTC, t8m commented on test/certs/ext-acceptablePrivilegePolicies.pem
> +-----END CERTIFICATE-----
Same as above

2024-06-25 10:22 UTC, t8m approved these changes
Assuming @nhorman's approval holds.

2024-06-26 11:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-06-26 13:01 UTC, t8m commented
Partially squashed and merged to the master branch. Thank you for your contribution.

2024-06-26 13:01 UTC, closed without merging