Replace and Deprecate TS_VERIFY_CTX Functions and Add Documentation
openssl/openssl pull request #24701
Opened 2024-06-21 13:25 UTC by erbsland-dev

This pull request addresses two main areas related to the `TS_VERIFY_CTX` functions:

## 1. Replace and Deprecate Functions

Fixes #18854 by replacing and deprecating the following functions due to poorly documented memory handling, which could lead to memory leaks:
- `TS_VERIFY_CTX_set_data`
- `TS_VERIFY_CTX_set_store`
- `TS_VERIFY_CTX_set_certs`
- `TS_VERIFY_CTX_set_imprint`

These functions are replaced with:
- `TS_VERIFY_CTX_set0_data`
- `TS_VERIFY_CTX_set0_store`
- `TS_VERIFY_CTX_set0_certs`
- `TS_VERIFY_CTX_set0_imprint`

Updates have been made to existing code to use the new function calls instead of the deprecated ones.

### 2. Add and Update Documentation
- Mark the existing `TS_VERIFY_CTX_set_certs` function as deprecated in the documentation.
- Add missing documentation for the deprecated functions:
  - `TS_VERIFY_CTX_set_data`
  - `TS_VERIFY_CTX_set_imprint`
  - `TS_VERIFY_CTX_set_store`
- Write missing documentation for the following functions:
  - `TS_VERIFY_CTX_new`
  - `TS_VERIFY_CTX_init`
  - `TS_VERIFY_CTX_free`
  - `TS_VERIFY_CTX_cleanup`
  - `TS_VERIFY_CTX_set_flags`
  - `TS_VERIFY_CTX_add_flags`
  - `TS_VERIFY_CTX_set0_data`
  - `TS_VERIFY_CTX_set0_imprint`
  - `TS_VERIFY_CTX_set0_store`
  - `TS_VERIFY_CTX_set0_certs`

These changes improve memory management, enhance future extensibility, and provide clearer usage guidelines through updated and additional documentation.

- [x] documentation is added or updated

2024-06-21 14:01 UTC, nhorman commented
@erbsland-dev looks like there are a few minor doc nits to correct

2024-06-21 19:00 UTC, erbsland-dev commented
@nhorman I fixed the documentation issues.

2024-06-21 19:28 UTC, nhorman approved these changes

2024-06-23 15:31 UTC, shahsb approved these changes

2024-06-24 12:53 UTC, t8m requested changes
Good work!

2024-06-24 12:53 UTC, t8m commented on doc/man3/TS_VERIFY_CTX.pod
> +
Nit: please drop this extra empty line

2024-06-24 12:53 UTC, t8m commented on doc/man3/TS_VERIFY_CTX.pod
> +
Please drop this empty line

2024-06-24 12:53 UTC, t8m commented on include/openssl/ts.h
> +OSSL_DEPRECATEDIN_3_4_FOR("Memory usage was not defined, replace with TS_VERIFY_CTX_set0_imprint().")
I'd suggest not putting the deprecation reason into the message. Or at least make it shorter `Unclear semantics, replace with...`.

2024-06-24 12:53 UTC, t8m commented on include/openssl/ts.h
> +OSSL_DEPRECATEDIN_3_4_FOR("Previous ctx data was not released, replace with TS_VERIFY_CTX_set0_store().")
As above

2024-06-24 12:53 UTC, t8m commented on include/openssl/ts.h
> +OSSL_DEPRECATEDIN_3_4_FOR("Previous ctx data was not released, replace with TS_VERIFY_CTX_set0_certs().")
As above

2024-06-24 12:53 UTC, t8m commented on doc/man3/TS_VERIFY_CTX.pod
> +For all the following methods, unless noted otherwise, B<ctx> is the
I know you're just copying the page however as you're already touching this, could you please use `I<ctx>` and similarly elsewhere throughout the manpage where names of arguments are referenced?

2024-06-24 12:54 UTC, t8m commented
(Tests exempted because we do not have any TS subsystem testcases at all yet.)

2024-07-02 18:26 UTC, t8m commented
@erbsland-dev Could you please also rebase this to resolve the conflict?

2024-07-02 20:00 UTC, erbsland-dev commented
@t8m Sure, I'll do it, but it probably won't be until the weekend.

2024-07-06 13:35 UTC, erbsland-dev commented
@t8m I just rebased the pull request to the latest master. Could you please review how I merged `util/libcrypto.num`? I’m not entirely sure I did it correctly.

2024-07-06 15:18 UTC, erbsland-dev commented
@t8m Rebasing done and I integrated all your change requests.

2024-07-08 09:45 UTC, t8m approved these changes
@nhorman please reconfirm your approval

2024-07-08 11:22 UTC, nhorman commented
approval holds

2024-07-09 17:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-07-10 07:41 UTC, closed without merging

2024-07-10 07:41 UTC, t8m commented
Merged to the master branch after reformatting the commit messages. Thank you for your contribution.