free'ing appname if it was set after initializing crypto.
openssl/openssl pull request #24730
Opened 2024-06-25 14:54 UTC by sgzmd

Fixes: #24729

As proposed in #24729, we need to free appname after crypto finished initializing, iff it was set. We are checking `appname != NULL` rather than settings.appname -- this is equivalent at the moment but possibly could change later, so that `settings.appname` set prior to this code which may cause double-free.

CLA: trivial

##### Checklist
N/A

2024-06-25 16:18 UTC, nhorman commented
ok with trivial

2024-06-25 16:18 UTC, nhorman approved these changes

2024-06-25 17:12 UTC, sgzmd commented
Apologies for accidental re-review request, this is OK to merge.

2024-06-25 17:36 UTC, nhorman approved these changes

2024-06-25 19:55 UTC, t8m requested changes

2024-06-25 19:55 UTC, t8m commented on crypto/conf/conf_sap.c
> +    }
free() accepts NULL argument, please drop the `if`

2024-06-25 22:35 UTC, paulidale approved these changes

2024-06-25 22:35 UTC, paulidale commented
okay with trivial

2024-06-26 09:43 UTC, t8m approved these changes
Commits to be squashed and the merge commit dropped when merging.

OK with CLA: trivial

2024-06-26 09:53 UTC, sgzmd commented
> Commits to be squashed and the merge commit dropped when merging.
Done

2024-06-26 12:45 UTC, bernd-edlinger commented
Thanks, but could you also reword the commit message to reflect the latest version?

2024-06-26 12:49 UTC, sgzmd commented
> Thanks, but could you also reword the commit message to reflect the latest version?

Done

2024-06-26 13:03 UTC, t8m commented
This was just a squash and reword of the commit message -> approval: done stands.

2024-06-26 13:49 UTC, nhorman commented
ack, approval holds

2024-06-26 14:24 UTC, bernd-edlinger approved these changes
LGTM

2024-06-26 23:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been  updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2024-06-27 17:51 UTC, t8m commented
Merged to all the active branches with slightly reworded commit message. Thank you for your contribution.

2024-06-27 17:51 UTC, closed without merging