Check sk_X509_value result before dereference
openssl/openssl pull request #24760
Opened 2024-06-28 09:45 UTC by JohnnySavages

`issuer` passed as second parameter to `check_issued` may result in NULL dereference

Found by Linux Verification Center (linuxtesting.org) with SVACE.

CLA: trivial

2024-06-28 13:05 UTC, t8m requested changes
Please revert the changes to return values of the check_revocation and check_cert functions. They have a defined semantics which cannot be changed. Please see https://www.openssl.org/docs/manmaster/man3/X509_STORE_CTX_check_revocation_fn.html

2024-06-28 13:07 UTC, t8m commented on crypto/x509/x509_vfy.c
> +
BTW this is a _cannot happen_ condition however it makes some sense to check it anyway for clarity.

2024-07-26 07:56 UTC, JohnnySavages commented on crypto/x509/x509_vfy.c
> +
Сorrected.

2024-08-24 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/otc but the last update was 30 days ago

2024-09-06 14:12 UTC, t8m approved these changes

2024-09-08 23:27 UTC, paulidale approved these changes

2024-09-09 13:16 UTC, hlandau approved these changes

2024-09-10 00:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-09-10 06:16 UTC, t8m commented
OK with CLA trivial. @paulidale @hlandau are you OK with CLA: trivial?

2024-09-24 08:01 UTC, hlandau commented
> OK with CLA trivial. @paulidale @hlandau are you OK with CLA: trivial?

Yes.

2024-09-24 15:41 UTC, t8m commented
Merged to the master branch. Thank you for your contribution.

2024-09-24 15:41 UTC, closed without merging