Add documentation for deprecated CMAC_CTX functions
openssl/openssl pull request #24814
Opened 2024-07-08 13:04 UTC by erbsland-dev

Fixes #5539: Create a new manual page `CMAC_CTX.pod` documenting the deprecated `CMAC_CTX` functions and add the necessary build dependencies. This page includes function descriptions, usage details, and replacement suggestions with the `EVP_MAC` interface.

- [x] documentation is added or updated

2024-07-08 14:24 UTC, mattcaswell requested changes
Good work!

Please also update util/missingcrypto.txt to remove from that file the list of functions that you have now documented. I'm actually slightly surprised that the CI did not complain about not doing this.

2024-07-08 14:24 UTC, mattcaswell commented on doc/man3/CMAC_CTX.pod
> +stored in the provided variable.
Important to note is that you can call `CMAC_Final` with a NULL output buffer, and the output length will still be stored, i.e. so you can call it twice - once to decide how big a buffer you need to allocate, then you allocate it and call it again.

2024-07-08 15:18 UTC, mattcaswell approved these changes

2024-07-08 19:21 UTC, t8m approved these changes
Good work!

2024-07-09 20:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-07-10 07:47 UTC, t8m commented
Merged to the master branch. Thank you for your contribution.

2024-07-10 07:47 UTC, closed without merging