Ensure cmd from fuzz buffer is always valid
openssl/openssl pull request #24827
Opened 2024-07-09 19:49 UTC by nhorman

The quic-srtm fuzzer uses a loop in which an integer command is extracted from the fuzzer buffer input to determine the action to take, switching on the values between 0 and 3, and ignoring all other commands.  Howver in the failing fuzzer test case here: https://oss-fuzz.com/testcase-detail/5618331942977536

The buffer provided shows a large number of 0 values (indicating an SRTM add command), and almost no 1, 2, or 3 values.  As such, the fuzzer only truly exercises the srtm add path, which has the side effect of growing the SRTM hash table unboundedly, leading to a timeout when 10 entries need to be iterated over when the hashtable doall command is executed.

Fix this by ensuring that the command is always valid, and reasonably distributed among all the operations with some modulo math.

Introducing this change bounds the hash table size in the reproducer test case to less than half of the initially observed size, and avoids the timeout.

Fixes openssl/project#679

2024-07-10 07:23 UTC, kroeckx commented
I don't see how this fixes anything. As far as I can see, it can still generate as many add commands as it wants. And the other values seem to be ignored anyway.

2024-07-10 10:26 UTC, mattcaswell commented
See #24831 where a similar issue in the lcidm is addressed in a different way.

2024-07-15 13:41 UTC, Sashan requested changes

2024-07-15 13:41 UTC, Sashan commented on fuzz/quic-srtm.c
> +        switch (cmd % CMD_MAX) {
I agree with @kroeckx and @mattcaswell, this change (modulo) operation should be combined with stuff found in [#24831](https://github.com/openssl/openssl/pull/24831)

2024-07-15 15:12 UTC, t8m approved these changes

2024-07-16 13:07 UTC, Sashan approved these changes
I'm fine with those changes, thanks.

2024-07-23 12:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-07-23 13:29 UTC, nhorman commented
merged

2024-07-23 13:29 UTC, closed without merging