Fix memory leak in `EVP_MD_CTX_free`
openssl/openssl pull request #24829
Opened 2024-07-10 07:20 UTC by erbsland-dev

Fixes #6343: Addressed a memory leak in the `EVP_MD_CTX_free` function. The issue occurred when `EVP_MD_CTX_free` called `EVP_MD_CTX_reset` to release the context's memory before freeing the context itself. If the context had the `EVP_MD_CTX_FLAG_REUSE` flag set, the memory was not properly freed. By clearing the flag before calling the reset function, this problem is resolved.

2024-07-10 08:27 UTC, beldmit commented
See also #17255

2024-07-10 12:44 UTC, nhorman approved these changes

2024-07-10 13:02 UTC, t8m commented
Tests exempted because this is an arcane legacy feature.

2024-07-10 13:03 UTC, t8m approved these changes

2024-07-10 13:08 UTC, erbsland-dev commented
@t8m 

> Tests exempted because this is an arcane legacy feature.

I’m relieved to hear that. Writing a test for this would have been very tricky.

2024-07-10 14:44 UTC, bernd-edlinger commented
Note this is flag is supposed to be used internally only.  Making this a fully supported API opens a can of worms.
e.g. If I suppose the flag may already be set by the caller here:
https://github.com/openssl/openssl/blob/eaf577c865c41946b478b4da5f8c477e132d470d/crypto/evp/digest.c#L676-L681
Then you must of course also clear the flag when the else branch is taken, otherwise we have the next memory leak.

2024-07-10 15:31 UTC, t8m commented
> Note this is flag is supposed to be used internally only. Making this a fully supported API opens a can of worms. e.g. If I suppose the flag may already be set by the caller here:
> 
> https://github.com/openssl/openssl/blob/eaf577c865c41946b478b4da5f8c477e132d470d/crypto/evp/digest.c#L676-L681
> 
> Then you must of course also clear the flag when the else branch is taken, otherwise we have the next memory leak.

OK then @bernd-edlinger, what do you suggest as an alternative fix?

2024-07-10 15:32 UTC, t8m commented
BTW, I do not think this PR makes the flag a fully supported API.

2024-07-10 15:50 UTC, erbsland-dev commented
@bernd-edlinger, I would like to fully understand your argument.

Before writing this PR, I reviewed this particular part of the code and checked all use cases of the `EVP_MD_CTX_FLAG_REUSE` flag. At the point where `EVP_MD_CTX_reset` is called, not `EVP_MD_CTX_free`, the context still exists, and the user is still required to call `EVP_MD_CTX_free` on `out` at a later point. Therefore, I did not see potential for a memory leak here, but I may be mistaken.

The documentation for `EVP_MD_CTX_reset` states: "Resets the digest context I<ctx>. This can be used to reuse an already existing context." It does not mention if and how the `reset` function frees resources.

Since a call to `EVP_MD_CTX_free` is still required on the context, and this method uses `reset` internally to free its resources before the context is freed, it seems reasonable to reset `EVP_MD_CTX_FLAG_REUSE` to make the implementation work as expected.

Could you please explain how exactly this leads to another memory leak? I appreciate your insights and want to ensure we address any potential issues correctly.

2024-07-10 17:28 UTC, bernd-edlinger commented
@erbsland-dev the only mention of this flag is in doc/man3/EVP_DigestInit.pod, line 555:
https://github.com/openssl/openssl/blob/45cada1339bacc81765b02367bdbaf878445081d/doc/man3/EVP_DigestInit.pod#L555

So currently it looks like the only place where it is designed ever to be used is here:
https://github.com/openssl/openssl/blob/45cada1339bacc81765b02367bdbaf878445081d/crypto/evp/digest.c#L676-L682

Note if you want to fix that flag, you need to have an idea why it should be used outside of this context.
So you need at least an idea what it is good for, but look at the memcpy in line 682.
What If you do something like this
```C
out = EVP_MD_CTX_dup(x);
EVP_MD_CTX_set_flags(out, EVP_MD_CTX_FLAG_REUSE);
EVP_MD_CTX_copy(out, y);
```

So, if I suppose, that `x`, and `y` may have different digest parameters, then the else branch above will be taken,
the `EVP_MD_CTX_reset(out)` will not clear the `md_data`, the memory pointed to by `md_data` will be lost.
Right?  Or did I miss anything?

So if we encourage people to use that flag for their purpose, we should at least try to fix it really, so at least say
add an `EVP_MD_CTX_clear_flags(out, EVP_MD_CTX_FLAG_REUSE)` in the else path, but since I just stared
for 5 minutes at the code I am not really sure that this is the only possible surprise here.
Documenting that this flag is not supposed to be used in user code is of course another solution.

2024-07-10 18:40 UTC, erbsland-dev commented
@bernd-edlinger, thank you for clarifying. I understand your point now. I will take a closer look at the issue tomorrow and investigate how we can eliminate the problem caused by the flag.

2024-07-11 08:37 UTC, erbsland-dev commented
@t8m @bernd-edlinger I analyzed the code section and created a PR to eliminate the `EVP_MD_CTX_FLAG_REUSE` flag completely.

In this PR, I introduced an internal "take" function to extract the `md_data` from the context and nullify the internal pointer. This approach prevents the memory from being cleaned up prematurely and allows it to be reused after copying the context.

My only concern was regarding the `cleanup` method of the digest algorithm. However, this method should expect an already cleaned context where `md_data` is set to null. Therefore, this change should not cause any issues, especially considering this is a legacy branch that will eventually be removed from the code.

I’d appreciate any feedback or suggestions you might have on this approach. Thanks!

2024-07-11 09:21 UTC, t8m commented
Keep this PR as is, please. There is nowhere said the flag is supposed to be used in user code and this PR does NOT change this.

>  Documenting that this flag is not supposed to be used in user code is of course another solution.

Yeah, if you want, you can add more documentation in the sense that the flag is internal and must not be set explicitly by user code.

2024-07-11 11:45 UTC, erbsland-dev commented
@t8m No worries, I won’t update this PR further.

I agree that adding documentation for the internal flags, clearly stating that they are internal and must not be used in user code, would help prevent misunderstandings and misuse. In my experience, developers often rely on code completion in their IDEs, where these flags appear and may seem usable.

2024-07-11 14:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been  updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2024-07-11 14:12 UTC, t8m commented
@nhorman please reconfirm

2024-07-11 14:13 UTC, nhorman commented
ACK, approval holds

2024-07-11 14:53 UTC, beldmit approved these changes
LGTM

2024-07-12 08:03 UTC, bernd-edlinger requested changes
Well, if you want to go that way, how about fixing the possible memory leak I pointed out
previously like this:
```
diff --git a/crypto/evp/digest.c b/crypto/evp/digest.c
index 4c61ca4c42..a96b885317 100644
--- a/crypto/evp/digest.c
+++ b/crypto/evp/digest.c
@@ -673,6 +673,7 @@ int EVP_MD_CTX_copy_ex(EVP_MD_CTX *out, const EVP_MD_CTX *in)
     }
 #endif
 
+    EVP_MD_CTX_clear_flags(out, EVP_MD_CTX_FLAG_REUSE);
     if (out->digest == in->digest) {
         tmp_buf = out->md_data;
         EVP_MD_CTX_set_flags(out, EVP_MD_CTX_FLAG_REUSE);
```

2024-07-12 08:37 UTC, erbsland-dev commented
@bernd-edlinger Just to clarify, my fix is not about the reported misuse of the internal flag, but rather about addressing the potential memory leak it uncovered.

When I analyzed the code, I found that the `EVP_MD_CTX_FLAG_REUSE` flag is set but never cleared, which I believe is an oversight. This means that any context created by `EVP_MD_CTX_copy_ex` using the legacy code has this flag permanently set.

Initially, I considered clearing the flag right after the `EVP_MD_CTX_reset` call. However, that could have potentially impacted old user code that relied on the flag being set after the `EVP_MD_CTX_copy_ex` call.

Therefore, I decided to clear the flag in the `EVP_MD_CTX_free` method. This approach does not aim to prevent misuse of the flag but rather to minimize the impact on user code while addressing the memory leak.

2024-07-12 08:57 UTC, bernd-edlinger commented
> When I analyzed the code, I found that the EVP_MD_CTX_FLAG_REUSE flag is set but never cleared, which I believe is an oversight. This means that any context created by EVP_MD_CTX_copy_ex (with an identical digest) using the legacy code has this flag permanently set.

No, your conclusion is wrong, the flag is overwritten after use in the memcpy here:
https://github.com/openssl/openssl/blob/861e1f450c808bdf675bbf0d3e17303a3f16d06c/crypto/evp/digest.c#L682

2024-07-12 09:10 UTC, erbsland-dev commented
@bernd-edlinger 
> No, your conclusion is wrong, the flag is overwritten after use in the memcpy here:

Thank you for pointing that out. I completely missed it. Apologies for taking so long to realize it. Now I understand what you mean.

2024-07-12 13:43 UTC, erbsland-dev commented
@t8m It took me a while to fully understand @bernd-edlinger's argument, as I initially missed the line where the flag gets cleared. After reviewing the situation in more detail, I realize that the current PR only partially addresses the issue with the `EVP_MD_CTX_FLAG_REUSE` flag.

I propose two options:
1. Remove the code change and simply add documentation stating that these flags must not be used by user code.
2. Fully address the issue by preventing the internal flag from being used via the user API.

For the second option, more code changes would be necessary:

```diff
diff --git a/crypto/evp/digest.c b/crypto/evp/digest.c
index 18a64329b7..1a26d77b28 100644
--- a/crypto/evp/digest.c
+++ b/crypto/evp/digest.c
@@ -98,6 +98,8 @@ static int evp_md_ctx_reset_ex(EVP_MD_CTX *ctx, int keep_fetched)
 /* This call frees resources associated with the context */
 int EVP_MD_CTX_reset(EVP_MD_CTX *ctx)
 {
+    if (ctx != NULL)
+        EVP_MD_CTX_clear_flags(ctx, EVP_MD_CTX_FLAG_REUSE);
     return evp_md_ctx_reset_ex(ctx, 0);
 }
 
@@ -627,6 +629,7 @@ int EVP_MD_CTX_copy_ex(EVP_MD_CTX *out, const EVP_MD_CTX *in)
         return 0;
     }
 
+    EVP_MD_CTX_clear_flags(out, EVP_MD_CTX_FLAG_REUSE);
     evp_md_ctx_reset_ex(out, 1);
     digest_change = (out->fetched_digest != in->fetched_digest);
     if (digest_change && out->fetched_digest != NULL)
@@ -673,12 +676,13 @@ int EVP_MD_CTX_copy_ex(EVP_MD_CTX *out, const EVP_MD_CTX *in)
     }
 #endif
 
+    EVP_MD_CTX_clear_flags(out, EVP_MD_CTX_FLAG_REUSE);
     if (out->digest == in->digest) {
         tmp_buf = out->md_data;
         EVP_MD_CTX_set_flags(out, EVP_MD_CTX_FLAG_REUSE);
     } else
         tmp_buf = NULL;
-    EVP_MD_CTX_reset(out);
+    evp_md_ctx_reset_ex(out, 0);
     memcpy(out, in, sizeof(*out));
 
     /* copied EVP_MD_CTX should free the copied EVP_PKEY_CTX */
 ```

- Move the flag reset code into the `EVP_MD_CTX_reset` function to prevent any use of the flag from user code. (maybe also move the NULL check to this point).
- Reset the flag prior to calling the internal function `evp_md_ctx_reset_ex` in the necessary places.
- This approach ensures that there is only a single, narrow branch of code where the flag is actually used.

This solution should resolve any potential memory leak caused by the flag, although it does add more code to the library.

Could you please provide your feedback on these options?

2024-07-12 13:47 UTC, t8m commented
Then I prefer adding just the docfix.

2024-07-12 13:59 UTC, t8m commented
Merged to all the active branches. Thank you for your patience.

2024-07-12 13:59 UTC, closed without merging