Ext battrcons
openssl/openssl pull request #24847
Opened 2024-07-10 22:33 UTC by JonathanWilbur

This PR adds support for the `basicAttConstraints` X.509v3 extension defined in ITU-T Recommendation X.509 for usage in attribute certificates. This is _different from, but similiar to_ the `basicConstraints` X.509v3 extension.

##### Checklist
- [x] documentation is added or updated
- [x] tests are added or updated

2024-07-10 22:43 UTC, JonathanWilbur commented
My PR is failing on style checks. I don't think it is possible for me to fix the styling problem: either I indent the arguments to those functions to column 61 and then the names overflow the 80-character column limit, or I indent them less to avoid it, which violates the rule. How do I proceed?

2024-07-11 01:54 UTC, JonathanWilbur commented
Alternatively, I _could_ just put this in the same file as `basicConstraints`, since it uses the _exact same syntax_.

2024-07-11 08:19 UTC, mattcaswell commented
> My PR is failing on style checks.

The style checking is new and somewhat experimental. Its currently coming up with quite a few false positives. Adding "style: waived"

2024-07-11 08:48 UTC, t8m requested changes

2024-07-11 08:48 UTC, t8m commented on test/certs/ext-basicAttConstraints.pem
> +-----END CERTIFICATE-----
Please add the missing EOL

2024-07-11 08:48 UTC, t8m commented on crypto/x509/build.info
> +        v3_usernotice.c v3_bacons.c
Nit: As bacon is a real word meaning something completely else, could you please avoid using this abbreviation? I.e. bacons -> battcons or something like that everywhere.

2024-07-11 08:48 UTC, t8m commented on crypto/x509/v3_bacons.c
> +    OSSL_BASIC_ATTR_CONSTRAINTS *bcons,
Here bcons is used, battcons would be better IMO

2024-07-11 13:26 UTC, JonathanWilbur commented
All feedback addressed and ready for review. I am pretty sure the one check failure (other than the code style, I mean) is unrelated to my changes.

2024-07-11 14:18 UTC, t8m commented
All seems good except there is a merge commit. Could you please rebase to drop it?

2024-07-11 19:52 UTC, JonathanWilbur commented
All feedback addressed and ready for review again. @nhorman would you be interested in reviewing this?

2024-07-11 19:57 UTC, t8m approved these changes

2024-07-14 23:49 UTC, JonathanWilbur commented
@mattcaswell would you have any interest in reviewing this one?

2024-07-16 14:27 UTC, JonathanWilbur commented
@t-j-h Would you be interested in reviewing this one, since it only needs one more approval?

2024-07-19 14:30 UTC, JonathanWilbur commented
@t8m It seems like a lot of people that are usually responsive are not. This can't be a coincidence. Is everybody busy with the OpenSSL issues cleanup?

2024-07-19 14:43 UTC, FdaSilvaYY reviewed
👍

2024-07-19 14:43 UTC, FdaSilvaYY commented on crypto/x509/v3_battcons.c
> + * Copyright 1999-2021 The OpenSSL Project Authors. All Rights Reserved.
nit: Just 2024

2024-07-19 14:43 UTC, FdaSilvaYY commented on crypto/x509/v3_battcons.c
> +    *extlist);
nit : unneeded line break.

2024-07-19 14:43 UTC, FdaSilvaYY commented on crypto/x509/v3_battcons.c
> +        ASN1_OPT(OSSL_BASIC_ATTR_CONSTRAINTS, authority, ASN1_FBOOLEAN),
nit:  one indent is enough ?

2024-07-19 14:43 UTC, FdaSilvaYY commented on crypto/x509/v3_battcons.c
> +    STACK_OF(CONF_VALUE)
nit useless line break.

2024-07-19 15:35 UTC, t8m commented
> @t8m It seems like a lot of people that are usually responsive are not. This can't be a coincidence. Is everybody busy with the OpenSSL issues cleanup?

More likely people are on vacations, etc.

2024-07-20 13:39 UTC, nhorman approved these changes

2024-07-20 20:08 UTC, JonathanWilbur commented
@t8m @nhorman @FdaSilvaYY , all feedback addressed and this is ready for review again. (Just a few trivial style changes.)

2024-07-23 19:30 UTC, JonathanWilbur commented
Is this able to receive the `approval: done` label yet?

2024-07-23 19:33 UTC, nhorman commented
yep, has acks from myself and @t8m.  Not sure why the automation didn't flag it.

2024-07-24 20:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-07-24 20:37 UTC, nhorman commented
pushed to master, thank you!

2024-07-24 20:37 UTC, closed without merging