Fix coverity-1604666
openssl/openssl pull request #24896
Opened 2024-07-15 18:32 UTC by nhorman

Coverity recently flaged an error in which the return value for EVP_MD_get_size wasn't checked for negative values prior to use, which can cause underflow later in the function.

Just add the check and error out if get_size returns an error.

Fixes openssl/private#566

2024-07-15 20:44 UTC, t8m requested changes

2024-07-15 20:44 UTC, t8m commented on crypto/rsa/rsa_oaep.c
> +    if (tlen <= 0 || flen <= 0 || mdlen < 0)
Please use `mdlen <= 0` as there is no point in digest with zero length and we have the same checks elsewhere.

2024-07-15 22:17 UTC, paulidale approved these changes

2024-07-16 13:08 UTC, t8m approved these changes

2024-07-17 14:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-07-17 14:32 UTC, t8m commented
Merged to all the active branches. Thank you.

2024-07-17 14:32 UTC, closed without merging