Eckeygen fips check
openssl/openssl pull request #25008
Opened 2024-07-26 04:08 UTC by slontis

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

2024-07-26 04:09 UTC, slontis commented
Still in draft form..

2024-07-30 04:44 UTC, slontis commented
The first commit should be ignored (it is included by on #24978)

Should be rebased after https://github.com/openssl/openssl/pull/24978 is merged

2024-07-30 04:53 UTC, slontis commented
Code style updates

2024-08-07 22:54 UTC, paulidale requested changes

2024-08-07 22:54 UTC, paulidale commented on doc/man7/EVP_PKEY-EC.pod
> +The following KeyGen settable parameter is also available for the OpenSSL FIPS
_key generation_ instead of _KeyGen_.

There is another instance of this on line 22 which could be updated too.

2024-08-08 06:50 UTC, slontis commented
Just did a rebase.

2024-08-09 02:01 UTC, paulidale approved these changes

2024-08-11 23:54 UTC, slontis commented
ping @openssl/committers

2024-08-14 18:49 UTC, nhorman approved these changes

2024-08-15 19:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-08-15 20:19 UTC, nhorman commented
merged to master, thank you!

2024-08-15 20:19 UTC, closed without merging