Add debuginfo build target
openssl/openssl pull request #25174
Opened 2024-08-13 19:18 UTC by nhorman

In the webinar we are currently producing on debugging openssl applications, we talk about ways to allow debugable binaries without having to ship all the debug DWARF information to production systems.

Add an optional target to do that DWARF separation to aid users

##### Checklist
- [x] documentation is added or updated

2024-08-13 21:25 UTC, t8m commented
Would you please consider extending some CI job with `make debuginfo` to check it?

2024-08-15 09:35 UTC, t8m approved these changes

2024-08-15 09:36 UTC, t8m commented
@nhorman I think this is worth adding CHANGES.md entry.

2024-08-15 18:09 UTC, t8m requested changes

2024-08-15 18:09 UTC, t8m commented on CHANGES.md
> + * Add debuginfo makefile target for unix platofms to produce
Either `make` or `Makefile`, also s/platofms/platforms/

2024-08-15 18:09 UTC, t8m commented on CHANGES.md
> +   a separated DWARF info file from the corresponding shared libs
s/separated/separate/ sounds better to me, also please add a dot at the end of the sentence.

2024-08-19 07:08 UTC, t8m approved these changes

2024-08-19 07:08 UTC, t8m commented
ping @openssl/committers for second review

2024-08-19 09:31 UTC, tom-cosgrove-arm approved these changes
LGTM

2024-08-21 13:50 UTC, t8m commented
Merged to the master branch. Thank you.

2024-08-21 13:50 UTC, closed without merging