feat: add support for the issuedOnBehalfOf X.509v3 extension
openssl/openssl pull request #25241
Opened 2024-08-20 23:29 UTC by JonathanWilbur

This PR adds support for the `issuedOnBehalfOf` X.509v3 extension defined in ITU-T Recommendation X.509. It's syntax is defined as:

```asn
issuedOnBehalfOf EXTENSION ::= {
  SYNTAX         GeneralName
  IDENTIFIED BY  id-ce-issuedOnBehalfOf }
```

##### Checklist
- [x] tests are added or updated

2024-08-21 07:49 UTC, Sashan requested changes
Thank you looks good to me. I have just minor/bikeshedding suggestion on `i2r_IOBO()`.

2024-08-21 11:37 UTC, JonathanWilbur commented on crypto/x509/v3_iobo.c
> +static int i2r_IOBO(X509V3_EXT_METHOD *method,
I fixed this. I also fixed the copyright year at the top of the file!

2024-08-21 11:51 UTC, Sashan approved these changes
Thank you for changing the function name.
all looks good to me.

2024-08-22 15:26 UTC, nhorman approved these changes
just the one copyright nit

2024-08-22 16:43 UTC, t8m commented on crypto/x509/v3_iobo.c
> + * Copyright 1999-2024 The OpenSSL Project Authors. All Rights Reserved.
This should be AFAIK just 2024

2024-08-23 09:14 UTC, t8m approved these changes

2024-08-23 09:14 UTC, t8m commented
Assuming @nhorman approval holds.

2024-08-23 11:38 UTC, nhorman commented
Ack, approval still good

2024-08-24 10:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been  updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2024-08-25 01:34 UTC, shahsb approved these changes
LGTM.

Do we need to add Documentation changes for this?

2024-08-26 16:25 UTC, JonathanWilbur commented
I fixed the merge conflict resulting from `auditIdentity` getting merged in.

2024-08-27 14:42 UTC, JonathanWilbur commented
@t8m or @mattcaswell can I get a merge or re-review, if needed? This one has been `done` for four days.

2024-08-27 14:48 UTC, t8m commented
As this was a trivial rebase, I do not think this needs re-approvals.
Merging.

2024-08-27 14:49 UTC, t8m commented
Merged to the master branch. Thank you for your contribution.

2024-08-27 14:49 UTC, closed without merging