EVP_CIPHER_CTX_get_algor_params() may attempt to access params array
openssl/openssl pull request #25303
Opened 2024-08-28 12:39 UTC by Sashan

at position -1 (prams[=1]).

The issue has been reported by coverity check.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2024-08-28 12:44 UTC, nhorman approved these changes

2024-08-28 12:44 UTC, t8m commented on crypto/evp/evp_lib.c
> +        const char *derk = params[i].key;
It would be better to split the condition in 2 steps and just error out if `i < 0`.

2024-08-28 13:49 UTC, t8m requested changes

2024-08-28 13:49 UTC, t8m commented on crypto/evp/evp_lib.c
> +    if (i < -1)
`< 0`

2024-08-28 13:49 UTC, t8m commented on crypto/evp/evp_lib.c
> +    if ((der = OPENSSL_malloc(params[i].return_size)) != NULL) {
Please keep `derl` usage.

2024-09-02 13:24 UTC, levitte commented on crypto/evp/evp_lib.c
> +
I would move this to line 1276

2024-09-02 13:59 UTC, tom-cosgrove-arm approved these changes
Reconfirming

2024-09-03 19:19 UTC, t8m commented
Merged to the master branch. Thank you.

2024-09-03 19:19 UTC, closed without merging