Recycle the TLS key that holds thread_event_handler
openssl/openssl pull request #25300
Opened 2024-08-28 01:15 UTC by zhihaoy

fixes: #25278 

The change cleans up TLS when handling errors in `ossl_thread_event_ctx_new` as well.

2024-08-28 12:05 UTC, t8m approved these changes

2024-08-28 12:17 UTC, nhorman requested changes

2024-08-28 12:17 UTC, nhorman commented on crypto/initthread.c
> +        goto deinit;
The style checker is catching this.  I know this didn't introduce it, but coding style says that, if you have a conditional with only one statement, you don't put curly braces around it.  Removing the curly braces here will get the style check ci job to pass

2024-08-28 16:53 UTC, nhorman approved these changes

2024-08-30 05:43 UTC, zhihaoy commented
ping

2024-08-30 11:47 UTC, nhorman commented
Its approved, we're just waiting to merge it now, which at this point has to wait until sept 5 (alpha release), as the tree is currently frozen

2024-08-30 12:37 UTC, t8m approved these changes

2024-08-31 12:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been  updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2024-09-05 15:21 UTC, t8m commented
Merged to the master, 3.4, 3.3, 3.2 and 3.1 branches. Does not apply cleanly to 3.0.

Thank you for your contribution.

2024-09-05 15:21 UTC, closed without merging