Add test for BIO password callback functionality
openssl/openssl pull request #25330
Opened 2024-08-29 21:10 UTC by erbsland-dev

Related to #8441

This commit introduces a test suite for the password callback mechanism used when reading or writing encrypted keys via a BIO in OpenSSL. The test is designed to cover various edge cases, particularly focusing on scenarios where the password callback might return unexpected or malformed data from user code.

By simulating different callback behaviors, including negative returns, zero-length passwords, excessively long passwords, and others, this test aims to ensure robust handling of all possible callback outcomes.

- [X] tests are added or updated

2024-08-30 10:10 UTC, t8m commented
I am unsure whether this should go into all branches or not.

2024-08-30 10:11 UTC, t8m approved these changes

2024-08-30 12:28 UTC, erbsland-dev commented
> I am unsure whether this should go into all branches or not.

My goal was to address the specific issues in the password callback handling, but I don’t have the broader context to judge the impact or importance of this fix across different branches. I’ll leave it to the maintainers to decide the appropriate branches for inclusion, and I’m happy to make any changes as needed based on your recommendations.

2024-08-30 13:42 UTC, mattcaswell requested changes

2024-08-30 13:42 UTC, mattcaswell commented on test/bio_pw_callback_test.c
> +static BUF_MEM *encrypted_key_data = NULL;
You treat encrypted_key_data as just a pointer to a buffer of bytes below (e.g. `char *`) - but you've declared it here as a `BUF_MEM *` which is definitely not correct (a `BUF_MEM` is a structured type)

2024-08-30 13:42 UTC, mattcaswell commented on test/bio_pw_callback_test.c
> +    free(encrypted_key_data);
Probably you mean `OPENSSL_free()` here (assuming `encrypted_key_data` is a buffer of bytes...see my other comment)

2024-08-30 13:42 UTC, mattcaswell commented on test/bio_pw_callback_test.c
> +    free(encrypted_key_data);
Probably you mean `OPENSSL_free`

2024-08-30 13:42 UTC, mattcaswell commented on test/bio_pw_callback_test.c
> +    memset(callback_data, 0, sizeof(CALLBACK_DATA));
`OPENSSL_zalloc` would be better than these two lines

2024-08-30 13:42 UTC, mattcaswell commented on test/bio_pw_callback_test.c
> +static BIO *bio = NULL;
Not really sure why this is a global, rather than a local in each function that needs it

2024-08-30 15:11 UTC, t8m approved these changes

2024-08-30 15:16 UTC, beldmit approved these changes
LGTM

2024-08-30 15:57 UTC, erbsland-dev commented
@t8m I'm not sure if the failure of "GitHub CI / self-hosted (freebsd-13.2)" is related to this pull request or not.

2024-08-30 16:02 UTC, mattcaswell commented
>  I'm not sure if the failure of "GitHub CI / self-hosted (freebsd-13.2)" is related to this pull request or not.

No. An intermittent failure we see from time to time which we can't track down.

2024-08-31 16:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been  updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2024-09-01 02:14 UTC, shahsb requested changes

2024-09-01 02:14 UTC, shahsb commented on test/bio_pw_callback_test.c
> +static char cb_magic = 'p';
```suggestion
static const char cb_magic = 'p';
```

Please use `const` for all of these constants.

2024-09-01 02:14 UTC, shahsb commented on test/bio_pw_callback_test.c
> +static int key_password_len = 13;
Minor/nit: It would be nice to use `size_of()` to calculate size and try to avoid hardcoding's wherever possible.

2024-09-02 08:47 UTC, t8m approved these changes

2024-09-02 08:48 UTC, t8m commented
@beldmit please reconfirm

2024-09-05 15:43 UTC, beldmit approved these changes
LGTM

2024-09-06 17:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-09-09 07:06 UTC, t8m commented
Merged to all the active branches. Thank you for your contribution.

2024-09-09 07:06 UTC, closed without merging