Add Missing Error Messages for AES-OCB Tag Length Validation
openssl/openssl pull request #25425
Opened 2024-09-10 19:27 UTC by erbsland-dev

Related to #8381: Addressing found issues by adding specific error messages to improve feedback when tag length checks fail for the `EVP_CTRL_AEAD_SET_TAG` parameter in the AES-OCB algorithm.

- Added `PROV_R_INVALID_TAG_LENGTH` error to indicate when the current tag length exceeds the maximum tag length of the algorithm.
- Added `PROV_R_INVALID_TAG_LENGTH` error to indicate when the current tag length in the context does not match a custom tag length provided as a parameter.
- Added `PROV_R_FAILED_TO_SET_PARAMETER` error to handle cases where an invalid pointer is passed in encryption mode.

2024-09-11 07:31 UTC, t8m requested changes

2024-09-11 07:31 UTC, t8m commented on providers/implementations/ciphers/cipher_aes_ocb.c
> +                ERR_raise(ERR_LIB_PROV, PROV_R_FAILED_TO_SET_PARAMETER);
ERR_R_PASSED_INVALID_ARGUMENT is more appropriate here, I would also check this condition first and the taglen second.

2024-09-11 07:48 UTC, t8m approved these changes

2024-09-11 23:30 UTC, paulidale approved these changes

2024-09-13 00:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-09-13 08:14 UTC, t8m commented
Squashed with adjusted commit message and merged to all the active branches. Thank you for your contribution.

2024-09-13 08:14 UTC, closed without merging