docs: Document the implemented composite signature+hash algorithms
openssl/openssl pull request #25422
Opened 2024-09-10 14:47 UTC by levitte

The details for RSA and EdDSA have already been documented, albeit the
RSA documentation wasn't conforming properly to the POD format.

Fixes #25433

2024-09-10 15:40 UTC, t8m requested changes
Just nits

2024-09-10 15:40 UTC, t8m commented on doc/man7/EVP_SIGNATURE-ECDSA.pod
> +
Nit: spurious empty line

2024-09-10 15:40 UTC, t8m commented on doc/man7/EVP_SIGNATURE-DSA.pod
> +Can't be used with L<EVP_PKEY_sign_message_init(3)>
Nit: `It cannot be...`

2024-09-10 15:40 UTC, t8m commented on doc/man7/EVP_SIGNATURE-ECDSA.pod
> +Can't be used with L<EVP_PKEY_sign_message_init(3)>
Nit: `It cannot be...`

2024-09-10 17:30 UTC, t8m submitted a review, later dismissed

2024-09-11 12:38 UTC, mattcaswell submitted a review, later dismissed
A minor nit, but otherwise looks good.

2024-09-11 12:44 UTC, levitte commented on doc/man7/EVP_SIGNATURE-DSA.pod
> +DSA signature schemes with diverse message digest algorithm.  They are all
Fixed, and in `EVP_SIGNATURE-RSA.pod` and `EVP_SIGNATURE-ECDSA.pod` as well

2024-09-11 12:52 UTC, mattcaswell approved these changes

2024-09-12 13:26 UTC, levitte commented
Merged

master:
3cd5aeb3ccc4e9a4082c0890abd878e9ea74884b docs: Document the implemented composite signature+hash algorithms

3.4:
642567ad8ae73de373fc4640f6c1f20fd2f89337 docs: Document the implemented composite signature+hash algorithms

2024-09-12 13:27 UTC, closed without merging