Clarify Tag Length Setting in OCB Mode
openssl/openssl pull request #25424
Opened 2024-09-10 17:22 UTC by erbsland-dev

Fixes #8331: Updated the description for setting the tag length in OCB mode to remove the misleading “when encrypting” phrasing. This change emphasizes that setting a custom tag length requires a call with NULL, applicable to both encryption and decryption contexts.

- [x] documentation is added or updated

2024-09-10 17:34 UTC, t8m requested changes

2024-09-10 17:34 UTC, t8m commented on doc/man3/EVP_EncryptInit.pod
> +prior to setting the IV during encryption, then a default tag length is used.
Actually also remove the `during encryption` here

2024-09-10 18:41 UTC, t8m approved these changes

2024-09-17 04:22 UTC, fwh-dc commented
@t8m Will the mentioned issue be auto-closed when `Fixes #8331` is not on its own line in the commit message? If not It'd be great if you (@erbsland-dev) could update the commit message.

2024-09-17 06:36 UTC, t8m commented
Not sure. At worst we can either reword the commit message when merging or close the fixed issue manually.

2024-09-17 06:56 UTC, paulidale commented
The two are linked already.  Merging & closing this will close #8331 too.

2024-09-17 07:06 UTC, fwh-dc approved these changes
LGTM

2024-09-17 19:49 UTC, t8m commented
> The two are linked already. Merging & closing this will close #8331 too.

Actually just linking the issue and PR in the Github interface does not help with closing the issue as the merge happens outside of GH and the commit is rebased before merging so GH cannot associate it with the PR from which it comes. So yeah, sometimes the committer who does the merge needs to remember to close the linked issue manually.

2024-09-18 08:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been  updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2024-09-19 18:52 UTC, t8m commented
Merged to all the active branches. Thank you for your contribution.

2024-09-19 18:52 UTC, closed without merging