fips: add lots of potentially missing ossl_prov_is_running checks
openssl/openssl pull request #25580
Opened 2024-09-30 15:01 UTC by xnox

After rudimentary analysis, it appears the below functions can
potentially produce output, whilst the provider is in error state.

These functions were detected using this method:

```
CFLAGS='-save-temps' ./Configure enable-fips --debug
make -j10
find . -name '*.i' | xargs git add -f
git grep --cached -p ossl_prov_is_running | grep libfips-lib > ossl_prov_is_running.txt
git grep --cached -p 'return' | grep  libfips-lib > return.txt
grep '\.i=' return.txt > func-with_return.txt
grep '\.i=' ossl_prov_is_running.txt > func-with-ossl_prov_is_running.txt
grep --fixed-strings --line-regexp --file=func-with-ossl_prov_is_running.txt return.txt > func-without-ossl_prov_is_running.txt
grep -e newctx -e initctx -e dupctx func-without-ossl_prov_is_running.txt  | grep -v ossl_prov_is_running
```

And from there doing manual inspection, as the list was short at that
point.

As in compile with keeping pre-processed source code; and use `git
grep --cached -p` to find these preprocessed files, and scan for calls
to return or opssl_prov_is_running, with function name printed. And
then exclude one from the other, to hopefully get a list of all the
functions that do not check for ossl_prov_is_running.

As number of functions without "func-without-ossl_prov_is_running"
check is large, I do wonder which other functions are "interesting" to
check for. I think I'm not scanning for _update functions
correctly. Any tips on improving above analysis will help with
maintaining such checks going forward.

2024-09-30 22:56 UTC, paulidale requested changes
Nice work.  A couple of false positives though.

2024-09-30 22:56 UTC, paulidale commented on providers/implementations/kem/rsa_kem.c
> +    if (!ossl_prov_is_running())
This check should be done in `rsakem_generate()` I think.
That's the only caller of this function (via `rsasve_generate()`) and it matches the check added in `rsasve_recover()`.

2024-09-30 22:56 UTC, paulidale commented on providers/implementations/kem/rsa_kem.c
> +    if (!ossl_prov_is_running())
This check should be done in `rsakem_generate()` I think.
That's the only caller of this function and it matches the check added in `rsasve_recover()`.

2024-09-30 22:56 UTC, paulidale commented on providers/implementations/macs/kmac_prov.c
> +    if (!ossl_prov_is_running())
Update functions deliberately don't have the is running check.  The init and final get the check so the operation errors out without a performance hit.

2024-09-30 22:56 UTC, paulidale commented on providers/implementations/macs/kmac_prov.c
> +    if (!ossl_prov_is_running())                                               \
This one isn't required because of the check in `kmac_new()` which gets called initialising `macctx`.

2024-10-01 00:13 UTC, paulidale approved these changes

2024-10-01 06:55 UTC, tom-cosgrove-arm approved these changes
LGTM

2024-10-01 09:37 UTC, mattcaswell approved these changes

2024-10-02 07:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-10-02 10:21 UTC, t8m commented
Merged to the master branch. Thank you for your contribution.

2024-10-02 10:21 UTC, closed without merging

2024-10-06 22:53 UTC, xnox commented
Can this please be cherry-picked into 3.4?

2024-10-07 08:05 UTC, t8m commented
Perhaps. After beta is out and tree unfrozen.

2024-10-07 08:06 UTC, t8m commented
@mattcaswell @paulidale OK with 3.4 cherry-pick?

2024-10-07 08:37 UTC, paulidale commented
Don't disagree with a cherry pick.

2024-10-10 02:12 UTC, xnox commented
3.4 is open for this cherry-pick? do i need to submit a pr?

2024-10-10 02:57 UTC, paulidale commented
It cherry picked cleanly.