Fips cis
openssl/openssl pull request #25638
Opened 2024-10-09 04:33 UTC by paulidale

- [ ] documentation is added or updated
- [x] tests are added or updated

2024-10-10 07:50 UTC, hlandau requested changes
One nit, otherwise LGTM

2024-10-10 07:50 UTC, hlandau commented on .github/workflows/prov-compat-label.yml
> +#    if: ${{ contains(github.event.pull_request.labels.*.name,'extended tests') }}
Can be deleted

2024-10-15 22:15 UTC, paulidale commented on .github/workflows/prov-compat-label.yml
> +#    if: ${{ contains(github.event.pull_request.labels.*.name,'extended tests') }}
Done.

2024-10-18 01:59 UTC, paulidale commented
Ping @openssl/committers for reviews

2024-10-21 23:53 UTC, paulidale commented
Ping?

2024-10-23 21:56 UTC, paulidale commented
Ping @hlandau ?

2024-11-04 22:42 UTC, paulidale commented
Ping for reviews?

2024-11-12 08:49 UTC, hlandau approved these changes

2024-11-12 08:49 UTC, hlandau commented
Needs a second review

2024-11-21 01:08 UTC, paulidale commented
Clean rebase to master.  Ping for review.

2024-12-22 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2025-01-04 08:44 UTC, hlandau approved these changes
Still good

2025-02-12 02:01 UTC, paulidale commented
unrequited

2025-02-12 02:01 UTC, closed without merging