Adds DTLS unified header support
openssl/openssl pull request #25668
Opened 2024-10-11 11:50 UTC by fwh-dc

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2024-11-20 09:00 UTC, fwh-dc commented
ping @openssl/committers

2024-12-04 10:30 UTC, fwh-dc commented
@t8m rebased, please reconfirm

@openssl/committers the is ready for a second review.

2024-12-04 11:15 UTC, t8m requested changes

2024-12-04 11:15 UTC, t8m commented on ssl/record/methods/dtls_meth.c
> +                 * is only set if one has been negotiated: silently discard */
Nit: no apostrophe in ID's and please reformat properly or just have `/*  OpenSSL does not support connection IDs: silently discard */`

2024-12-04 12:38 UTC, t8m approved these changes

2024-12-05 11:35 UTC, fwh-dc commented
@openssl/committers ping for second review.

2025-01-07 09:08 UTC, fwh-dc commented
@openssl/committers ping for second review.

2025-01-15 13:18 UTC, fwh-dc commented
@t8m I've rebase the change on top of the updated DTLS-1.3 feature branch. And I've added a change to set the additional data correctly for DTLS 1.3 for de/encrypting records. It was a defect I found when testing against the wolfssl dtls 1.3 implementation.

2025-01-15 14:34 UTC, t8m commented
Close&reopen to re-run CI.

2025-01-15 14:53 UTC, t8m approved these changes

2025-01-22 10:47 UTC, t8m commented
ping @openssl/committers for reviews

2025-02-17 08:22 UTC, fwh-dc commented
@openssl/committers ping for second review

2025-03-10 17:45 UTC, mattcaswell requested changes
Comments so far (ran out of time for further review today).

2025-03-10 17:45 UTC, mattcaswell commented on ssl/record/methods/dtls_meth.c
> +                              : (length = TLS_BUFFER_get_len(&rl->rbuf)) > 0)) {
I'm confused by this logic. This seems to say that we if we have a non-zero length then we go to the failure code below?? Surely we want to do this in the event of a zero length only?

2025-03-10 17:45 UTC, mattcaswell commented on ssl/record/methods/dtls_meth.c
> +                              : (length = TLS_BUFFER_get_len(&rl->rbuf)) > 0)) {
Also...the length is set to the length of the whole buffer. But we already consumed some of it. Shouldn't this be set to `length - rechdrlen`?

2025-03-10 17:45 UTC, mattcaswell commented on ssl/record/methods/dtls_meth.c
> +        more = rr->length - (nread - rechdrlen);
This adjustment here seems odd. We should have just set `rr->length` to the correct value in the first place, rather than trying to adjust it here.

2025-03-10 17:45 UTC, mattcaswell commented on ssl/record/methods/dtls_meth.c
> +            && ossl_assert(rl->sn_enc_ctx != NULL)
This looks strange. If the assert fails we don't go into the error logic below.

2025-03-10 17:45 UTC, mattcaswell commented on ssl/record/methods/dtls_meth.c
> +            && (!ossl_assert(rl->packet_length >= rechdrlen + 16)
What is the magic number here?

2025-03-10 17:45 UTC, mattcaswell commented on ssl/record/methods/dtls_meth.c
> +            || (sbit ? !WPACKET_memcpy(thispkt, rl->sequence + 6, 2)
We are conditional on `sbit` here. But this is set to a compiled in constant??

2025-03-12 08:08 UTC, fwh-dc reviewed
@mattcaswell Please have a look again.

2025-03-12 17:16 UTC, mattcaswell submitted a review, later dismissed
LGTM

2025-03-12 17:17 UTC, mattcaswell commented
Ah...except the CI failures look relevant.

2025-03-12 20:26 UTC, fwh-dc commented
@mattcaswell Fixed. Please have a look.
@t8m please reconfirm

2025-03-17 07:49 UTC, fwh-dc commented
@t8m ping

2025-03-18 17:00 UTC, openssl-machine commented
This pull request is ready to merge

2025-03-18 17:57 UTC, t8m commented
Squashed and merged to the feature branch. Thank you for your contribution.

2025-03-18 17:57 UTC, closed without merging