Windows: Fix identical file tests to compare results as text
openssl/openssl pull request #25675
Opened 2024-10-12 08:08 UTC by kiyolee

For these identical file tests, even the in and out filenames are the same, output file format would change to be DOS format on Windows and that failed the tests.

CLA: trivial

2024-10-14 08:02 UTC, tom-cosgrove-arm commented
So why don't the tests fail at the moment?

2024-10-14 22:02 UTC, slontis commented
Maybe git been configured to modify line endings?

2024-10-19 09:52 UTC, kiyolee commented
OK, it is the git config core.autocrlf which I have it false to preserve unix format, even on Windows.
However, wouldn't it be better that the tests are independent of how developers config their git?

2025-03-31 11:55 UTC, t8m requested changes

2025-03-31 11:55 UTC, t8m commented on test/recipes/15-test_ml_dsa_codecs.t
> +        ok(!compare_text($der0, $der),
I do not think this is correct - these are binary files.

2025-03-31 11:55 UTC, t8m commented on test/recipes/15-test_ml_dsa_codecs.t
> +        ok(!compare_text($s, $refsig),
This is again binary data, I do not think this is right.

2025-03-31 11:55 UTC, t8m commented on test/recipes/15-test_ml_kem_codecs.t
> +        ok(!compare_text($der0, $der),
As above

2025-03-31 11:55 UTC, t8m commented on test/recipes/15-test_ml_kem_codecs.t
> +        ok(!compare_text($ss0, $ss),
Again binary data.

2025-04-01 12:32 UTC, kiyolee commented on test/recipes/15-test_ml_dsa_codecs.t
> +        ok(!compare_text($der0, $der),
Fixed in a new commit.

2025-04-01 12:32 UTC, kiyolee commented on test/recipes/15-test_ml_dsa_codecs.t
> +        ok(!compare_text($s, $refsig),
Fixed in a new commit.

2025-04-01 12:32 UTC, kiyolee commented on test/recipes/15-test_ml_kem_codecs.t
> +        ok(!compare_text($der0, $der),
Fixed in a new commit.

2025-04-01 12:32 UTC, kiyolee commented on test/recipes/15-test_ml_kem_codecs.t
> +        ok(!compare_text($ss0, $ss),
Fixed in a new commit.

2025-04-01 13:03 UTC, t8m commented
Commits to be squashed when merging.

2025-04-01 13:13 UTC, t8m commented
As you already squashed the commits, could you please also amend the commit message to reflect what is the actual change in the patch as it is now just a cleanup thing.

2025-04-01 13:17 UTC, closed without merging

2025-04-01 13:18 UTC, t8m commented
Thank you for your effort anyway.

2025-04-01 13:20 UTC, kiyolee commented
The updated title does reflect what has been left in the PR.