Fix potential memory leak in PKCS7_set_attributes()
openssl/openssl pull request #25713
Opened 2024-10-16 18:39 UTC by nielsdos

If sk_X509_ATTRIBUTE_set() fails, then the duplicated attribute could leak. Solve this by storing the attribute in a variable and calling X509_ATTRIBUTE_free().

Note: this was detected using an experimental static analyser I'm working on. I understand this is quite an unlikely bug.
I could also be wrong because my results are based on static analysis even though I manually read the code as well.

2024-10-17 07:13 UTC, t8m requested changes
The leak cannot really happen as the stack is first created as shallow copy of the `sk` stack so there is no way that the sk_set function would really fail.

However instead of doing this a proper thing to do would be to use sk_X509_ATTRIBUTE_deep_copy().

2024-10-23 09:12 UTC, nielsdos commented
Thanks, I've force pushed that change.

2024-10-23 16:39 UTC, t8m approved these changes

2024-11-23 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2024-11-27 11:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-11-28 14:27 UTC, t8m commented
Merged to the master branch. Thank you for your contribution.

2024-11-28 14:27 UTC, closed without merging