Support DEFAULT keyword and '-' prefix in SSL_CTX_set1_groups_list()
openssl/openssl pull request #25813
Opened 2024-10-28 07:35 UTC by fwh-dc

Fixes #25790

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

2024-10-28 12:02 UTC, mattcaswell requested changes

2024-10-29 10:41 UTC, fwh-dc commented on ssl/t1_lib.c
> +    while (elem[0] == '-' || elem[0] == '?') {
You're right. Fixed.

2024-10-29 10:58 UTC, mattcaswell approved these changes
Looks good. Consider adding a CHANGES.md entry

2024-10-29 11:01 UTC, mattcaswell commented
CIs are failing

2024-10-29 12:47 UTC, mattcaswell commented
There's still some CI failures with the latest push

2024-10-29 13:05 UTC, fwh-dc commented
> There's still some CI failures with the latest push

Yes the issue is with these lines in minimal builds:

https://github.com/openssl/openssl/blob/71cd2a493a9b9570cc99b89199034b04f8a8db52/test/sslapitest.c#L9784-L9786

Is it correct that the length is 0? And which definition can I use for enabling the check?

2024-10-29 13:53 UTC, mattcaswell commented
I suppose the problem comes with the combination of no-ec and no-dh. That leaves you with no groups left.

2024-10-29 13:56 UTC, mattcaswell commented
i.e. `!defined(OPENSSL_NO_EC) || !defined(OPENSSL_NO_DH))`, or something like that

2024-10-29 13:56 UTC, mattcaswell commented
There's quite a few other tests in that file gated on those defines

2024-10-31 12:18 UTC, fwh-dc commented
> I suppose the problem comes with the combination of no-ec and no-dh. That leaves you with no groups left.

Thanks! I did not know that was possible. I'm pretty sure the update works.

2024-10-31 12:23 UTC, t8m requested changes

2024-10-31 12:23 UTC, t8m commented on test/sslapitest.c
> +#endif
I would not add these checks as in future they might be misleading, i.e. when we will have some additional groups such as ML-KEM. I.e., just keep the equivalency check.

2024-10-31 12:23 UTC, t8m commented on test/sslapitest.c
> +#endif
Same here, just skip the check.

2024-10-31 12:46 UTC, fwh-dc commented
@t8m Thanks! Fixed now.

2024-10-31 13:27 UTC, mattcaswell approved these changes

2024-10-31 17:39 UTC, tmshort commented
Ciphers use `!` for removal, do we want to introduce `-` for removal? Shouldn't we be consistent in these lists?

2024-11-01 09:29 UTC, mattcaswell commented
Hmm. Good point. Yeah that might be better.

2024-11-01 09:36 UTC, t8m commented
> Ciphers use `!` for removal, do we want to introduce `-` for removal? Shouldn't we be consistent in these lists?

Ciphers use both `!` and `-` for removal with `!` having the special meaning of _remove forever with no means to re-add_. So this doesn't introduce anything new and IMO `-` is better as the removal does not have any special meaning here.

2024-11-01 09:37 UTC, fwh-dc commented
Yes I was trying to be consistent with:

https://github.com/openssl/openssl/blob/59f5f6c73cd2e1e2bd8ef405fdb6fadf0711f639/doc/man1/openssl-ciphers.pod.in#L136C1-L147C73

2024-11-01 09:38 UTC, t8m approved these changes

2024-11-01 14:00 UTC, tmshort commented
OK, I've seen examples of ciphers with `!` in it, but I'm not sure I've seen an example with `-` (maybe it's there?).

2024-11-01 16:25 UTC, t8m commented
From the openssl-ciphers(1) manpage:

       Each cipher string can be optionally preceded by the characters !, - or
       +.

       If  !  is  used then the ciphers are permanently deleted from the list.
       The ciphers deleted can never reappear in the list  even  if  they  are
       explicitly stated.

       If  -  is  used then the ciphers are deleted from the list, but some or
       all of the ciphers can be added again by later options.

       If + is used then the ciphers are moved to the end of  the  list.  This
       option  doesn't  add  any  new  ciphers it just moves matching existing
       ones.

2024-11-02 10:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been  updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2024-11-04 10:50 UTC, t8m commented
Merged to the master branch. Thank you for your contribution.

2024-11-04 10:50 UTC, closed without merging