Add support for SLH_DSA
openssl/openssl pull request #25882
Opened 2024-11-06 03:47 UTC by slontis

This is a work in progress.

Existing code that I have running locally will be broken up into separate commits to make reviewing easier.

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

2024-11-06 11:04 UTC, slontis commented
@t-j-h Run out of steam for the day.. Hopefully will get through quite a few of the items above tomorrow.
This should at least give you an idea of how I am trying to deal with parameters.

2024-11-18 11:42 UTC, baentsch commented on doc/designs/slh-dsa.md
> +The FIPS 205 the SLH_DSA private key contains the public key.
Not quite complete sentence.

2024-11-21 06:55 UTC, slontis commented
@openssl/committers This should be in a reviewable state now. Additional tests will be added in a separate PR.

2025-01-11 16:26 UTC, vdukhovni requested changes

2025-01-12 22:00 UTC, paulidale commented
This needs a rebase.

2025-01-23 02:03 UTC, slontis commented on crypto/slh_dsa/slh_dsa_backend.c
> +    nid = OBJ_obj2nid(alg->algorithm);
code removed

2025-01-23 02:06 UTC, slontis commented on crypto/slh_dsa/slh_dsa_ctx.c
> +                                  OSSL_LIB_CTX *lib_ctx, const char *propq)
Partially did this, for this algorithm I have too many things to pass around to not have a ctx (and a large number of functions). The constant things have moved into the key. The operation related contexts are still stored in a container. Even doing that change took a large part of a day.

2025-01-23 02:07 UTC, slontis commented on crypto/slh_dsa/slh_dsa_key.c
> +
not relevant anymore

2025-01-23 02:09 UTC, slontis commented on crypto/slh_dsa/slh_dsa_key.c
> +                || RAND_bytes_ex(lib_ctx, pub, pk_seed_len, 0) <= 0)
The DRBG uses 256 bits when you specify 0.

2025-01-23 02:44 UTC, slontis commented on crypto/slh_dsa/slh_dsa.c
> +}
Not sure this translates very nicely,  in_len is 1 or 2 bytes

2025-01-23 03:02 UTC, vdukhovni commented on crypto/slh_dsa/slh_dsa.c
> +}
> Not sure this translates very nicely, in_len is 1 or 2 bytes

Yeah, given a variable-length big-endian encoding, what you have is probably simplest, do you want to return 0 or some fixed "garbage" output if the input length is unexpectedly large (garbage in)?

2025-01-23 03:54 UTC, slontis commented
Lots of cleanups.. Ref counts removed. Old ASN1 decoders have been replaced with simple direct decoders,

2025-01-23 04:02 UTC, slontis commented on crypto/slh_dsa/slh_dsa.c
> +}
This is only used in this file..
Looking closer this uses 7 or 8 bytes in one case and 1 or 2 in the other.

2025-01-23 04:03 UTC, slontis commented on crypto/slh_dsa/slh_dsa.c
> +}
I am not worried about invalid lengths here as it is dealing with constant parameters as input..

2025-01-26 08:19 UTC, vdukhovni reviewed
Almost ready. Some nits.

2025-01-26 08:19 UTC, vdukhovni commented on doc/man7/EVP_SIGNATURE-SLH-DSA.pod
> +it may be set by passing an OSSL_PARAM array to L<EVP_PKEY_sign_init_ex2(3)> or
```suggestion
The C<context-string> parameter, described below, can be used for both signing and verification.
It may be set by passing an OSSL_PARAM array to L<EVP_PKEY_sign_init_ex2(3)> or
```

2025-01-26 08:19 UTC, vdukhovni commented on include/crypto/x509.h
> +                                                const uint8_t **pp, long length);
Are these still needed with decoders no longer using ASN1 methods? Might a single function instead do the job, and get an `evp_type` argument?

2025-01-26 08:19 UTC, vdukhovni commented on include/crypto/x509.h
> +int ossl_i2d_SLH_DSA_SHAKE_256F_PUBKEY(const SLH_DSA_KEY *a, uint8_t **pp);
Same question for encoders.

2025-01-26 08:19 UTC, vdukhovni commented on providers/implementations/encode_decode/decode_der2key.c
> +     * encoded public key (since the large public key size is 64 bytes):
```suggestion
     * encoded public key (since the largest public key size is 64 bytes):
```

2025-01-26 08:19 UTC, vdukhovni commented on providers/implementations/encode_decode/encode_key2text.c
>                               const unsigned char *buf, size_t buflen)
This function has moved. The branch should be rebased on master, and then the PR on the updated branch.

2025-01-26 08:19 UTC, vdukhovni commented on providers/implementations/keymgmt/slh_dsa_kmgmt.c
> +static void *slh_dsa_load(const void *reference, size_t reference_sz)
Perhaps `#ifndef FIPS_MODULE` for this function.

2025-01-27 23:45 UTC, slontis commented on doc/designs/slh-dsa.md
> +to not encode the passed in message.
For what purpose - when you do that you are basically just passing in another message, so this really doesnt test anything. These are ACVP tests that are meant for FIPS validation, I do not claim to support them. (Unless you do the entire sequence of calls inside the FIPS boundary it is pointless). Note that for the FIPS certification you tick boxes indicating which capabilities you support (it is not a requirement to support all capabilities)

2025-01-27 23:48 UTC, slontis commented on providers/implementations/encode_decode/encode_key2text.c
>                               const unsigned char *buf, size_t buflen)
Could you rebase the branch on master please?

2025-01-28 02:51 UTC, slontis commented on providers/implementations/keymgmt/slh_dsa_kmgmt.c
> +static void *slh_dsa_load(const void *reference, size_t reference_sz)
If we decide to do that it should be applied at a later date to all keymanagement files.

2025-01-28 02:55 UTC, slontis commented on include/crypto/x509.h
> +                                                const uint8_t **pp, long length);
looks like they are no longer required

2025-01-28 03:11 UTC, slontis commented on crypto/slh_dsa/slh_adrs.c
> +     */
Not really - there is a slh_adrs_zero() that handles this..

2025-01-28 03:24 UTC, vdukhovni commented on doc/designs/slh-dsa.md
> +to not encode the passed in message.
My question is about the API supported by SLH-DSA, and whether as a result it is possible to use EVP_DigestSign with a null digest, so that `openssl dgst -sign`... work. I am not asking about the ACVP tests, or about supporting non-prehash variants

2025-01-28 03:33 UTC, vdukhovni commented on providers/implementations/encode_decode/encode_key2text.c
>                               const unsigned char *buf, size_t buflen)
The branch has been rebased.

2025-01-28 03:55 UTC, vdukhovni approved these changes

2025-01-28 03:55 UTC, vdukhovni commented on crypto/slh_dsa/slh_dsa.c
> +    tree_id_mask = ((uint64_t)~0) >> (64 - (params->h - params->hm));
The `~` may need to go in front of the cast, otherwise, this could be a cast from the (int)~0 to 64 bits, which isn't what you want. I wrote the `~` that way deliberately in the suggestion.

2025-01-28 05:58 UTC, slontis commented
Rebase from master caused a few things to change..
Moved code from encode_key2any.c to  ossl_slh_dsa_key_to_text() in slh_dsa_key.c
MAKE_ENCODER() param list changed & pub_to_der & priv_to_der now take an extra ctx param..

2025-01-28 22:12 UTC, paulidale commented on INSTALL.md
> -    <https://github.com/smuellerDD/jitterentropy-library>
Why remove this?

2025-01-30 05:40 UTC, slontis commented on INSTALL.md
> -    <https://github.com/smuellerDD/jitterentropy-library>
ACCIDENTAL REMOVAL..

2025-01-30 05:44 UTC, slontis commented
@paulidale updated..

2025-02-03 00:24 UTC, t-j-h approved these changes
Approved without or without the comments being addressed. 
They are for the most parts nits.

2025-02-03 00:24 UTC, t-j-h commented on crypto/slh_dsa/slh_adrs.h
> +typedef uint8_t *SLH_ADRS;
I'm really not a fan of using a typedef to hide a pointer ... it really makes the rest of the APIs a little "strange" from a quick glance - you don't immediate know you are passing around references ...

2025-02-03 00:24 UTC, t-j-h commented on crypto/slh_dsa/slh_dsa.c
> +        return (sig_len != NULL);
Is this consistent with our approach in the other sig implementations for not raising errors on these checks here?

2025-02-03 00:24 UTC, t-j-h commented on crypto/slh_dsa/slh_dsa.c
> +        && ossl_slh_ht_verify(hctx, pk_fors, sig_rpkt, pk_seed,
Style wise you are using goto err and ret = ... in the sign function but are taking a different approach here.
It grates that they are different when they don't need to be style-wise and they are right next to each other.

2025-02-03 00:24 UTC, t-j-h commented on crypto/slh_dsa/slh_dsa.c
> +    encoded_len = 1 + 1 + ctx_len + msg_len;
it would be nice to note what the 1 + 1 is for  - sure I can see it below - but nice to not have to do that - so it is right in front of the reader.

2025-02-03 00:24 UTC, t-j-h commented on crypto/slh_dsa/slh_dsa.c
> + * OPENSSL_load_u64_be() cant be used here as the |in_len| may be < 8
Nice comment - preempted me writing why aren't you using it ...

2025-02-03 00:24 UTC, t-j-h commented on crypto/slh_dsa/slh_dsa_local.h
> + * FIPS 205 SLH_DSA algorithms have many different parameters which includes
Nit - SLH-DSA not SLH_DSA here ...

2025-02-03 00:24 UTC, t-j-h commented on crypto/slh_dsa/slh_fors.c
> +         * TODO - This is a really inefficient way of doing this, since at
Not marked as a TODO the way we would normally do so ...

2025-02-03 00:24 UTC, t-j-h commented on doc/designs/slh-dsa.md
> +As the security of SLH-DSA depends only on hash functions, I do not foresee
I wouldn't use first person here - this is a consolidated view - not just yours - i.e. "we".

2025-02-03 00:24 UTC, t-j-h commented on doc/designs/slh-dsa.md
> +Currently I do not support the Pre Hash variant as this does not sit well with the
Reword not in first person. And just note it isn't supported. I'd leave the rest of this out.

2025-02-03 00:26 UTC, t-j-h commented
Separately - was assert.h includes needed in all the places that they are - or is that left over from earlier code?

2025-02-03 00:27 UTC, paulidale commented on doc/designs/slh-dsa.md
> +As the security of SLH-DSA depends only on hash functions, I do not foresee
"We" is still first person, just plural :grin: 
I agree with the comment though.

2025-02-03 00:28 UTC, paulidale commented on crypto/slh_dsa/slh_adrs.h
> +typedef uint8_t *SLH_ADRS;
+1 for this change.

2025-02-03 01:10 UTC, slontis commented on crypto/slh_dsa/slh_dsa.c
> +        return (sig_len != NULL);
Others dont even check sig_len so I will remove the check and rearrange..

2025-02-03 01:12 UTC, slontis commented on crypto/slh_dsa/slh_dsa.c
> +        && ossl_slh_ht_verify(hctx, pk_fors, sig_rpkt, pk_seed,
Code style is different because there is no allocations, and in that case it should return,,

2025-02-03 01:13 UTC, slontis commented on crypto/slh_dsa/slh_dsa.c
> +    encoded_len = 1 + 1 + ctx_len + msg_len;
You can also see it above in the description of the function

2025-02-03 01:21 UTC, slontis commented
Anywhere where I was doing an assert was a sanity check.. I have removed them (they were sanity checks for things that should never happen).

2025-02-03 01:22 UTC, slontis commented
I would rather remove them than have dead branches

2025-02-03 01:33 UTC, paulidale approved these changes
Looks good.  One very minor nomenclature point.  I'd prefer it addressed but that won't prevent my approval since the meaning is clear.

2025-02-03 01:33 UTC, paulidale commented on doc/designs/slh-dsa.md
> +OpenSSL API's.
NIST uses _pre-hash_ as the variant name.  I suggest we do too.

2025-02-03 02:37 UTC, t-j-h approved these changes
Just for the record. Previous approval still stands.

2025-02-03 02:40 UTC, slontis commented on doc/designs/slh-dsa.md
> +OpenSSL API's.
Not going to change this,...

2025-02-03 02:55 UTC, vdukhovni approved these changes
LGTM.

If the typedef of `SLH_ADRS` is no longer used anywhere, it could be removed perhaps?

2025-02-03 02:56 UTC, slontis commented
Removed the typedef uint8_t SLH_ADRS completely..

2025-02-03 03:37 UTC, paulidale approved these changes

2025-02-04 03:42 UTC, slontis commented
rebased with no changes

2025-02-04 03:45 UTC, paulidale commented
Still good & mergeable IMO.

2025-02-04 03:50 UTC, slontis commented
just waiting for tests to pass.

2025-02-04 04:50 UTC, closed without merging

2025-02-04 04:51 UTC, slontis commented
Merged to feature branch...
Thanks for the reviews..
Its finally in!