Enable AES and SHA3 optimisations on Apple Silicon M4-based macOS systems
openssl/openssl pull request #25940
Opened 2024-11-13 15:35 UTC by tom-cosgrove-arm

AES gets a performance enhancement of 7-33%.

Tested on an M4 Pro, but the CPU cores are the same on M4 and M4 Max.

2024-11-13 16:18 UTC, tom-cosgrove-arm commented
I don't think the CI failure is related to this change

```
80-test_cmp_http.t ...................... 
Failed 1/6 subtests 
```

2024-11-14 09:07 UTC, kroeckx approved these changes

2024-11-14 22:47 UTC, paulidale approved these changes
Would checking for "Apple M" at the start being reasonable here?

2024-11-15 18:34 UTC, shahsb approved these changes

2024-11-15 23:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-11-16 22:24 UTC, GrahamCampbell requested changes
I wonder if it would be better to check starts with `Apple M` instead?

2024-11-22 13:56 UTC, t8m commented
Merged to the master branch. Thank you for your contribution.

2024-11-22 13:56 UTC, closed without merging

2024-11-23 22:11 UTC, gerardobladimirmaciaslue commented
80-test_cmp_http.t ...................... 
Failed 1/6 subtests

2024-11-25 08:26 UTC, tom-cosgrove-arm commented
@gerardobladimirmaciaslue 
> 80-test_cmp_http.
> Failed 1/6 subtests

[This is usually related to proxy environment variables](https://github.com/openssl/openssl/issues/22467#issuecomment-2172976164), but without any more information it is not really possible to help you.

it's generally a better idea to open a GitHub question with as much information as you can provide, after checking existing issues and questions to see if someone else has the same problem (and maybe a solution).