fips: zeroize temporary self-check out MD variable
openssl/openssl pull request #25945
Opened 2024-11-14 04:40 UTC by xnox

At least this is done on module startup only.

2024-11-14 04:44 UTC, paulidale reviewed
Why?  There is absolutely nothing secret or even remotely related to a secret here.  It's a checksum of the module.

2024-11-14 04:50 UTC, xnox commented
> Why? There is absolutely nothing secret or even remotely related to a secret here. It's a checksum of the module.

ISO zeroization requirements are not just for secrets, but for public security parameters too. Recall #24355.

For Level 2 certification all temporary values must be zeroized by the module once no longer needed. As this is computed and not returned it must be zeroized, as otherwise it is not needed anymore.

> ISO 19790:2012/Cor.1:2015 7.9 requires cryptographic module to provide methods to zeroize all unprotected security sensitive parameters (which includes both Critical/Private and Public security parameters). And those that are temporally stored are required to be zeroized after they are no longer needed at security levels 2 and higher.

2024-11-14 04:56 UTC, paulidale commented
This isn't _security sensitive_.  The integrity check is to detect bit flip errors and the like, not to provide any kind of real security against deliberate attacks against the module.  It's impossible for it to do the latter.

The module is available, the HMAC key is available so computation of the checksum is trivial.

2024-11-14 05:09 UTC, xnox commented
> This isn't _security sensitive_. 

From ISO/IEC 19790:2012 TECHNICAL CORRIGENDUM 1, Section 7.5 Software/Firmware security

> The temporary value(s) generated during the integrity test of the module’s software or firmware shall [05.10] be zeroised from the module upon completion of the integrity test;

2024-11-15 12:00 UTC, kroeckx approved these changes

2024-11-15 14:01 UTC, t8m requested changes

2024-11-15 14:01 UTC, t8m commented on providers/fips/self_test.c
> +    OPENSSL_cleanse(out, MAX_MD_SIZE);
```suggestion
    OPENSSL_cleanse(out, sizeof(out));
```

2024-11-17 21:38 UTC, paulidale commented
OTC: **should we do this?**

2024-11-18 19:07 UTC, jvdsn commented
> but the temporary values are considered to be PSP

I wouldn't say they are considered PSP, there's just this very specific requirement that they need to be zeroized. They aren't listed as PSP (or SSP) in the Security Policy. Just for some additional context, this was changed in the latest version of the ISO (though not yet finalized nor adopted by CMVP) from a **shall** to a **should** statement. So this will go away in the future but at this point it is still required.

2024-11-19 09:29 UTC, t8m commented
**OTC: We are OK for this to go in.**

2024-11-20 15:52 UTC, t8m approved these changes

2024-11-20 16:26 UTC, tom-cosgrove-arm approved these changes

2024-11-21 17:00 UTC, openssl-machine commented
This pull request is ready to merge

2024-11-21 17:50 UTC, shahsb approved these changes

2024-11-22 13:25 UTC, t8m commented
Merged to the master branch. Thank you for your contribution.

2024-11-22 13:25 UTC, closed without merging