Revert the behavior change of CMS_get1_certs() and CMS_get1_crls()
openssl/openssl pull request #26100
Opened 2024-12-03 11:41 UTC by t8m

Fixes #26079

2024-12-03 13:22 UTC, mattcaswell requested changes

2024-12-03 13:22 UTC, mattcaswell commented on crypto/cms/cms_lib.c
> +        OSSL_STACK_OF_X509_free(certs);
Just `sk_X509_free`? We don't need to "pop" anything since we know then number of entries is 0.

2024-12-03 13:22 UTC, mattcaswell commented on crypto/cms/cms_lib.c
> +        sk_X509_CRL_pop_free(crls, X509_CRL_free);
`sk_X509_CRL_free`?

2024-12-03 14:12 UTC, t8m commented
@mattcaswell updated, also fixed the CI

2024-12-04 09:47 UTC, mattcaswell approved these changes

2024-12-04 09:52 UTC, t-j-h commented on doc/man3/CMS_add0_cert.pod
> +or NULL if there are none or error occurs.
nit - "or an error"

2024-12-04 09:52 UTC, t-j-h submitted a review, later dismissed
Approved with or without nit being fixed.

2024-12-04 09:53 UTC, t-j-h commented
Also agree with backfit to 3.4 as discussed in OTC meeting

2024-12-04 13:51 UTC, t8m commented
Fixup pushed @t-j-h @mattcaswell please reconfirm

2024-12-05 10:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been  updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2024-12-05 20:11 UTC, DDvO approved these changes

2024-12-05 22:41 UTC, t-j-h approved these changes
I would not use ossl_assert in the manner in which you've added it here in the last commit - claiming knowledge that a current function implementation cannot fail is a foot-gun for subsequent changes to that function and not a documented API contract.

Approved with or without changing that - as there are other such unfortunate uses of ossl_assert in the code.

2024-12-06 14:53 UTC, DDvO commented
I like the way you solved the pre-existing potential double-free on up_ref failure that I had [reported](https://github.com/t8m/openssl/commit/fceeac461aef41b40bc8aa417ec4adf8cd9e9527#r149938761).
By moving the up_ref() before the push(), which in this case cannot fail, we should be on the safe side.
In case not, the assert() could kick in - don't know if an abort by the assertion would be better than a mem leak,
but the new solution is much better than original code, which would have crashed badly in case of an up_ref() failure.

2024-12-06 15:03 UTC, DDvO commented
Sigh, one could avoid all such nasty memory (de-)allocation trouble by using something like Rust.

2024-12-06 15:55 UTC, t8m commented
> I like the way you solved the pre-existing potential double-free on up_ref() failure that I had [reported](https://github.com/t8m/openssl/commit/fceeac461aef41b40bc8aa417ec4adf8cd9e9527#r149938761): By simply moving the up_ref() before the push(), which in this case cannot fail, we should be on the safe side. In case not, the assert() could kick in - don't know if an abort by an assertion failure would be better than a mem leak, but the new solution is much better than original code, which would have crashed badly in case of an up_ref() failure.

This is a debug-build-only abort, so not a production build abort. We use ossl_assert() exactly for this.

2024-12-10 09:53 UTC, t8m commented
Merged to the master and 3.4 branches. Thank you for the reviews.

2024-12-10 09:53 UTC, closed without merging