passwd: Add -rounds option to specify rounds independent of salt
openssl/openssl pull request #26136
Opened 2024-12-09 06:31 UTC by AlexanderBeyn

As explained in #16530 , passwd only allows number of rounds used with SHA256/SHA512 algorithms to be specified as part of a salt. This change adds a -rounds option to passwd to explicitly specify the number of rounds, while letting the salt itself to be generated randomly.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

2024-12-09 09:14 UTC, t8m commented
Could you please sign a CLA? We cannot accept the PR without it.

https://openssl-library.org/policies/cla/index.html

2024-12-09 09:19 UTC, t8m requested changes

2024-12-09 09:19 UTC, t8m commented on apps/passwd.c
> +            return NULL;
Please output an appropriate error message here. Also move it after declarations.

2024-12-09 09:19 UTC, t8m commented on apps/passwd.c
> +                           quiet, table, reverse, pw_maxlen, mode, rounds))
Please add a check before the loop that rounds is used only with SHA-based algorithms. Output an error message and return failure otherwise.

2024-12-13 14:39 UTC, AlexanderBeyn commented
@t8m I've sent in the CLA. Do I need to close this pull request and open a new one?

2024-12-13 18:14 UTC, t8m commented
Could you please drop the merge commit? `git reset --hard HEAD~ ; git push --force` should help.

2024-12-14 04:14 UTC, AlexanderBeyn commented
Oops, that merge commit definitely shouldn't have been there. Fixed.

2024-12-16 10:04 UTC, t8m requested changes

2024-12-16 10:05 UTC, t8m commented
The CI is relevant.

2024-12-17 11:59 UTC, AlexanderBeyn commented
Ooops. I think I did this rebase very wrongly.

2024-12-17 12:02 UTC, closed without merging