Enable x86-64 SHA-512 family optimizations with SHA512 ISA extension
openssl/openssl pull request #26147
Opened 2024-12-11 08:24 UTC by stanciuadrian

The SHA-256 (`SZ=4`) and SHA-512 (`SZ=8`) dispatcher paths have been separated while keeping the SHA-256 path unmodified.

Due to early constraints in register availability, two 32-bit `OPENSSL_ia32cap_P` reads have been coalesced into one. As a consequence, several bit positions used in feature checks have gained a 32 bits offset.

Replaced `test` with `bt` to allow use of 64-bit immediate indices in CPUID feature checks.

Split the SHA512 BMI2+AVX2+BMI1 dispatcher branch into:
- AVX2+SHA512: high priority, with SHA512 ISA extension
- AVX2+BMI2+BMI1: fallback

The added implementation has its own copy of `K512` without duplicated elements every 16 bytes.
Shuffle indices have been reused from `K512`.

Added binary translators for `vsha512msg1`, `vsha512msg2`, `vsha512rnds2` for older assemblers.

Verification with [Intel® Software Development Emulator](https://www.intel.com/content/www/us/en/developer/articles/tool/software-development-emulator.html)'s instruction mix histogram:

```bash
$ LD_LIBRARY_PATH=`pwd` sde64 -lnl -- ./apps/openssl version -a
CPUINFO: OPENSSL_ia32cap=0x7ffaf3ffffebffff:0x9bc007bc239cb7ab:0x00c0009700145030:0x0000000200000430:0x0000000000000000

$ LD_LIBRARY_PATH=`pwd` sde64 -lnl -mix -- ./test/sha_test
1..5
ok 1 - test_static_sha1
ok 2 - test_static_sha224
ok 3 - test_static_sha256
ok 4 - test_static_sha384
ok 5 - test_static_sha512

$ grep VSHA512 sde-mix-out.txt
VSHA512MSG1                                                           64
VSHA512MSG2                                                           64
VSHA512RNDS2                                                         160
VSHA512MSG1                                                           64
VSHA512MSG2                                                           64
VSHA512RNDS2                                                         160
```

`openssl speed` speedups have been obtained with:
```bash
$ LD_LIBRARY_PATH=`pwd` taskset -c 1 ./apps/openssl speed -evp sha384
$ LD_LIBRARY_PATH=`pwd` taskset -c 1 ./apps/openssl speed -evp sha512
$ LD_LIBRARY_PATH=`pwd` taskset -c 1 ./apps/openssl speed -evp sha512-224
$ LD_LIBRARY_PATH=`pwd` taskset -c 1 ./apps/openssl speed -evp sha512-256
```

| Digest | Block Size (bytes) | Speedup |
| ------------- | ------------- | ------------- |
| SHA-384  | 16  | 1.62 |
|   | 64  | 1.63 |
|   | 256 | 2.50 |
|   | 1024 | 3.52 |
|  | 8192 | 4.42 |
|   | 16384  | 4.54 |
| SHA-512  | 16  | 1.65 |
|   | 64  | 1.65 |
|   | 256 | 2.52 |
|   | 1024 | 3.51 |
|  | 8192 | 4.43 |
|   | 16384  | 4.52 |
| SHA-512/224 | 16  | 1.66 |
|   | 64  | 1.65 |
|   | 256 | 2.55 |
|   | 1024 | 3.55 |
|  | 8192 | 4.44 |
|   | 16384  | 4.52 |
| SHA-512/256 | 16  | 1.66 |
|   | 64  | 1.67 |
|   | 256 | 2.55 |
|   | 1024 | 3.55 |
|  | 8192 | 4.44 |
|   | 16384  | 4.52 |

Setup: Intel Core Ultra 5 238V, benchmark pinned to 2nd P-core, Turbo Boost off
Results should be interpreted in the context of the `openssl speed` benchmark.

##### Checklist
- [X] `cfi` metainfo on `win64` path
- [X] documentation is added or updated (`CHANGES.txt`)

2025-01-15 15:05 UTC, stanciuadrian commented
@t8m, could you please enable the CI workflow one more time? Thanks!

2025-01-20 15:54 UTC, tkanteck reviewed
Thanks Adrian. It looks good to me. I only have two small suggestions.

2025-01-20 15:54 UTC, tkanteck commented on crypto/sha/asm/sha512-x86_64.pl
> +	vsha512msg2	%ymm3,%ymm4					# W[20..23] = ymm4 + S1(W[18..21])
indentation of comments looks bit off here and below (above too)

2025-01-20 15:54 UTC, tkanteck commented on crypto/sha/asm/sha512-x86_64.pl
> +	# ymm2 = FEBA, ymm3 = HGDC
it may be worth adding a comment about register content notation
```
ymm0 = ABCD
A - most significant word in ymm0
D - least significant word in ymm0
```

2025-01-21 19:31 UTC, stanciuadrian commented on crypto/sha/asm/sha512-x86_64.pl
> +	# ymm2 = FEBA, ymm3 = HGDC
Nice find, thank you! Added:
```
#################################################
# Format of comments describing register contents
#################################################
# ymm0 = ABCD
# A is the most  significant word in `ymm0`
# D is the least significant word in `ymm0`
#################################################
```

2025-01-21 20:40 UTC, stanciuadrian commented on crypto/sha/asm/sha512-x86_64.pl
> +	vsha512msg2	%ymm3,%ymm4					# W[20..23] = ymm4 + S1(W[18..21])
GitHub using 8 spaces per tab might cause it.
Replaced tabs by 4 spaces in new code according to [coding style](https://openssl-library.org/policies/technical/coding-style/).

2025-01-21 20:47 UTC, stanciuadrian commented
Rebased over `master` and applied all feedback.
@t8m, might it be possible to have the CI workflows run after pushes, please?

2025-01-25 09:14 UTC, stanciuadrian commented
Rebased over `master`.

2025-01-31 08:03 UTC, tkanteck reviewed
Thanks Adrian for addressing my comments. It looks good to me.
Approved by: Tomasz Kantecki [tomasz.kantecki@intel.com](mailto:tomasz.kantecki@intel.com)

2025-02-03 00:52 UTC, paulidale approved these changes
Look okays but the assembly wasn't checked in detail.

2025-02-07 13:54 UTC, nhorman requested changes

2025-02-07 13:54 UTC, nhorman commented on crypto/sha/asm/sha512-x86_64.pl
> +    vsha512rnds2 %xmm0,%ymm11,%ymm12
I think I'm missing something here, but I don't see any check for the availability of these new instructions at run time.  AIUI vsha512* is only available on arrow lake and lunar lake cpus.  I'm guessing that you're making a check of a support bit in ia32cap_P somewhere, but I'm not seeing where that happens or how the differentiation is made

2025-02-10 15:51 UTC, stanciuadrian commented on crypto/sha/asm/sha512-x86_64.pl
> +    test \$`1<<0`,%r10d             # AVX2 confirmed, check SHA512
With https://github.com/openssl/openssl/pull/25709 `OPENSSL_ia32cap_P` was extended from 2 `uint64_t`s to 5 and feature flags corresponding to SHA512/SM3/SM4 capabilities are copied to the 3rd `uint64_t` at bit indices:
- 32 for SHA512 ISA extension
- 33 for SM3 ISA extension
- 34 for SM4 ISA extension

At this line `%r10d` points to `(uint8_t *)OPENSSL_ia32cap_P + 20`.

A `uint32_t` at this location will indicate the following capabilities:
- bit 0 (lsb) is SHA512
- bit 1 is SM3
- bit 2 is SM4

@nhorman could you please let me know if I've answered your question.

2025-02-12 13:47 UTC, stanciuadrian commented on crypto/sha/asm/sha512-x86_64.pl
> +    vsha512rnds2 %xmm0,%ymm11,%ymm12
Replied [elsewhere](https://github.com/openssl/openssl/pull/26147#discussion_r1949378378).

2025-02-25 13:10 UTC, stanciuadrian commented
@t8m I've rebased over `master`, could you please approve the CI workflows ?

2025-03-29 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2025-04-01 08:27 UTC, stanciuadrian commented
@t8m, could you please enable the CI workflows?

2025-04-01 17:55 UTC, nhorman commented
My results:
```
master
======
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
sha384          101015.23k   404744.19k   737599.40k  1108408.32k  1299660.80k  1316580.01k
sha512          101999.13k   406851.01k   738956.03k  1107295.23k  1298628.61k  1315826.35k
sha512-224      101566.91k   404883.73k   738147.93k  1109486.59k  1300234.24k  1316951.38k
sha512-256      101991.37k   407033.75k   742700.80k  1109605.03k  1298642.26k  1315782.66k

branch 26147
============
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
sha384          171234.76k   684023.47k  1849964.20k  3902573.23k  5765712.55k  5978991.27k
sha512          171595.65k   685518.81k  1845805.23k  3893685.59k  5765174.61k  5977238.19k
sha512-224      169970.08k   680814.87k  1840055.47k  3904490.08k  5765193.73k  5976118.61k
sha512-256      173015.29k   690231.62k  1856828.50k  3896105.98k  5767951.70k  5979504.64k

speedup (slowdown)
=============================
sha384          1.6951       1.6900      2.5080       3.5208       4.4363   4.5413
sha512          1.6962       1.6965      2.5127       3.5185       4.4415   4.5442
sha512-224      1.6734       1.6815      2.4928       3.5191       4.4339   4.5378
sha512-256      1.6963       1.6957      2.5001       3.5112       4.4415   4.5444
```

Looks to match those reported at the top of the PR

2025-04-01 17:55 UTC, nhorman approved these changes

2025-04-01 23:32 UTC, paulidale approved these changes

2025-04-02 16:10 UTC, tom-cosgrove-arm commented
There is a timer that starts when `approval: done` is set, that will automatically move to `approval: ready to merge` after 24 hours, provided no-one comments on the PR :). (This is to allow for those "oh, I didn't think of that at the time!" thoughts that come hours later, or for people who were AFK during the approval process to veto if they see an issue, while allowing a relatively automatic progression towards merging)

2025-04-03 00:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been  updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2025-04-03 00:15 UTC, paulidale commented
Merged after resolving a trivial CHANGES.md conflict.
Thanks for the contribution.

2025-04-03 00:15 UTC, closed without merging