Check returns of sk_X509_CRL_push and handle appropriately.
openssl/openssl pull request #26234
Opened 2024-12-21 13:30 UTC by fwh-dc

Related to #26227. There are `sk_X509_CRL_push()` return values that aren't checked.

2024-12-23 08:40 UTC, mattcaswell requested changes

2024-12-25 21:43 UTC, fwh-dc commented on crypto/cmp/cmp_asn.c
> -        (void)sk_X509_CRL_push(crls, crl_copy); /* cannot fail */
good point

2024-12-25 21:44 UTC, fwh-dc commented on apps/lib/apps.c
> +    if (crl && !sk_X509_CRL_push(crls, crl))
Had forgotten to add it to the goto body. Done now.

2024-12-25 21:44 UTC, fwh-dc commented on apps/crl2pkcs7.c
>              goto end;
Good point.

2025-01-06 20:57 UTC, Sashan submitted a review, later dismissed
I think this should go in.

2025-01-07 07:17 UTC, t8m requested changes

2025-01-07 07:17 UTC, t8m commented on test/crltest.c
> +
up_ref can fail. Can you please check the return value of up_ref first and only if it succeeds, push it. And free() on failed push of course to down_ref.

2025-01-07 09:05 UTC, fwh-dc commented on test/crltest.c
> +
You're right. It is actually fixed correctly in #26294. I'll just revert this change to avoid the conflict.

2025-01-08 10:29 UTC, t8m approved these changes

2025-01-23 08:58 UTC, fwh-dc commented
@Sashan Can this go in?

2025-01-23 10:24 UTC, t8m commented
ping @openssl/committers for review

2025-01-23 10:27 UTC, beldmit approved these changes
LGTM

2025-01-24 11:00 UTC, openssl-machine commented
This pull request is ready to merge

2025-01-24 12:38 UTC, t8m commented
Merged to the master branch. Thank you for your contribution.

2025-01-24 12:38 UTC, closed without merging

2025-01-24 14:08 UTC, t8m commented on crypto/cmp/cmp_asn.c
>              goto err;
It's harmless so IMO not worth it.