Add a funding.json file
openssl/openssl pull request #26247
Opened 2024-12-23 11:33 UTC by mattcaswell

For details about this file format see:
https://floss.fund/funding-manifest/

2024-12-23 11:43 UTC, mattcaswell commented
Hmmm. The check_docs CI failure is unrelated. See [this comment](https://github.com/openssl/openssl/pull/26157#issuecomment-2559535648).

2024-12-23 18:54 UTC, t8m approved these changes
Approved with the nit fixed

2024-12-23 18:54 UTC, t8m commented on funding.json
> +        "description": "The OpenSSL software library is a robust, commercial-grade, full-featured toolkit for general-purpose cryptography and secure communication. It is a fundamental open source co
Nit: add missing space `... keep our users safe. The features...`

2024-12-24 06:33 UTC, levitte requested changes
The specification is quite specific about the wellKnown URL (emphasis mine):

> ... the wellKnown URL **must** point to a /.well-known/funding-manifest-urls file

Ref: https://floss.fund/funding-manifest/#wellknown

Also, we should ensure that this file is present on the relevant websites before merging this PR.  Are there website PRs doing this already?  Would you mind linking to them?

2024-12-24 06:33 UTC, levitte commented on funding.json
> +            "wellKnown": "https://openssl-foundation.org/funding-manifest-urls"
Should be https://openssl-foundation.org/.well-known/funding-manifest-urls

2024-12-24 06:33 UTC, levitte commented on funding.json
> +            "wellKnown": "https://openssl-library.org/funding-manifest-urls"
Should be https://openssl-library.org/.well-known/funding-manifest-urls

2024-12-24 07:51 UTC, mattcaswell commented
Feedback addressed. Please take another look.

2024-12-24 08:08 UTC, levitte commented
LGTM.  But, my approval is pending the /.well-known/funding-manifest-urls files being in place

2024-12-30 13:59 UTC, t8m approved these changes

2024-12-30 13:59 UTC, t8m commented
> LGTM. But, my approval is pending the /.well-known/funding-manifest-urls files being in place

Should be in place now

2025-01-03 16:08 UTC, beldmit approved these changes
LGTM

2025-01-04 07:25 UTC, hlandau approved these changes

2025-01-04 08:24 UTC, levitte commented
> > LGTM. But, my approval is pending the /.well-known/funding-manifest-urls files being in place
> 
> Should be in place now

They are

2025-01-04 08:24 UTC, levitte approved these changes

2025-01-04 17:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but as this PR has been  updated in that time the label 'approval: ready to merge' is not being automatically set.  Please review the updates and set the label manually.

2025-01-06 14:03 UTC, mattcaswell commented
Pushed.

2025-01-06 14:03 UTC, closed without merging