Check returns of several sk_XXX_push functions and handle appropriately.
openssl/openssl pull request #26240
Opened 2024-12-21 21:18 UTC by fwh-dc

Check returns of sk_POLICY_MAPPING_push, sk_GENERAL_NAME_push, sk_ACCESS_DESCRIPTION_push, sk_X509_push, sk_X509_NAME_push, sk_OPENSSL_CSTRING_push, sk_SCT_push, sk_DIST_POINT_push, sk_OSSL_CMP_CRLSTATUS_push, sk_ASN1_UTF8STRING_push and sk_ASN1_OBJECT_push and handle appropriately.

The only missing checks are some from sk_SSL_CIPHER_push(). But I couldn't find a nice way to handle it.

2024-12-30 10:12 UTC, t8m requested changes

2024-12-30 10:12 UTC, t8m commented on apps/cmp.c
> +        || (itav = OSSL_CMP_ITAV_new0_certProfile(sk)) == NULL)
I'd keep this as is.

2024-12-30 10:12 UTC, t8m commented on apps/lib/names.c
>      sk_OPENSSL_CSTRING_push(names, name);
I'd just add a comment and `(void)` cast.

2024-12-30 10:12 UTC, t8m commented on crypto/cmp/cmp_asn.c
> -    (void)sk_GENERAL_NAME_push(names, name); /* cannot fail */
Please keep as is

2024-12-30 10:12 UTC, t8m commented on crypto/cmp/cmp_genm.c
> +        || (req = OSSL_CMP_ITAV_new0_crlStatusList(list)) == NULL)
Please keep as is

2024-12-30 10:12 UTC, t8m commented on crypto/conf/conf_lib.c
>          sk_OPENSSL_CSTRING_push(names, v->section);
Please do not add TODO comments. Just say, we are ignoring a failure.

2024-12-30 10:12 UTC, t8m commented on crypto/x509/v3_crld.c
> +                || !ossl_assert(sk_DIST_POINT_push(crld, point)))
Same as elsewhere I would not change this. We can depend on no failure on pre-reserved pushes.

2025-01-03 07:43 UTC, fwh-dc commented
@t8m Thanks, for the review. I've fixed your comments and some additional similar cases.

2025-01-03 14:49 UTC, t8m approved these changes

2025-01-06 21:44 UTC, Sashan approved these changes
I think those changes should go in.

2025-01-07 22:00 UTC, openssl-machine commented
This pull request is ready to merge

2025-01-08 10:12 UTC, t8m commented
Merged to the master branch with adjusted commit message (the title should be just a short one line text, the rest should be in the commit message body). Thank you for your contribution.

2025-01-08 10:12 UTC, closed without merging