Workaround for RSA on AArch64 Big Endian
openssl/openssl pull request #26257
Opened 2024-12-24 11:27 UTC by nickolaev

10646160125 introduced and optimized RSA NEON implementation for AArch64 architecture, namely Cortex-A72 and Neoverse N1. This implementation is broken in Big Endian mode, which is not widely used, therefore not properly verified.
Here we disable this optimized implementation when Big Endian platform is used.

Fixes: #22687

2024-12-25 14:32 UTC, fochoao-alt requested changes
```
b.ne    .Lmul_mont
    cmp     $num,#32
    b.le    .Lscalar_impl
#ifndef __KERNEL__
#ifndef __AARCH64EB__
    adrp    x17,OPENSSL_armv8_rsa_neonized
    ldr     w17,[x17,#:lo12:OPENSSL_armv8_rsa_neonized]
    cbnz    w17, bn_mul8x_mont_neon
#endif
#endif
```

2024-12-30 14:31 UTC, t8m commented
Could you please amend the commit message to include `CLA: trivial` on a separate line?

2025-01-03 11:37 UTC, fochoao-alt approved these changes

2025-01-06 11:32 UTC, tom-cosgrove-arm commented
Ping @paul-elliott-arm for visibility

2025-01-06 19:02 UTC, fochoao-alt commented
CLA: trivial

2025-01-06 19:04 UTC, fochoao-alt commented
> Could you please amend the commit message to include `CLA: trivial` on a separate line?

CLA: trivial

[openssl-cla-trivial.pdf](https://github.com/user-attachments/files/18323516/openssl-cla-trivial.pdf)

2025-01-06 19:09 UTC, fochoao-alt requested changes
CLA: trivial

2025-01-06 19:19 UTC, t8m commented
> > Could you please amend the commit message to include `CLA: trivial` on a separate line?
> 
> CLA: trivial
> 
> [openssl-cla-trivial.pdf](https://github.com/user-attachments/files/18323516/openssl-cla-trivial.pdf)

That must be done by the author of the pull request.

2025-01-06 19:25 UTC, fochoao-alt commented
> > > Could you please amend the commit message to include `CLA: trivial` on a separate line?
> > 
> > 
> > CLA: trivial
> > [openssl-cla-trivial.pdf](https://github.com/user-attachments/files/18323516/openssl-cla-trivial.pdf)
> 
> That must be done by the author of the pull request.

Ok, thanks for letting me know.
Fernando Ochoa Olivares

MIT Researcher.

2025-01-09 11:38 UTC, t8m approved these changes

2025-01-09 11:57 UTC, tom-cosgrove-arm approved these changes
LGTM, thanks!

2025-01-10 07:40 UTC, fochoao-alt commented
CLA: trivial

2025-01-10 12:00 UTC, openssl-machine commented
This pull request is ready to merge

2025-01-15 16:54 UTC, t8m commented
Merged to all the active branches. Thank you for your contribution.

2025-01-15 16:54 UTC, closed without merging