fix read out of buffer bounds when dealing with BIO_ADDR
openssl/openssl pull request #26252
Opened 2024-12-23 16:05 UTC by Sashan

This issue was discoevered while I was testing SSL_new_from_listener() using a newly created unit test. It has turned out the QUIC stack at few places contain pattern as follows:
	foo(QUIC_WHATEVER *q, BIO_ADDR *a)
	{
	   q->a = *a;
	}

The problem is that derefencning a that way is risky. If the address `a` comes from BIO_lookup_ex() it may actually be shorter than sizeof(BIO_ADDR). Using BIO_ADDR_copy() is the right thing to do here.

Fixes: #26241

2024-12-23 16:22 UTC, mattcaswell requested changes

2024-12-23 16:22 UTC, mattcaswell commented on ssl/quic/quic_channel.c
> -    ch->addressed_mode  = 1;
Why do we lose this line in this case?

2024-12-23 16:22 UTC, mattcaswell commented on ssl/quic/quic_record_tx.c
> +                BIO_ADDR_copy(&txe->local, pkt->local);
Don't we need to check the return value of these two calls?

2024-12-24 08:10 UTC, mattcaswell approved these changes

2024-12-24 08:10 UTC, mattcaswell commented on test/recipes/75-test_quicapi_data/ssltraceref.txt
> +  Length: 81
It's slightly surprising that this PR would impact the ssltraceref.txt. I'm not really sure why it has.

2024-12-26 18:58 UTC, t8m approved these changes

2024-12-26 19:00 UTC, t8m commented
Hmm... and the CI is relevant. Not sure why the trace is now different on Linux vs Windows. This should be investigated.

2024-12-26 20:41 UTC, fochoao-alt approved these changes

2024-12-30 17:35 UTC, t8m approved these changes

2025-02-22 00:08 UTC, openssl-machine commented
This PR is in a state where it requires action by @openssl/committers but the last update was 30 days ago

2025-02-22 04:29 UTC, vdukhovni approved these changes

2025-02-25 14:57 UTC, t8m commented
Squashed and merged to the master, 3.4, 3.3 and 3.2 branches. Thank you.

2025-02-25 14:57 UTC, closed without merging