cleanup for dead assignment to argc
openssl/openssl pull request #26273
Opened 2024-12-27 06:39 UTC by alexprabhat99

Fixes: #25825

2024-12-28 04:56 UTC, fochoao-alt approved these changes

2024-12-30 14:23 UTC, t8m approved these changes
OK with CLA: trivial

2024-12-31 12:19 UTC, fochoao-alt commented
Sounds better.

2024-12-31 13:07 UTC, tom-cosgrove-arm requested changes
I would be okay with CLA: trivial, but it needs to be in the commit message:

@alexprabhat99  we need you to amend the commit message (replacing the existing commit) to contain `CLA: trivial` on a separate line in the commit message body, separated from the rest of the commit message by an empty line. See https://openssl-library.org/policies/cla/index.html. For an example, see [my comment here](https://github.com/openssl/openssl/pull/25257#pullrequestreview-2255031758).

2025-01-21 20:33 UTC, paulidale approved these changes

2025-01-21 20:34 UTC, paulidale commented
I'm okay with CLA: trivial too.

2025-01-23 09:00 UTC, openssl-machine commented
24 hours has passed since 'approval: done' was set, but this PR has failing CI tests. Once the tests pass it will get moved to 'approval: ready to merge' automatically,alternatively please review and set the label manually.

2025-01-23 10:22 UTC, t8m commented
Merged to the master branch. Thank you for your contribution.

2025-01-23 10:22 UTC, closed without merging