Refactor PEM_read_bio_{PrivateKey,Parameters,DHparams}
openssl/openssl pull request #2746
Opened 2017-02-25 23:39 UTC by levitte

They now go through internal STORE routines to do their job.

Just like #2696 and #2697, this PR will not build correctly until #1961, #2011 and #2745 have been approved and merged.

2017-02-27 01:42 UTC, kaduk commented
This seems like it might make it harder for #1700 to achieve its goal of using memory from the secure heap for the temporary buffer used while reading private keys from disk.
(It looks like the latest version of that hasn't gotten any team review despite sitting there for a while ... probably overdue for a rebase, anyway, I suppose.)

2017-02-27 05:17 UTC, levitte commented
Not really, but the proper place would be to introduce secure heap in `crypto/store/loader_file.c` in #2011.

2017-02-27 13:32 UTC, levitte commented
I just added some code in #2011 that adds support for finer control of loaders.  With that, the following diff should provide fairly good support for what you do in #1700, no?

``` diff
diff --git a/crypto/store/loader_file.c b/crypto/store/loader_file.c
index 9d7e860dec..b59ecf6113 100644
--- a/crypto/store/loader_file.c
+++ b/crypto/store/loader_file.c
@@ -551,6 +551,8 @@ struct store_loader_ctx_st {
         is_pem,
         is_dir
     } type;
+#define FILE_FLAG_SECMEM         (1<<0)
+    unsigned int flags;
     union {
         struct {                 /* Used with is_raw and is_pem */
             BIO *file;
@@ -737,6 +739,36 @@ static STORE_LOADER_CTX *file_open(const char *scheme, const char *user,
     return NULL;
 }
 
+int file_ctrl(STORE_LOADER_CTX *ctx, int cmd, va_list args)
+{
+    int ret = 1;
+
+    switch (cmd) {
+    case STORE_C_USE_SECMEM:
+        {
+            int on = *(va_arg(args, int *));
+
+            switch (on) {
+            case 0:
+                ctx->flags &= ~FILE_FLAG_SECMEM;
+                break;
+            case 1:
+                ctx->flags |= FILE_FLAG_SECMEM;
+                break;
+            default:
+                STOREerr(STORE_F_FILE_CTRL, ERR_R_PASSED_INVALID_ARGUMENT);
+                ret = 0;
+                break;
+            }
+        }
+        break;
+    default:
+        break;
+    }
+
+    return ret;
+}
+
 static STORE_INFO *file_load_try_decode(STORE_LOADER_CTX *ctx,
                                         const char *pem_name,
                                         const char *pem_header,
@@ -862,12 +894,22 @@ static STORE_INFO *file_load_try_repeat(STORE_LOADER_CTX *ctx,
     return result;
 }
 
+static void pem_free_flag(char *pem_data, int secure)
+{
+    if (secure)
+        OPENSSL_secure_free(pem_data);
+    else
+        OPENSSL_free(pem_data);
+}
 static int file_read_pem(BIO *bp, char **pem_name, char **pem_header,
                          unsigned char **data, long *len,
                          const UI_METHOD *ui_method,
-                         void *ui_data)
+                         void *ui_data, int secure)
 {
-    int i = PEM_read_bio(bp, pem_name, pem_header, data, len);
+    int i = secure
+        ? PEM_read_bio_flags(bp, pem_name, pem_header, data, len,
+                             PEM_FLAG_SECURE);
+        : PEM_read_bio(bp, pem_name, pem_header, data, len);
 
     if (i <= 0)
         return 0;
@@ -881,9 +923,9 @@ static int file_read_pem(BIO *bp, char **pem_name, char **pem_header,
                                         ui_data)
             || !PEM_do_header(&cipher, *data, len, file_get_pem_pass,
                               &pass_data)) {
-            OPENSSL_free(*pem_name);
-            OPENSSL_free(*pem_header);
-            OPENSSL_free(*data);
+            pem_free_flag(*pem_name, secure);
+            pem_free_flag(*pem_header, secure);
+            pem_free_flag(*data, secure);
             *pem_name = NULL;
             *pem_header = NULL;
             *data = NULL;
@@ -1064,7 +1106,8 @@ static STORE_INFO *file_load(STORE_LOADER_CTX *ctx,
             matchcount = -1;
             if (ctx->type == is_pem) {
                 if (!file_read_pem(ctx->_.file.file, &pem_name, &pem_header,
-                                   &data, &len, ui_method, ui_data))
+                                   &data, &len, ui_method, ui_data,
+                                   (ctx->flags & FILE_FLAG_SECMEM) != 0))
                     goto err;
             } else {
                 if (!file_read_asn1(ctx->_.file.file, &data, &len))
@@ -1075,9 +1118,9 @@ static STORE_INFO *file_load(STORE_LOADER_CTX *ctx,
                                           ui_method, ui_data, &matchcount);
 
          err:
-            OPENSSL_free(pem_name);
-            OPENSSL_free(pem_header);
-            OPENSSL_free(data);
+            pem_free_flag(pem_name, (ctx->flags & FILE_FLAG_SECMEM) != 0);
+            pem_free_flag(pem_header, (ctx->flags & FILE_FLAG_SECMEM) != 0);
+            pem_free_flag(data, (ctx->flags & FILE_FLAG_SECMEM) != 0);
         } while (matchcount == 0 && !file_eof(ctx));
 
         /* We bail out on ambiguity */
diff --git a/include/openssl/store.h b/include/openssl/store.h
index e73b1df01b..f8ee6cd5be 100644
--- a/include/openssl/store.h
+++ b/include/openssl/store.h
@@ -70,6 +70,8 @@ int STORE_ctrl(STORE_CTX *ctx, int cmd, ... /* args */);
 /*
  * Common ctrl commands that different loaders may choose to support.
  */
+/* int on = 0 or 1; STORE_ctrl(ctx, STORE_C_USE_SECMEM, &on); */
+# define STORE_C_USE_SECMEM      1
 /* Where custom commands start */
 # define STORE_C_CUSTOM_START    100
 
```

2017-02-27 13:36 UTC, levitte commented
To finalize support in this PR:

``` diff
diff --git a/crypto/pem/pem_pkey.c b/crypto/pem/pem_pkey.c
index 01b9828534..8b9d014a8e 100644
--- a/crypto/pem/pem_pkey.c
+++ b/crypto/pem/pem_pkey.c
@@ -38,6 +38,13 @@ EVP_PKEY *PEM_read_bio_PrivateKey(BIO *bp, EVP_PKEY **x, pem_password_cb *cb,
 
     if ((ctx = store_attach_pem_bio(bp, ui_method, u)) == NULL)
         goto err;
+#ifndef OPENSSL_NO_SECURE_HEAP
+    {
+        int on = 1;
+        if (STORE_ctrl(ctx, STORE_C_USE_SECMEM, &on))
+            goto err;
+    }
+#endif
 
     while ((info = STORE_load(ctx)) != NULL
            && STORE_INFO_get_type(info) != STORE_INFO_UNSPECIFIED) {
@@ -88,6 +95,13 @@ EVP_PKEY *PEM_read_bio_Parameters(BIO *bp, EVP_PKEY **x)
 
     if ((ctx = store_attach_pem_bio(bp, UI_null(), NULL)) == NULL)
         goto err;
+#ifndef OPENSSL_NO_SECURE_HEAP
+    {
+        int on = 1;
+        if (STORE_ctrl(ctx, STORE_C_USE_SECMEM, &on))
+            goto err;
+    }
+#endif
 
     while ((info = STORE_load(ctx)) != NULL
            && STORE_INFO_get_type(info) != STORE_INFO_UNSPECIFIED) {
@@ -171,6 +185,13 @@ DH *PEM_read_bio_DHparams(BIO *bp, DH **x, pem_password_cb *cb, void *u)
 
     if ((ctx = store_attach_pem_bio(bp, ui_method, u)) == NULL)
         goto err;
+#ifndef OPENSSL_NO_SECURE_HEAP
+    {
+        int on = 1;
+        if (STORE_ctrl(ctx, STORE_C_USE_SECMEM, &on))
+            goto err;
+    }
+#endif
 
     while ((info = STORE_load(ctx)) != NULL
            && STORE_INFO_get_type(info) != STORE_INFO_UNSPECIFIED) {
```

2017-02-27 13:37 UTC, levitte commented
*Note: I haven't tested those diffs*

2017-02-27 17:06 UTC, kaduk commented
> With that, the following diff should provide fairly good support for what you do in #1700, no?

Looks like it (and not very hairy, either).
I guess I should get cracking on the PEM-reader test corpus I've got sitting around, and then update #1700.

2019-10-31 13:37 UTC, mattcaswell commented
Needs a rebase

2019-11-04 14:00 UTC, mattcaswell requested changes

2019-11-04 14:00 UTC, mattcaswell commented on crypto/pem/pem_pkey.c
> +        if (!OSSL_STORE_ctrl(ctx, OSSL_STORE_C_USE_SECMEM, &on))
As above: is this actually necessary?

2019-11-04 14:10 UTC, levitte commented on crypto/pem/pem_pkey.c
> +        if (!OSSL_STORE_ctrl(ctx, OSSL_STORE_C_USE_SECMEM, &on))
Good question. I cannot remember why I did this, it might just be thoughtless copy-n-paste

2019-11-06 13:18 UTC, levitte commented on crypto/pem/pem_pkey.c
> +        if (!OSSL_STORE_ctrl(ctx, OSSL_STORE_C_USE_SECMEM, &on))
Fixed

2019-11-06 13:18 UTC, levitte commented on crypto/pem/pem_pkey.c
> +        if (!OSSL_STORE_ctrl(ctx, OSSL_STORE_C_USE_SECMEM, &on))
Fixed

2019-11-06 13:18 UTC, levitte commented
Rebased and fixups added

2019-11-06 13:33 UTC, mattcaswell approved these changes

2019-11-07 22:38 UTC, levitte commented
Merged.

1427d33cee59d6fe54efe1b5a322a1d7c8c03c20 Refactor PEM_read_bio_{PrivateKey,Parameters,DHparams}

2019-11-07 22:38 UTC, closed without merging