Make getting and setting the RAND default method thread safe
openssl/openssl pull request #3137
Opened 2017-04-06 09:32 UTC by levitte

From a comment in #3136, where it was noticed that `RAND_set_rand_method()` and friends weren't thread safe.

2017-04-06 12:21 UTC, mattcaswell requested changes
I wonder what the performance impact of this is?

2017-04-06 12:21 UTC, mattcaswell commented on crypto/rand/rand_lib.c
> +    OPENSSL_init_crypto(0, NULL);
Why is this necessary? It looks like a potential source of deadlocks

2017-04-06 12:21 UTC, mattcaswell commented on crypto/rand/rand_lib.c
>      return default_RAND_meth;
Are assignments atomic? This read of the variable is unprotected by a lock, so I wonder what happens if RAND_set_rand_method() is executed at the same time as this read is taking place.

2017-04-06 12:25 UTC, levitte commented on crypto/rand/rand_lib.c
>      return default_RAND_meth;
It's protected by the read on line 58, no?

2017-04-06 12:25 UTC, levitte commented on crypto/rand/rand_lib.c
>      return default_RAND_meth;
Or oh, RAND_*set*_rand_method()!  Ok, I get what you mean

2017-04-06 12:26 UTC, levitte commented on crypto/rand/rand_lib.c
> +    OPENSSL_init_crypto(0, NULL);
Perhaps it isn't...  I copied this stoopidly from the one in `md_rand.c`...

2017-04-06 12:35 UTC, levitte commented
Fixed all outstanding concerns

> I wonder what the performance impact of this is?

Good question

2017-04-06 12:44 UTC, mattcaswell commented
Travis is showing a failure.

2017-04-06 12:48 UTC, mattcaswell commented on crypto/rand/rand_lib.c
> +    tmp_meth = default_RAND_meth;
Does default_RAND_meth have to be declared volatile for this to work? Can the compiler "optimise" this solution away? I'm not really sure.

2017-04-06 12:50 UTC, levitte commented
> Travis is showing a failure.

Yeah, I forgot to free the locks...

2017-04-06 13:04 UTC, levitte commented
You know, this isn't done anywhere else (have a look at `crypto/rsa/rsa_lib.c` for example), and back in #3136, @richsalz makes a good point reminding us of #2244.  Closing this.

2017-04-06 13:07 UTC, mattcaswell commented
I'm confused. The discussion in #2244 seems to suggest that this PR has it exactly right and is what we should be doing??

2017-04-06 13:18 UTC, levitte commented
Maybe I'm confused too, I thought it about redoing the whole defaults stuff to happen mostly at compile time...

2017-04-06 15:13 UTC, mattcaswell commented
Travis is now passing. LGTM. My only outstanding question is my one on volatile above.

2017-04-06 17:53 UTC, kaduk reviewed
> redoing the whole defaults stuff to happen mostly at compile time...

There's using compile-time initialization instead of CRYPTO_THREAD_run_once(), and then there's having the default_foo variable for what is the default method when a method is not explicitly specified.  The latter makes sense to allow changing at runtime.

2017-04-06 17:53 UTC, kaduk commented on crypto/rand/rand_lib.c
> +    tmp_meth = default_RAND_meth;
I believe that the function call to unlock will provide a compiler-level barrier (and the lock itself will give a memory barrier at runtime).  Function calls are considered to have side effects, in the abstract machine.

2017-04-06 18:32 UTC, levitte commented
So, errr, was that an approval hidden in there somewhere?

2017-04-06 18:55 UTC, kaduk approved these changes
Sure, you can count it as an approval from me if you want.  (Not that it adds up to anything concrete, of course.)

2017-04-06 18:55 UTC, kaduk commented on crypto/rand/rand_lib.c
>  static const RAND_METHOD *default_RAND_meth = NULL;
In other projects I usually see a comment "requires rand_meth_lock for access" or semantically similar; do we want to do something like that?

2017-04-06 20:02 UTC, mattcaswell approved these changes

2017-04-07 02:56 UTC, levitte commented
Merged.

master: 87975cfa91c3f06a52f2550ed2ef632644be6dde and 789a2b6250d5e05dfde6ce259e79ef8c172c9f3f
1.1.0: 67114d93b47aa02192272182595c2b5d1bba8298 and df13eb7ae70073de8c95ca3c7d2f587037582470

2017-04-07 02:56 UTC, closed without merging