Refactor INTxx to be like other ASN.1 types, and embed the items explicitely
openssl/openssl pull request #3199
Opened 2017-04-12 10:16 UTC by levitte

##### Checklist

- [x] tests are added or updated

2017-04-12 10:16 UTC, levitte commented
Separate 1.1.0 backport coming up next.

2017-04-12 10:19 UTC, levitte commented
1.1.0 backport in #3200

2017-04-12 10:37 UTC, levitte commented
Rebased to include the new test in #3174, which was what started this effort.  It'll be exciting to see how this goes.

2017-04-12 11:20 UTC, levitte commented
Ouch...  I just played with external tests, and there are errors...

@jon-oracle, you know pyca, right?  I'd like to debug the issues I get, but haven't the faintest clue how to go about it...  Would you mind giving me a quick crash course?

2017-04-12 11:26 UTC, levitte commented
Likewise, I haven't the faintest clue how to debug the BoringSSL stuff...  @mattcaswell, do you have some quick instructions?  I had a quick look at runner.go, and noticed it's possible to run tests under GDB, but I don't know go enough to know how to actually do that...

2017-04-12 12:03 UTC, levitte commented
For BoringSSL, I suspect the failures are unrelated to this PR.  I get similar errors with ce57ac4, which is pre-INTxx.

2017-04-12 12:06 UTC, levitte commented
... and the same goes for the pyca tests.

2017-04-12 13:25 UTC, dot-asm commented
SPARC passes tests. Well, I haven't tested #3174, but fuzz tests that previously crashed, don't anymore.

2017-04-12 13:32 UTC, levitte commented
Errrr, you *have* tested #3174, since it's been merged into master and this PR has been rebased on top of that.

2017-04-12 13:43 UTC, dot-asm commented
> you have tested #3174,

I've meant the one that tries to trigger the problem deliberately, and it's #3190. Sorry about confusion :-)

2017-04-12 13:45 UTC, levitte commented
Ah, thanks for the reminder, that one needs a rebase, it seems...

2017-04-12 19:38 UTC, kaduk approved these changes
Thanks for doing this.

2017-04-12 19:38 UTC, kaduk commented on crypto/asn1/x_int64.c
> +    **(uint64_t **)pval = 0;
This is perhaps playing a little fast-and-loose with the spec, in that while **pval is created as an object of type uint64_t, *pval was created as an object of type ASN1_VALUE *.  But, if that sort of distinction was going to cause runtime problems, ~all of the ASN.1 code would be affected, and this change is still a vast improvement over what it's replacing, so I wouldn't worry about it.
(I'll just comment on the one instance, even though there are others.)

2017-04-12 20:02 UTC, levitte commented on crypto/asn1/x_int64.c
> +    **(uint64_t **)pval = 0;
If you have a look around, you'll find that `ASN1_VALUE` has no definition apart from a typedef:

```
: ; git grep ASN1_VALUE_st
include/openssl/asn1.h:typedef struct ASN1_VALUE_st ASN1_VALUE;
```

That means that `*pval` is create as an object of *whatever* and then being cast to `ASN1_VALUE *` so we have a consistent C type to throw around in the rest of the code.

It's true, though, that we "play a little fast-and-loose" insofar that we trust the programmer to map the ASN.1 types to the correct corresponding C type.  If the programmer gets that wrong, there's hell to pay (quite literally in some cases).  This is well known, and we dont worry about it...  too much ;-)  (that, or we quietly wisper "Here be dragons" and hope we don't awaken C'Thulu)

2017-04-12 20:03 UTC, kaduk commented on crypto/asn1/x_int64.c
> +    **(uint64_t **)pval = 0;
Yup :)

2017-04-12 20:12 UTC, levitte commented
@openssl/team, I wonder about the hold up.  The current situation with INTxx isn't pretty, this fix is needed

2017-04-12 22:16 UTC, levitte commented
Found one bug.  Fix coming up.

2017-04-12 22:55 UTC, mattcaswell commented
I looked at this and have to admit I have absolutely no clue as to how this works.

2017-04-12 23:53 UTC, mattcaswell requested changes
I spent the last hour going through this and think I've got a better handle on how this works. Just one comment

2017-04-12 23:53 UTC, mattcaswell commented on crypto/asn1/x_int64.c
> +    if (*pval == NULL && !uint64_new(pval, it))
Does this ever get exercised in our tests at the moment? If I understand things correctly this will only ever happen when it is non-embedded.

2017-04-13 04:25 UTC, jon-oracle commented
@levitte re your comment on pyca, I'm by no means an expert but if there are any problems let me know and I'll take a look

2017-04-13 05:39 UTC, levitte commented on crypto/asn1/x_int64.c
> +    if (*pval == NULL && !uint64_new(pval, it))
Actually, yes. `fuzz/asn1.c` exercises these types as non-embedded. That's how I discovered the need for this very line

2017-04-13 05:41 UTC, levitte commented
@jon-oracle, thanks. The pyca issue turned out to be unrelated to this PR, though.

2017-04-13 06:45 UTC, levitte commented
> I spent the last hour going through this and think I've got a better handle on how this works.

I understand perfectly.  I haven't even dared to go too deep into the asn1 code before now...

2017-04-13 08:12 UTC, mattcaswell approved these changes
It occurs to me that if we ever encounter a platform where sizeof(long) != sizeof(void *) then the LONG/ZLONG datatype will be unfixable on that platform (at least by this mechanism). We can only do this for the INTxx datatypes because they are new.

2017-04-13 08:21 UTC, levitte commented
> It occurs to me that if we ever encounter a platform where sizeof(long) != sizeof(void *) then the LONG/ZLONG datatype will be unfixable on that platform (at least by this mechanism). We can only do this for the INTxx datatypes because they are new.

Yup.  P64L32 systems beware, I'm well aware of that.  That's why I've abolished all our uses of LONG / ZLONG on master (should 6a32a3c058dbd9fa7cec5b020e4f027808972e4a be backported to 1.1.0?)

2017-04-13 08:24 UTC, levitte commented
Merged.  49005bb8b3e134d5c8c5c8fc87aecb74d1437286 to 9612e15760784c59d3104bfe49e75323e5776bb1

2017-04-13 08:24 UTC, closed without merging

2017-04-13 09:07 UTC, dot-asm commented
Problem with this approach is that it doesn't actually fixes the #3191, but works around it. I mean it simply makes specific types in question work, but problem is still there. In other words either ASN1_TFLG_EMBED should not be even an option, or there still is a problem to fix...

2017-04-13 09:22 UTC, levitte commented
Not sure I understand.  `ASN1_TFLG_EMBED` exists exactly for this purpose, to have some stuff directly embedded in the corresponding struct instead of having a pointer to that stuff, no?

The issue of #3191 happened because the upper level ASN.1 code *assumes* the field is a pointer unless marked as embedded.  Take away that assumption and the problem goes away.  The description in #3191 isn't exactly right, by the way...

2017-04-13 09:40 UTC, levitte commented
Too say it bluntly, LONG / ZLONG is the abusive bastard of the current  asn1 code... But it came along long before ASN1_TFLG_EMBED if I'm correctly informed, so it's forgiven as it's slowly put to rest.

2017-04-13 10:02 UTC, levitte commented
I've added an addendum in #3191 to clarify the issue.

2017-04-13 12:38 UTC, richsalz commented
> if we ever encounter a platform where sizeof(long) != sizeof(void *)

Add a test to sanitytest to make sure that the builds fail, then.

2017-04-13 12:47 UTC, levitte commented
Given `type-lp.se`:

``` C
#include <assert.h>
#include <stdio.h>

int main()
{
    printf("sizeof(long) = %u\n", sizeof(long));
    printf("sizeof(void *) = %u\n", sizeof(void *));
    assert(sizeof(long) == sizeof(void *));
}
```

I already know one:

```
$ cc test-lp  
$ link test-lp
$ run test-lp
sizeof(long) = 4
sizeof(void *) = 4
$ cc test-lp/pointer=long
$ link test-lp
$ run test-lp
sizeof(long) = 4
sizeof(void *) = 8
assert error: expression = sizeof(long) == sizeof(void *), in file USER:[LEVITTE]TEST-LP.C;2 at line 8
%SYSTEM-F-OPCCUS, opcode reserved to customer fault at PC=FFFFFFFF80B767D4, PS=0000001B
%TRACE-F-TRACEBACK, symbolic stack dump follows
  image    module    routine             line      rel PC           abs PC      
 DECC$SHR_EV56                              0 00000000000DC7D4 FFFFFFFF80B767D4
 DECC$SHR_EV56                              0 00000000001A94F4 FFFFFFFF80C434F4
 TEST-LP  TEST-LP  main                  1699 0000000000000114 0000000000020114
 TEST-LP  TEST-LP  __main                1695 0000000000000064 0000000000020064
                                            0 FFFFFFFF8038BC04 FFFFFFFF8038BC04
%TRACE-I-END, end of TRACE stack dump
```

2017-04-13 13:27 UTC, dot-asm commented
> I've added an addendum in #3191 to clarify the issue.

Thanks.