Add the STORE module take 2, for loaded certs, keys and more given a URI (cont)
openssl/openssl pull request #3542
Opened 2017-05-25 06:28 UTC by levitte

This is a new pull request to replace #2011, which has encountered github performance issues.

This STORE module adds the following functionality:

- A function STORE_open(), STORE_load() and STORE_close() that accesses
a URI and helps loading the supported objects (PKEYs, CERTs and CRLs
for the moment) from it.
- An opaque type STORE_INFO that holds information on each loaded object.
- A few functions to retrieve desired data from a STORE_INFO reference.
- Functions to register and unregister loaders for different URI schemes.  This enables dynamic addition of loaders from applications or from engines.

Also includes a loader for the "file" scheme.  The goal is to have it load PEM files and raw DER files alike, transparently.

Fixes #1958, #1959 

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

2017-05-25 06:32 UTC, levitte commented
Copying remaining big issues from #2011:

1) `STORE_` vs `OSSL_STORE_` prefix (not yet concluded as far as I can see)
2) ENDOFDATA vs `ferror` like interface.

I'm currently working on 3.  1 is waiting on team decision (I want it to become policy if we decide for `OSSL_STORE_`)...

2017-05-25 20:23 UTC, dwmw2 commented
We spoke of the desire to keep your test cases lifted from OpenConnect, in sync with the ones I have.

So I thought I should let you know I added a new one that you should incorporate:
http://git.infradead.org/users/dwmw2/openconnect.git/commitdiff/962d242

2017-05-26 16:18 UTC, levitte commented
@dwmw2, hmmm, that will take some work to adapt, and especially since I try to be platform agnostic...

2017-05-26 16:27 UTC, levitte commented
Of the listed things to fix, I realised I forgot to add one, @t-j-h's concern with opening up internal APIs, so I'll add that here:

1) `STORE_` vs `OSSL_STORE_` prefix (not yet concluded as far as I can see)
2) **[DONE]** ~ENDOFDATA vs~ `ferror` like interface.
3) Exposing `asn1_d2i_read_bio` as internal API vs making `ASN1_d2i_bio` accept a NULL `d2i` ( @t-j-h )

I feel unsure about (3)...  exposing things internally within libcrypto is already done for other things, I don't quite see why this one is a bad thing.  @t-j-h, are you very attached to an unreachable `asn1_d2i_read_bio` or can we let that item go?

2017-05-27 09:45 UTC, dwmw2 commented
> @dwmw2, hmmm, that will take some work to adapt, and especially since I try to be platform agnostic...

The test case itself, yeah. I need to find a Windows box (suspect Wine won't cut it here) and work that out. But having an expectation that it *should* work... that's a different story (qv).

2017-05-27 10:00 UTC, dwmw2 commented
Just attempting to work out what this looks like for PKCS#11... 

Given a RFC7512 URI string (which is actually a search term that may produce more than result), we call `STORE_open()` with that URI and then iterate over the results with `STORE_load()`, yes? 

I think that works sanely, and fits the same usage model as when there is more than one object within a given file. Will we eventually have a `SSL_CTX_use_STORE(uri, ui_method, ui_data, post_process, post_process_data)` function?

The only thing I think I'm missing is explicit documentation of the lifetime of the `ui_method` and `ui_data`. I need them to last as long as the last private key exported from the store. They can't go away when the `STORE_CTX` itself does. That's to deal with `CKA_ALWAYS_AUTHENTICATE` keys (and probably hotplug and other nastiness).

2017-05-27 11:22 UTC, levitte commented
@dwmw2 wrote:
> Just attempting to work out what this looks like for PKCS#11...
> 
> Given a RFC7512 URI string (which is actually a search term that may produce more than result), we call `STORE_open()` with that URI and then iterate over the results with `STORE_load()`, yes?

Yes. Basically, it's roughly modeled from stdio, with the difference that we start with a URI in place of a file name.  

> I think that works sanely, and fits the same usage model as when there is more than one object within a given file. Will we eventually have a `SSL_CTX_use_STORE(uri, ui_method, ui_data, post_process, post_process_data)` function?

Obviously, you haven't seen #2696 and #2697... They're pretty rad, especially #2697. 

> The only thing I think I'm missing is explicit documentation of the lifetime of the `ui_method` and `ui_data`. I need them to last as long as the last private key exported from the store. They can't go away when the `STORE_CTX` itself does. That's to deal with `CKA_ALWAYS_AUTHENTICATE` keys (and probably hotplug and other nastiness).

I would expect `ui_method` to live for as long as the object (exe or dll) that implements it. As for `ui_data`, there's no general guarantee. Either way, the decision is up to the application or engine or whatever that implements the `ui_method`. 

I would expect that any condition specific to an engine *will be documented with said engine*

2017-05-27 15:50 UTC, levitte commented
@dwmw2, and idea re `ui_method` and `ui_data` is to write a `UI_METHOD` of your own that wraps around the incoming `ui_method` and that caches all responses.  The next time there's an authentication request, simply replay the cache.  It's probably not the easiest `UI_METHOD` to write, but should be doable...

2017-05-27 16:22 UTC, levitte commented
(previous comment removed...  I can't believe I wrote that out loud...)

2017-05-27 19:29 UTC, dwmw2 commented
So... If a pkcs11 STORE backend might exist one day and if my users might one day give me a string which happens to reference an object therein, as the cert they want to use... Then I need to have read that documentation before I write my application today?

I would be much happier with lifetime rules for the ui_data warning up front that *some* back ends may keep references to it for as long as keys exist.

Those other PRs... Neat. Need to think about how we handle that for system trust, especially w.r.t. `find_issuer()` which will want to specify the subject in the uri and *also* postprocess.

2017-05-27 20:12 UTC, levitte commented
Do you mean the `find_issuer` in `crypto/x509/x509_vfy.c`?  In that case, I've no idea what you're talking about...  However, if you're thinking in more general searching terms, you might want to have a look at the add-on in #2688.

2017-05-27 20:28 UTC, levitte commented
> So... If a pkcs11 STORE backend might exist one day and if my users might one day give me a string which happens to reference an object therein, as the cert they want to use... Then I need to have read that documentation before I write my application today?

Well, it would seem appropriate to read docs that come with the backends you're about to use, if there is any, no?  I don't understand why that would be questionable...  I find it as natural as having to read `socket(7)` to figure out the socket level option names and arguments for `getsockopt(3)`...

> I would be much happier with lifetime rules for the ui_data warning up front that *some* back ends may keep references to it for as long as keys exist.

Mm, good point.  I think I can write something generic enough.  I'll get back to that on Monday.

2017-05-27 20:55 UTC, dwmw2 commented
Yes I'm thinking of that `find_issuer()`. Linux distributions now tend to have trust roots in a PKCS#11 token and only export it to a flat file for backward compatibility. Iterating over all  objects​ in the token *isn't* the best way to do it. I'll take a closer look...

2017-05-27 20:57 UTC, dwmw2 commented
For the other thing... I write my application to use the STORE interface long before the back end in question even exists. A sysadmin installs the PKCS#11 back end once it's written, and a user chooses a cert with a PKCS#11 URI.   It wasn't "me" who used that back end.

2017-05-28 05:45 UTC, levitte commented
Ah, I get your point.

The *normal* thing, at least from the usual OpenSSL perspective, would be to have the backend duplicate the UI data...  which is, of course, difficult with the current UI API.  But then, I could easily add something that would do exactly that.  I would think that's a saner way of doing things.

2017-05-28 07:37 UTC, dwmw2 commented
"duplicate the ui_data"?

This is an opaque (to OpenSSL) datum which ends up being passed back to the application in order to request the password. It contains GUI context or something, and may have a chain of other refcounted objects  hanging off it that OpenSSL can know nothing about....

2017-05-28 07:44 UTC, levitte commented
See #3575.

2017-05-28 08:39 UTC, levitte commented
My thought is that if the ui_data can't be duplicated (regardless of reason), then your backend can't support things like `CKA_ALWAYS_AUTHENTICATE`.  The benefit of doing it this way is expliciteness.  The application will have to *explicitely* support this kind of duplication, and the backend will be able to return an error if that support is missing, which I think is much better than merely hoping that the application is well behaved and keeps the ui_data around for its life time (and getting mysterious crashes if it doesn't).

2017-05-28 08:48 UTC, dwmw2 commented
Ack, that works. Thanks.  A nice obvious failure mode if an app forgets to provide a dup method -- even today with just the file backend where it isn't strictly  needed -- is extra helpful.

2017-05-28 10:06 UTC, dwmw2 commented
I'm starting to wonder if a callback function to get the password might be better than a UI. People build without UI support (e.g. MacOS) and do we want it to be a dependency? The "user" prompts we offer are never going to be perfectly suited for presenting directly to the user anyway (with translations and referring to the object being unlockedj with the terminology that the app+user use for it.

Using a callback also lets us punt on the charset question and insist we only take UTF-8. Because now there is *app* code between the STORE and the `UI_OpenSSL()` *if* they happen to use that, so we can tell them it's their responsibility to convert.

We also get to convey other flags like "wrong PIN" and "last chance" with our own callback, in machine readable way (i.e. so the app can modify its behaviour and stop using the cached pin, etc.)

2017-05-28 10:15 UTC, levitte commented
I disagree.  Having a "simple" callback function will require that the application knows exactly what the backend will want to prompt for, or that the backend might find itself limited to what the callback function takes.

2017-05-28 10:23 UTC, dwmw2 commented
Yeah, that's true..  at least for a very simple function, and once you've d made it less simple it probably looks a bit like a UI... :)

Apps can put a lot of the context information into the ui_data, which helps with my first point. I'm happy to say you Sam well ought to handle charsets properly, which resolved my second point.

What remains is the "you got it wrong last time" and "you are screwed if you get it wrong again" and other time-of-invocation flags. Those are relatively easy to add to the existing UI I suppose.

2017-05-28 10:24 UTC, dwmw2 commented
Damn autocorrect

2017-06-01 08:59 UTC, dwmw2 commented
So #3575 gives us the management of `ui_data` that allows this to work with keys that require a PIN every time. What remains on this side is to make it abundantly clear to applications using the STORE interface that they must expect such, and not expect that the `ui_data` goes out of scope the moment they're done with the STORE. Bonus points for making it hard to get it wrong, by *requiring* it even for files somehow.

2017-06-01 09:08 UTC, levitte commented
I'm sorry, I didn't quite understand that last part.  "*requiring* it even for files somehow"???  How did I do that?

2017-06-01 09:09 UTC, dwmw2 commented
You didn't, and I'm not sure how to offhand. But if you can make it hard for application authors to get this wrong, I'll award bonus points :)

2017-06-01 09:44 UTC, levitte commented
I'm not even sure what "getting it wrong" would mean in this context, especially re the file scheme.  Let's just not make things overly complicated, shall we?

2017-06-01 10:38 UTC, dwmw2 commented
*"getting it wrong"* for an application would involve assuming your user will only ever use file URIs and not bothering to implement the mechanism provided in #3575, so you get unexpected breakage when the user happens to choose a hardware key that always needs a PIN.

Forcing the application to get it right... well, as I said I can't think of a great way of doing that. You're right that it's probably overly complicated. Maybe we could just make sure that the file loader invokes the UI data_destructor method only when the last EVP_PKEY goes away, not when the STORE itself is (earlier) destroyed. Or maybe a `$OPENSSL_STORE_ALWAYS_PROMPT` to make it ask for the file password again every time a key is used, even though it didn't need to. But I'm not really advocating either of those; they're just examples of the class of things we *might* consider doing. If we could find one that was simple and effective. But I suspect that documenting it extremely clearly is the best we can do.

2017-06-01 10:50 UTC, levitte commented
The file scheme loader *has no interest* in the UI user data after the loaded keys have been unlocked.  *None*.  I don't see why it should.  I understand your desire to set an example, but really...

2017-06-12 13:51 UTC, levitte commented
I renamed the lot by changing the `STORE` prefix to `OSSLSTORE`.  That should make it unique enough without becoming too bulky and without causing other trouble in our subsystems (the error codes aren't allowed to have an underscore in the prefix, for example).

Now, to rebase it on a fresher master

2017-06-26 08:58 UTC, levitte commented
Update:

1) **[DONE]** ~`STORE_` vs `OSSL_STORE_` prefix (not yet concluded as far as I can see)~ (the prefix became `OSSLSTORE_`)
2) **[DONE]** ~ENDOFDATA vs~ `ferror` like interface.
3) Exposing `asn1_d2i_read_bio` as internal API vs making `ASN1_d2i_bio` accept a NULL `d2i` ( @t-j-h )

I've received no response whatsoever re 3), so I think I'll ignore it.  After all, it's internal to libcrypto, we have a number of similar exposures already, I really don't see much harm.

@dwmw2, I've heard your concerns re character encoding, and I agree that we need a general overhaul on the matter.  *This* PR is not the place.

@openssl/committers and @openssl/omc, I think it's time for another review, maybe even a final one...

2017-06-26 10:06 UTC, mattcaswell commented
Re: STORE_ vs OSSL_STORE_ vs OSSLSTORE_, I think there was a comment from @t-j-h  (I think via email) along the lines that it should be OSSLSTORE and we should fix "make errors", but I don't recall exactly. Has that been responded to?

2017-06-26 10:42 UTC, levitte commented
"fixing" mkerr.pl to accept underscores in module names has ramifications that I have no desire digging into.  The fact that the module can't include an underscore makes for a very clear distinction where the module name ends and where the function / reason indication starts.

So, instead of battling what double prefix to use, I chose a simple rename.  The initial request was to make it unique enough, and this rename does solve that problem.  It also avoids getting extremely long symbol names (they are already long enough, adding something like `OPENSSL_` in front of them became bulky, just like you commented by email).

I certainly hope we can stay with this compromise.

2017-06-26 15:02 UTC, mattcaswell requested changes
Some relatively minor comments. When I approve this I will do so subject to no objections being raised from @t-j-h

2017-06-26 15:02 UTC, mattcaswell commented on doc/man1/storeutl.pod
> +B<uri> ...
Seems to be missing documentation for the -text option.

2017-06-26 15:02 UTC, mattcaswell commented on apps/storeutl.c
> +        OPENSSL_assert(info != NULL);
Should this be an OPENSSL_assert() here? This isn't actually an OpenSSL bug (necessarily), but an engine bug (which may be external).

2017-06-26 15:02 UTC, mattcaswell commented on crypto/store/loader_file.c
> +    }
{} not required

2017-06-26 15:02 UTC, mattcaswell commented on crypto/store/loader_file.c
> +        }
Unecessary {}

2017-06-26 15:02 UTC, mattcaswell commented on crypto/store/loader_file.c
> +     */
It looks to me like 10 is the exact length of "Proc-Type:" that PEM_get_EVP_CIPHER_INFO() is expecting to see in the header. That function will fail if it doesn't see that (unless the header length is 0 or just contains "\n".

2017-06-26 15:02 UTC, mattcaswell commented on crypto/store/store_register.c
> +        OSSLSTOREerr(OSSLSTORE_F_OSSLSTORE_LOADER_NEW, ERR_R_MALLOC_FAILURE);
return NULL?

2017-06-26 15:02 UTC, mattcaswell commented on doc/man7/store.pod
> +store - Store retrieval functions
Probably all the above library man pages should reference this page somewhere prominent near the beginning of the page (and in the SEE ALSO section).

2017-06-26 15:23 UTC, levitte commented on doc/man1/storeutl.pod
> +B<uri> ...
Ah, thanks.  Fixed

2017-06-26 15:30 UTC, levitte commented on apps/storeutl.c
> +        OPENSSL_assert(info != NULL);
Mm...  considering this is an app, and that the correct response is to break out, I wasn't too concerned.  But ok, it's probably a nice thing to allow the store to close either way, so I'll just print an error and break out of the loop.

2017-06-26 15:37 UTC, levitte commented on crypto/store/loader_file.c
> +     */
Good catch, I'll change the comment

2017-06-26 15:37 UTC, levitte commented on crypto/store/loader_file.c
> +    }
Fixed

2017-06-26 15:37 UTC, levitte commented on crypto/store/loader_file.c
> +        }
Fixed

2017-06-26 15:43 UTC, levitte commented on doc/man7/store.pod
> +store - Store retrieval functions
This file should also be renamed to `osslstore.pod`, should it not?

2017-06-26 15:46 UTC, mattcaswell commented on doc/man7/store.pod
> +store - Store retrieval functions
Yes, makes sense.

2017-06-26 15:48 UTC, richsalz commented on doc/man7/store.pod
> +store - Store retrieval functions
If you changed it to "osslstore - Store retrieval functions" then yes.  The filename should match ojne of the entries in the NAME section.  The find-doc-nits script should have complained.

2017-06-26 16:11 UTC, levitte commented
I think I've addressed all outstanding change requests

2017-06-27 09:34 UTC, mattcaswell approved these changes
Approved subject to @t-j-h not objecting WRT the naming issue. Please check with him before merging.

2017-06-27 13:34 UTC, levitte commented
(for our external readers)
We've had an internal debate, and we ended up deciding on claiming the name spaces OSSL and OPENSSL, using them as prefixes with a separating underscore.  #3781 was needed to fulfill this.

So we finally end up with a module called OPENSSL_STORE

2017-06-27 13:38 UTC, mattcaswell approved these changes
Subject to the one nit being fixed.

2017-06-27 13:38 UTC, mattcaswell commented on util/private.num
> +OSSLSTORE_post_process_info_fn          datatype
These look out of date

2017-06-27 14:03 UTC, levitte commented on util/private.num
> +OSSLSTORE_post_process_info_fn          datatype
Good catch!  Fixed.

2017-06-27 21:00 UTC, levitte commented
I found that the file loader might not correctly detect if a piece of data didn't match any object handler or if some other error occured in the object handler that's currently being attempted.  The difference is crucial to see if it should continue to check every remaining object handler or not.  Also, there are cases that I discovered while working with another branch, where the STORE error messages kind of shadow the issues found with a piece of data.

I'm currently tinkering with the file loader to fix these issues.

2017-06-28 23:58 UTC, levitte commented
Issues fixed, it's all in the last commit.  The others have the name changed integrated in them.

2017-06-29 09:11 UTC, mattcaswell approved these changes
One minor nit. Approved assuming that's fixed.

2017-06-29 09:26 UTC, levitte commented on crypto/store/loader_file.c
> + *                  Usually becomes 0 (no patch) or 1 (match!), but may
Fixed

2017-06-29 09:27 UTC, levitte commented
Apart from the comment fix, I found a nasty little bug that had escaped Travis because I didn't have it run the full set of tests.  All in the just added commit, please have a look

2017-06-29 09:27 UTC, levitte commented
(I've set it to run extended tests, I certainly hope that will be the last thing to deal with)

2017-06-29 09:30 UTC, mattcaswell approved these changes
Approved assuming the builds pass.

2017-06-29 09:39 UTC, levitte commented
The job to watch is the `enable-msan` one...  that's where I found failures in my personal Travis instance

2017-06-29 09:52 UTC, levitte commented
Yes, builds passed!  Time to merge.

2017-06-29 09:56 UTC, levitte commented
Merged.  c785fd48e68611c837f4e30027c02b84525501af to 6fc1d33c90015d3ad5738ec99aaa12fdb9640295

Thanks for the review, everyone

2017-06-29 09:56 UTC, closed without merging

2017-06-29 10:03 UTC, levitte commented
Next in line, I propose starting with a couple of easy ones, #3483 and #2745.  After that, #2746 (which might or might not be controversial)

2017-06-29 10:20 UTC, levitte commented
Another choice might be to have a look at #2688, which is a requirement for #3481 (the CNG engine, that I know has caught some interest).

2017-06-29 18:54 UTC, kaduk commented on crypto/store/store_register.c
> +        return 0;
I thought we super-double-plus ensured that the scheme field was never NULL, so most of this is redundant.

2017-06-29 19:21 UTC, kaduk commented on crypto/store/store_lib.c
> +    return ctx->loader->error(ctx->loader_ctx);
These functions seem like a giant footgun, as we don't enforce in OSSL_STORE_register_loader() that all the method functions are non-NULL.
Maybe I missed some previous discussion on this pull request and this is in fact the behavior we want from our "don't check user input for NULL" policy, but my personal preference would be to reject registering an incomplete loader.

2017-06-29 19:33 UTC, levitte commented on crypto/store/store_register.c
> +        return 0;
Good point.

2017-06-29 19:42 UTC, levitte commented on crypto/store/store_lib.c
> +    return ctx->loader->error(ctx->loader_ctx);
Good point.

2017-06-29 19:50 UTC, levitte commented
@kaduk, see #3805

2017-06-30 17:46 UTC, kaduk commented on crypto/store/loader_file.c
> +        if (strcmp(pem_name, PEM_STRING_PUBLIC) != 0)
Do things break if this is pem_check_suffix() instead of strcmp()?

2017-06-30 18:12 UTC, kaduk commented on crypto/store/loader_file.c
> +            path = &uri[5];
No one complained about magic numbers in pointer arithmetic? ;)

2017-06-30 18:32 UTC, bernd-edlinger commented on crypto/store/loader_file.c
> +        if (strncmp(&uri[5], "//localhost/", 12) == 0) {
by the way, isn't the DNS part of an URI case-insensitive?

2017-07-02 09:51 UTC, levitte commented on crypto/store/loader_file.c
> +        if (strcmp(pem_name, PEM_STRING_PUBLIC) != 0)
Yes.  `PEM_STRING_PUBLIC` identifies PKCS#8 public keys, which has the algo OID as part of the contents.  As far as I know, that's what we actively support.  Is there are reason you'd like us to support public keys that are typed in the PEM name?

2017-07-02 09:52 UTC, levitte commented on crypto/store/loader_file.c
> +            path = &uri[5];
Obviously not...  but then, considering the comparison with "file:" just above, this isn't much of a mystery, is it?

2017-07-02 09:53 UTC, levitte commented on crypto/store/loader_file.c
> +        if (strncmp(&uri[5], "//localhost/", 12) == 0) {
Good point.

2017-07-02 09:56 UTC, levitte commented on crypto/store/loader_file.c
> +        if (strncmp(&uri[5], "//localhost/", 12) == 0) {
#3827

2017-07-03 16:15 UTC, kaduk commented on crypto/store/loader_file.c
> +        if (strcmp(pem_name, PEM_STRING_PUBLIC) != 0)
No; I wasn't quite sure on the difference between the forms, and noted that we have a couple examples of "RSA PUBLIC KEY" in documentation, so wondered what the difference was.  Thanks for clarifying.

2024-04-01 00:59 UTC, Et7f3 commented on doc/man7/ossl_store.pod
> + OSSL_STORE_CTX *ctx = OSSL_STORE_open("file:/foo/bar/data.pem");
I have issue with this example provided. The first time I saw this function it hasn't this prototype: https://github.com/openssl/openssl/blame/4fd397821139723fd4e51a03e92df33e9a9fadcc/include/openssl/store.h#L55-L58 I will use code from storeutl to help me.