Add UI functionality to duplicate the user data
openssl/openssl pull request #3575
Opened 2017-05-28 07:36 UTC by levitte

This can be used by engines that need to retain the data for a longer time
than just the call where this user data is passed.

##### Checklist

- [x] documentation is added or updated

2017-05-28 07:36 UTC, levitte commented
@dwmw2, I believe you're interested in this

2017-05-28 09:14 UTC, dwmw2 commented
Staring at it on my.phone probably doesn't help but... Where does the 'destroy' function originally come from? Shouldnt it be passed in from the app as an additional argument to the 'set duplicator' call. Dup and free functions are a pair. (And if it's recounting are just Inc and dec)

2017-05-28 09:23 UTC, levitte commented
Very good point, I'll fix

2017-05-28 09:40 UTC, dwmw2 commented
I might even go so far as to suggest that the add_user_data function should take all three. To add user data without the dup/free funcs you should need to explicitly pass NULL

2017-05-28 09:42 UTC, levitte commented
I went the other way and made the destructor a UI_METHOD function as well.

2017-05-28 09:43 UTC, dwmw2 commented
... and the UI data so added is always destroyed by OpenSSL for consistency.

2017-05-28 09:59 UTC, dwmw2 commented
LGTM

2017-05-31 11:09 UTC, mattcaswell requested changes

2017-05-31 11:09 UTC, mattcaswell commented on doc/man3/UI_create_method.pod
> +UI_method_get_data_duplicator, UI_method_get_data_destructor,
Update HISTORY section?

2017-05-31 11:09 UTC, mattcaswell commented on doc/man3/UI_new.pod
> +UI_add_user_data, UI_dup_user_data, UI_get0_user_data, UI_get0_result,
HISTORY?

2017-05-31 11:09 UTC, mattcaswell commented on crypto/ui/ui_lib.c
> +int UI_dup_user_data(UI *ui, void *user_data)
Should this really be called UI_set1_user_data()?

2017-05-31 12:08 UTC, levitte commented on crypto/ui/ui_lib.c
> +int UI_dup_user_data(UI *ui, void *user_data)
That would be inconsistent with the rest of the UI API.  You might want to argue that the API should be "modernised", but that's for 1.2.0, not for now.

Background: the whole set0 / set1 semantics came after UI, as far as I recall, or was at least not settled and well known throughout the whole team at the time.

2017-05-31 12:14 UTC, levitte commented on doc/man3/UI_create_method.pod
> +UI_method_get_data_duplicator, UI_method_get_data_destructor,
Done

2017-05-31 12:14 UTC, levitte commented on doc/man3/UI_new.pod
> +UI_add_user_data, UI_dup_user_data, UI_get0_user_data, UI_get0_result,
Done

2017-05-31 16:18 UTC, mattcaswell commented on crypto/ui/ui_lib.c
> +int UI_dup_user_data(UI *ui, void *user_data)
How about add1 then? There are quite a few instances of that in the public APIs already.

2017-05-31 16:23 UTC, levitte commented on crypto/ui/ui_lib.c
> +int UI_dup_user_data(UI *ui, void *user_data)
How about looking at the rest of ui.h first? There is quite a number of add/dup pairs, why should this particular function differ?

2017-05-31 16:26 UTC, mattcaswell commented on crypto/ui/ui_lib.c
> +int UI_dup_user_data(UI *ui, void *user_data)
Hmm. Ok.

2017-05-31 16:26 UTC, mattcaswell approved these changes

2017-05-31 17:00 UTC, levitte commented
Merged. 545360c4dfbf90f63918be3d98e344adc7ca2d7f

Thanks!

2017-05-31 17:00 UTC, closed without merging