change salt handling, way 1
openssl/openssl pull request #4486
Opened 2017-10-08 13:43 UTC by EasySec

This is an attempt to workaround the 'curse' of the salt handling using the enc command :
The salt is not always stored with the encrypting data.
As could be expected, it is stored when it was generated on the fly (not supplied with args), but not only.
It is stored when no key is given.
And when stored, even good IV and key fails to decrypt.
You must enter the password (but are NOT prompted for).

This first PR act as folows : 
If encrypting generate a salt IF NOT supplied using args.
If decrypting use salt from input BIO IF NOT supplied using args.

2018-07-12 18:12 UTC, richsalz commented
This is not strictly a 1.1.1 bug or feature-add, so I am removing the 1.1.1 milestone.

2021-05-03 13:56 UTC, t8m reviewed
I think this should be merged. Could you please adjust the enc manual page to clarify how salt is handled with your patch?

2021-05-03 13:57 UTC, t8m commented
We are sorry for neglecting this for so long.

2021-05-03 23:11 UTC, EasySec commented
> 
> 
> Could you please adjust the enc manual page to clarify how salt is handled with your patch?

I made a quick return on that matter today. What about the content of my new commit ? Do you think it's clear enough ?

2021-05-04 09:48 UTC, t8m requested changes
Just a few code formatting nits to fix.

2021-05-04 09:48 UTC, t8m commented on apps/enc.c
> +
Please drop this empty line.

2021-05-04 09:48 UTC, t8m commented on apps/enc.c
> +
Please drop this empty line

2021-05-04 09:48 UTC, t8m commented on apps/enc.c
> +                        else { /* file is NOT salted, NO salt available */
Else should be placed immediately after the `}`

2021-05-04 09:49 UTC, t8m commented
> I made a quick return on that matter today. What about the content of my new commit ? Do you think it's clear enough ?

I think it is OK.

2021-05-04 14:38 UTC, EasySec commented
> 
> 
> Just a few code formatting nits to fix.

Yes, sorry. Done.

2021-05-04 15:46 UTC, t8m approved these changes

2021-05-05 03:12 UTC, paulidale approved these changes

2021-05-06 04:00 UTC, openssl-machine commented
This pull request is ready to merge

2021-05-06 10:41 UTC, mattcaswell commented
Pushed!! Thanks for your contribution. It only took 3.5 years to merge this!

Prior to pushing I made a trivial edit to the documentation part of this PR to remove some spurious end of line whitespace.

2021-05-06 10:41 UTC, closed without merging