apps: Switch to using OSSL_STORE for loading keys, certs, ...
openssl/openssl pull request #7390
Opened 2018-10-12 15:14 UTC by levitte

This makes all the format specifiers largely irrelevant, except for
the ENGINE format when a key is given as a key ID only.  However, with
the engine loader, it's possible to change this:

    -engine {engineid} -key {keyid} -keyformat ENGINE

To this:

    -key engine://{engineid}/{keyid}

We retain the ENGINE format for the sake of compatibility.  All other
input formats are simply ignored.  Note that output formats is a
different story.

Fixes #1963

2018-10-14 13:42 UTC, petrovr commented
Richard Levitte wrote:
> This makes all the format specifiers largely irrelevant, except for
> the ENGINE format when a key is given as a key ID only.  However, with
> the engine loader, it's possible to change this:
>
>      -engine {engineid} -key {keyid} -keyformat ENGINE
>
> To this:
>
>      -key engine://{engineid}/{keyid}
[SNIP]
Proposed modification is not store specific.

Let me quote in brief from PKIX-SSH manual 
("http://securebox.termoneplus.com/man5/ssh_config.5.html") for option 
IdentityFile.

(1) If file name starts with prefix ‘engine:’ instead from file identity 
load is redirected to “loadable cryptographic module” (engine).
Name format is engine:{engineid}:{keyid} using syntax above.

(2) Prefix “store:” could be used if cryptographic library supports 
ossl_store(7) functionality.
In such case name format is store:{uri}. Engine if applicable is encoded 
in URI-scheme.

Second case is more generic. It is store related as it allows use of 
URIs not supported by engine.
For instance based on store functionality PKIX-SSH could use directly as 
identify key and certificates stored in PKCS#12 file (side effect).
Without store user should unpack (extract) PKCS#12 file into text file 
(PEM format).


Otherwise there is no big difference for PKIX-SSH:
(1) ssh ... -i engine:e_nss:{keyid} vs
(2) ssh ... -i store:nss:{keyid}
Remark: in both cases engine require explicit configuration.


And one note more: {engineid}/{keyid} is not _in store URI format._  You 
know engine , you know keyid, but you don't know how to build store URI. 
It is engine specific and is more one direction process: URI -> 
{{engineid}, {keyid}, {extras...}}.

Regards,
Roumen Petrov

2018-10-14 16:44 UTC, levitte commented
Ah, there's a précédent for a engine: scheme. Sure, I can use that instead.

Why someone has implemented a store: scheme is beyond me, though. Does that mean that if I want to express a file name in uri form, I would have to write `store:file:///home/levitte/foo.pem`? Why isn't `file:///home/levitte/foo.pem` enough? I cannot see why we should support such a contraption...

2018-10-15 16:34 UTC, petrovr commented
Richard Levitte wrote:
> Ah, there's a précédent for a engine: scheme. Sure, I can use that instead.
> 
> Why someone has implemented a store: scheme is beyond me, though. Does that mean that if I want to express a file name in uri form, I would have to write `store:file:///home/levitte/foo.pem`?

So I use prefix:data, whre prefix is engine or store  just to avoid 
failback case into code.

There is no reason OpenSSL to use such format.


>  Why isn't `file:///home/levitte/foo.pem` enough? I cannot see why we should support such a contraption...
> 

Yep . Support of "Store URI" as input source should be enough . Perhaps 
if store fails with "invalid scheme" then code could try to open file 
(failback case).

Drawback of "Store URI" is that engine may not be loaded.
Work around is to keep "engine" argument.


Regards,
Roumen Petrov

2018-10-15 16:44 UTC, levitte commented
> Perhaps if store fails with "invalid scheme" then code could try to open file (failback case).

The current file loader does this already, i.e. it defaults to `file:` if no scheme is present.

2018-10-15 16:45 UTC, levitte commented
> Drawback of "Store URI" is that engine may not be loaded. Work around is to keep "engine" argument.

The proper workaround is to do what I do in this PR, i.e. define a `engine:` scheme loader.  See `apps/app_engine_loader.c`

2018-10-15 22:17 UTC, kaduk commented
Please do not start using an unregistered URI scheme: https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

2018-10-17 09:48 UTC, levitte commented
Code updated to use `engine:{engineid}:{keyid}`

2018-10-18 05:03 UTC, levitte commented
Apparently, I hadn't completed what I said.  Now fixed, and tests added.

2018-10-18 18:45 UTC, levitte commented
Finally, this builds and tests fine. I will fix the docs, then it will be time for a review

2018-10-19 18:33 UTC, petrovr commented
Richard Levitte wrote:
> Apparently, I hadn't completed what I said.  Now fixed, and tests added.
> 


Perhaps in next weeks :-( I could find time to continue discussion.

Regards,
Roumen

2019-04-25 06:23 UTC, dwmw2 commented
I'll echo the "please don't use an unregistered URI scheme" comment with its converse: please *do* support PKCS#11 URIs directly, without them having to be prefixed or mangled. The `{engine}:…` form mentioned above would have worked for that, given that the name of the engine in question would be `pkcs11`.

If you end up with a form that doesn't Just Work for RFC7512 PKCS#11 URIs, please special-case them to use the pkcs11 engine. Thanks.

2019-04-25 07:56 UTC, levitte commented
If you create a proper OSSL_STORE loader that registers the scheme "pkcs11:", then you can use that scheme directly.

The "engine:" 'scheme' is an interim construct to allow access via the older ENGINE calls to access keys; `ENGINE_load_private_key` and `ENGINE_load_public_key`.  However, if the engine offers an OSSL_STORE loader, *there is no reason whatsoever to use the "engine:" 'scheme'*

2019-04-25 08:00 UTC, dwmw2 commented
Perfect. Thank you.

2019-10-31 13:53 UTC, mattcaswell commented
Needs a rebase

2019-11-04 14:53 UTC, mattcaswell commented
> But seeing that PKIX-SSH uses the same scheme, and uses a different syntax to boot, that might be qualification enough to make a provisional registration after all. (I don't see it ever changing status to something more provisionalpermanent, btw)

Was the scheme ever registered as suggested here?

2019-11-04 16:04 UTC, levitte commented
> Was the scheme ever registered as suggested here?

No, but can certainly be done.  I have the impression that it's not very hard...

2019-11-04 16:22 UTC, mattcaswell requested changes
I'd also suggest a CHANGES entry might be in order for the change in behaviour of "-inform"

2019-11-04 16:22 UTC, mattcaswell commented on crypto/store/loader_file.c
> +                                               void *ui_data, const char *uri);
The comment above here needs updating

2019-11-04 16:22 UTC, mattcaswell commented on doc/man1/openssl.pod
> +This is a temporary measure until engines have learned to provide an
I somehow suspect this won't be temporary and this wording will still be here in 10 years time. Perhaps reword?

2019-11-04 16:22 UTC, mattcaswell commented on util/libcrypto.num
> +OSSL_STORE_LOADER_set_attach            4751	3_0_0	EXIST::FUNCTION:
These functions don't seem to be documented.

2019-11-04 16:22 UTC, mattcaswell commented on test/recipes/90-test_store.t
> +			    "-in", "engine:ossltest:ot:".to_abs_file($file)])));
Given the extent of the option changes in the apps this seems very light testing

2019-11-04 19:43 UTC, levitte commented on apps/app_engine_loader.c
> +        OSSL_STORE_LOADER_free(loader);
Considering we have declared ENGINE legacy, I dunno how keen I'm on that.  But, we could re-evalutate that when I've finished #9389

2019-11-04 19:44 UTC, levitte commented
> Needs a rebase

Getting at it now

2019-11-04 21:36 UTC, levitte commented
The more I looked at the branch, the more I realised it's not quite ready for final review.  So I put it back in WIP.

Comments are still welcome!

2020-02-13 13:08 UTC, t-j-h commented
This is still a WIP but placing a hold so it doesn't end up in OpenSSL 3.0 without a discussion and decision on the points already raised in the feedback.

2020-03-15 00:08 UTC, openssl-machine commented
Automated Ping: This issue is in a state where it requires action by @openssl/omc but the last update was 30 days ago

2020-10-09 10:12 UTC, DDvO commented
This is related to #12647 and likely further more recent PRs..

2021-07-22 15:42 UTC, t8m commented
Isn't this change already implemented in master/3.0?

2021-07-22 15:44 UTC, levitte commented
> Isn't this change already implemented in master/3.0?

Almost, there were nuances that are not caught by @DDvO's changes.
I've left this unchanged for a while for the sake of priority, but intended to rebase this when I've got a chunk of time, to see what there is left.

2022-01-19 08:27 UTC, mattcaswell commented
OMC: There is no decision to be made here at this stage.

2024-06-28 14:52 UTC, closed without merging