asn1parse: avoid free of partial allocation
openssl/openssl pull request #8753
Opened 2019-04-15 11:28 UTC by levitte

The way the loaded file is stored in memory was a bit confusing.
With '-strictpem', it was simply held by |str|, and when not, it was
held with |buf|...  with |str| pointing at the data, still.

To confuse matters more, when using '-strparse', |str| was re-used to
hold the position from where to start parsing.

So when '-strparse' and '-strictpem' are used together, both |buf| and
|str| are freed, but |str| pointed somewhere in the data that was
already held by |buf|, resulting in a double free.

The situation is resolved by always having |buf| hold the pointer to
the file data, and always and only use |str| to hold the position to
start parsing from.  Now, we only need to free |buf| properly.

Fixes #8752

2019-04-16 23:48 UTC, mspncp requested changes
I think the fix is correct but your explanation contains a mistake:

```
So when '-strparse' and '-strictpem' are used together, both |buf| and
|str| are freed, but |str| pointed somewhere in the data that was
already held by |buf|, resulting in a double free.
```

In the buggy version (without your patch), it is not the two pointers `str` and `buf` that get freed, because `buf == NULL` (verified in the debugger). Rather, it's the following "evil" code


https://github.com/openssl/openssl/blob/f2dbb71cb6bf6cd570f96e7663a22dd87854f08b/apps/asn1pars.c#L253-L258

which effectively assigns

```
str = tmpbuf = at->value.asn1_string->data;
```


which is why the crash occurs here in the call `ASN1_TYPE_free(at)` after `OPENSSL_free(str)`:


https://github.com/openssl/openssl/blob/f2dbb71cb6bf6cd570f96e7663a22dd87854f08b/apps/asn1pars.c#L306-L308

2019-04-16 23:48 UTC, mspncp commented on apps/asn1pars.c
> +        buf->length = buf->max = num;
_(Side note: Huh, it seems like `BUF_MEM` was forgotten when the structures were made opaque? A public struct with a rudimentary API. I would have expected to see something like `BUF_MEM_set(buf, data, length)` or `BUF_MEM_attach(buf, data, length)` ..._

2019-04-18 12:46 UTC, levitte commented
Okie, I've changed the commit message, and the title+description if this PR to match

2019-04-18 15:49 UTC, mspncp approved these changes
Two nits in the commit message, which you might want to fix while merging, but don't have to:

- Insert "using" in first paragraph:  `When using '-strictpem', ...`  
- Maybe it's better to stay in past tense in the second paragraph (because you are still describing the bug) and only switch to present tense in the third paragraph.

2019-04-18 17:20 UTC, levitte commented
Thanks for the advice, @mspncp.  I ended up following it.

2019-04-18 17:22 UTC, levitte commented
Merged.

master:
4f29f3a29b8b416a501c7166dbbca5284b198f81 asn1parse: avoid double free

1.1.1:
18111b130abc0f53b41abbbf82b27d7232ec99f2 asn1parse: avoid double free

2019-04-18 17:22 UTC, closed without merging