Rework the perl fallback functionality
openssl/openssl pull request #9826
Opened 2019-09-09 09:59 UTC by levitte

The module with_fallback.pm was kind of clunky and required a transfer
module.  This change replaces if with a much more generic pragma type
module, which simply appends given directories to @INC (as opposed to
the 'lib' pragma, which prepends the directories to @INC).

This also supports having a file MODULES.txt with sub-directories to
modules.  This ensures that we don't have to spray individual module
paths throughout our perl code, but can have them collected in one
place.

(do note that there is a 'fallback' module on CPAN.  However, it isn't
part of the core perl, and it has no support the any MODULES.txt kind
of construct)

2019-09-09 15:02 UTC, mattcaswell commented
Travis failures look relevant:

````
Parameter to use fallback must be a directory, not a file at /home/travis/build/openssl/openssl/_srcdist/test/generate_ssl_tests.pl line 27.
BEGIN failed--compilation aborted at /home/travis/build/openssl/openssl/_srcdist/test/generate_ssl_tests.pl line 27.
````

2019-09-09 15:09 UTC, levitte commented
> Travis failures look relevant:

Fixup pushed

2019-09-12 10:03 UTC, mattcaswell requested changes

2019-09-12 10:22 UTC, mattcaswell approved these changes
LGTM

2019-09-12 10:50 UTC, closed without merging